 <?php 
 
//  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
//     $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
//  $categoryId = $category->getId();
// $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
//  $connection = $resource->getConnection(); 
// $sql = "SELECT * FROM `category_script` where category_id='".$categoryId."'";

//  $results = $connection->fetchAll($sql); 

//  if(!empty($results)){
//  	$scrvalues=$results[0]['category_content'];
//  }
//   else{
//   	$scrvalues='';
//   }      

    ?>