<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Review\Block\Product\ReviewRenderer $block */

$url = $block->getReviewsUrl() . '#reviews';
$urlForm = $block->getReviewsUrl() . '#review-form';
$urlAskForm = $block->getReviewsUrl() . '#askquestion';
$urlLvideoForm = $block->getReviewsUrl() . '#custom-form';
?>
<?php if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>

<ul class="rating-reivew list-inline<?= !$rating ? ' no-rating' : '' ?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if ($rating):?>
    <li class="rating list-inline-item p-0 rating-summary">
         <div class="rating-result" title="<?= $block->escapeHtmlAttr($rating); ?>%">
             <span style="width:<?= $block->escapeHtmlAttr($rating); ?>%">
                 <span>
                     <span itemprop="ratingValue"><?= $block->escapeHtml($rating); ?></span>% of <span itemprop="bestRating">100</span>
                 </span>
             </span>
         </div>
     </li>
    <?php endif;?>
     <li class="list-inline-item bd-right"> <a class="action view"
           href="<?= $block->escapeUrl($url) ?>">
            <span itemprop="reviewCount"><?= $block->escapeHtml($block->getReviewsCount()) ?></span>&nbsp;
            <span><?= ($block->getReviewsCount() == 1) ? $block->escapeHtml(__('Review')) : $block->escapeHtml(__('Reviews')) ?></span>
        </a></li>
         <li class="list-inline-item bd-right removeadd"><a class="action add" href="<?= $block->escapeUrl($urlForm) ?>"><?= $block->escapeHtml(__('Add Your Review')) ?></a></li>

         <!-- This is for custom ask question form -->
         <li class="list-inline-item askques"><a class="action add" href="<?= $block->escapeUrl($urlAskForm) ?>"><?= $block->escapeHtml(__('Ask a question')) ?></a></li>
          <!-- End -->
          <li class="list-inline-item "><a class="action add" href="<?= $block->escapeUrl($urlLvideoForm) ?>"><?= $block->escapeHtml(__('Live Video Shopping')) ?></a></li>
</ul>
<?php elseif ($block->getDisplayIfEmpty()): ?>
    <ul class="rating-reivew list-inline" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
       <li class="list-inline-item bd-right removeadd"><a class="action add" href="<?= $block->escapeUrl($urlForm) ?>"><?= $block->escapeHtml(__('Add Your Review')) ?></a></li>

         <!-- This is for custom ask question form -->
         <li class="list-inline-item askques"><a class="action add" href="<?= $block->escapeUrl($urlAskForm) ?>"><?= $block->escapeHtml(__('Ask a question')) ?></a></li>
         <li class="list-inline-item "><a class="action add" href="<?= $block->escapeUrl($urlLvideoForm) ?>"><?= $block->escapeHtml(__('Live Video Shopping')) ?></a></li>   
    </ul>
<?php endif; ?>
