<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$redirect = $objectManager->get('Magento\Framework\App\Response\RedirectInterface');
$ref_url = $redirect->getRefererUrl();
$customer = $block->getCustomer();
$customerObj = $objectManager->create('Magento\Customer\Model\Customer')
        ->load($customer->getId());
if (strpos($ref_url, "customer/account/create")!==false){
    ?>
    <script type="text/javascript">
       dataLayer.push({'event':'signup','email':'<?php echo $customerObj->getData('email'); ?>','firstname':'<?php echo $customerObj->getData('firstname'); ?>','mobile_number':'<?php echo $customerObj->getData('mobile'); ?>'}); 
    </script>

    <?php
}
else if(strpos($ref_url, "customer/account/login")!==false) {
    ?>
    <script type="text/javascript">
       dataLayer.push({'event':'signin','email':'<?php echo $customerObj->getData('email'); ?>','firstname':'<?php echo $customerObj->getData('firstname'); ?>','mobile_number':'<?php echo $customerObj->getData('mobile'); ?>'}); 
    </script>

    <?php 
}
 ?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong  style="font-size:1.5rem;"><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">

        <div class="box box-information">
            <strong class="box-title" >
                <span style="font-size:1.2rem;"><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p style="font-size:1rem;padding-bottom:10px;">
                    <?= $block->escapeHtml($block->getName()) ?><br>                   
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>

                </p>
                <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
            </div>
            <div class="box-actions">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a>
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()): ?>
            <div class="box box-newsletter">
                <strong class="box-title" >
                    <span style="font-size:1.2rem;"><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p style="font-size:1rem;padding-bottom:10px;">
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
