<div id="middle" class="enquiry-card">
<h4 class="enquiry-heading">Subscribe for Metal Rate Update</h4>
<form id="custom-form" class="form metal" enctype="multipart/form-data" action="<?php echo $block->getUrl('tryathome/index/index/')?>" id="custom-form" method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
       <input name="source" value="Metal Rate"  type="hidden" />
<div class="col enquiry">
<div class="row"><input name="cust_name" class="form-control required-entry in" data-validate="{required:true}" type="text" placeholder="Customer Name" aria-required="true"></div>
<div class="row"><input name="area" class="form-control required-entry in"  type="text" placeholder="Enter Your Area"></div>
<div class="row"><input name="email" class="form-control required-entry in"  type="email" placeholder="Enter Your Email" ></div>
<div class="row input-group"><input name="mobile" id="mobile" class="form-control required-entry in mobile"  type="tel" placeholder="Mobile Number"><div class="input-group-append">
  <button class="btn btn-verify otp-verify-submit" type="button">VERIFY</button>
  <span id="OtpBaseUrl" class="OtpBaseUrl" style="display: none"><?php echo "https://stage2.vaibhavjewellers.com/";//$block->getUploadFormUrl(); ?></span>
</div>
</div>
<div class="row input-group">
<input type="hidden" name="verify" class="txt_verify" tabindex="1000" value="0" id="upload-design" data-validate="{required:true, 'validate-upload-design-verify':true}" data-msg-required="Please enter Mobile" aria-required="true" aria-invalid="true" aria-describedby="verify-error" /> <span class="customized-errmsg" style="color: red; text-align:center;"></span>
                <div class="verifyErr" id="verifyErr" style="display:none; text-align: left;
    width: 100%; font-size: 13px; color:#fe0000; ">
                  <?php echo __( "Mobile verification is pending");?>
                </div>
                <div class="RepeatErr" id="RepeatErr" style="display:none; text-align: left;
    width: 100%; font-size: 13px; color:#fe0000;">
                  <?php echo __( "Mobile number already taken");?>
                </div>
                <div class="ValidErr" id="ValidErr" style="display:none; text-align: left;
    width: 100%; font-size: 13px; color:#fe0000;">
                  <?php echo __( "Please Enter Mobile Number");?>
                </div>
                <div class="ValidErrt" id="ValidErrt" style="display:none; text-align: left;
    width: 100%; font-size: 13px; color:#fe0000;">
                  <?php echo __( "Phone Number should be 10 digits");?>
                </div>
                <div class="SuccessMsg" id="SuccessMsg" style="display:none; text-align: left;
    width: 100%; font-size: 13px; color:#fe0000;">
                  <?php echo __( "Mobile number verified");?>
                </div>
                </div>  

<div class="row input-group verification user_otp" style="display:none;">
                  
                      <input type="text" name="otp" class="form-control otp" placeholder="Enter Code" data-validate="{required:true}" data-msg-required="Please enter OTP">
                      <div class="input-group-append">
                      <button type="button" class="btn btn-verify otp-verification">Verify OTP</button>
                    </div>
                  </div>

<button class="btn update-submit" type="submit">SUBMIT</button></div>
</form>
</div>
<script>
/*require([
  'jquery',
  'mage/mage',
], function($){
   $( "#submit" ).click(function() { 
   alert("hjhjkjl");       
       $('input[name="mobile"]').validation();
       if(!$('input[name="mobile"]').validation('isValid')){
           return false;
       }
   });
});*/
require([
    'jquery',
    'mage/mage'
], function($){
    /*  jQuery(document).ready(function () {
    $.validator.addMethod(
                    'validate-customer-dob',function(v){
                        if(("#datepicker").val()=='') {
                            return false;
                        } /*else {
                            var test =new Date(v); 
                          var age = ((Date.now() - test) / (31557600000));
                          return (age > 18);
                        }
                    },$.mage.__('please select date and time!!')
                ); 
    });*/
   var dataForm = $('#custom-form');
   dataForm.mage('validation', {});

   $("#mobile").keypress(function (e) {
     //if the letter is not digit then display error and don't type anything
     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
        //display error message
        $("#errmsg").html("Digits Only").show().fadeOut("slow");
               return false;
    }
   });
 
});


</script>

<script type="text/javascript">
  require([
                                      'jquery', // jquery Library
                                      'jquery/ui', // Jquery UI Library
                                      'jquery/validate', // Jquery Validation Library
                                      'mage/translate' // Magento text translate (Validation message translte as per language)
                              ], function($){
                              jQuery(document).ready(function () {
                                  $.validator.setDefaults({ ignore: '' });
                                  $.validator.addMethod(
                                          'validate-upload-design-verify', function (value) {
                                         return (value=='1') 
                                          },$.mage.__('Mobile verification is pending')
                                  );
                                  $.validator.addMethod(
                                          'validate-customize-design-verify', function (value) {
                                         return (value=='1') 
                                          },$.mage.__('Mobile verification is pending')
                                  );
                                   $.validator.addMethod(
                                          'validate-designer-design-verify', function (value) {
                                         return (value=='1') 
                                          },$.mage.__('Mobile verification is pending')
                                  );
                              });
                              });
</script>
<script type="text/javascript">
  require([
                                      'jquery', // jquery Library
                                      'jquery/ui', // Jquery UI Library
                                      'jquery/validate', // Jquery Validation Library
                                      'mage/translate' // Magento text translate (Validation message translte as per language)
                              ], function($){ 
  jQuery(document).ready(function () {
                              jQuery(document).on('click', '.otp-verify-submit', function(){
                                  //var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
                                  //baseUrl = baseUrl.trim();
                                  //var controllerUrl = 'sociallogin/popup/phoneverify';
                                  //var ajxUrl = baseUrl.concat(controllerUrl);
  /*                                  if (jQuery("#telephone").val() == '') {
                                      jQuery("#ValidErr").show();
                                      jQuery("#RepeatErr").hide();
                                      jQuery("#SuccessMsg").hide();
                                      return false;
                                  } else {
                                      if (jQuery("#telephone").val().length != 10){
                                          jQuery("#ValidErrt").show();
                                          jQuery("#ValidErr").hide();
                                          jQuery("#user_otp").hide();
                                          jQuery("#RepeatErr").hide();
                                          jQuery("#SuccessMsg").hide();
                                          
                                          return false;
                                      }
                                  }*/
                                  //var form_data = "telephone="+jQuery("#telephone").val();
                                 /* jQuery.ajax({
                                      url: ajxUrl, // Upload Script
                                      showLoader: true,   
                                      dataType: 'json',
                                      data: form_data,
                                      type: 'post',*/
                                      //success: function(data) {
                                          /*if(data) {*/
                                              //if(jQuery("#telephone").valid()) {
                                                      var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
                                                      baseUrl = baseUrl.trim();
                                                      var controllerUrl = 'sociallogin/popup/codesend';
                                                      var ajxUrl = baseUrl.concat(controllerUrl);
                                                      if (jQuery(".mobile").val() == '') {
                                                      jQuery(".ValidErr").show();
                                                      jQuery(".RepeatErr").hide();
                                                      jQuery(".SuccessMsg").hide();
                                                      return false;
                                                  } else {
                                                      if (jQuery(".mobile").val().length != 10){
                                                          jQuery(".ValidErrt").show();
                                                          jQuery(".ValidErr").hide();
                                                          jQuery(".user_otp").hide();
                                                          jQuery(".RepeatErr").hide();
                                                          jQuery(".SuccessMsg").hide();
                                                          return false;
                                                      }
                                                  }
                                                  jQuery(".otp-verify-submit").hide();
                                                  var form_data = "telephone="+jQuery(".mobile").val();//jQuery("#user_mobile :input").serialize();
                                                  jQuery.ajax({
                                                  url: ajxUrl, // Upload Script
                                                  showLoader: true,   
                                                  dataType: 'json',
                                                  data: form_data, // Setting the data attribute of ajax with file_data
                                                  type: 'post',
                                                  success: function(data) {  // Do something after Ajax completes 
                                                                 // jQuery("div[id='verifyloading']").hide();
                                                                      // alert(data['message']);
                                                      jQuery('.RepeatErr').hide();
                                                      jQuery('.verifyErr').hide();
                                                          if (data['success'] == true)
                                                          {
                                                          jQuery(".RepeatErr").hide();
                                                                      jQuery(".verify-error").hide();
                                                                      jQuery(".mobile-error").hide();
                                                                      jQuery('.RepeatErr').html("");
                                                                      jQuery('.SuccessMsg').html("");
                                                                      jQuery('.SuccessMsg').html(data['message']);
                                                                      jQuery('.SuccessMsg').show();
                                                                      jQuery(".otp").val('');
                                                                      jQuery(".user_otp").show();
                                                                       jQuery(".otp-verify-submit").text('Resend Otp');
                                                                      jQuery(".ValidErrt").hide();
                                                                      jQuery(".ValidErr").hide();
                                                                      } else {
                                                                      jQuery(".SuccessMsg").hide();
                                                                      jQuery('.SuccessMsg').html("");
                                                                      jQuery('.RepeatErr').html("");
                                                                      //jQuery('#RepeatErr').html(data['message']);
                                                                      jQuery('.RepeatErr').show();
                                                                      jQuery(".otp-verify-submit").show();
                                                                      jQuery(".user_otp").hide();
                                                                      }
                                                                  }
                                                      });
                                          
                                        /*  } else {
                                              jQuery("#ValidErr").hide();
                                              jQuery('#RepeatErr').show();
                                              jQuery("#ValidErrt").hide();
                                              //jQuery("#otp-verify-submit").text('Mobile Number alreday taken click to change again');
                                              jQuery("#ValidErr").hide();
                                          }*/
                                 /*     }else {
                                      jQuery("#ValidErr").hide();
                                      jQuery('#RepeatErr').show();
                                      jQuery("#ValidErrt").hide();
                                      //jQuery("#otp-verify-submit").text('Mobile Number alreday taken click to change again');
                                      jQuery("#ValidErr").hide();
                                  }*/
                              //}
                                  //});
                              });
                              jQuery(document).on('click', '.otp-verification', function(){
                              //if(jQuery(".otp").valid()) { 
                                  var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
                                  baseUrl = baseUrl.trim();
                                  var controllerUrl = 'sociallogin/popup/codeverify';
                                  var ajxUrl = baseUrl.concat(controllerUrl);
                                  var frm_data = "telephone="+jQuery(".mobile").val();
                                  var form_data = frm_data + "&" + "otp="+jQuery(".otp").val();
                                  if (jQuery("#otp").val() == '')
                                  {
                                 return false;
                                 }
                                  jQuery('.verifyErr').hide();
                                  jQuery('.RepeatErr').hide();
                                  jQuery.ajax({
                                  url: ajxUrl, // Upload Script
                                          showLoader: true,
                                          dataType: 'json',
                                          data: form_data, // Setting the data attribute of ajax with file_data
                                          type: 'post',
                                          success: function(data) {// Do something after Ajax completes 
                                          //alert(data['message']);
                                          //alert('verification success');
                                          if (data['success'] == true)
                                          {
                                          jQuery(".RepeatErr").hide();
                                          jQuery('.SuccessMsg').html("");
                                          jQuery(".verify-error").hide();
                                          jQuery(".telephone-error").hide();
                                          jQuery('.SuccessMsg').html(data['message']);
                                          jQuery('.SuccessMsg').show();
                                          jQuery(".user_otp").hide();
                                          jQuery('input[name="verify"]').val('1');
                                          jQuery(".verifyErr").hide();
                                          jQuery(".otp-verify-submit").hide();
                                          } else {
                                          jQuery(".SuccessMsg").hide();
                                          jQuery('.RepeatErr').html("");
                                          jQuery('.RepeatErr').html(data['message']);
                                          jQuery('.RepeatErr').show();
                                          jQuery(".otp-verify-submit").text('Resend Otp');
                                          jQuery(".otp-verify-submit").show();
                                          jQuery(".user_otp").hide();
                                          jQuery('input[name="verify"]').val('0');
                                          }
                                          }
                                  });
                              //}
                              });
   });                                                                        
  });
</script>