 <div id="popup-modal" class="row input-group verification user_otp" style="display: none;" >
                  <input style="width: 100%;margin-left: 15px;" type="text" name="otp" class="form-control otp" placeholder="Enter Code" data-validate="{required:true}" data-msg-required="Please enter OTP">
                   <div class="input-group-append" style="margin-left: 15px;margin-top: 10px;float: right;width: 100%;text-align: right;">
                 <button type="button"  class="btn btn-verify otp-verification">Verify OTP</button>
                    </div>
                  </div>
             <div><a class="btn btn-verify otp-verify-submit" style="text-decoration: underline !important;  font-weight: bold;">VERIFY</a> </div>