<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<!-- <div class="inner-block-newsletter">
 -->  
   <div class="inner-block-newsletter" style="content-visibility: auto; contain-intrinsic-size: 80px;background-color: #f1e4f2 !important; ">
         <form class="newsletter-validate-detail"
                novalidate
                action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'>
            <div class="container-fluid d-flex justify-content-center px-5 py-3">
                <h2 class="signUp-txt" style="color: #6f2c91 !important;">Sign Up for Our Newsletter:</h2>
                <div class="align-items-center d-flex w-60">
                
                             
                                <input class="p-2 newsletter" name="email" type="email"
                                   placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{required:true, 'validate-email':true}"/>
                                    <?php echo $block->getBlockHtml('formkey'); ?>
                                    <button class="subs-button" class="p-2" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                          <?= $block->escapeHtml(__('SUBSCRIBE')) ?>
                        </button>
                       
                    </div> 
                </div>
                 </form>
            </div>
  <script type="text/javascript">
   require(["jquery"], function ($) {
    $(document).ready(function () {
        $('.subs-button').click(function () { 
            if ($('.newsletter-validate-detail').valid()) {
    //              dataLayer.push({'event':'email_subscribe',
    //     'email':$('#newsletter').val()
       
    // });
                return true;
            }
        });
    });
});
 </script>
        </div>
<!-- </div>
 --><!-- </div>
 -->
