<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<style>
.dropbtn1 {
  
  
  font-size: 16px;
  border: none;
  cursor: pointer;
}

.dropdown1 {
  display: inline-block;
}

.dropdown-content1 {
  display: none;
  position: absolute !important;
  background-color: #fff;
  min-width: 200px;
  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
  z-index:1;
  margin-left: 105px;
  margin-top: -97px !important;
}

.dropdown-content1 a {
  color: black;
  padding: 8px 10px;
  text-decoration: none;
  display: block;
}

.dropdown-content1 a:hover {background-color: #f1f1f1}

.dropdown1:hover .dropdown-content1 {
  display: block;
}

.dropdown1:hover .dropbtn1 {
}
li.dropdown1 ul li {
    margin-bottom: 0px;
}
</style>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div class="col-md-4">
<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="d-flex justify-content-center" > <!-- logo -->
<?php else: ?>
    <a class="d-flex justify-content-center" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img class="px-lg-5 py-xl-2 w-100 vlogo" src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>" width="146" height="44"
        >
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>
</div>