<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();
$brands     = $block->getBrands();
?>

<h3><?php echo __('Categories'); ?></h3>
<ul class="o-list term-list">

    <?php
    // Loop through categories
    foreach ( $categories as $category ) : ?>	   
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
			 <?php if($category->getId() != 2){ ?>
            <a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="<?php echo($block->isActive($category) ? ' active' : ''); ?>">
                <?php echo $category->getName(); ?>
            </a>
			<?php } ?>
            <?php if ( $category->hasChildren() ) : ?>
			     <?php if($category->getId() != 2){ ?>
                 	<span class="expand"><?php echo $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span>
				<?php } ?>
            <?php endif; ?>

            <?php echo $block->getChildCategoryView($category); ?>
        </li>
        
	<?php //} ?>
    <?php endforeach; ?>
</ul>

<script type="text/javascript">
	/* Simply invoke iffe of sidebarmodule */
	require(['jquery','sidebarmodule'], function ($) {
        jQuery('ul.term-list li > ul.o-list--unstyled').each(function(){
 	var LiN = jQuery(this).nextAll().find('li').length;
	console.log('this'+ LiN);
    if( LiN >= 4){ 
        jQuery('li', this).eq(4).nextAll().hide().addClass('toggleable');
        jQuery(this).append('<li class="more" id="viewMore">View More</li>');  
    }

});
    jQuery('ul.term-list li').on('click','.more', function(){
        if( jQuery(this).hasClass('less') ){    
            jQuery(this).text('View More').removeClass('less');    
        }else{
            jQuery(this).text('View Less').addClass('less'); 
        }
        jQuery(this).siblings('li.toggleable').slideToggle();
    });
}); 
</script>