<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
    .price:last-child {
        border-right: none;
    }

    .price:first-child {
        padding: 0px 0px;
    }

    .price {
        padding: 0 40px;
        border-right: 0.1px solid #d7d7d7;
        text-align: center;
    }

    .cms-page-view table td {
        border-left: 0px !important;
    }

    @media only screen and (max-width: 820px) {
        .main {
            padding: 0px !important;
        }
    }

    @media only screen and (max-width: 768px) {
        .today-gold-price {
            width: 100% !important;
            left: 0px !important;
        }

        .d-sm-none {
            display: block !important;
        }


        h3 {
            font-size: 1.75rem;
        }

        #sticky_header .mobile-search form input {
            width: 350px;
        }

        #sticky_header {
            justify-content: center;
        }
    }




    @media only screen and (max-width: 425px) {
        .today-gold-price>.card-body>.col-md-12 {
            display: grid !important;
            align-items: center;
            justify-content: center;
        }

        .today-gold-price>.card-body>.col-md-12>.price {
            border-right: none;
            border-bottom: 0.1px solid #d7d7d7;
            padding: 20px 0;
            text-align: center;
        }

        .today-gold-price>.card-body>.col-md-12>.price:last-child {
            border-right: none;
            border-bottom: none;
        }

        .newsletter {
            display: grid !important;
        }

        .newsletter>label {
            width: 100% !important;
        }

        .newsletter>input {
            width: 100% !important;
        }

        .card_header-card {
            right: 40px !important;
        }

        .card_header-card {
            float: left !important;
            left: 50%;
            transform: translate(-50%, 0%);
            right: 0px !important;
        }

        #sticky_header .mobile-search form input {
            width: 200px !important;
        }

        .selectPlace {
            width: 190px !important;
        }
    }


    @media only screen and (max-width: 375px) {
        .card_header-card {
            right: 30px !important;
        }

        #sticky_header .mobile-search form input {
            width: 175px !important;
        }
    }

    @media only screen and (max-width: 320px) {
        .card_header-card {
            right: 30px !important;
        }

        #sticky_header .mobile-search form input {
            width: 130px !important;
        }

        #sticky_header .logo img {
            width: 50px !important;
        }
    }

    @media only screen and (max-width: 280px) {
        .card_header-card {
            right: 5px !important;
            width: 250px !important;
        }


        #sticky_header .mobile-search form input {
            width: 100px !important;
        }

        #sticky_header .logo img {
            width: 40px !important;
        }
    }

    .submit {
        background: #6e2083;
        border: 1px solid #6e2083;
        color: #ffffff !important;
    }

    .submit:hover {
        background: #6e2083;
        border: 1px solid #6e2083;
        color: #ffffff !important;
    }


    .place {
        text-transform: capitalize;
        font-weight: 900;
    }

    .bannercard {
        color: #6e2083;
        font-weight: 800;
    }

    .card_header-card {
        width: 300px;
        border-radius: 10px;
        float: right;
        top: 50px;
        right: 100px;
        z-index: 0;
    }

    .bannercard>p {
        font-size: 14px;
        font-weight: 500;
    }


    .banner-images {
        padding: 0px !important;
        overflow: hidden;
        background-image: url('https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/header.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        height: 450px;
    }

    .currentDate {
        font-weight: 700;
        color: #000000;
        font-size: 18px;
    }

    .todayGoldPrice {
        font-weight: 700;
        color: #000000;
        font-size: 18px;
    }

    .selectPlace {
        border: 0.5px solid #d7d7d7;
        border-radius: 30px;
        width: auto;
        font-weight: 700;
        color: #000000;
        font-size: 18px;
        text-transform: capitalize;
        width: 100%;
        height: 40px;
    }

    .selecting_spans {
        color: #818181;
        font-size: 12px;
    }

    .today-gold-price {
        width: 60%;
        left: 20%;
        align-items: center;
        padding: 20px 0 20px 0;
        box-shadow: 1px 5px 15px 3px #d5d5d5;
        border-radius: 15px;
    }

    .align_explore {
        margin-left: 50%;
        transform: translate(-50%, 0%);
    }

    .page-header {
        margin: 0 !important;
    }

    .text>li {
        list-style: disc;
        margin-left: 20px;
    }

    .textol>li {
        list-style: decimal;
        margin-left: 20px;
    }

    h3,
    h4,
        {
        color: #000000;
    }


    p {
        text-align: justify;
    }

    .page-title-wrapper.category-heading {
        margin-top: 0px;
    }

    .newsletter {
        height: 35px !important;
    }


    .customer_sliders {
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .section {
        text-align: center;
        margin-top: 2.5%;
    }

    .scroll-arrow {
        display: inline-block;
        position: relative;
        vertical-align: middle;
        cursor: pointer;
        padding: 0;
        margin: 0;
        opacity: 0.5;
        font-size: 34px;
        transition: 0.2s;
    }

    .scroll-arrow:hover {
        transition: 0.2s;
        opacity: 1;
    }

    .imgList {
        scroll-behavior: smooth;
        display: inline-block;
        position: relative;
        vertical-align: middle;
        text-align: center;
        overflow-x: scroll;
        overflow-y: hidden;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .imgList::-webkit-scrollbar {
        display: none;
    }

    .product_main:hover {
        transition: 0.2s;
    }

    /*My style*/
    .product_main {
        /*li*/
        list-style: none;
        display: inline-block;
        position: relative;
        vertical-align: middle;
        margin-left: 1.5%;
        transition: 0.2s;
        width: 300px;
        /*li*/
        width: fit-content;
        border: #6c757d1f !important;
        border-style: groove !important;
        border-width: 1px !important;
        margin-bottom: 0px !important;
        padding-bottom: 0px !important;
        height: fit-content;
    }

    .product_container {
        width: 225px !important;
    }


    .product_details_slider {
        background-color: #d3d3d35e;
        height: 70px;
    }

    .product_name_slider {
        overflow: hidden;
        color: gray;
        font-size: .9em;
        margin: 0 10px 0 10px;
        padding: 10px 0 3px 0;
        text-overflow: ellipsis;
    }

    .price_slider {
        font-size: 15px !important;
        color: #1c1821;
        font-weight: 800 !important;
        display: flex;
        justify-content: center;
    }

    .page-title-wrapper {
        display: none;
    }

    @media screen and (max-width: 450px) {
        .scroll-arrow {
            width: auto;
        }
    }

    .heading2 {
        font-size: 20px;
    }
    </style>


</head>

<body>