<script src="https://accounts.google.com/gsi/client" async defer></script>
<script>
  window.onload = function () {
    google.accounts.id.initialize({
      client_id: '49100888762-mjfhjssracvndpteeuqc0efm1vbggihv.apps.googleusercontent.com', // Replace with your Google Client ID
      callback: handleCredentialResponse  // We choose to handle the callback in client side, so we include a reference to a function that will handle the response
    });
    google.accounts.id.prompt();
  }
</script>
<script>
     function handleCredentialResponse(response) {
          // Here we can do whatever process with the response we want
          // Note that response.credential is a JWT ID token
          console.log(response)
          console.log(JSON.stringify(parseJwt(response.credential)));
     }
     function parseJwt (token) {
        var base64Url = token.split('.')[1];
        var base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        var jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
         return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
     }).join(''));

       return JSON.parse(jsonPayload);
     };
</script>
