<?php  

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$store = $storeManager->getStore();

$currency=$store->getCurrentCurrencyCode();

$rate = $store->getCurrentCurrencyRate();


$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $object_manager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('pricemanager');

//Select Data from table
$sql = "Select * FROM  $tableName WHERE id = 1" ;
$result = $connection->fetchAll($sql);


 ?>
<style>
    button.subscription:active,button.subscription:hover {
        background-color:#6e2083;
    }
    h1.table-heading {
    padding: 17px 0 3px;
    font-size: 16px;
    letter-spacing: 1px;
    color: #6e2083;
    font-weight: 700;
}
</style>

<div class="metal-table">
<h1 style="font-size: 17px;margin-bottom: 8px" class="table-heading">TODAY'S GOLD RATE</h1>
<table class="table table-borderless">
<thead>
<tr>
<th>Metal</th>
<th>Purity</th>
<th>Price per Gram</th>
</tr>
</thead>
 <?php if($currency=='INR'): ?>
<tbody>
<tr>
<td>Gold</td>
<td>24 KT</td>
<td><?php echo $result[0]['24K']; ?> INR</td>
</tr>
<tr>
<td>Gold</td>
<td>22 KT</td>
<td><?php echo $result[0]['22K']; ?> INR</td>
</tr>
<tr>
<td>Gold</td>
<td>18 KT</td>
<td><?php echo $result[0]['18K']; ?> INR</td>
</tr>
<tr>
<td>Silver</td>
<td>100%</td>
<td><?php echo $result[0]['hundred']; ?> INR</td>
</tr>
<tr>
<td>Platinum</td>
<td>99.5</td>
<td><?php echo $result[0]['p_hundred']; ?> INR</td>
</tr>
</tbody>
<?php else: ?>
<tbody>
<tr>
<td>Gold</td>
<td>24 KT</td>
<td><?php echo $result[0]['24K']*$rate; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>22 KT</td>
<td><?php echo $result[0]['22K']*$rate; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>18 KT</td>
<td><?php echo $result[0]['18K']*$rate ; ?></td>
</tr>
<tr>
<td>Silver</td>
<td>100%</td>
<td><?php echo $result[0]['hundred']*$rate; ?></td>
</tr>
<tr>
<td>Platinum</td>
<td>995</td>
<td><?php echo $result[0]['p_hundred']*$rate; ?></td>
</tr>
</tbody>
<?php endif; ?>
</table>
<button onclick='document.getElementById("middle").scrollIntoView({
            behavior: "smooth"
        });' class="subscription">Subscribe for Gold Rate Update</button></div>