<div class="inner-block-newsletter" style="content-visibility: auto; contain-intrinsic-size: 80px;">
    <div class="container-fluid d-flex justify-content-between px-5 py-3">
        <h2 >Sign Up for Our Newsletter:</h2>
        <div class="align-items-center d-flex w-70">
            <input class="p-2" type="text" placeholder="Email">
            <button class="p-2">SUBSCRIBE</button>
        </div>
    </div>
</div>
</div>