<div class="inner-block-testimonials p-2 bg-color-grey3">
    <div id="slider" class="w-100" style='max-width: 100%;'>
        <div id="deo1" class="carousel slide" data-ride="carousel">
    
            <!-- Indicators -->
            <!-- <ul class="carousel-indicators">
                <li data-target="#deo" data-slide-to="0" class="active"></li>
                <li data-target="#deo" data-slide-to="1"></li>
                <li data-target="#deo" data-slide-to="2"></li>
            </ul> -->
    
            <!-- The slideshow -->
           

<div class="carousel-inner">
   <div class="carousel-item active">
      <div class='row w-100 m-0'>
         <div class='col-md-4'>
            <div class='div-border'>
               <div class="youtube border-0 mr-2 w-100" data-embed="sUeTcnz8QMo">
                  <div class="play-button"></div>
               </div>
            </div>
         </div>
         <div class='col-md-4'>
            <div class='div-border'>
               <div class="youtube border-0 mr-2 w-100" data-embed="bIAINaRHfpw">
                  <div class="play-button"></div>
               </div>
            </div>
         </div>
         <div class='col-md-4'>
            <div class='div-border'>
               <div class="youtube border-0 mr-2 w-100" data-embed="8lt1aSw8UMs">
                  <div class="play-button"></div>
               </div>
            </div>
         </div>
      </div>
   </div>
   </div>
    
            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#deo1" data-slide="prev">
                <span class="carousel-control-prev-icon fa fa-angle-left"></span>
            </a>
            <a class="carousel-control-next" href="#deo1" data-slide="next">
            <span class="carousel-control-next-icon fa fa-angle-right"></span>
            </a>
        </div>
    </div>
</div>
<script type="text/javascript">

    ( function() {

    var youtube = document.querySelectorAll( ".youtube" );
    
    for (var i = 0; i < youtube.length; i++) {
        
        var source = "https://img.youtube.com/vi/"+ youtube[i].dataset.embed +"/sddefault.jpg";
        
        var image = new Image();
                image.src = source;
                image.addEventListener( "load", function() {
                    youtube[ i ].appendChild( image );
                }( i ) );
        
                youtube[i].addEventListener( "click", function() {

                    var iframe = document.createElement( "iframe" );

                            iframe.setAttribute( "frameborder", "0" );
                            iframe.setAttribute( "allowfullscreen", "" );
                            iframe.setAttribute( "src", "https://www.youtube.com/embed/"+ this.dataset.embed +"?rel=0&showinfo=0&autoplay=1" );

                            this.innerHTML = "";
                            this.appendChild( iframe );
                } );    
    };
    
} )();
</script>