<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
    $_helper    = $this->helper('Magento\Catalog\Helper\Output');
    $_category  = $block->getCurrentCategory(); //$_category
    //print_r($_category->getData());die();
    //echo $_category->getImageUrl();die();
    $_imgHtml   = '';
    
    if ($_imgUrl = $_category->getImageUrl()) {
          $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    //print_r($category->getData());die();
    $getalt=$category->getData('mainbanner_alttext');
        //echo "imgurl".$_imgUrl;die();
    	//$logger->info($_imgUrl);
        $_imgHtml = '<img class="category-banner image" src="' . $_imgUrl . '" alt="'.$getalt.'" width="1510" height="354" />';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        /* @escapeNotVerified */ echo $_imgHtml;
    }
else {?>
<div class="myspacediv" style="margin-top:18px;"></div>
<?php }
?>


