
<?php  ?>


		<div class="filter-list">
			<span>Price</span>
			<ul class="filter-items">
				<li class="filter-item-list">Shop for</li>
				<li class="filter-item-list">Occasion</li>
				<li class="filter-item-list">Earring style</li>
				<li class="filter-item-list">Gemstone</li>
				<li class="filter-item-list">Gifts</li>
				<li class="filter-item-list">Theme</li>
			</ul>
		</div>
		<div class="filter-list">
			<span>Product type</span>
			<ul class="filter-items">
				<li class="filter-item-list">Shop for</li>
				<li class="filter-item-list">Occasion</li>
				<li class="filter-item-list">Earring style</li>
				<li class="filter-item-list">Gemstone</li>
				<li class="filter-item-list">Gifts</li>
				<li class="filter-item-list">Theme</li>
			</ul>
		</div>
		<div class="filter-list">
			<span>weight ranges</span>
			<ul class="filter-items">
				<li class="filter-item-list">Shop for</li>
				<li class="filter-item-list">Occasion</li>
				<li class="filter-item-list">Earring style</li>
				<li class="filter-item-list">Gemstone</li>
				<li class="filter-item-list">Gifts</li>
				<li class="filter-item-list">Theme</li>
			</ul>
		</div>
		<div class="filter-list">
			<span>Material</span>
			<ul class="filter-items">
				<li class="filter-item-list">Shop for</li>
				<li class="filter-item-list">Occasion</li>
				<li class="filter-item-list">Earring style</li>
				<li class="filter-item-list">Gemstone</li>
				<li class="filter-item-list">Gifts</li>
				<li class="filter-item-list">Theme</li>
			</ul>
		</div>
		<div class="filter-list">
			<span>metal</span>
			<ul class="filter-items">
				<li class="filter-item-list">Shop for</li>
				<li class="filter-item-list">Occasion</li>
				<li class="filter-item-list">Earring style</li>
				<li class="filter-item-list">Gemstone</li>
				<li class="filter-item-list">Gifts</li>
				<li class="filter-item-list">Theme</li>
			</ul>
		</div>
		<div class="filter-list" data-toggle="modal" href='#more_filters'>
			<span>see more filters</span>
		</div>
