<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
//echo $mediaUrl;die();
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>
<?php
     $_helper    = $this->helper('Magento\Catalog\Helper\Output');
     $_category  = $block->getCurrentCategory();
      //echo $mediaUrl.$_imgUrl = $_category->getImageUrl('mobile_banner');die();
     $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl('mobile_banner')) {
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
        $getalt=$category->getData('mainbanner_alttext');
        $_imgHtml = '<picture><source type="image/webp" data-srcset="' . $_imgUrl . '" srcset="' . $_imgUrl . '"><img class="category-banner image" height="160" width="360" src="' . $_imgUrl . '" data-srcset="' . $_imgUrl . '" srcset="' . $_imgUrl . '" alt="'.$getalt.'" data-pagespeed-no-transform style="width: 100%;"/></picture>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
        /* @escapeNotVerified */ echo $_imgHtml;
    }  

?>


