<div id="messages"><div class="messages"><div class="message message-notice notice"><div><?php echo __('<b>TIP:</b> Use this module to update the product image after import the products.'); ?></div></div></div></div>
<div class="download_image_info">
<p><?php echo __("This module is used to download products images from the live URLs and generate CSV according to our extension.") ?></p>
<p>&nbsp;</p>
<p><b><?php echo __("HOW TO USE") ?>:-</b></p>
<ul>
	<li><?php echo __("1. Make your CSV file as per given") ?> <a href="https://www.magebees.com/media/mconnect_uploadfiles/import-export-products-magento-2-csv/download_images_sample.csv" target="_blank"><?php echo __("Sample CSV") ?></a> <?php echo __("file.") ?></li>
	<li><?php echo __("2. Upload a file from the 'Download Products Images' section. ")?></li>
	<li><?php echo __("3. Click on the 'Download Images and Generate CSV' button. ")?></li>
	<li><?php echo __("4. Your images are downloaded and stored in the pub/media/import folder and generate CSV file according to our extension and store in the var/import folder.")?></li>
	<li><?php echo __("5. Now goto MageBees -> Import Export Products -> Import Products -> Run Profile. Select your generated CSV file and click on Validate & Import File Data Button.")?></li>
</ul>
</div>