<div class="docwrap">
	<div class="secone"><a href="https://www.magebees.com/media/mconnect_uploadfiles/user_guide_magebees_import_export_products_for_magento_2.pdf" target="_blank"><?php echo __("User Guide") ?></a></div>
	<div class="secone"><a href="https://www.magebees.com/media/mconnect_uploadfiles/i/m/import_export_product_sample_csv.zip" target="_blank"><?php echo __("Sample CSV Files") ?></a></div>
</div>