<div id="messages"><div class="messages"><div class="message message-notice notice"><div><?php echo __('<b>TIP:</b> Use this module to update the product image after import the products.'); ?></div></div></div></div>
<div class="download_image_info">
<p><?php echo __("This module is used to download products images from live URL and generate CSV according to our extension.") ?></p>
<p>&nbsp;</p>
<p><b><?php echo __("HOW TO USE") ?> :-</b></p>
<ul>
	<li><?php echo __("1. Make your CSV file as per given") ?> <?php echo __("Sample CSV") ?> <?php echo __("file.") ?></li>
	<li><?php echo __("2. Upload file from 'Download Products Images' section. ")?></li>
	<li><?php echo __("3. Click on 'Download Images and Generate CSV' button. ")?></li>
	<li><?php echo __("4. Your images are downloaded and stored in <b>pub/media/import</b> folder and generate CSV file according to our extension and store in <b>var/import</a></b> folder.")?></li>
	<li><?php echo __("5. Now goto <b>MageBees -> Import Export Products -> Import Products -> Run Profile</b>. Select your generated CSV file and click on Validate & Import File Data Button.")?></li>
</ul>
</div>