<?php
/** @var \Mirasvit\SeoToolbar\Block\Toolbar $block */
?>
<div class="mst-seo-toolbar__toolbar">
    <div class="mst-seo-toolbar__toolbar-header" data-role="header">
        <i class="fa fa-tachometer"></i> <?= __('SEO Toolbar') ?>

        <div class="close" data-role="close">
            <div class="icon-close">×</div>
        </div>
    </div>

    <div class="mst-seo-toolbar__toolbar-content">
        <?php foreach ($block->getSections() as $section => $items): ?>
            <section>
                <label><?= $section ?></label>

                <ul>
                    <?php /** @var \Mirasvit\SeoToolbar\Api\Data\DataProviderItemInterface $item */ ?>
                    <?php foreach ($items as $item): ?>
                        <li>
                            <div class="title"><?= $item->getTitle() ?></div>
                            <div class="status _<?= $item->getStatus() ?>"></div>
                            <div class="description">
                                <?= nl2br($block->escapeHtml($item->getDescription())) ?>
                                <div class="note"><?= nl2br($block->escapeHtml($item->getNote())) ?></div>
                            </div>
                            <?= $item->getAction() ?>
                        </li>
                    <?php endforeach ?>
                </ul>
            </section>
        <?php endforeach ?>
    </div>
</div>

<script>
    require([
        'jquery',
        'mage/cookies'
    ], function ($) {
        var $toolbar = $('.mst-seo-toolbar__toolbar');
        var cookieName = "mst-seo-toolbar";

        if ($.mage.cookies.get(cookieName) === 'off') {
            $toolbar.removeClass('_hidden').addClass('_hidden');
        } else {
            $toolbar.removeClass('_hidden');
        }

        $('[data-role=close]', $toolbar).on('click', function (e) {
            e.preventDefault();
            $toolbar.removeClass('_hidden').addClass('_hidden');
            $.mage.cookies.set(cookieName, 'off', {expires: new Date(Date.now() + (24 * 60 * 60)), path: '/'});
        });

        $('[data-role=header]', $toolbar).on('click', function (e) {
            if (!$(e.target).hasClass('icon-close')) {
                e.preventDefault();
                $toolbar.removeClass('_hidden');
                $.mage.cookies.set(cookieName, 'on', {expires: new Date(Date.now() + (24 * 60 * 60)), path: '/'});
            }
        });
    });
</script>
