<?php 
$product = $this->getCurrentProduct() ?>
<?php 

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
	//$StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
	$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
    $emiController = $product->getResource()->getAttribute('emi_controller')->getFrontend()->getValue($product);
    $attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
    $attributeSetRepository = $attributeSet->get($product->getAttributeSetId());
    $attribute_set_name = $attributeSetRepository->getAttributeSetName();
	  $producttype = $product->getTypeId();
	 //$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
    $_product = $block->getProduct(); // quantity_and_stock_status
	//$producttype = $product->getTypeId();
    if ($currentProduct = $block->getCurrentProduct()) {
    $product_name = $currentProduct->getName();
     $product_id =   $currentProduct->getSku();
     $product_price =   $currentProduct->getFinalPrice();
   }
    $productQty = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
?>
<div class="left_price_break">
<span class="price_btn">View Price break up</span>
</div>
<?php if($emiController == 'Yes' && $attribute_set_name == 'Default'){ ?>

<!-- <div class="view_emi">
    <span id="emi_opt_btn" class="emi-plans">View EMI plans</span>
</div> -->
<?php } ?>
<?php if($product && $product->getCheckDeliveryEnable()==1): ?>
	<form data-mage-init='{"validation": {}}' class="form" id="checkDelivery-form" method="post" autocomplete="off" onSubmit="return checkPostcode()">
		   <!--legend class="legend"><span><?php // echo __('Check Delivery') ?></span></legend><br-->
		   <!--<a href="#" data-toggle="tooltip" title="Hooray!"><span class="fa fa-bell"></span></a>-->
			
			 <?php if($productQty == 0 && $producttype == 'simple') { ?>
				<div style="display:block;">
					<label for="delivery_postcode" class="label">
            <span class="ish" style="font-size: 15px;"><?php echo __('International Shipment') ?></span>
          </label>
					<input id="international-checkbox" name="checkboxsss" type="checkbox" >
				</div>
				<div id="international-shipment-div" class="control" style="display:none;">
					<input type="text" placeholder="530016" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
				</div>
        <div class="contact-section mb-4">
          <div class="d-inline-block mr-3" style="width: 50%">
          <div id="delivery-form" class="container__item">
          <input type="text" value="" data-validate="{required:true, 'validate-digits':true}" name="postcode" id="delivery_postcode"  class="delivery-code form__field" placeholder="530016" style="width: 90% !important; margin-top: 0px !important;margin-bottom: 0px !important; " />
        <button type="submit" class="cust-btn cust-btn--primary cust-btn--inside uppercase">Check</button>
          </div>
        </div>

          <div class="contact-us d-inline-block px-4 pt-1" style="width: 50%; border-left: 0px !important;">
            <div class="d-inline-block align-top mr-2"><img loading="lazy" width="32" height="32" class="img-fluid" src="<?php echo $this->getUrl('pub/media/');?>contact.svg" alt="Contact"></div>
            <div class="d-inline-block align-right"  style="width: 78%"><div class="font-weight-bold">+ 91 91774 03000</div> <div class="need-help">Need help? Call us</div></div>
          </div>
          </div>
				<?php } else {  ?>
					<div class="international_Shipment">
						<label for="delivery_postcode" class="label"><span class="ish" style="font-size: 15px; "><?php echo __('For international Shipment') ?></span></label>
						<input id="international-checkbox" name="checkboxsss" type="checkbox" >
					</div>
				  <div id="international-shipment-div" class="control" style="display:none;">
          <input type="text" placeholder="530016" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
          </div>   
<div class="contact-section mb-4">
    <div class="d-inline-block mr-3" style="width: 50%">
    <div id="delivery-form" class="container__item">
        <input type="text" value="" data-validate="{required:true, 'validate-digits':true}" name="postcode" id="delivery_postcode"  class="delivery-code form__field" placeholder="530016" style="width: 90% !important; margin-top: 0px !important;margin-bottom: 0px !important; " />
        <button type="submit" class="cust-btn cust-btn--primary cust-btn--inside uppercase">Check</button>
    </div>
  </div>

          <div class="contact-us d-inline-block px-4 pt-1" style="width: 50%; border-left: 0px !important;">
            <div class="d-inline-block align-top mr-2"><img loading="lazy" width="32" height="32" class="img-fluid" src="<?php echo $this->getUrl('pub/media/');?>contact.svg" alt="Contact"></div>
            <div class="d-inline-block align-right"  style="width: 78%"><div class="font-weight-bold">+ 91 91774 03000</div> <div class="need-help">Need help? Call us</div></div>
          </div>
          </div>
			<?php } ?>
			
			<div class="message" style="margin:75px auto 10px auto; padding: 10px 10px; width: 100%; position: relative;height: auto;"></div>
		
	</form>
	<script type="text/x-magento-init">
		{
			"#checkDelivery-form": {
				"validation": {}
			}
		}
	</script>
	<script>
		function checkPostcode() {
			var deliveryMessage = jQuery('#checkDelivery-form .message');
			deliveryMessage.removeClass('success').removeClass('error').hide();
			var deliveryForm = jQuery('#checkDelivery-form');
			if(deliveryForm.valid()) {
			 //    dataLayer.push({'event':'pincode_check_product',
    //     'pincode':jQuery('#delivery_postcode').val()
       
    // });
				jQuery.ajax({
					type: "POST",
					url: '<?php echo $this->getUrl('checkDelivery/postcode/check',array('id'=>$product->getId())) ?>',
					data: deliveryForm.serialize(),
					dataType: "json",
					showLoader: true,
					success: function(response) {
						deliveryMessage.addClass(response.type).html(response.message).show();
						jQuery('.showmessage').hide();
                        jQuery('.showmessage1').hide();
					}
				});
			}
			return false;
		}
	require([ 'jquery', 'jquery/ui'], function($){ 
      $(document).ready(function($) {
		$('#international-checkbox').change(function () {
        if (!this.checked){
			     $('#form_type').val(1);
           $('#delivery-form').show();
           $('#product-addtocart-button').show();
           $('#buy-now').show();
           $('.contact-section').show();
		       $('#international-button').hide();
		}
    else 
		{
  			 $('#form_type').val(0);
  			 $('#delivery-form').hide();
  			 $('#product-addtocart-button').hide();
  			 $('#buy-now').hide();
  			 $('#international-button').show();
  			 $('.showmessage').hide();
         $('.contact-section').hide();
        $('.showmessage1').hide();
		}
    });
      });
 });
	</script>
<?php 
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockqty = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('checkDelivery/config/success_message');
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$shippingCode = $product->getData('expected_delivery_date');
$smartbuy = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
if(isset($shippingCode)){
                 $cusdate = $shippingCode;
                $dt = date("Y-m-d");
                $Expecteddate = date( 'd M, Y', strtotime( "$dt +$cusdate day" ) );
                $Finalmessage = str_replace('one week', $Expecteddate, $conf);
                /*$response['type'] = 'success';
                $response['message'] = $Finalmessage;*/
                }/*else{
                    $response['type'] = 'success';
                    $response['message'] = $Finalmessage;//$SuccessMessage; 
                } */
?>
<?php if(isset($shippingCode) ) { ?>
<div class="showmessage1" style="text-align: left;color: green;"><?php echo $Finalmessage;?></div>
<?php } elseif($producttype != 'configurable'){ ?>
<div class="showmessage1" style="text-align: left;color: green;"><?php echo $conf;?></div>
<?php } ?>


<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
    $product = $this->getCurrentProduct();
     $_product = $block->getProduct();
  $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());

if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0  && $producttype == 'simple')
{ ?>
  <div id="international-button" style="display: block;">
    <button type="button"class="p-3 try-on send_enquiry en-button" style="background: #6e2083;"><img class="shop-img" src="https://www.vaibhavjewellers.com/pub/media/camera.svg" alt=""> <span>SEND ENQUIRY</span> </button>
  </div>
<?php } else { ?>
  <div id="international-button" style="display:none">
    <button type="button"class="p-3 try-on bg-color-voilet send_enquiry en-button" style="background: #6e2083;"><img class="shop-img" src="https://www.vaibhavjewellers.com/pub/media/camera.svg" alt=""> <span>SEND ENQUIRY</span> </button>
  </div>
<?php } ?>


<?php if(true){?>
<div id="header-mpdal-customer" style="display:none;">

<h2>For Product Enquiry</h2>
  <h3>Provide your details</h3>
    <form class="form-customer-equiry" onsubmit="return IsRecapchaValid()" action="<?php echo $this->getUrl('sendinquiry/index/postnew', ['_secure' => true]); ?>" id="meghraj_custdes_form1" method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
      <div class="form-5">
        <div class="inputbox1">
          <input name="name" id="name" type="text" class="input-text required-entry in" placeholder="Full Name" /> 
        </div>
        <input name="productname" value="<?php echo $product->getName(); ?>"  type="hidden" /> 
        <input name="producturl" value="<?php echo $product->getProductUrl(); ?>"  type="hidden"  /> 
        <input name="productcode" value="<?php echo $product->getSku(); ?>"  type="hidden" /> 
        <input name="type" id="form_type" value="1"  type="hidden" /> 
        
        <div class="inputbox1">
          <input name="email" id="emailenq" type="text" class="input-text required-entry validate-email in" placeholder="Email Address" /> 
        </div>
        <div class="inputbox1"> 
          <input name="contact" id="contact" type="text" class="input-text required-entry in" placeholder="Mobile Number" />
          <span id="errmsg" style="color: red; text-align:center;"></span>
        </div>
        <div class="inputbox1"> 
          <input name="area" id="area" type="text" class="input-text required-entry in" placeholder="Area" />
        </div>
        <div class="textareainputbox1">
          <textarea name="details" id="details" class="input-text required-entry in" placeholder="Details of Jewellery"></textarea>
          <span id="spntxt" style="color: red; text-align:center;"></span>
        </div>
         <div style="display: flex;flex-direction: column; align-items: center;">
      <div class="g-recaptcha" data-sitekey="6LeuJPIUAAAAAII47muzblK2Z1wubDtwPJZgnek4"></div>
      <div  id="captcha-error" style="text-align: center;margin-top: 5px;color: #e02b27;font-size: 0.9rem;" ></div>
    </div>
        <div class="submitbtn1">
          <button name="submit" id="sub" onclick="return chk()">Submit</button>
        </div>
      </div>
    </form>
</div>
<?php } ?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            if (jQuery("#header-mpdal-customer").length != 0) { 
            var popup = modal(options, $('#header-mpdal-customer'));
            $("#international-button").on('click',function(){ 
                $("#header-mpdal-customer").modal("openModal");
            });
            }

        }
    );
</script>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 $(document).ready(function(){
   $("#contact").keypress(function (e) {
     //if the letter is not digit then display error and don't type anything
     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
        //display error message
        $("#errmsg").html("Digits Only").show().fadeOut("slow");
          return false;
    }
   });
    $("#details").keypress(function (e){
       var yourInput = $(this).val();
    re = /[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi;
    var isSplChar = re.test(yourInput);
    if(isSplChar)
    {
     $("#spntxt").html("Special Characters are not allow").show().fadeOut("slow");
         //return false;
         var no_spl_char = yourInput.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '');
      if(no_spl_char){
      $(this).val(no_spl_char);
      return true;
    }
    }
   });
   $("#sub").click(function(){
        /*details validation*/
        var des = $("#details").val();
        var contact = $("#contact").val();
        var area = $("#area").val();
    re = /[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi;
    var isSplCharDes = re.test(des);
    var isSplCharContact = re.test(contact);
    var isSplCharArea = re.test(area);
    if(isSplCharDes || isSplCharContact || isSplCharArea)
    {
     $("#spntxt").text("Special Characters are not allow in this form");
         return false;
    }else{
      $("#spntxt").text("");
         return true;  
    }
   });
 }); 
}); 
</script>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
    async defer>
</script>
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
  <script type="text/javascript">
  var onloadCallback = function() {

  };
   function IsRecapchaValid() 
                                {
                                    var v = grecaptcha.getResponse();
                                     //console.log("praveen");   
                                    if(v.length == 0)
                                    {
                                       // document.getElementById('captcha').innerHTML="You can't leave Captcha Code empty";
                                       document.getElementById('captcha-error').innerHTML="Please Check captcha";

                                        return false;
                                    }
                                    else
                                    {
                                      document.getElementById('captcha-error').innerHTML="";
                                        //document.getElementById('captcha').innerHTML="";
                                        return true; 
                                    }
                                }
</script>
<?php endif; ?>


<script>
   require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            
            $(".price_btn").on('click',function(){ 
              $("#price_breakup_btn").trigger("click");
              
            });
          }
    );
</script>
<style type="text/css">
            .uppercase {
  text-transform: uppercase;
}
.international_Shipment{
  /*padding-bottom: 12px;
  float: right;*/

}
.international_Shipment span.ish{
  font-size: 13px !important;
}

.left_price_break{
    /*float: left;*/
    /*font-size: xx-large;*/
    /*margin-top: 3%;*/
}

.cust-btn {
  display: inline-block !important;
  background: transparent !important;
  color: inherit !important;
  font: inherit !important;
  border: 0 !important;
  outline: 0 !important;
  padding: 0 !important;
  -webkit-transition: all 200ms ease-in !important;
  transition: all 200ms ease-in !important;
  cursor: pointer !important;
}
.cust-btn--primary {
  background: #b272d3 !important;
    color: #fff !important;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1) !important;
    border-radius: 2px !important;
    padding: 7px 14px !important;
}
.cust-btn--primary:hover {
  background: #b272d3 !important;
}
.cust-btn--primary:active {
  background: #7f8ff4 !important;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2) !important;
}
.cust-btn--inside {
  margin-left: -50px !important;
}
#delivery_postcode-error {
 position: absolute;
 margin-left: 30px;
 font-size:0.8rem !important;
}
.form__field:not([disabled]):focus {
      box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1) !important;
}

.form__field {
 width: 250px !important;
    /*background: #f5f6fa !important;*/
    color: #a3a3a3 !important;
    font: 500 12px/1.55 Lato,sans-serif !important;
    height: 100% !important;
    box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1) !important;
 /*   border: 0 !important;
    outline: 0 !important;*/
    padding: 18px 12px !important;
}
#checkDelivery-form .message.success, #checkDelivery-form .message.error {
    margin: 72px 0 0px;
    padding: 12px 15px 12px 0px;
    font-size: 12px;
    padding-left: 15px;

}
.showmessage, #checkDelivery-form .message.success {
  display:block;
    font-size: 12px;
    color: #006400;
     margin :71px auto 0px auto;
     background: #e5efe5;
    color: #006400;
    height: 26px;
    padding: 5px 10px;
    width: 70%;
    position: relative;
}
#checkDelivery-form .message.success {
  display:block;
    font-size: 12px;
    color: #006400;
    margin :20px auto 0px auto;
     background: #e5efe5;
    color: #006400;
    height: auto;
    padding: 5px 10px;
    width: 70%;
    position: relative;
}

#international-button{
  margin-top: 20% !important;
}
.emi_opt_btn {
    letter-spacing: 0.2px;
    color: darkcyan;
    text-transform: uppercase;
    font-weight: 600;
    font-size: 14px;
}
.message.error {
    display: block;
    color: #e02b27;
    position: relative;
}
</style>