<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<div id="sticky_header" class="container-fluid  mt-2" style="display: none;">
    <div class="align-items-center d-flex">
        <div class="align-items-center d-flex justify-content-start">
        <span  class="nav-toggle menu-open"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
        <?php if ($block->isHomePage()):?>
            <strong class="logo">
        <?php else: ?>
            <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
        <?php endif ?>
                <img class="w-65" src="<?= /* @escapeNotVerified */$this->getUrl('pub/media/');?>sticky_vaibhav_logo.png"
                     title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                     alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                />
        <?php if ($block->isHomePage()):?>
            </strong>
        <?php else:?>
            </a>
        <?php endif?>
    </div> 
<div class="align-items-center d-flex justify-content-end">
    <div id="sticky_search_container">
    </div>
     <div id="sticky_switcher_container">
    </div>
     <div id="sticky_cart_container">
    </div>
</div>
    </div>
    </div>
<div class="container-fluid  mt-2">
<div class="align-items-center d-flex">
    <div class="align-items-center d-flex justify-content-start">
        <span  class="nav-toggle menu-open"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
        <?php if ($block->isHomePage()):?>
            <strong class="logo">
        <?php else: ?>
            <a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
        <?php endif ?>
                <img class="w-65" src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
                     title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                     alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
                     <?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
                     <?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
                />
        <?php if ($block->isHomePage()):?>
            </strong>
        <?php else:?>
            </a>
        <?php endif?>
    </div>
