<?php $helper = $this->helper("Prince\Buynow\Helper\Data"); ?>


<?php $addtocartId = $helper->getConfig('buynow/general/addtocartid'); ?>

<?php $buttonTitle = $helper->getConfig('buynow/general/buttontitle'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$sku = $product->getSku();
$product_type = $product->getTypeId();
$lengths = 35;

$smart_percentage = $product->getResource()->getAttribute('smart_percentage')->getFrontend()->getValue($product);
$productId = $product->getId();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$StockState = $StockState->getStockQty($productId);
$categories = $product->getCategoryIds();
$checkout_url = $block->getUrl('checkout');
$loginstatus=false;
$customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');
if ($customerSession->isLoggedIn() == true) {
  $loginstatus=true;
} 
?>
<input type="hidden" id="add-cart-detail" data-id="<?php echo $productId; ?>" value="<?php echo $block->getUrl('videoform/index/addtocart'); ?>">
  <?php if ($smart_percentage !="0" && isset($smart_percentage)):?>
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now-offer" class="shop-img cart" disabled data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '><img class="shop-img shop-img-bag" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
 <?php else : ?>
 <?php if($loginstatus) { ?>
  <button  type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="shop-img cart"  data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '><img class="shop-img shop-img-bag" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
  <?php } else { ?>
 <button  type="button" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="shop-img cart"><img class="shop-img shop-img-bag" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
  <?php } ?>
    <?php endif; ?>
 <?php 
$giftcard=0;
if (in_array('135', $categories)) { 
   $giftcard=1;
 } ?>   

<?php if($giftcard==1): ?>
    <script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 $(document).ready(function(){

   $("#buy-now").click(function(){
    console.log('Sarvesh Tiwari');
 if ($('#product_addtocart_form').valid()) {
                 window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 1000); 
            }else{
                alert("Please fill all required fields");
                //return false;
            }
});
});
}); 
</script>  
<?php else: ?>
  <script type="text/javascript">
require([
    'jquery',
    'mage/mage',
    'Magento_Ui/js/modal/modal'
], function($,modal){
 $(document).ready(function(){
      var product_type = "<?php echo $product_type; ?>";
  $("#buy-now").click(function(e){
     e.preventDefault();
    //  dataLayer.push({'event':'add_to_cart',
    //     'price':window.ProductData.price,
    //     'sku':window.ProductData.sku,
    //     'name':window.ProductData.name,
    //     'weight':window.ProductData.weight,
    //     'qty':1,
    //     'image_url':window.ProductData.image_url,
    //     'gcm_image_url':window.ProductData.gcm_image_url,
    //     'product_url':window.ProductData.product_url,
    //     'purity':window.ProductData.purity,
    //     'gross_weight':window.ProductData.gross_weight,
    //     'net_weight':window.ProductData.net_weight,
    //     'style':window.ProductData.style ,
    //     'brand':window.ProductData.brand
       
    // });
//        dataLayer.push({
//   event: 'addToCart',
//   eventLabel: window.ProductData.name,
//   ecommerce: {
//     currencyCode: window.VBJ.currencyCode,
//     add: {
//       products: [
//         {
//           name: window.ProductData.name,
//           id:window.ProductData.sku,
//           price: window.ProductData.price,
//           brand: window.ProductData.brand,
//           category: window.ProductData.parentCategory,
//           list: window.ProductData.style,
//           quantity:1
//         }
//       ]
//     }
//   }
// }); 
      var loginstatus = "<?php echo $loginstatus; ?>";
      if(loginstatus) {
        console.log("inside login");
          window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000); 
        } else {
           $("#customer-popup-login").modal("openModal");
        }
     
    });
     $("#buy-now-offer").click(function(){
       window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000); 
    });
 }); 
}); 
</script> 
<?php endif; ?>
<?php
/*$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('camweara_table');
$ruleIdsql = "SELECT sku FROM camweara_table WHERE sku='$sku'";
$ruleIdresults = $connection->fetchAll($ruleIdsql);
/*echo '<pre>';
print_r($ruleIdresults);
echo '</pre>';
if(count($ruleIdresults)>0){
echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Prince_Buynow::try-on.phtml")->toHtml();
}*/
?>