<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Catalog\Block\Product\Image */ 
/*$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
$productcoll = $objectManager->create('Magento\Catalog\Model\Product')->load($_product['entity_id']);
$imageUrl = $productcoll->getMediaConfig()->getMediaUrl($productcoll->getImage());
$//imageUrl = 'https://cdn-media.vaibhavjewellers.com/pub/media/catalog/product/cache/9bb9d677791f8666003e194c8a94aeff/5/8/580VA197-PTO1.jpg';
$url = $block->getImageUrl();
$my_var = '9bb9d677791f8666003e194c8a94aeff';
$my_url = str_replace("2765542505660baab28ecd555e27366e", $my_var, $url );*/
//echo 'image url - '. $block->getImageUrl();
?>

<span class="product-image-container"
      style="width:<?= /* @escapeNotVerified */ $block->getWidth() ?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?= /* @escapeNotVerified */ ($block->getRatio() * 100) ?>%;">
        <img class="product-image-photo"
            
            src="<?= /* @escapeNotVerified */ $block->getImageUrl() ?>"
            max-width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
            max-height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
            alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true) ?>"/></span>
</span>