<dl>
    <dt>
        <p style="color: #6e2083; text-align: center; font-size: 25px; padding-top: 25px;">Sorry ! Guess The Page is Deleted or Gone Now.</p>
    </dt>
    <dt>
        <p style="text-align: center;">Let us help you explore your favourite Jewellery Category!</p>
    </dt>
    <dt>
        <?php $baseUrl = $block->getBaseUrl()."pub/media/logo/410/410r.png"; ?>
        <p style="text-align: center; font-size: 20px;"><img style="width: 26%;" src="<?php echo $baseUrl; ?>" alt="410 page" width="487" height="222"></p>

    </dt>
    <dt>
        <a href="https://www.vaibhavjewellers.com/">
        <p style="text-align: center; font-size: 20px;"><button style="background-color: #6d1f81; color: #ffffff; border-color: #6d1f81;" type="button">Return Home</button></p>
    </a>
    </dt>
    <dt>
        <p style="text-align: center; font-size: 20px;"></p>
    </dt>



    <dd>
        <ul class="disc">
           
        </ul>
    </dd>
</dl>
