<?php

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */

?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>

<div class="product-info-cert">
    Product is certified by : 

<span class="info-cert">
<img class="bis-img" src="<?php echo $mediaUrl;?>bureau-of-indian_logo.png" alt="IGL logo" width="40" height="30"></span>

<span class="info-cert">
<img class="sgl-img" src="<?php echo $mediaUrl;?>SGL_logo.png" alt="SGL logo" width="40" height="30"></span>

<span class="info-cert">
<img class="cert-img" src="<?php echo $mediaUrl;?>IGI_logo.png" alt="SGL logo" width="40" height="30"></span>

</div>


<style type="text/css">

/* edit by prudhviraj radi on 15/03/2023 starts */

.product-info-cert {
    font-family: avenir !important;
    font-size: 12px !important;
    margin-top: 15px !important;
    border-bottom: 1px solid lightgrey;
}

.info-cert {
    display: inline-block; /* change the display type */
    margin: 10px 0;        /* apply the needed vertical margins */
}

.bis-img {
    max-width: 46px;
    margin-right: 12px!important;
}
.sgl-img {
    max-width: 54px;
    margin-right: 12px!important;
}
.cert-img {
    max-width: 60px;
    margin-right: 12px!important;
}

 /* edit by prudhviraj radi on 15/03/2023 ends */

</style>