<style>    
    #international-button .try-on{
        background-color: #6e2083 !important;
        border-radius: 4px;
        text-transform: uppercase;
        border: none !important;
        text-align: center;
        font-size: 16px !important;
        font-weight: 400;
        color: #FFF !important;
        text-decoration: none !important;
        padding: 12px !important;
        margin: 30px 0 15px 0;
        display: block;
        /*text-transform: uppercase;*/
        /*height: 55px;*/
        /*margin-top: 14px;*/
        /*width: 200px !important;*/
    }
    .prod-tab{
        margin-top: 20px;
    }
     
    .minicart-wrapper .block-minicart {
        margin: 0;
        list-style: none none;
        background: #fff;
        border: 1px solid #bbb;
        margin-top: 10px;
        min-width: 100%;
        z-index: 101;
        box-sizing: border-box;
        position: absolute;
        top: 100%;
        box-shadow: 0 3px 3px rgb(0 0 0 / 15%);
    }
    .product-info-price .price-final_price .special-price .price-final_price .price-wrapper .price{
        display: none;
    }
    .product-info-main .product-info-price .old-price .price-wrapper .price {

         display: block !important; 
    }
    .fz-big{
        font-size: 1.3rem !important;
    }
    .desc-head{
        padding-top: 1.5rem;
    }
    .slider_title{
        color: #6f2d91;
        text-decoration: underline;
        text-align: center;
        font-weight: 700;
    }
    .product-info-main .product-info-price .old-price .price-wrapper .price{
        display: none;
    }
    .product-info-main .product-info-price {
          margin-top: -10px !important;
    }
    .product-info-main .product-info-price .old-price .price-wrapper .price{
        font-size: 17px !important;
        padding-top: 13px;
        font-weight: 900 !important;
        color: #808080 !important;
        margin-top: -2px !important; 
        margin-left: 0px !important;
    }
    /*.offer-head.text-orange {
        float: left;
        color: black;
        font-size: 13px;
        margin-top: 2px !important;
    }*/
    .dis_make_charge_actual .price-wrapper {
        font-size: 15px !important;
        float: none;
        color: #ee853c !important;
    }
     .dis_make_charge_actual .price{
        color: #ee853c !important;
     }

        .setting_my_dimonds{
            display: none;
        }
    .breadcrumbs .item:not(:last-child):after {
        margin: 0 1px;
        font-size: 20px;

        /*-webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        line-height: 16px;
        font-family: FontAwesome !important;
        content: '\f054' !important;
        margin: 0 10px;
        vertical-align: top;
        display: inline-block;
        font-weight: 400;
        overflow: hidden;
        speak: none;
        text-align: center;*/
    }
    .scroll-arrow{
        width: 5px;
    }
    .breadcrumbs .items {
        margin-left: 50px !important;
        margin-right: 0px !important;
        margin-bottom: 0px !important;
        font-size: 12px !important;
        color: #707070;
        padding: 0;
        list-style: none none;
        margin-top: 15px !important;
    }
    .getzoom{
        margin-left: 70px;
    }

    .breadcrumbs{
        margin: 0 0 8px 85px !important;
        margin-bottom: 18px !important;
    }
    .breadcrumbs a {
        color: #aa09c2 !important;
        text-decoration: none !important;
    }
/*    .row{
        margin-top: 18px;
    }
*/    .xzoom-container {
        width: auto;
        margin: 0px auto;
        text-align: center;
        border: 0px solid lightgrey;
    }
    .product_main{
         margin-left: 10px !important;
    }
    .product_name_slider{
        margin-left: 10px;
        margin-right: 10px;
    }
  
    .products-related>.products{
        width: 100% !important;
    }


    .price_slider{
        margin-left: -125px;
    }

    .shop-img-bag{
        width: 18px;
        margin-right: 0.5rem;
        margin-top: -5px;
    }
    .add-to-cart{
        box-shadow: none !important;
        border-radius: 4px !important;
        width: 195px !important;
    }
    .cust-btn--primary{
        background: #6F2D91 !important;
        margin-left: -88px !important;
        font-size: 14px !important;
        padding: 9px 18px !important;
    }

    .cust-btn--primary:hover {
        background: #994ac1 !important;
    }
    

    .add-to-cart, .cart {
        font-weight: 400;
        color: #FFF !important;
        text-decoration: none !important;
        width: 130px;
        height: 42px;
        text-transform: uppercase;
    }
    .whatapp-no {
        font-size: 16px;
        font-weight: 700;
        letter-spacing: 0.3px;
        color: #128C7E;
    }
    .text-green {
        color: #128C7E;
    }

    .xzoom-gallery{
        border-radius: 3px;
        margin-left: 0px;
    }
    .xzoom-thumbs a{
        margin-right: 10px;
    }
    .xzoom{
        width: 500px !important;
    }
    .getzoom{
        margin-left: 120px;
    }
    .box-tocart{
        margin-bottom: 30px;
        margin-top: 40px;
    }
   
    .setting_my_dimonds{
        padding-top: 10px !important;
        padding-bottom: 10px !important;
    }
    .product-info-price .price-box .price-container .price {
        font-size: 17px !important;
        padding-top: 13px;
        font-weight: 900 !important;
    }
    .navigation {
        margin-bottom: 20px !important;
    }








/* edit by prudhviraj radi on 15/03/2023 starts */

    span.base {
        color: #646f75;
        font-size: 17px;
        font-weight: 900;
        padding-left: 0px;
    }

    .fz-small.text-violet.text-uppercase {
      color: #6e2083 !important;
      font-size: 13px;
      font-weight: 700;
    }

    .product-rev-del {
       display: grid;
       grid-template-columns: 0.6fr 0.9fr !important;
       padding-top: 10px;
    }
    .product-info-main .product-info-price {
      display: flex !important;
      width: 100%;
      align-items: center;
      border-bottom: 0px !important;
      margin-bottom: 0px !important;
      margin-top: 0px !important;
    }

    #price_breakup_btn {
      letter-spacing: 0.2px;
      color: darkcyan!important;
      /* text-transform: uppercase; */
      font-weight: 500;
      font-size: 14px;
     }

     .product-info-main .product-info-stock-sku {
	margin-top: 8px;
     }
     
     .product-info-main {
        margin-left: 0px;
        border-left: 1px solid #e4e2e2;
        padding-left: 40px;
        /*padding-right: 90px;*/
    }

    #checkDelivery-form .label{
        display: inline-block;
        margin: 10px 0 15px 0;
        font-size: 14px;
    }
    
    .try-on-button{
      float: unset !important;
      margin-right: unset !important;
      margin-top: unset !important;
    }
    .purchase-plan{
      float: unset !important;
      margin-right: unset !important;
      margin-top: unset !important;
    }

    .delivery-code{
       /* width: 301px !important;*/
    }
    
    .form__field {
      border: 1px solid #dcdcdc !important;
      color: #a3a3a3 !important;
      font: 500 12px/1.55 Lato,sans-serif !important;
      height: 100% !important;
      box-shadow: 0 6px 10px 0 rgb(0 0 0 / 10%) !important;
      padding: 12px 12px !important;
      width: 250px !important;
      background: #f5f6fa !important;
      outline: 0 !important;
    }

   .cust-btn--inside {
      margin-left: -88px !important;
      margin-right: 5px !important;
      font-size: 14px !important;
     }


    .showmessage, #checkDelivery-form .message.success {
      display: block !important;
      font-size: 12px !important;
      margin-top: 5px !important;
      color: #006400 !important;
      background: white !important;
      padding: 0px 5px !important;
      margin-bottom: 30px !important;
      height: 26px;
      width: 70%;
      position: relative;
     }

    .showmessage:after, #checkDelivery-form .message.success:after {
       color: white !important;
     }

    .try-on, .add-to-cart, .cart {
      font-size: 14px !important;
      margin-right: 1rem !important;
      text-decoration: none !important;
     }

    .add-to-cart {
      box-shadow: none !important;
      border-radius: 4px !important;
      /* width: 195px !important; */
     }

.add-to-cart, .cart {
    font-weight: 400;
    color: #FFF !important;
    width: 24% !important;
}
.add-to-cart {
    background-color: #6F2D91;
}

#product-addtocart-button {
    text-transform: uppercase !important;
    height: 40px !important;
    float: left;
    margin-top: -17px !important;
    width: auto !important;
}

#buy-now {
    box-shadow: none !important;
    border-radius: 4px !important;
    text-transform: uppercase !important;
    height: 40px !important;
    margin-top: -20px !important;
}

 /* edit by prudhviraj radi on 15/03/2023 ends */









    .emi-plans{
        color: #2a5296 !important;
    }



    .container__item .delivery-code{
        border: 1px soild #dcdcdc !important;
        margin-top: 6px !important;
        margin-bottom: 10px !important;
    }

    .mt-5, .my-5 {
        margin-top: 1rem !important;
    }




    .setting_my_dimonds .customize {
        border-bottom: 1px solid;
        color: #2a5296 !important;
        text-decoration: none !important;
        font-size: 13px !important;
        font-weight: 600 !important;
    }
    label {
        display: inline-block;
        margin: 10px 0 5px 0;
        font-size: 15px;
    }
    .info-tab {
        padding: 1.5rem 3rem 0 2rem;
    }
    .need-help {
        font-size: 13px !important;
        color: grey !important;
        padding-left: 16px !important;
    }
    .faq-submit {
        border: 0;
        border-radius: 4px !important;
        color: #ffffff;
        margin-top: 1rem;
        font-weight: 600;
        padding: .5rem 2rem;
        letter-spacing: .6px;
        background-color: #6f2d91;
        text-transform: uppercase;
    }
    .inner-block-newsletter {
        background-color: #f1e4f2 !important;
        margin-top: 15px;
    }
    .inner-block{
        margin-top: 30px;
    }
 
    .product-image-photo{
        height: auto !important;
    }
    #subcribe:hover{
        border: none;
        background-color: #9140a7 !important;
    }


    ol{
        display: inline-flex !important;
        overflow: auto !important;
    }
    .block-title{
        text-align: center;
        text-transform: capitalize;
    }
    .product-item-info{
        width: 225px !important;
    }
  /*  .product-item-details{
        background-color: #d3d3d35e;
    }*/
    .price-final_price{
    margin-bottom: 0px !important;
    }
    .product-item-actions{
        display: none !important;
    }
/*    .product-image-wrapper{
        padding-bottom: 100% !important;
    }*/
/*    li.product-item{
            margin-left: 18px !important;
    }*/
  /*  .product-item{
         border: #6c757d1f !important;
        border-style: groove !important;
        border-width: 1px !important;
        margin-bottom: 0px !important;
        padding-bottom: 0px !important;
        height: fit-content;
    }
    .block-products-list{
        margin-left: 25px !important;
    }

    
    .page-layout-1column .block.widget .products-grid .product-item {
        margin-left: calc((86% - 5 * (100%/6)) / 4);
    }

   
    @media (min-width: 1024px){
        .page-layout-1column .block.widget .products-grid .product-item:nth-child(4n+1) {
            margin-left: calc((86% - 5 * (100%/6)) / 4);
        }
    }

    
    @media (min-width: 1024px){
    .page-layout-1column .block.widget .products-grid .product-item:nth-child(5n+1) {
            margin-left: 20px !important;
        }
    }*/


    /*
    .product-info-main .product-info-price .price-box {
    width: 20% !important;
    padding-top: -5px;
    }
    .add-to-cart{
        margin-top:1px !important;
    }
    .cart{
          margin-top:1px !important;
    }
    .product-options-bottom .price-box .price-container .price, .product-info-price .price-box .price-container .price{
        line-height:0px !important;
        padding-top:20px !important;
        color:#000000 !important;
    }
    .product-info-main .product-info-price .price-box {
    width: 20% !important;
    padding-top: 3px;
}
.customize {
    border-bottom: 1px solid;
    font-size: 14px;
    color: #2a5296 !important;
    text-transform: uppercase !important;
    text-decoration: none !important;
}
.faq-submit {
    border: 0;
    background-color: #6f2d91;
    border-radius: 6px;
    color: #ffffff;
    margin-top: 1rem;
    font-weight: 600;
    padding: .5rem 2rem;
    letter-spacing: .6px;
    /* background-color: #e8e8e8; */
    text-transform: uppercase;
}
.block-title .title{
    text-align:center !important;
}
 .related{
    text-align:center !important;
}

.content {
    padding-top: 0px !important;
}
.item .product .product-item 
{
    border: 2px solid #ccc;
    border-radius: 4px;
    margin-left: 10px;
    margin-right: 10px;
    padding-left: 3px;
}
/*::-webkit-scrollbar {*/
/*    display: none;*/
/*}*/


::-webkit-scrollbar {
    width: 12px;
}
                    
::-webkit-scrollbar-track {
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
    border-radius: 10px;
}
                    
::-webkit-scrollbar-thumb {
    border-radius: 10px;
    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); 
    	background-color: #555;
}*/
/*.item .product .product-item{*/
/*    display:inline-block !important;*/
/*}*/
/*.content{*/
/*    padding-top:10px !important;*/
/*}*/

/*.block-content {*/
/*    width: 500px;*/
/*    height: 160px;*/
/*    display: flex;*/
/*    margin: 0 auto;*/
/*}*/
/*.block-content .products-related {*/
/*    display: flex;*/
/*    flex-wrap: nowrap;*/
/*    overflow-x: scroll;*/
/*    width: 100%;*/
/*}*/
/*.block-content  .products-related .product-item {*/
/*    width: 90%;*/
/*    height: 130px;*/
/*    flex: 0 0 auto;*/
/*    cursor: pointer;*/
/*}*/

/*@media (max-width: 500px) {*/
/*    .block-content {*/
/*        width: 100%;*/
/*    }*/
/*}*/

}


</style>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
// $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
//$producttype = $product->getTypeId();
$_product = $block->getProduct();
$price = $_product->getPrice();
$sku =  $_product->getSku();
$name = $_product->getName();
$weight = $_product->getWeight();
$image_url  = $block->getUrl('pub/media/catalog').'product'.$_product->getImage();
$product_url = $_product->getProductUrl(); 
$purity =$_product->getResource()->getAttribute('purity')->getFrontend()->getValue($_product);
$gross_weight = $_product->getResource()->getAttribute('gross_weight_approx_gms')->getFrontend()->getValue($_product);
$net_weight = $_product->getResource()->getAttribute('net_weight')->getFrontend()->getValue($_product);
$style = $_product->getResource()->getAttribute('style')->getFrontend()->getValue($_product);
$brands_name = $_product->getResource()->getAttribute('brands_name')->getFrontend()->getValue($_product);
$gst = (int)($_product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($_product));
$finalPriceAmt = round($_product->getPriceInfo()->getPrice('final_price')->getValue());
$gcm_image_upload = $_product->getResource()->getAttribute('gcm_image_upload')->getFrontend()->getValue($_product);
if(empty($gcm_image_upload)){
$getgcm_image_upload ='';
}
else{
$getgcm_image_upload  = $block->getUrl('pub/media/catalog').'attribute-data/'.$gcm_image_upload;
}
$price = $finalPriceAmt + $gst;
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryIds = $_product->getCategoryIds();
 $cat_string = "";
  $cat_ids="";
$categories = $categoryCollection->create()
                                 ->addAttributeToSelect('*')
                                 ->addAttributeToFilter('entity_id', $categoryIds);
 $category_name ='';
 $category_id ='';
$first = true;
foreach ($categories as $category) {
    $cat_string .=','.$category->getName();
     $cat_ids .=','.$category->getId();
     if ( $first )
    {
         $category_name = $category->getName();
         $category_id = $category->getId();
        $first = false;
    }
}
$cat_string = substr($cat_string, 1);
$cat_ids = substr($cat_ids, 1);

?>
<script type="text/javascript">
    var ProductData = {};
    ProductData.price = <?php echo $price;  ?>;
    ProductData.sku = '<?php echo $sku;  ?>';
    ProductData.name = '<?php echo $name;  ?>';
    ProductData.weight = '<?php echo $weight;  ?>';
    ProductData.image_url = '<?php echo $image_url;  ?>';
    ProductData.gcm_image_url = '<?php echo $getgcm_image_upload;  ?>';  
    ProductData.product_url = '<?php echo $product_url;  ?>';
    ProductData.purity = '<?php echo $purity;  ?>';
    ProductData.gross_weight = '<?php echo $gross_weight;  ?>';
    ProductData.net_weight = '<?php echo $net_weight;  ?>';
    ProductData.style = '<?php echo $style;  ?>';
    ProductData.brand = '<?php echo $brands_name;  ?>';
    ProductData.categories = '<?php echo $cat_string;  ?>';
    ProductData.category_ids =  '<?php echo $cat_ids;  ?>';
    ProductData.parentCategory = '<?php echo $category_name;  ?>';
    
    // dataLayer.push({'event':'product_view',
    //     'price':<?php echo $price;  ?>,
    //     'sku':'<?php echo $sku;  ?>',
    //     'name':'<?php echo $name;  ?>',
    //     'weight':'<?php echo $weight;  ?>',
    //     'image_url':'<?php echo $image_url;  ?>',
    //     'gcm_image_url':'<?php echo $getgcm_image_upload;  ?>',
    //     'product_url':'<?php echo $product_url;  ?>',
    //     'purity':'<?php echo $purity;  ?>',
    //     'gross_weight':'<?php echo $gross_weight;  ?>',
    //     'net_weight':'<?php echo $net_weight;  ?>',
    //     'style':'<?php echo $style;  ?>',
    //     'brand':'<?php echo $brands_name;  ?>',
    //     'categories':'<?php echo $cat_string;  ?>',
    //     'category_ids':'<?php echo $cat_ids;  ?>'
       
    // });
</script>
<div class="container-fluid mb-5 mt-5" style="content-visibility: auto; contain-intrinsic-size: 100px;">
        <div class="row">
            <div class="col pdt"><div class="prod-tab">product details</div></div>
            <div class="col destr"><div class="prod-tab">description</div></div>
        </div>
        <div class="row">
            <div class="col-6 pdtcon"> 
            <div class="prd-dtl-tab info-tab">             
               <?= $this->getChildHtml('specification'); ?>
            </div>
            </div>
            <div class="col-6 descon" id="askquestform">
             <div class="info-tab description d-block">
                 <!--  /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($block->getProduct(), $block->getProduct()->getDescription(), 'description') ?>  -->
                <div class="row w-100 m-0 justify-content-center">
                    <div class="heading-purchase"><h5>INCLUDED WITH PURCHASE</h5>
                    </div>
                     <div class="col-12 col-md-12 aspects" style="padding: 1rem .5rem 1rem;">
                     <picture>
                         <source type="image/webp"   data-srcset="<?php echo $this->getUrl('pub/media/').'product_include_price.jpg' ?>" srcset="<?php echo $this->getUrl('pub/media/').'product_include_price.jpg' ?>">
                    <img src="#" class="w-100" data-srcset="<?php echo $this->getUrl('pub/media/').'product_include_price.jpg' ?>" srcset="<?php echo $this->getUrl('pub/media/').'product_include_price.jpg' ?>" data-src="<?php echo $this->getUrl('pub/media/').'product_include_price.jpg' ?>" alt="vaibhav_advantage" width="680" height="160" data-pagespeed-no-transform>
                     </picture> 
                    </div>
                    <!-- <div class="col-6 col-md-6 aspects">
                        <ul>
                            <li>
                                <span><i class="fa fa-gift" aria-hidden="true"></i></span>Free Gift Box
                            </li>
                            <li>
                                <span><i class="fa fa-diamond" aria-hidden="true"></i></span>Conflicts Free Diamonds
                            </li>
                            <li>
                                <span><i class="fa fa-bus" aria-hidden="true"></i></span>Fast Shipping And Production
                            </li>
                        </ul>
                    </div> -->
                    <!-- <div class="col-6 col-md-6 aspects">
                        <ul>
                            <li>
                                <span><i class="fa fa-ring" aria-hidden="true"></i></span>Free Engraving
                            </li>
                            <li>
                                <span><i class="fa fa-id-card-o" aria-hidden="true"></i></span>Authenticity Certificates
                            </li>
                            <li>
                                <span><i class="fa fa-bus" aria-hidden="true"></i></span>Free Domestic Shipping
                            </li>
                        </ul>
                    </div> -->
                </div>
                <div class="row w-100 m-0 text-center justify-content-center info-div">
                    <div  class="heading-end"><h5>STAY SOCIAL WITH VAIBHAV JEWELLERS</h5></div>
                    <p>Follow us to stay updated on the latest collections, Offers and much more. We love surprises, so keep an eye out for those!</p>
                    <div class="d-flex justify-content-between m-auto w-75">
                        <a rel="nofollow" target="_blank" href="https://www.facebook.com/vaibhavjewllers">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://www.instagram.com/vaibhavjewellers/?hl=en">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://twitter.com/vaibhavjewelers?lang=en">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://www.youtube.com/channel/UCT6Uv0OflrUVA2VDNk_C2Tw">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://api.whatsapp.com/send?phone=919177403000">
                            <i class="fab fa-whatsapp"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://in.pinterest.com/VaibhavJewellers">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>              
                <?= $this->getChildHtml('product.askform'); ?>
            </div>
         </div>
        </div>
    </div>
 