<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>


<?php
$gst = (int)($_product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($_product));

$inr='₹';
$usd='$';

 $price_with_tax= round($_product->getSpecialPrice()+$gst);
 $inr_price= number_format($price_with_tax);

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
/*     $product_name = $product->getName();
     $product_id =   $product->getSku();
     $product_price =   $product->getFinalPrice();*/
?>
<?php
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
$shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
$gst = (int)($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
$currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
$currencySymbol = $currency->getCurrencySymbol();
  ?>
  <div data-bind="scope: 'config_product'">
  <div data-bind="visible: vbjOffer" class="pdp-offer mb-2 vbjoffer">
     <span class="offer-head text-orange"></span>
      <span class="offer-price text-orange"><span id="vbjoffer-price" class="dis_make_charge_actual" style="float: none;"> </span> <span class="mf offer-text"></span></span> 
  </div>
</div>
<div class="default-offer pdp-offer mb-2">
    <?php
  if($_product->getData('discount_making_charge_in') || $_product->getData('metal_discount_in') || $_product->getData('discount_diamond_in') || $_product->getData('discount_wastage') || $_product->getData('discount_product') ){
    $discount_making_charge_in = $_product->getData('discount_making_charge_in');
    $metal_discount_in= $_product->getData('metal_discount_in');
    $product_discount= $_product->getData('discount_product');
    $discount_diamond_in = $_product->getData('discount_diamond_in');
    $discount_wastage = $_product->getData('discount_wastage');
    $weight = $_product->getData('net_weight');
    $metal = $product->getResource()->getAttribute('metal')->getFrontend()->getValue($product);
    $purity = $product->getResource()->getAttribute('purity')->getFrontend()->getValue($product);
    $makingCharges = $product->getResource()->getAttribute('making_charge')->getFrontend()->getValue($product);
    $wastage = $product->getResource()->getAttribute('wastage')->getFrontend()->getValue($product);
    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('pricemanager');
//$sql = "SELECT * FROM" . $tableName;
$sql = "Select * FROM pricemanager";
$results = $connection->fetchAll($sql);
foreach($results as $key=> $result){
  $k14 = $result['14K'];
  $k18 = $result['18K'];
  $k22 = $result['22K'];
  $k24 = $result['24K'];
  $silver = $result['hundred'];
}
   //$vaweight = ($weight * $wastage)/100;
   $va = 0;
   $metalrate = 0;
   $metalprice = 0;
    if($metal =='Gold' && $purity =='24K'){
        $metalprice =  round($k24 * $weight);
        $va = round(($metalprice * $wastage) / 100);
        
    }elseif($metal =='Gold' && $purity =='22K'){
        $metalprice =  round($k22 * $weight);
        $va = round(($metalprice * $wastage) / 100);
        //$metalrate = $k22;
    }
    elseif($metal =='Gold' && $purity =='18K'){
        $metalprice =  round($k18 * $weight);
        $va = round(($metalprice * $wastage) / 100);
        //$metalrate = $k18;
    }
    elseif($metal =='Gold' && $purity =='14K'){
        $metalprice =  round($k14 * $weight);
        $va = round(($metalprice * $wastage) / 100);
        //$metalrate = $k14;
    }
    elseif($metal =='Silver'){
        $metalprice = round($silver * $weight);
        $va = round(($metalprice * $wastage) / 100);
    }
    $finalmakingcharges = round($makingCharges * $weight) + $va;
    $offerPer = round(($finalmakingcharges * $discount_wastage) / 100);
    $finalPrice = $_product->getPrice() + $_product->getData('tax_amount');
    $value = floatval(preg_replace('/[^\d\.]+/', '', $finalPrice));
    $afterOfferPrice = $inr . round($value - $offerPer);
    ?>
 <span class="offer-head text-orange">Offer Price :</span>
     <?php if($currencyCode =='INR' && $currencySymbol =='₹'){?>

         <?php switch (true) {
                    case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)):  ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on Product"; ?>)</span> 
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> 
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on Product"; ?>)</span>
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($discount_diamond_in)): ?>
                     <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 

                    <?php break;
                     case (isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span>
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on diamond cost"; ?>)</span> 
                    <?php break;
                     case (isset($discount_making_charge_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <?php break;
                    case (isset($metal_discount_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> </span> 
                    <?php break;
                      case (isset($discount_diamond_in)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                    <?php break;
                      case (isset($discount_wastage)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_wastage."% off on VA"; ?>)</span> 
                    <?php break;
                    case (isset($product_discount)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% off on Product"; ?>)</span> 
                    <?php break;
                }
                    ?>

    <?php
  } else { ?>

     <?php switch (true) {
                    case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)):  ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on Product"; ?>)</span> 
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span>  <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on Product"; ?>)</span> 
                     
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($discount_diamond_in)): ?>
                     <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 

                    <?php break;
                     case (isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span>
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                     <span class="offer-price text-orange" style="margin-top: -10px;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% savings on Product"; ?>)</span> 
                    <?php break;
                     case (isset($discount_making_charge_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <?php break;
                    case (isset($metal_discount_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> 
                    <?php break;
                      case (isset($discount_diamond_in)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> 
                    <?php break;
                     case (isset($discount_wastage)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $discount_wastage."% off on VA"; ?>)</span> 
                    <?php break;
                    case (isset($product_discount)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> (<?php echo $product_discount."% off on Product"; ?>)</span> 
                    <?php break;
                }
                    ?>

    
  <?php }
}
 ?>
                <!-- <span class="coupon text-gray" style="display: none;">Use coupon <span class="c-code text-uppercase text-orange p-1">making60</span> at checkout</span> -->
                </div>



                <?= $this->getChildHtml('product.smart.price'); ?>
                <!-- <div class="save-price mb-2"><span class="save-head">You save :</span> <span class="text-orange font-weight-bold"> Rs. 4048</span></div> -->
                <hr>