<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php $_product = $block->getProduct(); ?>

<?php
$gst = round($_product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($_product));

$inr='₹';
$usd='$';

$inr_price = round($_product->getFinalPrice()+$gst);


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
/*     $product_name = $product->getName();
     $product_id =   $product->getSku();
     $product_price =   $product->getFinalPrice();*/
?>
<?php
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
$shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
$gst = round($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
$currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
$currencySymbol = $currency->getCurrencySymbol(); 
  ?>
<div class="pdp-offer mb-2">

    <?php
  if($_product->getData('discount_making_charge_in')){
    $discount_making_charge_in = $_product->getData('discount_making_charge_in');
    ?>
 <span class="offer-head text-orange">Offer Price:</span>
     <?php if($currencyCode =='INR' && $currencySymbol =='₹'){?>
                    <span class="offer-price text-orange"><span class="price" style="float: none;"><?php echo $inr.$inr_price ?></span> (<?php echo $discount_making_charge_in."% Making OFF"; ?>)</span> 

    <?php
  } else { ?>
    <?php $usd_price=round($inr_price * 0.014) ?>
     <span class="offer-price text-orange"><span class="price" style="float: none;"><?php echo $usd.$usd_price ?></span> (<?php echo $discount_making_charge_in."% Making OFF"; ?>)</span> 

  <?php }
}
 ?>
                <span class="coupon text-gray">Use coupon <span class="c-code text-uppercase text-orange p-1">making60</span> at checkout</span>
                </div>

                <?= $this->getChildHtml('product.smart.price'); ?>
                <!-- <div class="save-price mb-2"><span class="save-head">You save :</span> <span class="text-orange font-weight-bold"> Rs. 4048</span></div> -->
                <hr>