<?php

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$currentProduct=$product;

$currentCategory = $objectManager->get('Magento\Framework\Registry')->registry('current_category'); //get current product
$producttype = $product->getTypeId(); //getting wrong product type
$_product = $block->getProduct(); // quantity_and_stock_status
$setName = $_product->getAttributeSetId();

    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
  $StockState->getStockQty($_product->getId(), $_product->getStore()->getWebsiteId());
    
// $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
// $connection = $resource->getConnection();
// $tableName = $resource->getTableName('salesrule');

// $sql = "Select rule_id FROM " . $tableName." WHERE conditions_serialized LIKE '%20%'";
             

//         $result = $connection->fetchAll($sql);
        
//         $categorys=$currentProduct->getCategoryIds();
//         foreach ($categorys as $key => $value) {
//         	$sql = "Select rule_id FROM " . $tableName." WHERE conditions_serialized LIKE '%20%'";
        	
//         }
       
// echo '<pre>'; print_r($result); echo '</pre>'; 
 
// echo $currentProduct->getName() . '<br />';
// echo $currentProduct->getSku() . '<br />';
// echo $currentProduct->getSpecialPrice() . '<br />';
// echo $currentProduct->getProductUrl() . '<br />';

?>

 	<div class="contact-section mb-4">
					<div class="d-inline-block mr-3">
						<a href="https://api.whatsapp.com/send?phone=919177403000" target="_blank"><i  style="background-color: #075e54;color: #fff;width: 35px;text-align: center;height: 35px;line-height: 35px;border-radius: 50px;font-size: 23px;" class="fab fa-whatsapp"></i>
						<span class="whatapp-no text-green">+ 91 91774 03000</span></a>
 <?php $_product = $block->getProduct();
 $_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
                      <a href="https://www.facebook.com/vaibhavjewllers?url=<?php echo $_helper->productAttribute($_product, $_product->getProductUrl(), 'product_url'); ?>&amp;title=<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" target="_blank" class="vaibhav_socialicons"><i style="
    background-color: #3b5998;color: #fff;width: 35px;text-align: center;height: 35px;line-height: 35px;border-radius: 50px;font-size: 23px;margin-right: 15px;margin-left: 10px;" class="fab fa-facebook-f"></i></a>
                      
					</div>
					<div class="contact-us d-inline-block px-4 pt-1">
						<div class="d-inline-block align-top mr-2"><img class="img-fluid" src="<?php echo $this->getUrl('pub/media/');?>contact.svg" alt="Contact"></div>
						<div class="d-inline-block align-right"><div class="font-weight-bold">+ 91 91774 03000</div> <div class="need-help">Need help? Call us</div></div>
					</div>
				</div>


