<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */ ?>
<?php
// echo $block->getReviewsSummaryHtml($block->getProduct(), false, true)
?>
<?php 
$_product = $block->getProduct();
$_product->getSku();


 ?>
	 <div class="fz-small text-violet text-uppercase">sku:<?php echo $_product->getSku() ?></div>
	 <div class="fz-small text-violet free_shipping">Free shipping in India</div>
	 <!-- <hr class="free_shipping_hr"> -->

