	<!-- Nav tabs -->

	<ul id="view_recent_prod" class="nav nav-tabs border-0">
	  <li class="nav-item">
	    <a class="nav-link active" data-toggle="tab" href="#view_similar">View Similar</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" data-toggle="tab" href="#recently_viewed">Recently Viewed</a>
	  </li>
	</ul>

	<!-- Tab panes -->
	<div class="tab-content mb-5 view-recent" style="content-visibility: auto;
  contain-intrinsic-size: 1000px;">
	<div class="tab-pane container-fluid active" id="view_similar">
		<?php echo $this->getChildHtml('catalog.product.related'); ?>
		<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
if(isset($category)){
$cateid=$category->getId();

}
else{

    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
    $categories = $product->getCategoryIds();	
	$cateid=end($categories);
	
}
$productsBlock = $this->getLayout()->createBlock('Bss\ProductsWidgetSlider\Block\Product\MostView');
$productsBlock->setData('show_price',1);
$productsBlock->setData('show_add_to_wishlist',1);
$productsBlock->setData('type_name',"Bss Products Widget - Most Viewed");
$productsBlock->setData('show_as_slider',1);
$productsBlock->setData('products_per_slide',5);
$productsBlock->setData('show_slider_navigation',0);
$productsBlock->setData('show_arrows',1);
$productsBlock->setData('auto_every',3);
$productsBlock->setData('products_count',10);
$productsBlock->setData('websiteID',0);
$productsBlock->setData('collection_sort_by',"views");
$productsBlock->setData('collection_sort_order',"ASC");
$productsBlock->setTemplate("product/widget/content/default.phtml");
$productsBlock->setConditionsEncoded("^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`category_ids`,`operator`:`==`,`value`:`".$cateid."`^],`1--2`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`attribute_set_id`,`operator`:`==`,`value`:`4`^]^]");

echo $productsBlock->toHtml();
?>
	</div>
	  	<div class="tab-pane container-fluid fade" id="recently_viewed">
		  <?php echo $this->getChildHtml('recent_products'); ?>
		</div>
	</div>