<select id="evstore" style="
    width: 15%;
    margin: 25px auto;
    display: block;
    background-color: #ffffff;
    border: 0;
    color: #6f2d91;
    font-family: Avenir-Heavy;
    border-radius: 0;
    font-weight: bold;">
    <option>SELECT YEAR</option>
    <option value="2015">2015</option>
    <option value="2014">2014</option>
    <option value="2013">2013</option>
    <option value="2012">2012</option>
 </select>
<script type="text/javascript">
require(['jquery'],function($){
    jQuery(function ($) {

        $(document).ready(function () {
            //alert("sarvesh");
        
            $('#evstore').change(function () {
                //alert(1);
                //var fdate = jQuery('#frmDate').val();
                //var tdate = jQuery('#toDate').val();
                var value = $('#evstore').val();
                //alert(value);
                var currentid = $('.sevents').first().attr('id');//jQuery(".sstore:first-child").attr("id");
                //alert(currentid);
                var un = "undefined";
                if (value == "2015"){
                    if(currentid != null){
                        $("#2015").insertBefore("#"+currentid);
                    }else{
                        $("#2015").insertBefore("#firstdiv");
                    }
                }
                  if (value == "2014"){
                    if(currentid != null){
                        $("#2014").insertBefore("#"+currentid);
                    }
                    else{
                        $("#2014").insertBefore("#firstdiv");
                    }
                }
                   if (value == "2013"){
                    if(currentid != null){
                        $("#2013").insertBefore("#"+currentid);
                    }
                    else{
                        $("#2013").insertBefore("#firstdiv");
                    }
                }
               

            });

        });
    });
});
</script>