<style type="text/css">
	body {
	font-size: 15px;
}
	.block-collapsible-nav .content {
    background: #fff;
    padding: 15px 0 0;
}

.block-collapsible-nav .item {
   margin: 10px 0 0;
    padding-top: 10px;
    border-top: 1px dashed #999;
}
.block-collapsible-nav .item a:hover {
    color: #121212;
    text-decoration: none;
}
.block-collapsible-nav .item a:visited {
    color: #999;
    text-decoration: none;
}
.block-collapsible-nav .item a {
    color: #999;
    text-decoration: none;
    padding:0;
    font-size: 15px;
}
.block-collapsible-nav .item:first-child {
	    margin-top: 0;
    border-top: 0;
    padding-top: 0;
}
.block-collapsible-nav .item a:hover {
    background: none;
    color: #121212;
    text-decoration: none;
}

.block-collapsible-nav .item.current a, .block-collapsible-nav .item.current>strong {
    border-color: #999;
    color: #121212;
    font-weight: 600;
}

.items .item:nth-child(2) {
	display: none;
}
.items .item:nth-child(4) {
	display: none;
}
.block-collapsible-nav-content .nav {
display: block;
}
.block-collapsible-nav .item.current a {
    border: none;
}
main#maincontent {
    margin-left: auto;
    margin-right: auto;
    max-width: 1200px !important;
    box-sizing: border-box;
}
.block-title strong , .box-title span  {
	font-size: 16px !important;
}
.box-content address {
	font-size: 15px;
}

.account .column.main>.table-wrapper, .account .column.main>.form-address-edit, .account .column.main>.form, .account .column.main .block {
	background-color: #fff;
    padding: 20px;
    box-shadow: 0px 0px 1px #8c8686;
    -moz-box-shadow: 0px 0px 1px #8c8686;
    -webkit-box-shadow: 0px 0px 1px #8c8686;
    -o-box-shadow: 0px 0px 1px #8c8686;
    -ms-box-shadow: 0px 0px 1px #8c8686;
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 0;
    margin-bottom: 20px;
}
.box-order-billing-address{
display:none;
}
.floatclass{
  float: left !important;
  width: 50% !important; 
}
.sales-order-print .invoice-btn-link{display:none;}
</style>