<script type="text/javascript">
 require(['jquery'],function($){
 $(document).ready(function(){
	$("#switcher-currency").click(function(){
        $(".switcher-dropdown").toggle();
    });
	$(".switcher-trigger").click(function(){
		if($("#switcher-currency-trigger").hasClass('active')) {
			$(".jewellary-currency").hide();
		} else {
			$(".jewellary-currency").show();
		}
    });
});
});   
</script>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * Currency switcher
 *
 * @var \Magento\Directory\Block\Currency $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="d-flex justify-content-end mt-minus-15">
    <div id="<?php if($request->getFullActionName() == 'cms_index_index' ) { echo "main_header_switcher_container"; } else { echo "sticky_switcher_container"; } ?>">
    <div id="switcher_content">
<div class="switcher currency switcher-currency" id="switcher-currency<?= $block->escapeHtmlAttr($id) ?>">
    <div class="actions dropdown options switcher-options">
        <div class="action switcher-trigger"
             id="switcher-currency-trigger<?= $block->escapeHtmlAttr($id) ?>"
             data-mage-init='{"dropdown":{}}'
             data-trigger-keypress-button="true">
            <strong class="language-<?= $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
                <span class="currency_text_span"><?= $block->escapeHtml($currentCurrencyCode) ?></span>
                 <span class="currency_icon_span" style="display: none;">
                     <i style="font-size:15px;margin-top: 5px;color:#000;" class="fas fa-coins"></i>
                </span>
            </strong>
        </div>
        <!-- <ul class="dropdown switcher-dropdown jewellary-currency" data-target="dropdown">
            <?php foreach ($currencies as $_code => $_name): ?>
                <?php if ($_code != $currentCurrencyCode): ?>
                    <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option">
                        <a href="#" data-post='<?= /* @noEscape */ $block->getSwitchCurrencyPostData($_code) ?>'><?=  $block->escapeHtml($_code) ?></a>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul> -->
    </div>
</div>
</div>
</div>
<?php endif; ?>
<!-- <div class="dropdown p-2 d-none d-sm-block">
    <button type="button" class="btn dropdown-toggle color-voilet p-0" data-toggle="dropdown">
        INR
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Link 1</a>
        <a class="dropdown-item" href="#">Link 2</a>
        <a class="dropdown-item" href="#">Link 3</a>
    </div>
</div> -->