<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$basemediaurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$imgix_url= $basemediaurl;//'https://cdn-media.vaibhavjewellers.com/pub/media/';                   

 ?>
<div class="container-fluid section-5">
    <div class="d-flex flex-wrap">
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/floral-collection.html">
               
                    <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/floral-block-1.jpg" alt="vaibhav-freedom-sale" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/butterfly-collection.html">              
                
                       <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/PriceFrom-Block-1.jpeg" alt="floral collection" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/floral-collection.html">               
               
                    <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/Pricefrom-Block-2.jpeg?auto=compress" alt="butterfly collection" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/butterfly-collection.html">                
                
                    <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/butterfly-block-1.jpg" alt="price-starts-from" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/personalize-your-jewellery">              
               
                     <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/finger-print-vaibhav.jpeg" alt="Diamond rings" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-50 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/personalize-your-jewellery">
                
                       <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/drawing-jewelery-vbj.jpeg" alt="Personalzed your jewellery" width="160"
                    height="160">
            </a>
        </div>
        <div class="w-100 p-1 img-container">
            <a href="https://www.vaibhavjewellers.com/video-shopping-page/">               
                
                    <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/mobile-video.jpg" alt="Live Video Shopping" width="325" height="325">
            </a>
        </div>
    </div>
</div>