<div class="container-fluid"
    style="padding: 0px !important; overflow: hidden; background-image: url('https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/header.jpg'); background-repeat: no-repeat; background-size: cover; height: 450px;">
    <div class="row">
        <div class="col-md-12">
            <div class="card header" style="width: 18rem; border-radius: 10px; float: right; top: 50px; right: 100px;">
                <div class="card-body">
                    <div class="message"></div>
                    <h5 class="card-title" style="color: #6e2083; font-weight: 800;">Subscribe Now!</h5>
                    <p style="font-size: 14px; font-weight: 500;">For Our Daily Gold Rate Updates.</p>
                    <form method="POST" action="">
                        <div class="form-group">
                            <input type="text" class="form-control" name="customerName" id="exampleName"
                                aria-describedby="emailHelp" placeholder="Enter Customer Name">
                        </div>
                        <div class="form-group">
                            <input type="email" class="form-control" name="email" id="exampleInputEmail1"
                                aria-describedby="emailHelp" placeholder="Enter Customer email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" name="area" id="exampleInputArea"
                                aria-describedby="emailHelp" placeholder="Enter Customer Area">
                        </div>
                        <div class="form-group">
                            <input type="tel" class="form-control mobile" name="mobilenumber" id="exampleInputMobile"
                                aria-describedby="emailHelp" placeholder="Enter Customer Mobile number">
                        </div>
                        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>