<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$basemediaurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 
$url = $storeManager->getStore()->getBaseUrl();
$imgix_url= $basemediaurl;//'https://mage23vaibhavjewellers.breezesites.io/pub/media/'; 
?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>
<div class="container-fluid">
            <div class="inner-block d-flex mt-5">
                <div class="w-50">
                    <a href="<?php echo $linkUrl;?>gold-jewellery/women/vaddanam.html">
                        <img class="w-100 hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/10.webp" alt="">
                    </a>
                </div>
                <div class="w-75">
                    <div class="w-100 d-flex ring-row">
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>gold-jewellery/women/earrings.html">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/11.webp" alt="">
                            </a>
                        </div>
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>diamond-jewellery/women/earrings/studs.html">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/12.webp" alt="">
                            </a>
                        </div>
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>gold-jewellery/women/earrings.html">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/13.webp" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="w-100 d-flex ring-row">
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>diamond-jewellery/women/earrings/studs.html">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/14.webp" alt="">
                            </a>
                        </div>
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>gold-jewellery/women/earrings.html?style=112">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/15.webp" alt="">
                            </a>
                        </div>
                        <div class="ring-col">
                            <a href="<?php echo $linkUrl;?>diamond-jewellery/women/earrings/studs.html">
                                <img class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/16.webp" alt="">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="inner-block-video mt-5 row">
                <div class="col-md-6">
                    <h5>Education</h5>
                    <div>
                        <img loading="lazy" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/Home Page (41).webp" class="col-md-3" alt="">
                        <a href="https://www.vaibhavjewellers.com/diamond-anatomy"><span style="color:black" class="col-md-7 offset-1">Know your Diamond</span></a>
                    <p class="flt">Diamond to the princess cut, we'll help you choose the shape that complements your style.</p>
                    </div>
                    <div class="pt-2">
                        <img loading="lazy" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/Home Page (56).webp" class="col-md-3" alt="">
                        <a href="https://www.vaibhavjewellers.com/gold-color"><span style="color:black"  class="col-md-7 offset-1">Know your Metal</span></a>
                    <p class="flt">GOLD Won't tarnish, rust, or corrode, and though it's very strong, it is also the most malleable of all metals.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <h5>Testimonials</h5>
                    <div id="slider" class="m-auto">
        <div id="deo" class="carousel slide" data-ride="carousel">
    
            <!-- Indicators -->
            <ul class="carousel-indicators">
                <li data-target="#deo" data-slide-to="0" class="active"></li>
                <li data-target="#deo" data-slide-to="1"></li>
                <li data-target="#deo" data-slide-to="2"></li>
            </ul>
    
            <!-- The slideshow -->
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/Vaibhav-Testimony-01.webp"
                        alt="Vaibhav-Testimony-Desktop-1" width="" height="">
                </div>
                <div class="carousel-item">
                <img src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/Vaibhav-Testimony-02.webp"
                        alt="Vaibhav-Testimony-Desktop-2" width="" height="">
                </div>
                
            </div>
    
            <!-- Left and right controls -->
            <a class="carousel-control-prev" href="#deo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#deo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>    
                </div>
            </div>
        </div>
    