<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$basemediaurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$imgix_url=$basemediaurl; 
 ?>
<div class="container-fluid section-7 mt-4">
    <div class="d-flex flex-wrap">
        <div class="w-50 p-1 img-container">
            <a href="<?php echo $imgix_url;?>gifts/gift-cards.html">         
            
                     <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/Vaibhav-Gift_Cards.jpeg?auto=compress" alt="Vaibhav-Mobile-Gift-Cards" width="160"
                    height="160">
                            </a>
        </div>
        <div class="w-50 p-1 img-container">
             <a href="<?php echo $imgix_url;?>gifts/goldcoins.html">        
            
                    <img src="" class="lazy-image w-100" loading="lazy" data-src="<?php echo $imgix_url;?>wysiwyg/homepage_images/mobile/Vaibhav-Gold_Coins.jpeg?auto=compress" alt="Vaibhav Gold Coins" width="160"
                    height="160">
        </a>
        </div>
        <div class="w-50 p-1">
            <div width="177" class="youtube border-0 w-100" height="95" data-embed="sJRRE47YQ0E"> <!-- src="https://www.youtube.com/embed/sJRRE47YQ0E" -->
                <div class="play-button"></div>
            </div>
        </div>
        <div class="w-50 p-1">
            <div width="177" class=" youtube border-0 w-100" height="95" data-embed="zXHcGtbOyDE"> <!-- src="https://www.youtube.com/embed/zXHcGtbOyDE" -->
                <div class="play-button"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    ( function() {

    var youtube = document.querySelectorAll( ".youtube" );
    
    for (var i = 0; i < youtube.length; i++) {
        
        var source = "https://img.youtube.com/vi/"+ youtube[i].dataset.embed +"/sddefault.jpg?auto=compress";
        
        var image = new Image();
                image.src = source;
                image.addEventListener( "load", function() {
                    youtube[ i ].appendChild( image );
                }( i ) );
        
                youtube[i].addEventListener( "click", function() {

                    var iframe = document.createElement( "iframe" );

                            iframe.setAttribute( "frameborder", "0" );
                            iframe.setAttribute( "allowfullscreen", "" );
                            iframe.setAttribute( "src", "https://www.youtube.com/embed/"+ this.dataset.embed +"?rel=0&showinfo=0&autoplay=1" );

                            this.innerHTML = "";
                            this.appendChild( iframe );
                } );    
    };
    
} )();
</script>