<?php $helper = $this->helper("Prince\Buynow\Helper\Data"); ?>
<?php $addtocartId = $helper->getConfig('buynow/general/addtocartid'); ?>
<?php $buttonTitle = $helper->getConfig('buynow/general/buttontitle'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$sku = $product->getSku();
$product_type = $product->getTypeId();
$lengths = 35;
$offer_percentage = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
$smart_percentage = $product->getResource()->getAttribute('smart_percentage')->getFrontend()->getValue($product);
$productId = $product->getId();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$StockState = $StockState->getStockQty($productId);
$checkout_url = $block->getUrl('checkout/cart/');
$loginstatus=false;
$customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');
if ($customerSession->isLoggedIn() == true) {
  $loginstatus=true;
}

$categories = $product->getCategoryIds();
?>



  <!--<button type="submit" title="<?php /* @escapeNotVerified */ //echo __($buttonTitle) ?>" id="buy-now" class="action primary buynow"  data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php //echo $formId; ?>"
        }
    }
    '>
        <span><?php /* @escapeNotVerified */ //echo __($buttonTitle) ?></span>
    </button>-->
    <input type="hidden" id="add-cart-detail" data-id="<?php echo $productId; ?>" value="<?php echo $block->getUrl('videoform/index/addtocart'); ?>">
  <?php if ($smart_percentage !="0" && isset($smart_percentage)):?>
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="p-3 d-inline-block cart" disabled data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '><img class="shop-img" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span style="text-transform: uppercase !important;"><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
 <?php else : ?>
 <?php if($loginstatus) { ?>
  <button  type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="p-3 cart"  data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '><img class="shop-img" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
  <?php } else { ?>
 <button  type="button" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="p-3 cart"><img loading="lazy" width="25" height="25" class="shop-img" src="<?php echo $this->getUrl('pub/media/');?>cart.svg" alt="">
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
  <?php } ?>
    <?php endif; ?>
    
 <?php 
$giftcard=0;
if (in_array('135', $categories)) { 
   $giftcard=1;
 } ?>   

<?php if($giftcard==1): ?>
    <script type="text/javascript">
/*require([
    'jquery',
    'mage/mage'
], function($){
 $(document).ready(function(){

    $("#buy-now").click(function(){
       var giftcard='<?php echo $giftcard; ?>';
       if(giftcard==1) {
        //('product-custom-option').v();
        var myarray = [];
        $('product-custom-option').each(function(i){
    const inputvalue = $(this).val();

  if (inputvalue !='') {
   myarray.push('true');
  } else {
     myarray.push('false');
  }

});
        if($.inArray('false', myarray)) {
         alert("Please fill all fields");
        } else {
          window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000);   
        }

       } else {

           window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000); 

       } 
    
    });

 }); 
}); */
</script>  
<?php else: ?>
  <script type="text/javascript">
require([
    'jquery',
    'mage/mage',
    'Magento_Ui/js/modal/modal'
], function($,modal){
 $(document).ready(function(){
       var product_type = "<?php echo $product_type; ?>";
  $("#buy-now").click(function(e){
    e.preventDefault();
       
      var loginstatus = "<?php echo $loginstatus; ?>";
      if(loginstatus) {
        console.log("inside login");
          window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000); 
        } else {
           $("#customer-popup-login").modal("openModal");
        }   
    });
  /*    var loginstatus = "<?php echo $loginstatus; ?>";
      if(loginstatus) {
        console.log("inside login");
          window.setTimeout(function() {
       window.location.href = '<?php echo $checkout_url; ?>';
    }, 2000); 
        } else {
           $("#customer-popup-login").modal("openModal");
        }*/
     
    });
 });  
</script> 
<?php endif; ?>


