<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$baseUrl = $block->getBaseUrl();
$imgUrl = $baseUrl.'/media/logo/sign-out-icon.png';
?>
<div class="logout_screen_info">
    <img src="<?php echo $imgUrl ?>" class="img-fluid" alt="Responsive image">
    <p><?= $block->escapeHtml(__('You have signed out and will go to our homepage in 5 seconds mine.')) ?></p>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/logout-redirect": {
                "url": "<?= $block->escapeJs($block->escapeUrl($block->getUrl())) ?>"
            }
        }
    }
</script>
<style type="text/css">
    .logout_screen_info img{
      display: block;
      margin-left: auto;
      margin-right: auto;
      padding-bottom: 50px;
    }

    .logout_screen_info p{
        text-align:center;
    }

    .page-main .page-title-wrapper .page-title{
        text-align: center !important;
        display: block !important;
      margin-left: auto !important;
      margin-right: auto !important;
      padding-top: 100px;
    }



</style>