<style>
  #exTab2 .list_menu{
    max-height: 450px;
    overflow: auto;
  }
  #exTab2 .list_menu a, .filter_side ._gray-darker {
    color: #000;
    font-size: 19px;
}
.filter_side .filter_side_list {
   
    padding: .2em;
   
}
.close_clear {
    font-size: 18px;
}
strong.block-subtitle.filter-current-subtitle{
  line-height: 33px;
}
.filter-current ol.items{ 
   margin-left: 10px;   
}
strong.block-subtitle.filter-current-subtitle{
 margin-left: 10px; 
}
</style>
<?php if ($block->canShowBlock()): ?>
<?php
    $filters = $block->getFilters();
    //$layerConfig = $this->helper('Mageplaza\LayeredNavigation\Helper\Data')->getLayerConfiguration($filters);
    $filtered = count($block->getLayer()->getState()->getFilters());
?>
<div class="block filter" id="layered-filter-block">
  <div class="block-content filter-content">
  <div id="ln_overlay" class="ln_overlay">
        <div class="loader">
            <img src="<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>" alt="Loading...">
        </div>
    </div>
    

    <div id="exTab2" class="container">
        <div class="cle_all">   
            <span class="close_clear">Filter</span>
            <span class="close_fli1">&times;</span>
        </div>
        <?php echo $block->getChildHtml('state') ?>

        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <div class="cle_all block-actions filter-actions">
                <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="close_clear action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a> <span style="display: none;" class="close_fli1">&times;</span>
            </div>
        <?php endif; ?>
    
        <?php $wrapOptions = false; ?>
        <ul class="nav nav-tabs list_menu">
        <?php foreach ($filters as $key => $filter): ?>
          
            <?php if ($filter->getItemsCount()): ?>

                 <?php if($filter->getRequestVar() != 'price'): ?>
                 
                <?php if (!$wrapOptions): ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo __('Filters') ?></strong>
                    
                <?php  $wrapOptions = true; endif; ?>
                
                  
                <li class="cate_list">
                 <a class="cat_li" data-href="<?php /* @escapeNotVerified */ echo __(trim(str_replace(' ','-',$filter->getName()))) ?>-1" href="#" data-toggle="tab"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></a>
                </li>
           <?php endif; ?>
            <?php endif; ?>

        <?php endforeach; ?>
         </ul>
         <div class="tab-content filter_side">
         <?php $count = 0; ?>
         <?php foreach ($filters as $key => $filter): ?>
          
            <?php if ($filter->getItemsCount()): ?>
                <?php if($filter->getRequestVar() != 'price'): ?>
                <?php  $count++; ?>
                  <div class="tab-pane <?php  if($count == 1){ echo ' active'; } ?>" id="<?php /* @escapeNotVerified */ echo __(trim(str_replace(' ','-',$filter->getName()))) ?>-1">
                     <?php /* @escapeNotVerified */  echo $block->getChildBlock('renderer')->setFilter($filter)->render($filter); ?>

                  </div>
              
                 <?php endif; ?>
           
            <?php endif; ?>

        <?php endforeach; ?>
</div>
        <?php if ($wrapOptions): ?>
           
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
    <?php endif; ?>

        <?php echo $block->getChildHtml('layer_additional_info') ?>
    </div>
</div>
</div>
<?php endif; ?>
