<?php $couponData = $block->getSessionDataOfCoupon();
$applyUrl = $block->getUrl('giftcard/giftcard/updategiftcard');
$clearUrl = $block->getUrl('giftcard/giftcard/cleardiscount');
?>
<?php //if ($block->isCustomerLoggrdIn()) {?>
	<div class="cart-discount giftcard-blk">
		<div class="block discount" id="block-discount" data-collapsible="true" role="tablist">
			<div class="title" data-role="title" role="tab" aria-selected="true" aria-expanded="true" tabindex="0" id="gift_card_tab">
				<strong id="block-discount-headingg" role="heading" aria-level="2">Gift Card</strong>
			</div>
			<div class="content" data-role="content" id="gift-card-block-discount" aria-labelledby="block-discount-heading" role="tabpanel" aria-hidden="false" style="display: block;">
					<form id="gift_card_form" action="<?php echo $applyUrl; ?>" data-mage-init='{"validation": {}}'>
					<div class="fieldset coupon">
						<input type="hidden" name="remove" id="remove-coupon" value="0">
						<div class="field" style="display:block;">
							<!-- <label for="coupon_code" class="" style="font-weight:600px;"><span>Gift Code:</span></label> -->
							<div class="control">
								<input type="text" class="input-text" id="gift_card_coupon_code" name="gift_card_coupon_code" value="<?php echo $block->getGiftVoucherCode();?>" placeholder="Enter Gift Code"
								data-validate="{required:true}">
							</div>
						</div>

						<?php /*<div class="field" style="display:block;">
							<label for="coupon_price" class="" style="font-weight:600px;"><span>Amount:</span></label>
							<div class="control">
								<input type="text" class="input-text" id="gift_card_coupon_amount" name="coupon_price" value="<?php echo $couponData['price'];?>" placeholder="Enter Amount"
								data-validate="{required:true}">
							</div>
						</div> */ ?>
						<div class="primary">
							<?php if (!strlen($block->getGiftVoucherCode())): ?>
								<input type="hidden" name="remove_gift_card" id="remove_gift_card" value="0" />
								<button class="" id="applyDiscountGiftCard" type="submit" value="Apply">
									<span>Apply</span>
								</button>
							<?php else: ?>
								<input type="hidden" name="remove_gift_card" id="remove_gift_card" value="1" />
								<button class="" id="clearDiscountGiftCard" type="submit" value="Cancel">
									<span>Cancel</span>
								</button>
							<?php endif; ?>
						</div>
					</div>
				</form> 
			</div>
		</div>
	</div>
<?php //} ?>
<script type="text/javascript">
require(
    [
        'jquery',
		      'mage/mage',
      'mage/validation'
    ],
    function($) {
		$(document).ready(function(){

			var applyUrl = "<?php echo $applyUrl; ?>";
			var clearUrl = "<?php echo $clearUrl; ?>";

			/*$('#gift_card_tab').on('click',function(){
				$("#gift-card-block-discount").toggle();
				$("#gift-card-block-discount").toggleClass('special');
			});*/

			/*$('#gift_card_form').on('submit',function(e){
				e.preventDefault();
			});*/

			/*$('#applyDiscountGiftCard').on('click',function(){
				var code = $('#gift_card_coupon_code').val();
				//var amount = $('#gift_card_coupon_amount').val();
				if ($( "#gift_card_form" ).validation('isValid')) {
					$('#gift_card_form').attr('action', applyUrl).submit();
					$('#gift_card_form').unbind();
					// $.ajax({
					// 		url     :   "<?php //echo $block->getUrl('giftcard/giftcard/updategiftcard')?>",
					// 		type    :   "POST",
					// 		dataType:   "json",
					// 		async   :   true,
					// 		data    :   {   
					// 					code:code,
					// 					//amount:amount
					// 		},
					// 		beforeSend:function() {
					// 			jQuery("body").trigger('processStart');
					// 		},
					// 		complete:function() {
					// 		},  
					// 		success: function($data){
					// 			jQuery("body").trigger('processStop');
					// 			location.reload(false);
					// 		}
					// });
				}
			});*/
			/*$('#clearDiscountGiftCard').on('click',function(){
				if ($( "#gift_card_form" ).validation('isValid')) {		
					$('#gift_card_form').attr('action', clearUrl).submit();
					$('#gift_card_form').unbind();
					// $.ajax({
					// 		url     :   "<?php //echo $block->getUrl('giftcard/giftcard/cleardiscount')?>",
					// 		type    :   "POST",
					// 		dataType:   "json",
					// 		async   :   true,
					// 		beforeSend:function() {
					// 			jQuery("body").trigger('processStart');
					// 		},
					// 		complete:function() {
					// 		},  
					// 		success: function($data){
					// 			jQuery("body").trigger('processStop');
					// 			location.reload(false);
					// 		}
					// });
				}	
			});*/
		});
    });
</script>
<style type="text/css">
	.checkout-cart-index #gift_card_form .fieldset.coupon {
     padding: 0px; 
     border: 0px; 
     background: none; 
}
</style>
