<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$product = $block->getProduct();
	$sku = $product->getSku();
	$product_id = $product->getId();
    $product_type = $product->getTypeId();
	$base_url= $block->getBaseUrl();
	$currentRate = 1;
	$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
	      //$finalPriceAmt = $product->getPrice();
            $productSpecialPriceById = $product->getSpecialPrice();
            $offer_percentage = $product->getResource()->getAttribute('smart_percentage')->getFrontend()->getValue($product);
            $discount_diamond_in = $product->getResource()->getAttribute('discount_diamond_in')->getFrontend()->getValue($product);
            $metal_discount_in = $product->getResource()->getAttribute('metal_discount_in')->getFrontend()->getValue($product);
            $discount_making_charge_in = $product->getResource()->getAttribute('discount_making_charge_in')->getFrontend()->getValue($product);
            $gst = round($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
            if(isset($discount_diamond_in) || isset($discount_making_charge_in) || isset($metal_discount_in) || $discount_making_charge_in !='' || $discount_diamond_in !='' || $metal_discount_in!=''){
            $splPriceAmt= $productSpecialPriceById;
        } else {
           $splPriceAmt = 0;
        }
	$gst = round($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
	$customOptions = $objectManager->get('Magento\Catalog\Model\Product\Option')->getProductOptionCollection($product); 

	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
            $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
            $currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
            $currencySymbol = $currency->getCurrencySymbol(); 
            if($currencyCode == 'USD')
            $currentRate = 1/($storeManager->getStore()->getBaseCurrency()->getRate($currencyCode));

   try {
    $_helper = $this->helper('Retailinsights\ConfigProducts\Helper\Data');
   	$purity_title= \Retailinsights\ConfigProducts\Helper\Data::PURITY_TITLE;
	$d_quality_title = \Retailinsights\ConfigProducts\Helper\Data::DIAMOND_TITLE;
	$ring_title = \Retailinsights\ConfigProducts\Helper\Data::RINGS_TITLE;

	$purity_attr= \Retailinsights\ConfigProducts\Helper\Data::PURITY_ATTR;
	$d_quality_attr = \Retailinsights\ConfigProducts\Helper\Data::DIAMOND_ATTR;
	$ring_attr = \Retailinsights\ConfigProducts\Helper\Data::RINGS_ATTR;
	$purity_selected = "";
	$ring_selected = "";
	$diamond_selected = "";

	$default_purity = $product->getResource()->getAttribute($purity_attr)->getFrontend()->getValue($product);
	$default_d_quality = $product->getResource()->getAttribute($d_quality_attr)->getFrontend()->getValue($product);
	$default_ringsize = $product->getResource()->getAttribute($ring_attr)->getFrontend()->getValue($product);


   
	foreach($customOptions as $optionKey => $optionVal):
		foreach((array) $optionVal->getValues() as $valuesKey => $valuesVal) {
			if($purity_title == $_helper->getStrReplaceWithHyphen($optionVal->getTitle())) {
				 if($_helper->getStrReplaceWithHyphen($default_purity) == $_helper->getStrReplaceWithHyphen($valuesVal->getTitle())) {
				 	$purity_selected = $valuesVal->getId();
				 }
			} elseif($ring_title == $_helper->getStrReplaceWithHyphen($optionVal->getTitle())) {

				 if($_helper->getStrReplaceWithHyphen($default_ringsize) == $_helper->getStrReplaceWithHyphen($valuesVal->getTitle())) {
				 	$ring_selected = $valuesVal->getId();
				 }

			} elseif($d_quality_title == $_helper->getStrReplaceWithHyphen($optionVal->getTitle())) {

				if($_helper->getStrReplaceWithHyphen($default_d_quality) == $_helper->getStrReplaceWithHyphen($valuesVal->getTitle())) {
				 	$diamond_selected = $valuesVal->getId();
				 }
			}
		}
	endforeach;

if(isset($sku)) { ?>
    <script type="text/javascript">
     var VBJ = {};
     VBJ.baseUrl = '<?php echo $base_url; ?>';
     VBJ.sku = '<?php echo $sku; ?>';
     VBJ.product_id = '<?php echo $product_id; ?>';
     VBJ.product_type = '<?php echo $product_type; ?>';
     VBJ.finalPrice = '<?php echo $finalPriceAmt; ?>';
     VBJ.specialPrice = '<?php echo $splPriceAmt; ?>';
     VBJ.default_purity= '<?php echo $purity_selected; ?>';
     VBJ.default_ringsize = '<?php echo $ring_selected; ?>';
     VBJ.default_diamond = '<?php echo $diamond_selected; ?>';
     VBJ.currency = '<?php echo $currencySymbol; ?>';
     VBJ.currencyCode = '<?php echo $currencyCode; ?>';
     VBJ.currencyRate = '<?php echo $currentRate; ?>';
    </script>


<?php } 
 } catch(Exeception $e) {

 }
?>
     <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "config_product": {
                        "component": "Retailinsights_ConfigProducts/js/viewModel"
                    }
                }
            }
        }
    }
</script>

  
	
