<?php
$dataHelper = $this->helper('\Magezon\LazyLoad\Helper\Data');
$threshold  = (int) $dataHelper->getConfig('general/threshold');
$delay      = (int) $dataHelper->getConfig('general/delay');
$effect     = $dataHelper->getConfig('general/effect');
$effectTime = (int) $dataHelper->getConfig('general/effect_time');
?>
<?php if ($dataHelper->isEnable()) { ?>
<script>
	require(['jquery', 'lazyLoad', 'lazyLoadPlugins'], function($) {
		var mgzLazyload = function() {
			$('.lazy').lazy({
				delay: <?= $delay ? $delay : '-1' ?>,
				threshold: <?= $threshold ?>,
				effect: "<?= $effect ?>",
				effectTime: <?= $effectTime ?>,
				afterLoad: function(element) {
					$(element).removeClass('lazy-loading').addClass('lazy-loaded');
				}
			});
		}
		mgzLazyload();
		$(document).on('ajaxComplete', function (event, xhr, settings) {
			mgzLazyload();
		});
		jQuery(document).ready(function($) {
			$('.owl-carousel').on('changed.owl.carousel', function(event) {
		    	mgzLazyload();
			});
		});
	});
</script>
<?php } ?>