<?php 
$product = $this->getCurrentProduct() ?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
	//$StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
	  $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
	 $producttype = $product->getTypeId();
	 //$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
	 
    $_product = $block->getProduct(); // quantity_and_stock_status
	//$producttype = $product->getTypeId();
     if ($currentProduct = $block->getCurrentProduct()) {
      $product_name = $currentProduct->getName();
      $product_id =   $currentProduct->getSku();
      $product_price =   $currentProduct->getFinalPrice();
   }
?>
<?php if($product && $product->getCheckDeliveryEnable()==1): ?>
	<form data-mage-init='{"validation": {}}' class="form" id="checkDelivery-form" method="post" autocomplete="off" onSubmit="return checkPostcode()" >
				<?php if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0 && $producttype == 'simple') { ?>
				<div style="display:none;">
					<label for="delivery_postcode" class="label"><span><?php echo __('For international Shipment') ?></span></label>
					<input id="international-checkbox" name="checkboxsss" type="checkbox" >
				</div>
				<div id="international-shipment-div" class="control" style="display:none;">
					<input type="text" placeholder="Enter Delivery Pincode" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
				</div>
				<?php } else { ?>
					<div>
						<label for="delivery_postcode" class="label"><span><?php echo __('For international Shipment') ?></span></label>
						<input id="international-checkbox" name="checkboxsss" type="checkbox" >
					</div>

      <div id="delivery-form" class="container__item">
      <input type="text" value="" data-validate="{required:true, 'validate-digits':true}" name="postcode" id="postcode"  class="delivery-code form__field" placeholder="Enter Delivery Pincode" />
      <button type="submit" class="cust-btn cust-btn--primary cust-btn--inside uppercase">Check</button>
      <!-- edit by prudhviraj radi on 18/01/2023 starts --> 
     <!-- <button class="try-on-button" type="button" title="Try On" id="tryon-add" onclick="onTryonClick();" style="">
    <img class="shop-img" src="https://www.vgoldjewellers.com/pub/media/add-to-cart.svg" alt=""> -->
    <!-- <img class="shop-img" src="camera.svg" alt=""> -->
    <!-- <span>Try On</span>
    </button> -->

    <button class="purchase-plan" type="button" title="Purchase Plan" id="purchase-plan" onclick="#" style="float: right; margin-right: -79px;margin-top: -50px;">
    <img class="shop-img" src="https://www.vgoldjewellers.com/pub/media/add-to-cart.svg" alt="">
    <!-- <img class="shop-img" src="camera.svg" alt=""> -->
    <span>Purchase Plan</span>
    </button>
    <!-- edit by prudhviraj radi on 18/01/2023 ends --> 
      
  </div>
			<?php } ?>
			
			<div class="message"></div>
		<?php if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0 && $producttype == 'simple') { ?>
		<div class="actions-toolbar" style="display:none;">
			<div class="primary">
				<div id="international-shipment-div2">
					<button type="submit" class="text-uppercase pin-check text-violet" title="<?php  echo __('Check') ?>"><span><?php echo __('Check') ?></span></button>
				</div>
			</div>
		</div>
				<?php } else { ?>
				
			
			<?php } ?>
		
	</form>
	<script type="text/x-magento-init">
		{
			"#checkDelivery-form": {
				"validation": {}
			}
		}
	</script>
	<script>
		function checkPostcode() {
      jQuery('input[name=postcode]').change(function() { 
      if(jQuery(this).val() == "") {        
              jQuery("#postcode-error").show();
          } else {
              jQuery("#showmessage").hide();
          }
      });
			var deliveryMessage = jQuery('#checkDelivery-form .message');
			deliveryMessage.removeClass('success').removeClass('error').hide();
			var deliveryForm = jQuery('#checkDelivery-form');
			if(deliveryForm.valid()) {
	/*		     dataLayer.push({'event':'pincode_check_product',
        'pincode':jQuery('#postcode').val()
       
    });*/
				jQuery.ajax({
					type: "POST",
					url: '<?php echo $this->getUrl('checkDelivery/postcode/check',array('id'=>$product->getId())) ?>',
					data: deliveryForm.serialize(),
					dataType: "json",
					showLoader: true,
					success: function(response) {
						deliveryMessage.addClass(response.type).html(response.message).show();
						jQuery('.showmessage').hide();
            jQuery('form#checkDelivery-form').css('margin-bottom','0px');
					}
				});
			} else {
       jQuery('form#checkDelivery-form').css('margin-bottom','30px');
      }
			return false;
		}
	require([ 'jquery', 'jquery/ui'], function($){ 
      $(document).ready(function($) {
		$('#international-checkbox').change(function () {
		console.log('check delivery phtml');
        if (!this.checked){
		$('#form_type').val(1);
               $('#delivery-form').show();
               $('#product-addtocart-button').css("visibility","visible");
               $('#buy-now').css("visibility","visible");
               $('#buy-now-offer').css("visibility","visible");
               $('.showmessage').show();
		$('#international-button').hide();
		}
        else 
		{
			$('#form_type').val(0);
        $('#delivery-form').hide();
			$('#product-addtocart-button').css("visibility","hidden");
			$('#buy-now').css("visibility","hidden");
			$('#buy-now-offer').css("visibility","hidden");
			$('#international-button').show();
			$('.showmessage').hide();
		 	
		}
    });
      });
 });
	</script>
<?php 
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockqty = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('checkDelivery/config/success_message');
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$shippingCode = $product->getData('expected_delivery_date');
$smartbuy = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
if(isset($shippingCode)){
                 $cusdate = $shippingCode;
                $dt = date("Y-m-d");
                $Expecteddate = date( 'd M, Y', strtotime( "$dt +$cusdate day" ) );
                $Finalmessage = str_replace('one week', $Expecteddate, $conf);
                /*$response['type'] = 'success';
                $response['message'] = $Finalmessage;*/
                }/*else{
                    $response['type'] = 'success';
                    $response['message'] = $Finalmessage;//$SuccessMessage; 
                } */
?>
<?php echo $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View")->setTemplate("Magento_Catalog::product/view/try-on.phtml")->toHtml() ?>
<?php if(isset($shippingCode) && $stockqty != 0 ) { ?>
<div class="showmessage"><?php echo $Finalmessage;?></div>
<?php } elseif($stockqty != 0  || $producttype == 'configurable'){ ?>
<div class="showmessage"><?php echo $conf;?></div>
<?php } ?>


<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
    $product = $this->getCurrentProduct();
     $_product = $block->getProduct();
  $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());

if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0  && $producttype == 'simple')
{ ?>


  <div id="international-button" style="display: block;">
   
    <button type="button" class="p-3 try-on" style="background: #6e2083;"><img class="shop-img" src="https://mage24stage.vaibhavjewellers.com/pub/media/camera.svg" alt=""> <span>SEND ENQUIRY</span> </button>
  </div>
<?php } else { ?>
  <div id="international-button" style="display:none">
  <button type="button"class="p-3 try-on bg-color-voilet" style="background: #6e2083;"><img class="shop-img" src="https://mage24stage.vaibhavjewellers.com/pub/media/camera.svg" alt=""> <span>SEND ENQUIRY</span> </button>
  </div>
<?php } ?>


<?php if(true){?>
<div id="header-mpdal-customer" style="display:none;">

<h2>For Product Enquiry</h2>
  <h3>Provide your details</h3>
    <form class="form-customer-equiry" action="<?php echo $this->getUrl('sendinquiry/index/postnew', ['_secure' => true]); ?>" id="meghraj_custdes_form1 vaibhav-shippment" method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
      <div class="form-5">
        <div class="inputbox1">
          <input name="name" id="name" type="text" class="input-text required-entry in" placeholder="Full Name" /> 
        </div>
        <input name="productname" value="<?php echo $product->getName(); ?>"  type="hidden" /> 
        <input name="producturl" value="<?php echo $product->getProductUrl(); ?>"  type="hidden"  /> 
        <input name="productcode" value="<?php echo $product->getSku(); ?>"  type="hidden" /> 
        <input name="type" id="form_type" value="1"  type="hidden" /> 
        
        <div class="inputbox1">
          <input name="emails" id="emailenq" type="text" class="input-text required-entry validate-email in" placeholder="Email Address" /> 
        </div>
        <div class="inputbox1"> 
          <input name="contact" id="contact" type="text" class="input-text required-entry in" placeholder="Mobile Number" />
          <span id="errmsg" style="color: red; text-align:center;"></span>
        </div>
        <div class="inputbox1"> 
          <input name="area" id="area" type="text" class="input-text required-entry in" placeholder="Area" />
        </div>
        <div class="textareainputbox1">
          <textarea name="details" id="details" class="input-text required-entry in" placeholder="Details of Jewellery"></textarea>
          <span id="spntxt" style="color: red; text-align:center;"></span>
        </div>
      <div style="display: flex;flex-direction: column; align-items: center;">
      <div class="g-recaptcha" data-sitekey="6LeuJPIUAAAAAII47muzblK2Z1wubDtwPJZgnek4"></div>
      <div  id="captcha-error" style="text-align: center;margin-top: 5px;color: #e02b27;font-size: 0.8rem;" ></div>
    </div>
      <div class="submitbtn1">
          <button name="submit" id="sub" data-action='submit'>Submit</button>
        </div>
      </div>
    </form>
</div>
<?php } ?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: '',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };
            if (jQuery("#header-mpdal-customer").length != 0) { 
            var popup = modal(options, $('#header-mpdal-customer'));
            $("#international-button").on('click',function(){ 
                $("#header-mpdal-customer").modal("openModal");
            });
            }

        }
    );
</script>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 $(document).ready(function(){
   $("#contact").keypress(function (e) {
     //if the letter is not digit then display error and don't type anything
     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
        //display error message
        $("#errmsg").html("Digits Only").show().fadeOut("slow");
          return false;
    }
   });
    $("#details").keypress(function (e){
       var yourInput = $(this).val();
    re = /[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi;
    var isSplChar = re.test(yourInput);
    if(isSplChar)
    {
     $("#spntxt").html("Special Characters are not allow").show().fadeOut("slow");
         //return false;
         var no_spl_char = yourInput.replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '');
      if(no_spl_char){
      $(this).val(no_spl_char);
      return true;
    }
    }
   });
   $("#sub").click(function(){
        /*details validation*/
        var des = $("#details").val();
        var contact = $("#contact").val();
        var area = $("#area").val();
    re = /[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi;
    var isSplCharDes = re.test(des);
    var isSplCharContact = re.test(contact);
    var isSplCharArea = re.test(area);
    if(isSplCharDes || isSplCharContact || isSplCharArea)
    {
     $("#spntxt").text("Special Characters are not allow in this form");
         return false;
    }else{
      $("#spntxt").text("");
         return true;  
    }
   });
 }); 
}); 
</script>
<?php endif; ?>
<style type="text/css">
.uppercase {
  text-transform: uppercase;
}
.cust-btn {
  display: inline-block !important;
  background: transparent !important;
  color: inherit !important;
  font: inherit !important;
  border: 0 !important;
  outline: 0 !important;
  padding: 0 !important;
  -webkit-transition: all 200ms ease-in !important;
  transition: all 200ms ease-in !important;
  cursor: pointer !important;
}
.cust-btn--primary {
  background: #b272d3 !important;
    color: #fff !important;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1) !important;
    border-radius: 2px !important;
    padding: 7px 14px !important;
}
.cust-btn--primary:hover {
  background: #b272d3 !important;
}
.cust-btn--primary:active {
  background: #7f8ff4 !important;
  box-shadow: inset 0 0 10px 2px rgba(0, 0, 0, 0.2) !important;
}
.cust-btn--inside {
  margin-left: -50px !important;
}
#postcode-error {
 position: absolute;
}
.form__field:not([disabled]):focus {
      box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1) !important;
}
.form__field {
 width: 250px !important;
    background: #f5f6fa !important;
    color: #a3a3a3 !important;
    font: inherit !important;
    height: 100% !important;
    box-shadow: 0 6px 10px 0 rgba(0, 0, 0, 0.1) !important;
    border: 0 !important;
    outline: 0 !important;
    padding: 18px 12px !important;
}
.showmessage:after, #checkDelivery-form .message.success:after  {
   color: #e5efe5;
  border-left: 13px solid;
  border-top: 13px solid transparent;
  border-bottom: 13px solid transparent;
  display: inline-block;
  content: '';
  position: absolute;
  top:0;
  right: -13px;
}
.showmessage , #checkDelivery-form .message.success {
  display:block;
  font-size: 12px;
  color: #006400;
  margin-top: 15px;
  margin-bottom: 30px;
  background: #e5efe5;
  color: #006400;
  height: 26px;
  padding: 5px 10px;
  width: 70%;
  position: relative;
}
.message.error {
    background: #fae5e5;
    color: #e02b27;
    display:block;
    font-size: 12px;
    margin-top: 15px;
    margin-bottom: 30px;
    height: 26px;
    padding: 5px 10px;
    width: 70%;
    position: relative;
    height: 36px;
    padding: 12px 20px 16px 25px;
    margin: 2px 0px 30px;
    width: 428px;
}
/**/
.try-on-button {
    box-sizing: border-box !important;
    vertical-align: middle !important;
    font-weight: 500;
    text-transform: uppercase;
    font-size: 14px !important;
    height: 40px !important;
    float: inherit;
    padding: 7px 12px !important;
    box-shadow: none !important;
    border-radius: 4px !important;
    color: #FFF !important;
    text-decoration: none !important;
    border: none !important;
    background-image: linear-gradient(to right,#fd8f02,#da9b31) !important;
    overflow: visible;
    margin-right: 5px;
    font-family: inherit;
    line-height: inherit;
}
.purchase-plan{
   box-sizing: border-box !important;
    vertical-align: middle !important;
    font-weight: 500;
    text-transform: uppercase;
    font-size: 14px !important;
    height: 40px !important;
    float: inherit;
    padding: 7px 12px !important;
    box-shadow: none !important;
    border-radius: 4px !important;
    color: #FFF !important;
    text-decoration: none !important;
    border: none !important;
    background-image: linear-gradient(to right,#fd8f02,#da9b31) !important;
    overflow: visible;
    font-family: inherit;
    line-height: inherit;
}
/**/
</style>
