<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_OneStepCheckout
 * @author    Extension Team
 * @copyright Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>

<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>

<?php // @codingStandardsIgnoreFile ?>

<?php
    $date = $block->getShippingArrivalDate();
    if ($date && $date != '0000-00-00 00:00:00') :
?>
    <div id="bss-osc-delivery-date">
        <br/>
        <strong><?= $block->escapeHtml(__('Delivery Date:')) ?></strong>
        <span><?php echo $date; ?></span>
    </div>
<?php endif; ?>
<?php if ($comment = $block->getShippingArrivalComments()) : ?>
    <div id="bss-osc-delivery-comment">
        <br/>
        <strong><?= $block->escapeHtml(__('Comment:')) ?></strong>
        <span><?php echo $comment; ?></span>
    </div>
<?php endif; ?>
<?php if ($block->getActiveJs()) : ?>
    <script type="text/x-magento-init">
        {
            "body": {
                "Bss_OneStepCheckout/js/delivery": {}
            }
        }
    </script>
<?php endif; ?>
