<?php



if(isset($_POST['submit'])){
// Multiple recipients
$to = 'anilkumar@vaibhavjewellers.in'; // note the comma

// Subject
$subject = 'Today gold Price';

// Message
$message = '
<html>
<head>
  <title>Today Gold Price</title>
</head>
<body>
  <p>Here are the birthdays upcoming in August!</p>
  <table>
    <tr>
      <td>'.$_POST["customerName"].'</td>
    </tr>
     <tr>
        <td>'.$_POST["email"].'</td>
    </tr>
    <tr>
        <td>'.$_POST["mobilenumber"].'</td>
    </tr>
    <tr>
        <td>'.$_POST["area"].'</td>
    </tr>
    <tr>
      <td>Sally</td><td>17th</td><td>August</td><td>1973</td>
    </tr>
  </table>
</body>
</html>
';

// To send HTML mail, the Content-type header must be set
$headers[] = 'MIME-Version: 1.0';
$headers[] = 'Content-type: text/html; charset=iso-8859-1';

// Additional headers
// $headers[] = 'To: Mary <mary@example.com>, Kelly <kelly@example.com>';
// $headers[] = 'From: Birthday Reminder <birthday@example.com>';
// $headers[] = 'Cc: anilkumar@vaibhavjewellers.in';
// $headers[] = 'Bcc: birthdaycheck@example.com';

// Mail it

if(mail($to, $subject, $message, implode("\r\n", $headers))){
    echo "mail sent successfully";
}else{
  echo "Mail not sent";
}

}

?>