<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
?>
<!-- <div class="p-2 color-voilet">
 -->
 <style type="text/css">
    /*21-12-2021*/
    .block-minicart .subtitle{
        display: none;
    }
    .block-minicart {
        display: block;
    }
    .minicart-items{
        display: table !important;
    }
    .minicart-items .product-item:not(:first-child) {
        border-top: 1px solid #e7e7e7;
    }
    @media only screen and (max-width: 479px) {
        .minicart-wrapper .block-minicart {
                width: 350px !important;
        }
    }
    .minicart-items .product-item-name a {
        color: #757575;
    }
    .product-item-name a {
        font-size: 14px !important;
    }
    #btn-minicart-close:hover{
        background: none !important;
        color: #757575 !important;
    }
    #btn-minicart-close{
        background: none !important;
        color: #ccc !important;
    }
    .minicart-items-wrapper {
        height: 350px !important;
        overflow-y: scroll;
        padding: 0 15px;
    }
    .block-minicart .amount .price{
        color: black !important;
        font-size: 16px !important;
    }
    .actions .secondary a{
        text-transform: uppercase;
        font-size: 14px;
        font-weight: 600;
    }
    .block-minicart .action.primary {
        background-color: #a657ca !important;
    }
    .minicart-items-wrapper .minicart-items .product-item {
        overflow: initial !important;
        width: 88% !important;
    }

    /*21-12-2021 END*/
    
     .minilist .action.delete:before, .minicart-wrapper .action.edit:before{
        font-size: 14px;
     }
     .minicart-items .action.edit:before, .minicart-items .action.delete:before{

        font-size: 14px;
        padding-left: 10px;
     }
     .minicart-wrapper .product .actions>.primary:not(:last-child), .minicart-wrapper .product .actions>.secondary:not(:last-child){
        margin-right: 0px;
     }
     
    .minicart-items .action.edit:before, .minicart-items .action.delete:before{
        content: '\f303';
    font-family: 'fontawesome';
    }
    .minicart-items .action.delete:before{
        content: '\f2ed';
    font-family: 'fontawesome';
    }
   
 </style>   
<div id="main_header_minicart_container" class="">
    <div id="minicart_content" class="p-2 color-voilet">
        <div data-block="minicart" class="minicart-wrapper">
            <a class="action showcart" aria-label="showcart" href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>"
               data-bind="scope: 'minicart_content'">
                   <i style="font-size:15px;margin-top: 5px;color:#000;display: none" class="fas fa-shopping-cart cart-icon"></i>
                <span class="counter qty empty"
                      data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
                    <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
                    <span class="counter-label">
                    <!-- ko if: getCartParam('summary_count') -->
                        <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
                        <!-- ko i18n: 'items' --><!-- /ko -->
                    <!-- /ko -->
                    </span>
                </span>
            </a>
            <?php if ($block->getIsNeedToDisplaySideBar()): ?>
                <div class="block block-minicart"
                     data-role="dropdownDialog"
                     data-mage-init='{"dropdownDialog":{
                        "appendTo":"[data-block=minicart]",
                        "triggerTarget":".showcart",
                        "timeout": "2000",
                        "closeOnMouseLeave": false,
                        "closeOnEscape": true,
                        "triggerClass":"active",
                        "parentClass":"active",
                        "buttons":[]}}'>
                    <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                    </div>
                    <?= $block->getChildHtml('minicart.addons') ?>
                </div>
            <?php endif ?>
            <script>
                window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
            </script>
            <script type="text/x-magento-init">
            {
                "[data-block='minicart']": {
                    "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
                },
                "*": {
                    "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                }
            }
            </script>
         </div>
    </div>
</div>
</div>
 
<!-- <div class="p-2 color-voilet">
    <a href="">
        <i class="fas fa-shopping-cart "></i>
        <span>(<span>0</span>)</span>
    </a>
</div> -->