<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>


<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
if($request->getFullActionName() == 'cms_index_index'){
 ?>

<div class="section-9 container-fluid py-3 mt-3">
            <h2 class="text-center">Sign Up for Our Newsletter</h2>
<div class="block newsletter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"/>
                            <?php echo $block->getBlockHtml('formkey'); ?>
                </div>
            </div>
            <div class="actions">
                <button id="subs-button" class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('SUBSCRIBE')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('SUBSCRIBE')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
</div>
<?php } else { ?>

<div class="inner-block-newsletter mt-5 this_is_mobile">
     <div class="container d-flex justify-content-between px-5 py-3 fgdfd">
            <h2 class="signUp-txt text-center">Sign Up for Our Newsletter</h2>
<div class="align-items-center d-flex w-70 news_letter">
    <div class="title"><strong><?= $block->escapeHtml(__('Newsletter')) ?></strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input class="p-2 inputext" name="email" type="email" id="newsletter"
                           placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                           data-mage-init='{"mage/trim-input":{}}'
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button id="subs-button" class="action subscribe primary p-2 subsri" title="<?= $block->escapeHtmlAttr(__('SUBSCRIBE')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('SUBSCRIBE')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
</div>
</div>

<?php } ?>

 <script type="text/javascript">
   /*require(["jquery"], function ($) {
    $(document).ready(function () {
        $('#subs-button').click(function () { // The button type should be "button" and not submit
            if ($('#newsletter-validate-detail').valid()) {
                 dataLayer.push({'event':'email_subscribe',
        'email':$('#newsletter').val()
       
    });
                return true;
            }
        });
    });
});*/
 </script>