<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 style="text-align: center; padding: 50px 0 0 0;">Today Gold Price in <span class="place"></span></h3>
            <p style="text-align: center; font-size: 12px;">Latest Update on at <span class="currentDate"></span> 10:00
                AM</p>
            <div class="card today-gold-price"
                style="width: 60%; left: 20%; align-items: center; padding: 20px 0 20px 0; box-shadow: 1px 5px 15px 3px #d5d5d5;border-radius: 15px;">
                <div class="card-body" style="width: -webkit-fill-available;">
                    <div class="col-md-12" style="display: flex;">
                        <div class="col-md-4 price">
                            <div class="form-group">
                                <span style="color: #818181; font-size: 12px;">Place</span><br>
                                <select class="selectPlace form-control"
                                    style="border: none; width: auto; font-weight: 700; color: #000000;"></select>
                            </div>
                        </div>
                        <div class="col-md-4 price">
                            <span style="color: #818181; font-size: 12px;">Date</span><br>
                            <span class="currentDate" style="font-weight: 700; color: #000000;"></span>
                        </div>
                        <div class="col-md-4 price">
                            <span style="color: #818181; font-size: 12px;">22k Rate per GM</span><br>
                            <span class="todayGoldPrice" style="font-weight: 700; color: #000000;"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>