 <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h4 style="text-align: center;">Determine the gold Price</h4>
            <p align="justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.</p>

              <p align="justify">There are shops that are as much as 300 years old and have passed on from generation to generation, who offer you best gold rates. Do check <span class="GoldpriceText">todays gold rate in <span class="place"></span></span> before you buy gold.</p>
              <p align="justify">Gold prices today in <span class="place"></span> is at <span class="oneGramPrice22k GoldpriceText"></span> per gram for 22k, while for 24k also called 999 gold, the prices is at <span class="oneGramPrice24k GoldpriceText"></span> per gram.</p>
          </div>
        </div>
       </div>