<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>

<span data-action="toggle-nav" class="action nav-toggle"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
<?php if ($block->isHomePage()):?>
    <strong class="d-flex justify-content-center" > <!-- logo -->
<?php else: ?>
    <a class="d-flex justify-content-center" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
<?php endif ?>
        <img class="px-lg-5 py-xl-2 w-100 vlogo" src="<?= /* @escapeNotVerified */ $block->getUrl('pub/media/logo/stores/1/') ?>logo.png"
             title="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
             <? //= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
             <? //= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
             width="168" height="50"
        />
<?php if ($block->isHomePage()):?>
    </strong>
<?php else:?>
    </a>
<?php endif?>