<?php
$blockObj= $block->getLayout()->createBlock('Mage2\Inquiry\Block\Inquiry');
$_product = $block->getProduct();
$is_enable = $blockObj->getQuestionDisplaySetting();
if($is_enable)
{
    $inquiryCollection = $blockObj->getInquiryCollection();
    $inquiryCount = count($inquiryCollection);
    if($inquiryCount)
    {
        ?>

        <div class='product-questions-container'>
            <p class="view-question"><label class="action submit primary view-question"><?php /* @escapeNotVerified */ echo __('View Questions') ?></label></p>
            <ul class='question-listing'>
                <?php

                foreach($inquiryCollection as $inquiry)
                { ?>
                    <div class="question-container">
                        <li>
                            <p><b> <?php /* @escapeNotVerified */ echo __('Question :') ?> </b><?php echo $inquiry->getMessage(); ?></p>
                        </li>
                        <li>
                            <p><b> <?php /* @escapeNotVerified */ echo __('Answer :') ?> </b></span><?php echo $inquiry->getAdminMessage(); ?></p>
                        </li>
                    </div>
                <?php } ?>

            </ul>
        </div>

    <?php }
} 
?>

<h6 class="fz-big desc-head">Have a question? <span class="fz-medium">We'd love to help <span class="font-weight-bold">+91 91774 03000</span></span></h6>
                    <form  class="form testimonial"
      action="<?php /* @escapeNotVerified */ echo $blockObj->getFormAction();?>"
      id="product-inquiry-form"
      method="post"
      enctype="multipart/form-data"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
       <input type="hidden" name="sku" value="<?php echo $_product->getSku();?>" type="text"/>
        <?php $product_url= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>  
        <input type="hidden" name="product_url" value="<?php echo $product_url;?>" />   
                        <div class="mb-2">
                                <label for="">Name *</label>
                               <input name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="" class="review-input" type="text" data-validate="{required:true}"/>
                            </div>
                        <div class="mb-2">
                                <label for="">Email *</label>
                                 <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value=""  class="review-input" type="email" data-validate="{required:true, 'validate-email':true}"/>
                            </div>
                       <div class="mb-2">
                                <label for="">Contact Number *</label>
                                <input name="mobile_number" id="mobile_number"   title="<?php /* @escapeNotVerified */ echo __('Contact number') ?>" value="" class="review-input" type="tel" data-validate="{required:true}" />
                            </div>
                         <div class="mb-2">
                                <label for="">Question *</label>
                                <input style="background-color: #fff !important;" type="text" name="message" id="message" title="<?php /* @escapeNotVerified */ echo __('Question') ?>" class="review-input" data-validate="{required:true}" />
                            </div>
                       
                        
                       <!--  <button class="faq-submit" type="submit">Submit</button> -->
                        <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="faq-submit">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
                    </form>

<script>

    require([
        'jquery',
        'inquiry'
    ], function () {
        'use strict';
    });
</script>