<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Cms::header.phtml")->toHtml() ?>
<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Cms::content.phtml")->toHtml() ?>
<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Cms::footer.phtml")->toHtml() ?>
<?php //include('header.php');?>
<?php //include('content.php');?> 
<?php //include('footer.php')?>