<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <style>
    .price:last-child {
        border-right: none;
    }

    .price:first-child {
        padding: 0px 0px;
    }

    .price {
        padding: 0 40px;
        border-right: 0.1px solid #d7d7d7;
        text-align: center;
    }

    .MultiCarousel {
        float: left;
        overflow: hidden;
        padding: 15px;
        width: 100%;
        position: relative;
    }

    .MultiCarousel .MultiCarousel-inner {
        transition: 1s ease all;
        float: left;
    }

    .MultiCarousel .MultiCarousel-inner .item {
        float: left;
    }

    .MultiCarousel .MultiCarousel-inner .item>div {
        text-align: center;
        margin: 15px;
        background: #f5f5f5;
        border: 1px solid #d7d7d7;
    }

    .MultiCarousel .leftLst,
    .MultiCarousel .rightLst {
        position: absolute;
        border-radius: 50%;
        top: calc(50% - 20px);
        background: #6e2083 !important;
        border: 1px solid #6e2083 !important;
        color: #ffffff !important;
    }

    .MultiCarousel .leftLst {
        left: 0;
    }

    .MultiCarousel .rightLst {
        right: 0;
    }

    .MultiCarousel .leftLst.over,
    .MultiCarousel .rightLst.over {
        pointer-events: none;
        background: #ccc;
    }

    .cms-page-view table td {
        border-left: 0px !important;
    }

    @media only screen and (max-width: 820px) {
        .main {
            padding: 0px !important;
        }
    }

    @media only screen and (max-width: 768px) {
        .today-gold-price {
            width: 100% !important;
            left: 0px !important;
        }

        .d-sm-none {
            display: block !important;
        }

        .align-items-center {
            justify-content: center;
        }

        #sticky_header .mobile-search form input {
            width: 350px;
        }

        h3 {
            font-size: 1.75rem;
        }
    }




    @media only screen and (max-width: 425px) {
        .today-gold-price>.card-body>.col-md-12 {
            display: grid !important;
            align-items: center;
            justify-content: center;
        }

        .today-gold-price>.card-body>.col-md-12>.price {
            border-right: none;
            border-bottom: 0.1px solid #d7d7d7;
            padding: 20px 0;
            text-align: center;
        }

        .today-gold-price>.card-body>.col-md-12>.price:last-child {
            border-right: none;
            border-bottom: none;
        }

        .newsletter {
            display: grid !important;
        }

        .newsletter>label {
            width: 100% !important;
        }

        .newsletter>input {
            width: 100% !important;
        }

        .card_header-card {
            right: 40px !important;
        }

        #sticky_header .mobile-search form input {
            width: 200px !important;
        }

        .card_header-card {
            float: left !important;
            left: 50%;
            transform: translate(-50%, 0%);
            right: 0px !important;
        }
    }


    @media only screen and (max-width: 375px) {
        #sticky_header .mobile-search form input {
            width: 175px !important;
        }

        .card_header-card {
            right: 30px !important;
        }
    }

    @media only screen and (max-width: 320px) {
        #sticky_header .mobile-search form input {
            width: 140px !important;
        }

        .card_header-card {
            right: 30px !important;
        }
    }

    @media only screen and (max-width: 280px) {
        .card_header-card {
            right: 5px !important;
            width: 250px !important;
        }

        #sticky_header .mobile-search form input {
            width: 100px !important;
        }

        #sticky_header .logo img {
            width: 40px !important;
        }
    }

    .submit {
        background: #6e2083;
        border: 1px solid #6e2083;
        color: #ffffff !important;
    }

    .submit:hover {
        background: #6e2083;
        border: 1px solid #6e2083;
        color: #ffffff !important;
    }

    svg>path {
        color: green;
    }

    .leftLst>svg>path {
        color: #ffffff;
    }

    .rightLst>svg>path {
        color: #ffffff;
    }

    .place {
        text-transform: capitalize;
        font-weight: 900;
    }

    .bannercard {
        color: #6e2083;
        font-weight: 800;
    }

    .card_header-card {
        width: 300px;
        border-radius: 10px;
        float: right;
        top: 50px;
        right: 100px;
        z-index: 0;
    }

    .bannercard>p {
        font-size: 14px;
        font-weight: 500;
    }


    .banner-images {
        padding: 0px !important;
        overflow: hidden;
        background-image: url('https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/header.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        height: 450px;
    }

    .currentDate {
        font-weight: 700;
        color: #000000;
        font-size: 18px;
    }

    .todayGoldPrice {
        font-weight: 700;
        color: #000000;
        font-size: 18px;
    }

    .selectPlace {
        border: 0.5px solid #d7d7d7;
        border-radius: 30px;
        width: auto;
        font-weight: 700;
        color: #000000;
        font-size: 18px;
        text-transform: capitalize;
        width: 100% !important;
    }

    .selecting_spans {
        color: #818181;
        font-size: 12px;
    }

    .today-gold-price {
        width: 60%;
        left: 20%;
        align-items: center;
        padding: 20px 0 20px 0;
        box-shadow: 1px 5px 15px 3px #d5d5d5;
        border-radius: 15px;
    }

    .align_explore {
        margin-left: 50%;
        transform: translate(-50%, 0%);
    }

    .page-header {
        margin: 0 !important;
    }

    .header a {
        font-size: 10px;
    }

    ul>li {
        list-style: disc;
        margin-left: 20px;
    }

    ol>li {
        list-style: decimal;
        margin-left: 20px;
    }

    h3,
    h4,
    h5,
    h6 {
        color: #000000;
    }

    .page-title-wrapper {
        display: none;
    }

    p {
        text-align: justify;
    }

    .newsletter {
        height: 35px !important;
    }
    </style>

</head>

<body>