 <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="row">
            <div class="col-md-6">
              <div class="card">
              <div class="card-title">
                  <h5>Gold Rate in <span class="place"></span> | 22K</h5>
                  <p style="font-size: 12px;">Latest Update on 24 May 2023 at 10:00 AM</p>
                </div>
                <div class="card-body">
                 
                  <table class="table table-reponsive table-striped">
                    <tr>
                        <td>1 Gram</td>
                        <td class="oneGramPrice22k"></td>
                    </tr>
                    <tr>
                        <td>8 Gram</td>
                        <td class="eightGramPrice22K"></td>
                    </tr>
                    <tr>
                        <td>10 Gram</td>
                        <td class="tenGramPrice22K"></td>
                    </tr>
                    <tr>
                        <td>100 Gram</td>
                        <td class="hundreedGramPrice22K"></td>
                    </tr>
                </table>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="card">
                <div class="card-body">
                <h5>Gold Rate in <span class="place"></span> | 24K</h5>
                  <p style="font-size: 12px;">Latest Update on 24 May 2023 at 10:00 AM</p>
                  <table class="table table-reponsive table-striped">
                      <tr>
                          <td>1 Gram</td>
                          <td class="oneGramPrice24k"></td>
                      </tr>
                      <tr>
                          <td>8 Gram</td>
                          <td class="eightGramPrice24K"></td>
                      </tr>
                      <tr>
                          <td>10 Gram</td>
                          <td class="tenGramPrice24K"></td>
                      </tr>
                      <tr>
                          <td>100 Gram</td>
                          <td class="hundreedGramPrice24K"></td>
                      </tr>
                  </table>
                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
       </div>
       