<?php

/**
 * @var \Mageplaza\HelloWorld\Block\Display $block
 */

$current_category= $block->getCurrentCategory();

$objectManager =\Magento\Framework\App\ObjectManager::getInstance();

$abstractProductBlock = $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\AbstractProduct');

$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

$cateid = '22';
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');

$collection = $productCollection->create();
$collection->addAttributeToSelect('*');
$collection->addCategoriesFilter(['in' => $cateid]);
$collection->addAttributeToFilter('visibility', \Magento\Catalog\Model\Product\Visibility::VISIBILITY_BOTH);
$collection->addAttributeToFilter('status',\Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED);
$collection->addAttributeToSort('created_at', 'DESC');
$collection->setPageSize(10); // fetching only 9 products
foreach ($collection as  $value) {
    $productUrl = $value->getProductUrl();
    $productName =  $value->getName();
    $productImage = $abstractProductBlock->getImage($value, 'product_small_image')->getImageUrl();
    $productPrice =  $abstractProductBlock->getProductPrice($value);
}


?>
<br><br>
<h4 style="text-align: center;"><strong>Best Categories</strong></h4>
<section class="customer_sliders">
    <div class="scroll-arrow" id="scroll-leftss">
        <i class="fa fa-chevron-circle-left"></i>
    </div>
    <div id="imgListss" class="imgList">
        <?php foreach ($collection as $value) {  ?>
        <div class="product_main">
            <div class="product_container">
                <a href="<?php echo $value->getProductUrl(); ?>">
                    <div class="product_img"><img
                            src=" <?php echo $abstractProductBlock->getImage($value, 'product_base_image')->getImageUrl(); ?>">
                    </div>
                    <div class="product_details_slider">
                        <div class="product_name_slider"><?php echo $value->getName(); ?></div>
                        <span class="price_slider"><?php echo $abstractProductBlock->getProductPrice($value); ?></span>
                    </div>
                </a>
            </div>
        </div>
        <? } ?>
    </div>
    <div class="scroll-arrow" id="scroll-rightss">
        <i class="fa fa-chevron-circle-right"></i>
    </div>
</section>
<p></p>
<br />
<button class="btn btn-primary submit align_explore"
    onclick="window.location.href='<?php echo $linkUrl;?>gold-jewellery/women/vaddanam.html'">Explore</button>
<p></p>
<br />



<script type="text/javascript">
var imgList = document.getElementById('imgListss');
var scrollRight = document.getElementById('scroll-rightss');
var scrollLeft = document.getElementById('scroll-leftss');

// When a user clicks on the right arrow, the ul will scroll 750px to the right
scrollRight.addEventListener('click', (event) => {
    imgList.scrollBy(750, 0);
});

// When a user clicks on the left arrow, the ul will scroll 750px to the left
scrollLeft.addEventListener('click', (event) => {
    imgList.scrollBy(-750, 0);
});
</script>

<!-- <div class="container" style="margin-top: 50px; margin-bottom: 50px;">
    <div class="row">
        <div class="col-md-12">

            <h4 style="text-align: center;">Explore our best selling categories</h4>
            <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel" data-interval="1000">
                <div class="MultiCarousel-inner">
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0101.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Antique Lakshmi Devi Vaddanam</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/Antique-Vadanam.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Antique Vaddanam</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0303.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Antique Radha Krishna Vaddanam</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0404.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Antique Paisley Short Gold Necklace</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0505.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Astonishing Antique Gold Kundan Necklace</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0606.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Designer Antique Gold Necklace</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0707.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Modern Classic Style Gold Bangles</p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="pad15">
                            <img src="https://mage24stage-cdn-static.vaibhavjewellers.com/static/frontend/Vbj/Vaibhav_Jewellary/en_US/Magento_Cms/images/Haram/0808.jpg"
                                class="img-reponsive img-fluid" alt="">
                            <p>Antique Gold Bangles With Kundan Work</p>
                        </div>
                    </div>


                </div>
                <button class="btn btn-primary leftLst"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                        fill="currentColor" class="bi bi-arrow-left-short" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M12 8a.5.5 0 0 1-.5.5H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5a.5.5 0 0 1 .5.5z" />
                    </svg></button>
                <button class="btn btn-primary rightLst"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                        fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd"
                            d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z" />
                    </svg></button>
            </div>
        </div>
    </div>
</div>
</div> -->