<?php

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */

?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$sku = $product->getSku();
$lengths = 35;
$productId = $product->getId();
    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
    $tableName = $resource->getTableName('mageplaza_autorelated_actions_index');

    $ruleIdsql = "SELECT rule_id FROM mageplaza_autorelated_actions_index WHERE product_id = '$productId'";
    $ruleIdresults = $connection->fetchAll($ruleIdsql);
    if(count($ruleIdresults)>0){
    $ruleId = $ruleIdresults[0]['rule_id'];
    $productssql = "SELECT product_id FROM mageplaza_autorelated_actions_index WHERE rule_id = '$ruleId'";
    $productsresults = $connection->fetchAll($productssql);
    $sliced_arrays = array_slice($productsresults, 0, 8);
    if (!empty($sliced_arrays)) {
    $str1 = '';
    foreach($sliced_arrays as $sliced_array){
        $productsIds = $sliced_array['product_id'];
        $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($productsIds);
        $skus = $_product->getSku();
        $array[] = $skus;
        $str1 = $str1.$skus. ',';
        $newarraynama=rtrim($str1,", ");
    }    
    $newarraynamas = $sku.','.$newarraynama;
}else{
    $newarraynamas= $sku;
}
}else {
    $newarraynamas= $sku;
}

$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('camweara_table');

$sql = "Select id FROM " . $tableName." WHERE sku='".$sku."'";

        $tryonflag=false;
        $result = $connection->fetchAll($sql);
  
    foreach ($result as $key => $value) {
        $tryonflag = ($value['id']!= '') ? true : false;
           # code...
       }   
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    $ids = $cat->getId();
    }
$catlast = end($categories);
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$StockState = $StockState->getStockQty($productId);
?>
<div class="product-info-cert">
    Product is certified by : 
    <span class="info-cert">
        <img class="bis-img" src="<?php echo $mediaUrl;?>bureau-of-indian_logo.png" alt="bureau of indian logo" width="39" height="30">
    </span>
    <span class="info-cert">
        <img class="sgl-img" src="<?php echo $mediaUrl;?>SGL_logo.png" alt="SGL logo" width="39" height="30">        
    </span>
    <span class="info-cert">
        <img class="cert-img" src="<?php echo $mediaUrl;?>IGI_logo.png" alt="IGI logo" width="39" height="30">
    </span>
</div>
<style type="text/css">
    
    /***** edit by prudhviraj radi on 18/01/2023 starts *****/
    .product-info-cert {
        font-family: avenir !important;
        font-size: 12px !important;
        margin-top: 15px !important;
        margin-bottom: 20px !important;
    }
    .info-cert {
        display: inline-block;
        margin-bottom: 5px;
    }
    .bis-img {
        max-width: 40px !important;
        margin-right: 12px !important;
    }
    .sgl-img {
        max-width: 52px !important;
        margin-right: 12px !important;
    }
    .cert-img {
        max-width: 55px !important;
        margin-right: 12px !important;
    }
    /***** edit by prudhviraj radi on 18/01/2023 ends *****/


</style>
<div class="">
    <!-- edit by prudhviraj radi on 18/01/2023 starts --> 
     <!-- <button class="try-on-button" type="button" title="Try On" id="tryon-add" onclick="onTryonClick();" style="">
    <img class="shop-img" src="<?php echo $mediaUrl;?>add-to-cart.svg" alt="add-to-cart" width="16" height="16">
    <span>Try On</span>
    </button> -->

    <a href="https://www.vaibhavjewellersjpo.com" rel="nofollow" target="_blank"><button class="try-on-button" type="button" title="Purchase Plan" id="purchase-plan">
    <img class="shop-img" src="<?php echo $mediaUrl;?>add-to-cart.svg" alt="purchase-plan" width="16" height="16">
    <span>Purchase Plan</span>
    </button>
    </a>
    <!-- edit by prudhviraj radi on 18/01/2023 ends --> 
</div>
<?php //} ?>
    <style>
          #iFrameID {
    opacity: 1;
    background-color: transparent;
    position: fixed;
    width: 760px;
    height: 480px;
    top: 0px;
    left: 0px;
    margin-left: 20%;
    margin-top: 2%;
    z-index: 100;
    display: none;
    border: none;
}
#iFrameOutsideDiv {
    display: none;
    position: fixed;
    width: 100%;
    height: 100%;
    top: 0px;
    left: 0px;
    z-index: 99;
    opacity: 0.8;
    background-color: black;
}
.grid-container-element { 
    display: grid; 
    grid-template-columns: 1fr 1fr; 
    grid-gap: 20px; 
    /*border: 1px solid black; */
    width: 70%; 
} 
.grid-child-element { 
    margin: 10px; 
    border: 1px solid;
    background-color: #e8732e;
}
  @media(max-width:480px){
#iFrameID{
                opacity:1;
                background-color: transparent;
                position:fixed;
                width:100%;                                                                                                                      
                height:100%;                                                                                                                                     
                top:0px;
                left:0px;
                margin-left: 0%;
                margin-top: 0%;
                z-index:1000;
                border: none;
                overflow:hidden;
}
  }
  @media(max-width:480px){
#iFrameID{
                opacity:1;

                background-color: transparent;

                position:fixed;

                width:100%;                                                                                                                      

                height:100%;                                                                                                                                     

                top:0px;

                left:0px;

                margin-left: 0%;

                margin-top: 0%;

                z-index:1000;

                border: none;

                overflow:hidden;

}
}
.try-on-button {
    box-sizing: border-box !important;
    vertical-align: middle !important;
    font-weight: 500;
    text-transform: uppercase;
    font-size: 14px !important;
    height: 40px !important;
    float: inherit;
    padding: 7px 12px !important;
    box-shadow: none !important;
    border-radius: 4px !important;
    color: #FFF !important;
    text-decoration: none !important;
    border: none !important;
    background-image: linear-gradient(to right,#fd8f02,#da9b31) !important;
    overflow: visible;
    margin-right: 5px;
    font-family: inherit;
    line-height: inherit;
}
.p-sku {
    border-bottom: 1px solid #ccc;
    height: 40px;
    width: 380px;
    max-width: 100%;
}
.fz-small.text-violet.text-uppercase {
    color: #aa09c2!important;
    width: 50% !important;
    padding-top: 10px;
    font-size: 13px;
    padding-right: 60px;
}
.fz-small.text-violet.free_shipping{
    /* float: left !important; */
    padding-top: 10px;
    font-size: 13px;
    padding-left:10px;
    }
</style>
<script>
function onTryonClick(argument) {
var url = "https://vaibhavjewellers.com/camweara/index.php?skus=<?php echo $newarraynamas; ?>";
if(screen.width > 480){
window.open(url,'_blank');
}else{
window.location.href = url;
}
}
function iFrameOutsideDivClick(){
console.log("iFrameOutsideDivClick entered");
document.getElementById("iFrameID").setAttribute("src", ""); 
document.getElementById("iFrameID").style.display = "none";
document.getElementById("iFrameOutsideDiv").style.display = "none";
}

window.addEventListener('message', function(event) { 

   console.log("message event origin "+ event.origin);

   if (~event.origin.indexOf('https://vaibhavjewellers.com/')) { 
       console.log("message: "+event.data);
     if(event.data == "closeIframe"){
               iFrameOutsideDivClick();
     }
     else if(event.data.includes("buynow")){
       var field = event.data.split('=');
       var skuSelected = field[1];
                               //add sku to cart and redirect to checkout
     }
               
   }else{ 
       // The data hasn't been sent from your site! 
       //  Do not use it. 
       return; 
   } 
});  
/* ----------------------------------------------*/
window.addEventListener('message', function(event) {
    // IMPORTANT: Check the origin of the data!
    if (~event.origin.indexOf('https://modakatech.com')) {
        console.log("message: "+event.data);
      if(event.data == "closeIframe"){
                iFrameOutsideDivClick();
      }
      else if(event.data.includes("buynow")){
          console.log('sarveshtiwari'+event.data );

        var field = event.data.split('=');

        var skuSelected = field[1];

        var addToCartUrl = "<?php
    $productId = 1778; // <--- set correct product id (e.g. 1)
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
    $addToCartUrl = $objectManager->get('Magento\Checkout\Helper\Cart')->getAddUrl($product);
    echo $addToCartUrl.'form_key/'; ?>";

    // add form key
    var formKey = jQuery.cookie("form_key");
    addToCartUrl += formKey;

    // add options
    var formData = new FormData();
    formData.append("product", <?php echo $productId ?>);
    formData.append("selected_configurable_option", "");
    formData.append("related_product", "");
    formData.append("form_key", formKey);
    //formData.append("options[2]", "Some custom data, foo bar"); // <--- set correct optionId (e.g. 2)
    formData.append("qty", cp.Menge);

    // make POST call with the custom options as body element
    var request = jQuery.ajax({
        url: addToCartUrl,
        method: "POST",
        processData: false,
        contentType: false,
        data: formData
    }).done(function( response ) { // redirect to cart if call was successful
        window.location = "https://vaibhavjewellers.com/checkout/cart"; // <--- set correct redirect link
    }).fail(function( jqXHR, textStatus ) {
        console.log("Couldn't add product to cart. " + textStatus);
    });

      }
    } else {

        // The data hasn't been sent from your site!

        //  Do not use it.

        return;
    }
});  
</script>