<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="container-fluid mobile-section d-block d-sm-none">
    <div class="footer-top row pt-4">
        <div class="col-12 text-center footer-logo">
            <img class="m-auto w-60" src="https://cdn-media.vaibhavjewellers.com/pub/media/logo/stores/1/logo.png" alt="">

            <p>We are global houseware product design company. We bring thought and creativity to every our items</p>
        </div>
        <div class="col-12 ">
            <div class="row">
                <div class="col-6">
                    <h5 class="footer-title">About Vaibhav</h5>
                    <ul>
                        <li>
                            <a href="#">
                                About Us
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Founder
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Management Team
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Vaibhav Advantage
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Work with Us
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                CSR
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Metal Rate
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Blog
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6">
                    <h5 class="footer-title">Customer Services</h5>
                    <ul>
                        <li>
                            <a href="#">
                                EMI
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Privacy Policy
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Shipping Policy
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Refund Policy
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Exchange Policy
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Terms of Use
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Terms & Conditions
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Contact Us
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12">
            <h5 class="footer-title">Our Branches</h5>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <ul>
                        <li class="my-2 footer-subtitle">
                            <a href="#">
                                Andra Pradesh
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Visakhapatnam
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Gajuwaka
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Kakinada
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Rajahmundry
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Anakapalli
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Srikakulam
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Parvathipuram
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Bobbili
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Gopalapatnam
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                More Branches...
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6">
                    <ul>
                        <li class="footer-subtitle my-2">
                            <a href="#">
                                Telangana
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Dilsukhnagar
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                A.S Rao Nagar
                            </a>
                        </li>
                    </ul>
                    <ul>
                        <li>
                            <a href="#">
                                Upcomming
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Vijayavada
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Guntur
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Panjagutta
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="color-white footer-bottom py-3 row bg-color-voilet">
        <div class="col-md-4 text-center">
            <h3>We Accept</h3>
            <div>
                <a href="#">
                    <img class="" src="https://cdn-media.vaibhavjewellers.com/pub/media/wysiwyg/mastercard.png"
                        alt="Vaibhav Online Payment">
                </a>
                <a href="#">
                    <img class="" src="https://cdn-media.vaibhavjewellers.com/pub/media/wysiwyg/visa.jpg"
                        alt="Vaibhav Online Payment">
                </a>
                <a href="#">
                    <img class="" src="https://cdn-media.vaibhavjewellers.com/pub/media/wysiwyg/american.jpg"
                        alt="Vaibhav Online Payment">
                </a>
            </div>
        </div>
        <div class="align-items-end col-md-4 d-flex justify-content-center">
            <p class="m-0">© 2018 Vaibhav Jewellers. All Rights Reserved</p>
        </div>
        <div class="col-md-4 text-center">
            <h3>Connect with us</h3>
            <div class="d-flex justify-content-between m-auto w-75">
                <a href="#">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="#">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="#">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="#">
                    <i class="fab fa-google-plus-g"></i>
                </a>
                <a href="#">
                    <i class="fab fa-youtube"></i>
                </a>
                <a href="#">
                    <i class="fab fa-whatsapp"></i>
                </a>
                <a href="#">
                    <i class="fab fa-pinterest"></i>
                </a>
            </div>
        </div>
    </div>
</div>