<div class="container-fluid">


		<div class="row">

			<div class="col-6 mobile_slider">

				<div id="product_slider" class="carousel slide" data-ride="carousel">

				<!-- Indicators -->

					<ul class="carousel-indicators">

						<li data-target="#product_slider" data-slide-to="0" class="active"><img class="img-fluid dotshide" src="images/prod-img.jpg" alt="product-image"></li>

						<li data-target="#product_slider" data-slide-to="1"><img class="img-fluid dotshide" src="images/prod-img-2.jpg" alt="product-image"></li>

						<li data-target="#product_slider" data-slide-to="2"><img class="img-fluid dotshide" src="images/prod-img-3.jpg" alt="product-image"></li>

						<li data-target="#product_slider" data-slide-to="3"><img class="img-fluid dotshide" src="images/prod-img-4.jpg" alt="product-image"></li>

					</ul>

					<!-- The slideshow -->

					<div class="carousel-inner">

						<div class="carousel-item active">

							<img class="img-fluid" src="images/prod-img.jpg" alt="product-image">

						</div>

						<div class="carousel-item">

							<img class="img-fluid" src="images/prod-img-2.jpg" alt="product-image">

						</div>

						<div class="carousel-item">

							<img class="img-fluid" src="images/prod-img-3.jpg" alt="product-image">

						</div>

						<div class="carousel-item">

							<img class="img-fluid" src="images/prod-img-4.jpg" alt="product-image">

						</div>

					</div>

				</div>

			</div>

			<div class="col-6 pl-4 imgae_dese">

				<div class="prod-title">22KT Signity Gold jhumkas</div>

				<ul class="rating-reivew list-inline">

					<li class="rating list-inline-item p-0">

						<img class="bs-image" src="images/rating.svg" alt="rating-star-image">

						<img class="bs-image" src="images/rating.svg" alt="rating-star-image">

						<img class="bs-image" src="images/rating.svg" alt="rating-star-image">

						<img class="bs-image" src="images/rating.svg" alt="rating-star-image">

						<img class="bs-image" src="images/rating.svg" alt="rating-star-image">

					</li>

					<li class="list-inline-item bd-right">32 Review(s)</li>

					<li class="list-inline-item bd-right removeadd">Add your review</li>

					<li class="list-inline-item askques">Ask a question</li>

				</ul>

				<div class="fz-small text-violet text-uppercase">sku:-135VG2683</div>

				<div class="fz-small text-violet">Free shipping in India</div>

				<hr class="below_free_shipping_india">

				<div class="pdp-price mb-2"><span class="product-price">Rs.2,88,660</span> <span class="emi-plans">View EMI plans</span></div>

				<div class="pdp-offer mb-2">

					<span class="offer-head text-orange">Offer Price: </span>

					<span class="offer-price text-orange">Rs.2,84,617 (02% Making OFF)</span> 

					<span class="coupon text-gray">Use coupon <span class="c-code text-uppercase text-orange p-1">making60</span> at checkout</span>

				</div>

				<div class="save-price mb-2"><span class="save-head">You save :</span> <span class="text-orange font-weight-bold"> Rs. 4048</span></div>

				<hr>

				<div class="inter-ship mb-3">For international shippment <input type="checkbox"></div>

				<div class="pincode-check mb-3"><span class="py-2 location-box"><img class="loc-img" src="images/location.svg" alt="geo-location"><input class="delivery-input" type="text" placeholder="Enter Delivery Pincode"></span><a href="#" class="text-uppercase pin-check text-violet">Check</a></div>

				<div class="shipping-date mb-2">Expected shipping by 17 Nov,2019</div>

				<hr>

				<div class="shopping mb-4 text-uppercase">

					<a class="p-3 d-inline-block try-on" href="#"><img class="shop-img" src="images/camera.svg" alt="">Try on</a>

					<a class="p-3 d-inline-block add-to-cart" href="#"><img class="shop-img" src="images/add-to-cart.svg" alt="">Add to cart</a>

					<a class="p-3 d-inline-block cart" href="#"><img class="shop-img" src="images/cart.svg" alt="">Shop now</a>

				</div>

				<a class="customize" href=" <?php echo $this->getUrl('personalize-your-jewellery');?>">For personalize & customized jewellery click here</a>

				<hr class="below_personalize_jewellery">
			</div>

		</div>

	</div>

	<div class="container-fluid mb-5">

		<div class="row">

			<div class="col pdt"><div class="prod-tab">product details</div></div>

			<div class="col destr"><div class="prod-tab">description</div></div>

		</div>

		<div class="row">

			<div class="col-6 pdtcon">				

				<div class="info-tab">

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1" data-toggle="collapse" data-target="#basic_info">Basic Information</a>

						<div id="basic_info" class="collapse show">

							<div class="clearfix detail-list">Item package quanitity <span class="float-right">1</span></div>

							<div class="clearfix detail-list">Metal  <span class="float-right">Gold</span></div>

							<div class="clearfix detail-list">Purity <span class="float-right">22K</span></div>

							<div class="clearfix detail-list">Brand <span class="float-right">Vaibhav</span></div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#diamond_info">Diamond Information</a>

						<div id="diamond_info" class="collapse">

							<div class="clearfix detail-list">Item package quanitity <span class="float-right">1</span></div>

							<div class="clearfix detail-list">Metal  <span class="float-right">Gold</span></div>

							<div class="clearfix detail-list">purity <span class="float-right">22K</span></div>

							<div class="clearfix detail-list">Brand <span class="float-right">Vaibhav</span></div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#certification_details">Certification Details</a>

						<div id="certification_details" class="collapse">

							<div class="clearfix detail-list">Gold certification <span class="float-right text-uppercase">Bis Hallmark</span></div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#prod_dimension">Product Dimension</a>

						<div id="prod_dimension" class="collapse">

							<div class="clearfix detail-list">Dimension</div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#metal_info">Metal Information</a>

						<div id="metal_info" class="collapse">

							<div class="clearfix detail-list">Gold color <span class="float-right">Yellow</span></div>

							<div class="clearfix detail-list">Gross Weight (Approx Gms) <span class="float-right">55.92</span></div>

							<div class="clearfix detail-list">Net Weight <span class="float-right">53.478</span></div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#other_info">Other Information</a>

						<div id="other_info" class="collapse">

							<div class="clearfix detail-list">Item package quanitity <span class="float-right">1</span></div>

							<div class="clearfix detail-list">Metal  <span class="float-right">Gold</span></div>

							<div class="clearfix detail-list">purity <span class="float-right">22K</span></div>

							<div class="clearfix detail-list">Brand <span class="float-right">Vaibhav</span></div>

						</div>

					</div>

					<div>

						<a href="javascript:void(0);" class="detail-collapse mt-1 collapsed" data-toggle="collapse" data-target="#prod-find">Product Findings</a>

						<div id="prod-find" class="collapse">

							<div class="clearfix detail-list">Item package quanitity <span class="float-right">1</span></div>

							<div class="clearfix detail-list">Metal  <span class="float-right">Gold</span></div>

							<div class="clearfix detail-list">purity <span class="float-right">22K</span></div>

							<div class="clearfix detail-list">Brand <span class="float-right">Vaibhav</span></div>

						</div>

					</div>

				</div>

			</div>



         <div class="row mobi_des">

            <div class="col destr"><div class="prod-tab">description</div></div>

        </div>



			<div class="col-6 descon">				

				<div class="info-tab description">

					<h6 class="fz-big desc-head">Have a question? <span class="fz-medium">We'd love to help <span class="font-weight-bold">+91 91774 03000</span></span></h6>

					<form action="">

						<input class="faq-text" type="text" placeholder="Name">

						<input class="faq-text" type="text" placeholder="Email">

						<input class="faq-text" type="text" placeholder="Contact number">

						<input class="faq-text" type="text" placeholder="Question">

						<button class="faq-submit" type="submit">Submit</button>

					</form>

				</div>

			</div>

		</div>

	</div>

	<!-- Nav tabs -->

	<ul id="view_recent_prod" class="nav nav-tabs border-0">

	  <li class="nav-item">

	    <a class="nav-link active" data-toggle="tab" href="#view_similar">View Similar</a>

	  </li>

	  <li class="nav-item">

	    <a class="nav-link" data-toggle="tab" href="#recently_viewed">Recently Viewed</a>

	  </li>

	</ul>



	<!-- Tab panes -->

	<div class="tab-content mb-5 view-recent">

	<div class="tab-pane container-fluid active" id="view_similar">

		<div class="row text-center">

			<div class="col view_pdts">

				<a href="#" class="d-block similar-products">

		  			<img class="img-fluid" src="images/jim1.jpg" alt="">

		  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

		  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

				</a>

			</div>

			<div class="col view_pdts">

				<a href="#" class="d-block similar-products">

		  			<img class="img-fluid" src="images/jim2.jpg" alt="">

		  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

		  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

				</a>

			</div>

			<div class="col view_pdts">

				<a href="#" class="d-block similar-products">

		  			<img class="img-fluid" src="images/jim3.jpg" alt="">

		  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

		  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

				</a>

			</div>

			<div class="col view_pdts">

				<a href="#" class="d-block similar-products">

		  			<img class="img-fluid" src="images/jim4.jpg" alt="">

		  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

		  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

				</a>

			</div>

			<div class="col view_pdts">

				<a href="#" class="d-block similar-products">

		  			<img class="img-fluid" src="images/jim5.jpg" alt="">

		  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

		  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

				</a>

			</div>

		</div>

	</div>

	  	<div class="tab-pane container-fluid fade" id="recently_viewed">

		  	<div class="row text-center">

		  		<div class="col recent_pdts">

		  			<a href="#" class="d-block similar-products">

			  			<img class="img-fluid" src="images/jim5.jpg" alt="">

			  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

			  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

		  			</a>

		  		</div>

		  		<div class="col recent_pdts">

		  			<a href="#" class="d-block similar-products">

			  			<img class="img-fluid" src="images/jim4.jpg" alt="">

			  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

			  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

		  			</a>

		  		</div>

		  		<div class="col recent_pdts">

		  			<a href="#" class="d-block similar-products">

			  			<img class="img-fluid" src="images/jim3.jpg" alt="">

			  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

			  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

		  			</a>

		  		</div>

		  		<div class="col recent_pdts">

		  			<a href="#" class="d-block similar-products">

			  			<img class="img-fluid" src="images/jim2.jpg" alt="">

			  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

			  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

		  			</a>

		  		</div>

		  		<div class="col recent_pdts">

		  			<a href="#" class="d-block similar-products">

			  			<img class="img-fluid" src="images/jim1.jpg" alt="">

			  			<div class="prod-name">22K Wrapped-n-Rapt Gold Earrings</div>

			  			<span class="view-price"><span class="font-weight-bold">₹ 18,047</span> <span class="text-strike">18,337</span></span>

		  			</a>

		  		</div>

		  	</div>

		</div>

	</div>

	<div class="container-fluid py-1">

		<div class="row mt-5">

			<div class="col">

				<div class="head2 text-uppercase text-violet">testimonial</div>

			<div id="testimonial" class="carousel slide" data-ride="carousel">

				  <!-- The slideshow -->

				  <div class="carousel-inner text-center">

				    <div class="carousel-item active">

				      <img src="images/Testimony_1.jpg" alt="testimonil">

				      <div class="future">I want my vaibhav to be my future generation's preferred jeweller too</div>

				    </div>

				    <div class="carousel-item">

				      <img src="images/Testimony_2.jpg" alt="testimonil">

				      <div class="future">I want my vaibhav to be my future generation's preferred jeweller too</div>

				    </div>

				    <div class="carousel-item">

				      <img src="images/Testimony_3.jpg" alt="testimonil">

				      <div class="future">I want my vaibhav to be my future generation's preferred jeweller too</div>

				    </div>

				  </div>



			</div>

			</div>

			<div class="col review-faq">

				<div class="head2 text-uppercase text-violet">write review</div>

				<!-- Nav tabs -->

				<ul class="nav nav-tabs text-center border-0">

				  <li class="nav-item col p-0 m-0">

				    <a class="nav-link border-0 active" data-toggle="tab" href="#review">Write a review</a>

				  </li>

				  <li class="nav-item col p-0 m-0">

				    <a class="nav-link border-0" data-toggle="tab" href="#faq">Ask a question?</a>

				  </li>

				</ul>



				<!-- Tab panes -->

				<div class="tab-content review-faq-tab">

			  		<div class="tab-pane container active pb-4" id="review">

			  			<form action="">

				  			<div class="mb-2">

				  				<div class="d-inline-block">Score*</div>

				  				<div class="d-inline-block">

				  					<img class="review-star" src="images/score.svg" alt="score-image">

				  					<img class="review-star" src="images/score.svg" alt="score-image">

				  					<img class="review-star" src="images/score.svg" alt="score-image">

				  					<img class="review-star" src="images/score.svg" alt="score-image">

				  					<img class="review-star" src="images/score.svg" alt="score-image">

				  				</div>

				  			</div>

				  			<div class="mb-2">

					  			<label for="">Name *</label>

					  			<input type="text" class="review-input">

				  			</div>

				  			<div class="mb-2">

				  				<label for="">E-mail ID</label>

				  				<input type="text" class="review-input">

				  			</div>

				  			<div class="mb-2">

				  				<label for="">Title *</label>

				  				<input type="text" class="review-input">

				  			</div>

				  			<div class="mb-2">

				  				<label for="">Review*</label>

				  				<textarea class="review-input" name="" id="" cols="30" rows="1"></textarea>

				  			</div>

				  			<div class="clearfix mt-4">

					  			<button class="send" type="submit">send</button>

					  			<button class="cancel" type="button">cancel</button>

				  			</div>

			  			</form>

				  	</div>

					<div class="tab-pane container fade" id="faq">

						<h6 class="fz-big">Have a question? <span class="fz-medium">We'd love to help <span class="font-weight-bold">+91 91774 03000</span></span></h6>

						<form action="">

							<input class="faq-text" type="text" placeholder="Name">

							<input class="faq-text" type="text" placeholder="Email">

							<input class="faq-text" type="text" placeholder="Contact number">

							<input class="faq-text" type="text" placeholder="Question">

							<button class="faq-submit" type="submit">Submit</button>

						</form>

					</div>

				</div>

			</div>

		</div>

	</div>

	<div class="advantage my-5">

		<h3 class="mb-3 vaijew">VAIBHAV ADVANTAGE</h3>

		<p>we believe in making jewellery shopping fun and spontaneous that is why we take care of everything else</p>

		<div class="divider"></div>

	</div>

	<div class="inner-block text-center">

        <div class="align-items-center d-flex justify-content-between m-auto px-5 mobile_hide">

            <span class="p-2 dayretun">

                <img class="w-100" src="images/store-fac-1.jpg" alt="shop-facilities">

                <p>15<br>Days Returns</p>

            </span>

            <span class="p-2 Exchange">

                <img class="w-100" src="images/store-fac-2.jpg" alt="shop-facilities">

                <p>Lifetime<br>Exchange</p>

            </span>

            <span class="p-2 jewellery">

                <img class="w-100" src="images/store-fac-3.jpg" alt="shop-facilities">

                <p>Certified<br>Jewellery</p>

            </span>

            <span class="m-3 shop-facilities">

                <img class="w-100" src="images/store-fac-4.jpg" alt="shop-facilities">

            </span>

            <span class="p-2 Refund">

                <img class="w-100" src="images/store-fac-5.jpg" alt="shop-facilities">

                <p>100%<br>Refund</p>

            </span>

            <span class="p-2 emiopt">

                <img class="w-100" src="images/store-fac-6.jpg" alt="shop-facilities">

                <p>EMI<br>Option</p>

            </span>

            <span class="p-2 international-shi">

                <img class="w-100" src="images/store-fac-7.jpg" alt="shop-facilities">

                <p>International<br>Shipping</p>

            </span>

        </div>





        <div class="align-items-center d-flex justify-content-between m-auto px-5 mobile_display">



            <div class="first_one">

                <span class="col-4 p-2 dayretun">

                    <img class="w-100" src="images/store-fac-1.jpg" alt="shop-facilities">

                    <p>15<br>Days Returns</p>

                </span>

                 <span class="col-4 m-3 shop-facilities">

                   <img class="w-100" src="images/store-fac-4.jpg" alt="shop-facilities">

                 </span>

                 <span class="col-4 p-2 Refund">

                  <img class="w-100" src="images/store-fac-5.jpg" alt="shop-facilities">

                  <p>100%<br>Refund</p>

                </span>



                

            </div>

        

            <div class="first_two">

                <span class="col-3 p-2 Exchange">

                    <img class="w-100" src="images/store-fac-2.jpg" alt="shop-facilities">

                    <p>Lifetime<br>Exchange</p>

                </span>

                <span class="col-3 p-2 jewellery">

                    <img class="w-100" src="images/store-fac-3.jpg" alt="shop-facilities">

                    <p>Certified<br>Jewellery</p>

                </span>



                <span class="col-3 p-2 emiopt">

                    <img class="w-100" src="images/store-fac-6.jpg" alt="shop-facilities">

                    <p>EMI<br>Option</p>

                </span>

                <span class="col-3 p-2 international-shi">

                    <img class="w-100" src="images/store-fac-7.jpg" alt="shop-facilities">

                    <p>International<br>Shipping</p>

                </span>

          </div>

        </div>





    </div>

    <div class="inner-block-newsletter mt-5">