<style>


/* edit by prudhviraj on 16/03/2023 starts */

.product-rev-del {
    display: grid;
    grid-template-columns: 0.6fr 0.9fr !important;
    padding-top: 10px;
}
.p-sku {
    border-bottom: 1px solid #ccc;
    height: 40px;
    width: 380px;
    max-width: 100%;
}
    .fz-small.text-violet.text-uppercase {
        color: #aa09c2!important;
        width: 50% !important;
        padding-top: 10px;
        font-size: 13px;
        float: left !important;
        /*padding-right: 60px;*/
    }

     .price_btn {
        letter-spacing: 0.2px;
        color: darkcyan !important;
        font-weight: 400 !important;
        text-transform: capitalize !important;
        /*text-transform: uppercase;
        font-weight: 600;*/
        font-size: 13px;
    }
    
    .message {
      padding: 10px 10px;
      height: auto;
      margin: 68px auto 10px auto !important;
      width: 100%;
      position: relative;
    }

    .catalog-product-view .cust-btn--inside {
       margin-left: -50px !important;
       padding: 10px 10px !important;
       font-size: 12px !important;
     }

/* edit by prudhviraj on 16/03/2023 starts */







    #international-button .send_enquiry{
        background-color: #6e2083 !important;
        border-radius: 4px;
        text-transform: uppercase;
        font-weight: normal !important;
        border: none !important;
        text-align: center;
        font-size: 14px !important;
        width: 50%;
    }
    .product .page-title{
        letter-spacing: .2px !important;
    }

.showmessage, #checkDelivery-form .message.success {
    display: block;
    font-size: 12px;
    /*margin: 20px auto 10px auto;*/
    background: #e5efe5;
    color: #006400;
    padding: 5px 10px;
    width: 80% !important;
    position: relative;
    height: auto;

    /* height: 26px; */
}

.showmessage:after, #checkDelivery-form .message.success:after{

    color: #e5efe5;
    border-left: 28pxpx solid;
    border-top: 26px solid transparent;
    border-bottom: 20px solid transparent;
    display: inline-block;
    content: '';
    position: absolute;
    top: 0;
    right: -13px;
}
 .showmessage:after, #checkDelivery-form .message.success:after {
       /* color: #e5efe5;
        border-left: 13px solid;
        border-top: 13px solid transparent;
        border-bottom: 13px solid transparent;
        display: inline-block;
        content: '';
        position: absolute;
        top: 0;
        right: -13px;*/
    }
 button:focus, button:active {
    background-color: #6e2083 !important;
} 


button:active, button:hover {
    background-color: #6e2083 !important;
    color: white !important;
    height: 46px !important;
}
    .product-info-main .product-info-price .old-price .price-wrapper .price {
         display: block !important;
         font-size: 22px; 
    }
    
    .mobile-section .footer-title {
        color: #ffffff !important;
        display: inline-block;
        position: relative;
        margin-bottom: 20px;
        margin-top: 20px;
    }
    .product-info-main .product-info-price .old-price .price-wrapper .price{
        display: none;
    }
    footer h5 {
        font-size: 16px;
        font-weight: 600 !important;
    }
    .footer-bottom h3 {
        margin: 0;
        border-bottom: 1px solid;
        padding: 10px;
        font-size: 16px;
        margin-bottom: 20px;
    }
    .footer-bottom{
        background-color: #431A44 !important;
    }
    .cp p {
        padding: 20px 0 0 0 !important;
        color: #fff !important;
        font: 13px/1 sans-serif !important;
    }
    .cp{
        padding: 40px 0 0 0;
    }

    .mobile-section .footer-title::after {
        position: absolute;
        content: "";
        width: 100%;
        height: 1px !important;
        background-color: #fff !important;
        left: 0;
        bottom: -5px;
    }
    footer li {
        font-size: 13px !important;
        padding-bottom: 10px !important;
    }
    .mobile-section .footer-top li a {
        color: #fff !important;
    }
    .pl-35{
        padding-left: 35px;
    }

    .page-footer {
        margin-top: 0;
        height: auto!important;
    }
    .mobile-section .footer-top{
        background-color: #6e2083 !important;
    }
    .inner-block-newsletter input#newsletter {
        height: 40px !important;
        margin: 0 0 0 15px;
        width: 240px;
    }
    .inner-block-newsletter button.p-2 {
        background: #6e2083;
        height: 38px;
        font-size: 1.4rem;
        width: 120px !important;
        margin-left: 6px;
        border-radius: 4px;
    }
    .inner-block-newsletter h2 {
        font-size: 17px !important;
        margin: 18px 0 10px 0px;
        letter-spacing: 0.3px;
        font-weight: 600;
    }
    .container-fluid.d-flex.justify-content-center.px-5.py-3 {
        display: initial!important;
        width: 100%;
        float: left;
        margin-left: 10px;
    }
    .pr-5, .px-5 {
        padding-left: 0 !important;
    }
    .pr-5, .px-5 {
        padding-right: 3rem !important;
    }
    .pt-3, .py-3 {
        padding-top: 1rem !important;
    }
    .nav-toggle:before {
        content: '\f0c9';
        font-family: 'fontawesome';
        font-size: 24px;
        margin-top: 5px;
    }
    #sticky_header {
            top: 20px !important;
        padding-bottom: 5px;
    }
    #sticky_header .mobile-search form button i {
        font-size: 18px;
        padding-right: 5px;
    }
    
    /* edit by prudhvi 19/01/2023 */
    span.base.ct-title {
        font-size: 16px !important;
        color: #212529 !important;
    }
    .category-heading {
        background: unset !important;
        font-weight: 600 !important;
        width: 100% !important;
        margin-bottom: 1em !important;
    }
    .btn-accordion{
        font-size: 16px !important;
    }
    .page-title-wrapper.category-heading {
        margin-top: 50px !important;
    }
    .product-info-price .price-box .price-container>span {
   
    }
    .customize{
        font-size: 14px !important;
    }
    .contact-section {
        width: 100%;
        float: left;
        margin-top: 1.5rem;
        margin-bottom: 2rem;
    }
    .breadcrumbs .item:not(:last-child):after {
        -webkit-font-smoothing: antialiased;
        font-size: 9px;
        line-height: 10px;
        font-family: FontAwesome !important;
        content: '\f054' !important;
        margin: 2px 5px;
        vertical-align: top;
        display: inline-block;
        font-weight: 400;
        overflow: hidden;
        speak: none;
        text-align: center;
    }
    .cust-btn--primary{
        background: #6F2D91 !important;
    }

    .cust-btn--primary:hover {
        background: #994ac1 !important;
    }
    .breadcrumbs{
        margin: 0 0 5px 15px !important;
        display: block !important;
        white-space: nowrap; 
        text-overflow: ellipsis!important;
        width: 90% !important;
        overflow: hidden !important;
    }
     .breadcrumbs .item {
        font-size: 9px !important;
    }
    .breadcrumbs .items {
        font-size: 9px !important;
        color: #707070;
        margin: 5px 0 0 0;
        padding: 0;
        list-style: none none;
    }
    #sticky_header .logo {
        top: 0 !important;
        left: 0 !important;
        margin: 0 !important;
        padding: 0 10px 0 10px !important;
    }
    #sticky_header .mobile-search form input {
        border-radius: 50px;
        width: 200px;
    }
    #sticky_header .block-search input {
        left: 0 !important;
        top: 0 !important;
        height: 35px;
        position: relative !important;
        font-size: 11px;
    }
    .mobile-search form input {
        border: 2px solid #6e2083;
        padding: 10px;
    }
    .img-container img.lazy-image.loaded {
        opacity: 1;
        margin-top: 5px;
    }
    .breadcrumbs a {
        color: #aa09c2;
        text-decoration: none;
    }
    .xzoom-gallery{
        border-radius: 4px !important;
        width: 90px !important;
        height: 90px !important;
        border: 1px solid #ccc !important;
        margin-right: 3px !important;
    }
    .carousel-indicators {
        position: absolute;
        right: 0;
        left: 0;
        margin-top: 10px;
        z-index: 15;
        display: flex;
        justify-content: center;
        padding-left: 0;
        margin-right: 15%;
        margin-left: 15%;
        list-style: none;
    }
    .carousel-indicators {
        top: 100%;
    }
    
    span.base.ct-title {
        font-size: 20px;
        color: #5a5a5a;
    }
    a.action.add {
        color: grey;
        font-size: 13px;
        font-weight: 400;
        padding: 0 0.7rem;
    }


    .product-info-price .price-box .price-container .price {
        color: black !important;
        display: block;
        margin-bottom: 5px;
        margin-top: 25px;
        margin-left: 130px !important;
    }
    .form__field {
        width: 300px !important;
        color: #a3a3a3 !important;
        font: 500 12px/1.55 Lato,sans-serif !important;
        height: 100% !important;
        padding: 12px 12px !important;
        margin-top: 15px;
        margin-bottom: 12px;
    }
    #buy-now>span{
        font-size: 14px;
    }
    .cust-btn--inside {
        margin-left: -85px !important;
    }
   
    .contact-us .align-right {
        float: left;
        width: 60%;
    }
    .card-header {
        background-color: #fdf0fb !important;
        border-bottom: 1px solid #bcbcbc !important;
    }
    .info-tab {
        padding: 0.5rem 3rem 0 1rem;
    }
     #buy-now {
        border-radius: 4px !important;
    }
    .try-on, .add-to-cart, .cart {
        font-weight: 400;
        color: #FFF !important;
        text-decoration: none !important;
        width: 130px;
        height: 42px;
        text-transform: uppercase;
    }
    .shop-img {
        width: 16px;
        margin-right: 0.3rem;
    }
    .need-help {
        font-size: 11px;
        color: grey;
    }
    .product-details-btn{
        background-color: #6f2d91 !important;
        color: white !important;
        border-color: #007bff !important;
        height: 40px;
        margin-top: 20px;
    }
    .card-body {
        font-weight: 600;
        padding: 5px 10px !important;
        font-size: 12px !important;
        text-decoration: none !important;
        border-bottom: 0px !important;
    }
    .detail-info{
        font-weight: 400;
    }
    .detail-qty {
        font-weight: 400;
    }
    .btn-link {
        color: black !important;
        font-weight: 600;
    }
    #view_recent_prod .nav-link.active {
        color: #6e2083;
        border-bottom: 2px solid;
        margin-bottom: 15px;
    }
    .inner-block-newsletter button.p-2 
    {
        background: #6e2083;
        height: 37px;
        font-size: 1.4rem;
        width: 90px;
    }
    .product_name_slider{
        margin-bottom: 5px;
    }
    .inner-block-newsletter h2{
        font-size: 16px !important;
        margin-bottom: 12px;
        margin-top: 10px;
        margin-left: 20px;
    }


    .nav-toggle:before {
        content: '\f0c9';
        font-family: 'fontawesome';
        font-size: 24px;
    }
    .product-item-name>a, .product.name a>a{
        font-size:15px;
    }
    .products-related{
        display: block !important;
    }
    .product-items{
        width: 100% !important;
    }
    .price{
        margin-bottom: -5%;
        margin-top: 9%;
    }
    .product-info-price span.price {
        width: 0px !important; 
        float: unset !important; 
        margin-left: 0!important; 
        text-align: unset !important; 
    }
    .deatils_btn{
        width: 100%;
        color: white !important;
        background-color: #6f2d91 !important;
        height: 45px;
        border-radius: 4px;
        margin-top: 20px;
    }

    .inner-block-newsletter{
        background: #6e2083 !important;
        margin: 10px 0 10px 0 !important;
        height: 110px;
    }
    .footer-logo{
        padding: 10px 0 15px 0;
    }
    .w-60{
        /*width: 0% !important;*/
    }
    .product-image-photo{
        height: auto !important;
    }
    .pager{
        display: none;
    }
    ol{
        display: inline-flex !important;
        overflow: auto !important;
    }


    .product-item {
        overflow: initial !important;
            width: 150px !important;
    }
   .block-title{
        text-align: center;
        text-transform: capitalize;
    }


</style>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
$producttype = $product->getTypeId();
$_product = $block->getProduct();
$price = $_product->getPrice();
$sku =  $_product->getSku();
$name = $_product->getName();
$weight = $_product->getWeight();
$image_url  = $block->getUrl('pub/media/catalog').'product'.$_product->getImage();
$product_url = $_product->getProductUrl(); 
$purity =$_product->getResource()->getAttribute('purity')->getFrontend()->getValue($_product);
$gross_weight = $_product->getResource()->getAttribute('gross_weight_approx_gms')->getFrontend()->getValue($_product);
$net_weight = $_product->getResource()->getAttribute('net_weight')->getFrontend()->getValue($_product);
$style = $_product->getResource()->getAttribute('style')->getFrontend()->getValue($_product);
$brands_name = $_product->getResource()->getAttribute('brands_name')->getFrontend()->getValue($_product);
$gst = (int)($_product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($_product));
$finalPriceAmt = round($_product->getPriceInfo()->getPrice('final_price')->getValue());
$gcm_image_upload = $_product->getResource()->getAttribute('gcm_image_upload')->getFrontend()->getValue($_product);
if(empty($gcm_image_upload)){
$getgcm_image_upload ='';
}
else{
$getgcm_image_upload  = $block->getUrl('pub/media/catalog').'attribute-data/'.$gcm_image_upload;
}
$price = $finalPriceAmt + $gst;
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categoryIds = $_product->getCategoryIds();
 $cat_string = "";
$categories = $categoryCollection->create()
                                 ->addAttributeToSelect('*')
                                 ->addAttributeToFilter('entity_id', $categoryIds);
 
foreach ($categories as $category) {
    $cat_string .=','.$category->getName();
}
$cat_string = substr($cat_string, 1);

?>
<script type="text/javascript">
    var ProductData = {};
    ProductData.price = <?php echo $price;  ?>;
    ProductData.sku = '<?php echo $sku;  ?>';
    ProductData.name = '<?php echo $name;  ?>';
    ProductData.weight = '<?php echo $weight;  ?>';
    ProductData.image_url = '<?php echo $image_url;  ?>';
    ProductData.gcm_image_url = '<?php echo $getgcm_image_upload;  ?>'; 
    ProductData.product_url = '<?php echo $product_url;  ?>';
    ProductData.purity = '<?php echo $purity;  ?>';
    ProductData.gross_weight = '<?php echo $gross_weight;  ?>';
    ProductData.net_weight = '<?php echo $net_weight;  ?>';
    ProductData.style = '<?php echo $style;  ?>';
    ProductData.brand = '<?php echo $brands_name;  ?>';
    ProductData.categories = '<?php echo $cat_string;  ?>';
    
    // dataLayer.push({'event':'product_view',
    //     'price': echo $price;  ?>,
    //     'sku':' echo $sku;  ?>',
    //     'name':' echo $name;  ?>',
    //     'weight':' echo $weight;  ?>',
    //     'image_url':' echo $image_url;  ?>',
    //     'gcm_image_url':' echo $getgcm_image_upload;  ?>',
    //     'product_url':' echo $product_url;  ?>',
    //     'purity':' echo $purity;  ?>',
    //     'gross_weight':' echo $gross_weight;  ?>',
    //     'net_weight':' echo $net_weight;  ?>',
    //     'style':' echo $style;  ?>',
    //     'brand':' echo $brands_name;  ?>',
    //     'categories':' echo $cat_string;  ?>'
       
    // });
</script>
<div class="container-fluid mb-5">
        <!-- <div class="row"> -->
            <!-- <div class="col pdt"><div class="prod-tab">product details</div></div> -->
            <!-- <div class="col destr"><div class="prod-tab">description</div></div> -->
        <!-- </div> -->
        <div class="container">
          <button type="button" style="background-color: #6f2d91 !important;color: white !important;border-color: #007bff !important;" class="btn btn-accordion deatils_btn btn-primary" data-toggle="collapse"  data-target="#pdetais">Product Details</button>
          <div id="pdetais" class="collapse show">
            

        <div class="row">
            <div class="pdtcon"> 
            <div class="info-tab">             
               <?= $this->getChildHtml('specification'); ?>
            </div>
            </div>
            <!-- <div class="row mobi_des">
                <div class="col destr"><div class="prod-tab">description</div></div>
            </div> -->
            <div class="descon">
             <div class="info-tab description ht-q m-0">  
             <!-- <div class="row justify-content-center">
                    <div class="heading-purchase"><h5>INCLUDED WITH PURCHASE</h5>
                    </div>
                    <div class="col-12 col-md-6 aspects">
                              <picture>
                         <source type="image/webp" data-srcset="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>" srcset="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>">
                    <img loading="lazy" src="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>" data-srcset="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>" srcset="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>" class="lazy-image" data-src="<?php echo $this->getUrl('pub/media/').'product_price_include.jpg'; ?>" width="330" height="157" alt="vaibhav-advantage-mobile" data-pagespeed-no-transform >
                    </picture> -->
                     <!--    <ul>
                            <li>
                                <span><i class="fa fa-gift" aria-hidden="true"></i></span>Free Gift Box
                            </li>
                            <li>
                                <span><i class="fa fa-diamond" aria-hidden="true"></i></span>Conflicts Free Diamonds
                            </li>
                            <li>
                                <span><i class="fa fa-bus" aria-hidden="true"></i></span>Fast Shipping And Production
                            </li>
                            <li>
                                <span><i class="fa fa-ring" aria-hidden="true"></i></span>Free Engraving
                            </li>
                            <li>
                                <span><i class="fa fa-id-card-o" aria-hidden="true"></i></span>Authenticity Certificates
                            </li>
                            <li>
                                <span><i class="fa fa-bus" aria-hidden="true"></i></span>Free Domestic Shipping
                            </li>
                        </ul> -->
                    <!-- </div> -->
                <!-- </div> -->
                 <!-- <div class="row text-center justify-content-center info-div">
                    <div  class="heading-end"><h5>STAY SOCIAL WITH VAIBHAV JEWELLERS</h5></div>
                    <p>Follow us to stay updated on the latest collections, Offers and much more. We love surprises, so keep an eye out for those!</p>
                    <div class="d-flex justify-content-between m-auto w-75">
                        <a rel="nofollow" target="_blank" href="https://www.facebook.com/vaibhavjewllers">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://www.instagram.com/vaibhavjewellers/?hl=en">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://twitter.com/vaibhavjewelers?lang=en">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://www.youtube.com/channel/UCT6Uv0OflrUVA2VDNk_C2Tw">
                            <i class="fab fa-youtube"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://api.whatsapp.com/send?phone=919177403000">
                            <i class="fab fa-whatsapp"></i>
                        </a>
                        <a rel="nofollow" target="_blank" href="https://in.pinterest.com/VaibhavJewellers">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>   -->           
                <?= $this->getChildHtml('product.askform'); ?>
            </div>
         </div>
        </div>


          </div>
        </div>

    </div>
