<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>

<?php 
$_product = $block->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');

$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
$shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
$gst = (int)($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
$currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
$currencySymbol = $currency->getCurrencySymbol(); 
$offer_percentage = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
$smart_percentage = $product->getResource()->getAttribute('smart_percentage')->getFrontend()->getValue($product);
$short_description = $product->getResource()->getAttribute('short_description')->getFrontend()->getValue($product);
$remarks = $product->getResource()->getAttribute('customattr')->getFrontend()->getValue($product);
$offerPrice = ($finalPriceAmt - ($finalPriceAmt * $smart_percentage)/100);

$priceWithoutTax = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
$makingCharges = $product->getResource()->getAttribute('making_charge')->getFrontend()->getValue($product);

$inr='₹';
$usd='$';

$price_with_tax= round($_product->getSpecialPrice()+$gst);
 $inr_price= number_format($price_with_tax);
?>


 <div data-bind="scope: 'config_product'">
  <div data-bind="visible: vbjOffer" class="pdp-offer mb-2 vbjoffer">
     <span class="offer-head text-orange"></span>
      <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"> </span> <span class="mf offer-text"></span></span> 
  </div>
</div>
    <?php 
  if($_product->getData('discount_making_charge_in') || $_product->getData('metal_discount_in') || $_product->getData('discount_diamond_in') || $_product->getData('product_discount') || $_product->getData('discount_wastage')){
    $discount_making_charge_in = $_product->getData('discount_making_charge_in');
    $metal_discount_in= $_product->getData('metal_discount_in');
    $product_discount= $_product->getData('product_discount');
    $discount_diamond_in = $_product->getData('discount_diamond_in');
    $discount_wastage = $_product->getData('discount_wastage');
    ?>
<div class="pdp-offer mb-2">
 <span class="offer-head text-orange">Offer Price:</span>
     <?php if($currencyCode =='INR' && $currencySymbol =='₹'){?>

                      <?php switch (true) {
                    case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)):  ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span> 
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf"></span> </span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"></span> </span>
                      <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf">(<?php echo $product_discount. "% savings on Product"; ?>)</span> </span>
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($discount_diamond_in)): ?>
                     <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>

                    <?php break;
                     case (isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf"></span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                     case (isset($discount_making_charge_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <?php break;
                    case (isset($metal_discount_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf"></span> </span>
                    <?php break;
                      case (isset($discount_diamond_in)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                    <?php break;
                     case (isset($product_discount)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                    case (isset($discount_wastage)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_wastage."% off on VA"; ?>)</span> </span>
                    <?php break;
                }
                    ?>
    <?php
  } else { ?>
  
                      <?php switch (true) {
                    case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)):  ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span> 
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> </span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($metal_discount_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> </span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                   case (isset($discount_making_charge_in) && isset($discount_diamond_in)): ?>
                     <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>

                    <?php break;
                     case (isset($metal_discount_in) && isset($discount_diamond_in) && isset($product_discount)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span></span>
                     <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                      <span class="offer-price text-orange" style="margin-top: -10px; margin-left: 32%;"><span class="dis_make_charge_actual" style="float: none; visibility: hidden;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span><span class="mdf"> (<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                     case (isset($discount_making_charge_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_making_charge_in. "% savings on Making Charges"; ?>)</span></span>
                    <?php break;
                    case (isset($metal_discount_in)): ?>
                    <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $metal_discount_in."% savings on metal charges"; ?>)</span> </span>
                    <?php break;
                      case (isset($discount_diamond_in)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_diamond_in."% savings on diamond cost"; ?>)</span> </span>
                    <?php break;
                     case (isset($product_discount)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $product_discount."% savings on Product"; ?>)</span> </span>
                    <?php break;
                    case (isset($discount_wastage)): ?>
                   <span class="offer-price text-orange"><span class="dis_make_charge_actual" style="float: none;"><?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?></span> <span class="mdf">(<?php echo $discount_wastage."% off on VA"; ?>)</span> </span>
                    <?php break;
                }
                    ?>
  <?php } ?>
 </div>
<?php }
 ?>
   <?php if($remarks): ?>
                    <p style="margin-bottom: 0px;font-size: 12px;"><b>Note: </b><?php echo $remarks; ?></p>
                 <?php endif; ?>
                <!-- <span class="coupon text-gray">Use coupon <span class="c-code text-uppercase text-orange p-1">making60</span> at checkout</span> -->
               


<?php if(isset($smart_percentage)){?>
<div id="smartbuy_prd" class="delay_deilvery" style="display: block;">
    <div class="smart_overlay"></div>
    <div id="delay_deilvery_opt">
    <!--<input type="hidden"  id="check_delayh" name="check_delayh" value="yes"/>-->
    <div id="smrtbuy_oncl">
    <input type="checkbox" value="offer" id="smartbuy_product" name="smartbuy_product">
    <input type="hidden" id="vaoffer" name="vaoofer" value="<?php echo $product->getId(); ?>">
    <input type="hidden" id="deliverytime" name="deliverytime" value="<?php echo $shippingCode ; ?>">
    <input type="hidden" id="vaprice" name="vaprice" value="">
    <label class="fanc_smrtch"></label>
    <label for="smartbuy_product" id="smartbuy_product_label" class="icon-smart-buy-01 smart_buy_label">
    <u class="smartby">Smart Buy</u>
    </label>
    <span id="OtpBaseUrl" class="OtpBaseUrl" style="display: none"><?php echo "https://www.vaibhavjewellers.com/staging/";//$block->getUploadFormUrl(); ?></span>
    <span class="smartmssg" style="font-size: 11px; margin-left: 1px;color:#6d1f81"></span>
    </div>
    </div>
    </div>
<?php } ?>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
$(document).ready(function(){
            // for hide add to cart button
             var offr = "<?php echo $smart_percentage; ?>";
            
             if(offr){
                 // $("#product-addtocart-button").css("display", 'none');
             }

       $('input[name="smartbuy_product"]').click(function(){
            var val = $("#smartbuy_product").val();
            if(val == 'offer'){
                $('.smartmssg').css("display", "block");
            if($(this).prop("checked") == true){
                $("#smartbuy_product").attr('value', 'nonoffer');
                $("#buy-now-offer").attr("disabled", false);
                $.cookie('cookie_name', 'nonoffer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                var date = new Date();
                date.setDate(date.getDate() + 30);
                const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
                var dd = date.getDate();
                var mm = monthNames[date.getMonth()];//date.getMonth() + 1;
                var y = date.getFullYear();
                var someFormattedDate = dd + ' ' + mm + ' , ' +  y;
                var conf = "<?php echo $conf; ?>";
                var res = conf.replace('one week', someFormattedDate);
                $('.showmessage').text(res);
                $('.pd_container_rgt_emi').css("display", "none");
                var currencyCode = "<?php echo $currencyCode; ?>";
                var currencySymbol = "<?php echo $currencySymbol; ?>";
                if(currencyCode=='INR' && currencySymbol=='₹'){

                var price_flag = $('#price_flag').val();
                var custom_price = $('#custom_price').val();
                var spl_price = $('#spl_price').val();
                  if(price_flag == '1') {
                    var price = (spl_price != "0") ? spl_price : custom_price;
                  } else {
                     console.log('<?php echo $gst; ?>');
                    console.log('<?php echo $finalPriceAmt; ?>');
                    var price = "<?php echo $finalPriceAmt +$gst; ?>";
                  }  
                    console.log(price);
                var apprx = "<?php echo $smart_percentage; ?>";
                if(apprx != null && apprx != ''){
                var realApprx = Math.ceil(parseFloat((price * apprx)/100));
                var realPrice = Math.ceil(parseFloat(price - realApprx));
                var num = realPrice.toLocaleString();
                }
                if(window.VBJ.specialPrice != "0") {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.special-price .price';
                      $(spl_element).html('₹'+num);
                  } else $('.special-price .price').html('₹'+num);
                } else {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.price';
                      $(spl_element).html('₹'+num);
                  } else $('.price').html('₹'+num);
                    
                } 
               
                 $('.save-amount').text('₹' + ' '+ realApprx);
                 $('.save-price').css('display','block');
               // $('.price').html('₹'+num);
                 $('.smartby').append($('.smartmssg').text('You have saved' + ' '+ '₹' + ' '+ realApprx + ' '+ 'for this products'));
               }else if(currencyCode=='USD' && currencySymbol=='$'){
                 var price_flag = $('#price_flag').val();
                var custom_price = $('#custom_price').val();
                var spl_price = $('#spl_price').val();
                  if(price_flag == '1') {
                    var price = (spl_price != "0") ? spl_price : custom_price;
                  } else {
                    console.log('<?php echo $gst; ?>');
                    console.log('<?php echo $finalPriceAmt; ?>');
                    var price = "<?php echo $finalPriceAmt +($gst*0.014); ?>";
                  } 
                var apprx = "<?php echo $smart_percentage; ?>";
                if(apprx != null && apprx != ''){
                  console.log(price);
                var realApprx = parseFloat(((price * apprx)/100).toFixed(2));
                console.log(realApprx);
                var realPrice = parseFloat((price - realApprx).toFixed(2));
                console.log(realPrice);  //Math.ceil()
                //alert('real price'+realPrice);
                var num = realPrice.toLocaleString();
                }
                 if(window.VBJ.specialPrice != "0") {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.special-price .price';
                      $(spl_element).html('$'+num);
                  } else $('.special-price .price').html('$'+num);
                } else {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.price';
                      $(spl_element).html('$'+num);
                  } else $('.price').html('$'+num);
                    
                } 
                 $('.save-amount').text('$' + ' '+ realApprx);
                 $('.save-price').css('display','block');

                 // $('.price').html(''+num);
                 // $('.smartby').append($('.smartmssg').text('You have saved' + ' '+ '$' + ' '+ realApprx + ' '+ 'for this products'));
                  
               }
            }
            }
            else {
            if(val =='nonoffer'){
                 $('.smartmssg').css("display", "none");
                 //$('.showmessage').text("");
            if($(this).prop("checked") == false){
                $("#smartbuy_product").attr('value', 'offer');
                $("#buy-now-offer").attr("disabled", true);
                 $('.save-price').css('display','none');
                $.cookie('cookie_name', 'offer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                $('.pd_container_rgt_emi').css("display", "block");
                $.cookie('cookie_name', 'offer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                $.cookie("cookie_name", 'null');
                var d =  new Date();
                var deliveryDate = "<?php echo $shippingCode; ?>";
                const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
                //const d = new Date();
                //console.log(monthNames[d.getMonth()]);
                d.setDate(d.getDate() + parseInt(deliveryDate, 10));
                var ddd = d.getDate();
                var mmm = monthNames[d.getMonth()];   //d.getMonth()+1;
                var yyy = d.getFullYear();
                var someFormattedDates = ddd + " " + mmm + " , " +  yyy;
                var conf = "<?php echo $conf; ?>";
                var ress = conf.replace('one week', someFormattedDates);
                $('.showmessage').text(ress);
                var currencyCode = "<?php echo $currencyCode; ?>";
                var currencySymbol = "<?php echo $currencySymbol; ?>";
                if(currencyCode=='INR' && currencySymbol=='₹'){
                var price_flag = $('#price_flag').val();
                var custom_price = $('#custom_price').val();
                var spl_price = $('#spl_price').val();
                  if(price_flag == '1') {
                    var price = (spl_price != "0") ? spl_price : custom_price;
                  } else {
                    var price = "<?php echo $finalPriceAmt +$gst; ?>";
                  } 
                var priceone = Math.ceil(parseFloat(price));
                var num = priceone.toLocaleString();
                if(window.VBJ.specialPrice != "0") {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.special-price .price';
                      $(spl_element).html('₹'+num);
                  } else $('.special-price .price').html('₹'+num);
                } else {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.price';
                      $(spl_element).html('₹'+num);
                  } else $('.price').html('₹'+num);
                    
                } 
                $('.save-price').css('display','none');
               // $('.price').html(''+num);
                 $('.smartby').append($('.smartmssg').text('You have saved' + ' '+ '$' + ' '+ realApprx + ' '+ 'for this products'));
              // $('.vcontainer').css("margin-top", "-45px");
                }else if(currencyCode=='USD' && currencySymbol=='$'){
                   var price_flag = $('#price_flag').val();
                var custom_price = $('#custom_price').val();
                var spl_price = $('#spl_price').val();
                  if(price_flag == '1') {
                    var price = (spl_price != "0") ? spl_price : custom_price;
                  } else {
                     var price = "<?php echo $finalPriceAmt +($gst*0.014); ?>";
                  } 
               
                var priceone = parseFloat(price).toFixed(2);
                //alert('real price'+price);
                var num = priceone.toLocaleString();
                 if(window.VBJ.specialPrice != "0") {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.special-price .price';
                      $(spl_element).html('$'+num);
                  } else $('.special-price .price').html('$'+num);
                } else {
                     if(price_flag == '1') {
                    var  spl_element = (spl_price != "0") ? '#vbjoffer-price' : '.price';
                      $(spl_element).html('$'+num);
                  } else $('.price').html('$'+num);   
                } 
                }
            }
            }
            }
        });
    });
});
</script>


