<style type="text/css">
 	
 	/*edit by prudhvi on 19/01/2023*/
 	
 	/*@media (max-width: 768px){
 	    
        .contact-us .d-inline-block {
            width: 15%;
            float: left;
            padding-right: 0!important;
            padding-left: 0!important;
        }
        .contact-us {
            vertical-align: top;
            border-left: unset !important;
        }
        
 	    
 	}*/
 	
 	</style>
 	
 	
<!--  	<div class="contact-section mb-4">
					<div class="contact-us d-inline-block px-4 pt-1">
						<div class="d-inline-block align-top mr-2"><img class="img-fluid" src="<?php //echo $this->getUrl('pub/media/');?>contact.svg" alt="Contact"></div>
						<div class="d-inline-block align-right"><div class="font-weight-bold ct-m">+ 91 91774 03000</div> <div class="need-help ct-m">Need help? Call us</div></div>
					</div>
	</div> -->
				
				