<?php
/**

 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 

// @codingStandardsIgnoreFile
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
/*     $product_name = $product->getName();
     $product_id =   $product->getSku();
     $product_price =   $product->getFinalPrice();*/
?>
<?php
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
$shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
$gst = (int)($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
$currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
$currencySymbol = $currency->getCurrencySymbol(); 
$offer_percentage = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
$short_description = $product->getResource()->getAttribute('short_description')->getFrontend()->getValue($product);
$offerPrice = ($finalPriceAmt - ($finalPriceAmt * $offer_percentage)/100);
?>
<?php
$priceWithoutTax = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
$makingCharges = $product->getResource()->getAttribute('making_charge')->getFrontend()->getValue($product);
$weight = $product->getResource()->getAttribute('net_weight')->getFrontend()->getValue($product);
//$priceFinal = round($priceWithoutTax - $finalmakingcharges);
// For discound code

$discount_making_charge_in = $product->getResource()->getAttribute('discount_making_charge_in')->getFrontend()->getValue($product);
$metal_discount_in= $product->getResource()->getAttribute('metal_discount_in')->getFrontend()->getValue($product);
$discount_diamond_in = $product->getResource()->getAttribute('discount_diamond_in')->getFrontend()->getValue($product);
$discount_wastage = $product->getResource()->getAttribute('discount_wastage')->getFrontend()->getValue($product);
// discount end
$gst = (int)($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$wastage = $product->getResource()->getAttribute('wastage')->getFrontend()->getValue($product);
$metal = $product->getResource()->getAttribute('metal')->getFrontend()->getValue($product);
$purity = $product->getResource()->getAttribute('purity')->getFrontend()->getValue($product);
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('pricemanager');
//$sql = "SELECT * FROM" . $tableName;
$sql = "Select * FROM pricemanager";
$results = $connection->fetchAll($sql);
foreach($results as $key=> $result){
  $k14 = $result['14K'];
  $k18 = $result['18K'];
  $k22 = $result['22K'];
  $k24 = $result['24K'];
}
   $vaweight = ($weight * $wastage)/100;
   $va = 0;
   $metalrate = 0;
   $metalprice = 0;
    if($metal =='Gold' && $purity =='24K'){
        $va = round($k24 * $vaweight);
        $metalprice =  round($k24 * $weight);
        $metalrate = $k24;
    }elseif($metal =='Gold' && $purity =='22K'){
        $va = round($k22 * $vaweight);
        $metalprice =  round($k22 * $weight);
        $metalrate = $k22;
    }
    elseif($metal =='Gold' && $purity =='18K'){
        $va = round($k18 * $vaweight);
        $metalprice =  round($k18 * $weight);
        $metalrate = $k18;
    }
    elseif($metal =='Gold' && $purity =='14K'){
        $va = round($k14 * $vaweight);
        $metalprice =  round($k14 * $weight);
        $metalrate = $k14;
    }
    $finalmakingcharges = round($makingCharges * $weight) + $va;
    /*$stonePrice = round($metalprice + $finalmakingcharges + $gst);
    $stonepriceFinal = round($priceWithoutTax + $gst - $stonePrice);*/
    $stonePrice = (int)($product->getResource()->getAttribute('stone_price')->getFrontend()->getValue($product));
    $priceBreakup = $product->getResource()->getAttribute('price_breakup')->getFrontend()->getValue($product);
    $sym = 'Rs';
    $discount_amount=0;
    $total_stone_discount=0;
    $total_metal_discount=0;
    $total_makeing_discount=0;
     $total_Wastage_discount=0;
    $wastageweight = $wastage*($weight/100);
    $wastageamnt = $wastageweight*$metalrate;

    if(isset($discount_making_charge_in)) { 

        $getMakingdiscount= round(($finalmakingcharges * $discount_making_charge_in ) / 100);
        $getMakingdiscount_gst = round(($getMakingdiscount*3)/100);
        $total_makeing_discount=$getMakingdiscount+$getMakingdiscount_gst;
    }
    if(isset($metal_discount_in)) { 

        $getMetaldiscount= round(($metalprice * $metal_discount_in ) / 100);
        $getMetaldiscount_gst = round(($getMetaldiscount*3)/100);
        $total_metal_discount=$getMetaldiscount+$getMetaldiscount_gst;
    }
    if(isset($discount_diamond_in)) { 

        $getStonediscount= round(($stonePrice * $discount_diamond_in ) / 100);
        $getStonediscount_gst = round(($getStonediscount*3)/100);
        $total_stone_discount=$getStonediscount+$getStonediscount_gst;
    }
     if(isset($discount_wastage)) { 

        $getWastagediscount= round(($wastageamnt * $discount_wastage ) / 100);
        $getWastagediscount_gst = round(($getWastagediscount*3)/100);
        $total_Wastage_discount=$getWastagediscount+$getWastagediscount_gst;
    }
    $discount_amount= $total_stone_discount + $total_metal_discount + $total_makeing_discount + $total_Wastage_discount;

?>

<style>
    /*.price_breakup_popup{
        margin-bottom: 10px !important;
        position: relative !important;
        display: none !important;
        margin-left: 25px!important;
        font-size: 11px;
        line-height: 16px;
        background: #fef5e6;
    }*/
    .prod-tab{
        background-color: #6e2083 !important;
    }
    .action-close{
        margin-top: 20px !important;
    }
    .modal-content{
        background: #fef5e6;
    }
    .modal-header{
        background: #fef5e6 !important;
    }
</style>
<?php if(true){?>
    <style>
     /*  .price_breakup_popup .showoffer {
         margin-left: 5px;
         color: #ee853c;
       } 
        .price_breakup_popup .strike {
        text-decoration: line-through;
       }*/
       .vbjoffer span:nth-child(n+3) {
        display: block;
        float: right;
       }
       #price_breakup_btn{
           color: #509ec4 !important;
       }
    </style>

<section class="vcontainer sarvesh">
    <!-- <div class="break"> -->
<div class="price_breakup a-centers hidden-xs">
<span  id="price_breakup_btn" class="emi-plans"></span> <!-- View Price break up -->
<div id="price_breakup_popup" class="price_breakup_popup">
    <table style="border: 1px solid black;">
    <tbody style="border: 1px solid black;">
        <tr style="border: 1px solid black;">
        <th style="border: 1px solid black;">Metal</th>
        <th style="border: 1px solid black;">Diamond/Stone</th>
        <th style="border: 1px solid black;">Making/VA</th>
        <th style="border: 1px solid black;">GST</th>
         <?php if($discount_making_charge_in || $metal_discount_in || $discount_diamond_in || $discount_wastage){?>
        <th class="pb-discount" style="border: 1px solid black;">Discount</th>
<?php } ?>
        </tr>
        <tr style="border: 1px solid black;">
        <td style="border: 1px solid black;"><span class="pb-metal"><?php echo ' '. $sym.' '.$metalprice; ?></span><span class="pb-metal-offer"></span></td>
        <td style="border: 1px solid black;"><span class="pb-diamond"><?php echo ' '. $sym.' '.$stonePrice; ?></span><span class="pb-diamond-offer"></span></td>
        <td style="border: 1px solid black;"><span class="pb-making"><?php echo ' '. $sym.' '.$finalmakingcharges; ?></span><span class="pb-making-offer"></span></td>
        <td style="border: 1px solid black;"><span class="pb-gst"><?php echo ' '. $sym.' '.$gst; ?></span><span class="pb-gst-offer"></span></td>
        <?php if($discount_making_charge_in || $metal_discount_in || $discount_diamond_in || $discount_wastage){?>
        <td  class="pb-discount" style="border: 1px solid black;color: #ee853c;">-<?php echo ' '. $sym.' '.$discount_amount; ?></td>
        <?php } ?>
        </tr>
    </tbody>
    </table>
</div>
</div>
<!-- </div> -->

</section>

<?php } ?>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Price Breakup',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#price_breakup_popup'));
        $("#price_breakup_btn").click(function() {
            console.log('Sarvesh VBJ30 Mobile!');
            $('#price_breakup_popup').modal('openModal');
        });
    });
</script>