<?php


/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php 
$_product = $block->getProduct();
$finalPrice = round($_product->getPrice());
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$attributeSet = $objectManager->create('Magento\Eav\Api\AttributeSetRepositoryInterface');
$attributeSetRepository = $attributeSet->get($product->getAttributeSetId());
$attribute_set_name = $attributeSetRepository->getAttributeSetName();
$gst = (int)($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$emiController = $product->getResource()->getAttribute('emi_controller')->getFrontend()->getValue($product) ?? '';
$offer_percentage = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
$totalPrice = $finalPrice + $gst;
$processingFee = round(($totalPrice * 6.5)/100);
/* Six month tenure */
$emiSixMonth = round(($totalPrice/6 * 4)/100) + round($totalPrice/6);
$emiSixMonthTotal = $emiSixMonth * 6;
/* Nine month tenure */
$emiNineMonth = round(($totalPrice/9 * 6)/100) + round($totalPrice/9);
$emiNineMonthTotal = $emiNineMonth * 9;
/* Tweleve month tenure */
$emiTweleveMonth = round(($totalPrice/12 * 12)/100) + round($totalPrice/12);
$emiTweleveMonthTotal = $emiTweleveMonth * 12;
/* Twenty Four month tenure */
$emiTwentyfourMonth = round(($totalPrice/24 * 16)/100) + round($totalPrice/24);
$emiTwentyfourMonthTotal = $emiTwentyfourMonth * 24;
?>

<div class="emi_container" id="emi_container_popup" style="display:none">
<div class="pd__emi__lg__head" style="border-bottom-style: groove;margin-bottom: 8px;">
<h2 style="text-align:center"><span class="emi__popup__icon"></span>BUY NOW PAY LATER</h2>
<hr>
</div>
<div class="emi-personal-loan active"><div class="content-height"><div class="pd__emi__lg__table"><p class="pd__emi__lg__titlenote">Easy installments on your jewellery purchase</p>
<table>  
    <tbody>
        <tr style="border: 1px solid black;"><th style="border: 1px solid black;">Tenure</th>
        <th style="border: 1px solid black;">Interest Rate</th>
        <th style="border: 1px solid black;">Processing Fee</th>
        <th style="border: 1px solid black;">EMI</th>
        <th style="border: 1px solid black;">EMI Total Amount</th></tr>
        <tr style="border: 1px solid black;">
        <td style="border: 1px solid black;">6 months</td>
        <td style="border: 1px solid black;">4 %</td>
        <td style="border: 1px solid black;"><?php echo $processingFee; ?></td>
        <td style="border: 1px solid black;"><?php echo $emiSixMonth;?></td>
        <td style="border: 1px solid black;"><?php echo $emiSixMonthTotal;?></td></tr>
        <tr style="border: 1px solid black;">
        <td style="border: 1px solid black;">9 months</td>
        <td style="border: 1px solid black;">6 %</td>
        <td style="border: 1px solid black;"><?php echo $processingFee; ?></td>
        <td style="border: 1px solid black;"><?php echo $emiNineMonth;?></td>
        <td style="border: 1px solid black;"><?php echo $emiNineMonthTotal;?></td></tr>
        <tr style="border: 1px solid black;">
        <td style="border: 1px solid black;">12 months</td>
        <td style="border: 1px solid black;">12 %</td>
        <td style="border: 1px solid black;"><?php echo $processingFee; ?></td>
        <td style="border: 1px solid black;"><?php echo $emiTweleveMonth;?></td>
        <td style="border: 1px solid black;"><?php echo $emiTweleveMonthTotal;?></td></tr>
        <tr style="border: 1px solid black;">
        <td style="border: 1px solid black;">24 months</td>
        <td style="border: 1px solid black;">16 %</td>
        <td style="border: 1px solid black;"><?php echo $processingFee; ?></td>
        <td style="border: 1px solid black;"><?php echo $emiTwentyfourMonth;?></td>
        <td style="border: 1px solid black;"><?php echo $emiTwentyfourMonthTotal;?></td></tr>
    </tbody>
</table>
        <p style="font-size:11px;color: #595959;font-weight: 300;margin-bottom: 10px;line-height: 16px;">*EMI also available with 6.5% down payment. Choose your preference at the time of purchase. Choose EMI option at the time of purchase on the payment page.<br>
        <strong class="emi__popup__error" style="color: #fa9373;">Note: </strong>Please be informed that Shipping/Delivery date may vary subject to approval of EMI.</p>
    </div>
    <div>
        <p style="text-align: center; padding-top: 10px;">
         <picture>
                    <source type="image/webp" data-srcset="/media/wysiwyg/EMI_button_slide.png" srcset="/media/wysiwyg/EMI_button_slide.png">
                    <img loading="lazy" src="/media/wysiwyg/EMI_button_slide.png" data-srcset="/media/wysiwyg/EMI_button_slide.png" srcset="/media/wysiwyg/EMI_button_slide.png" data-src="/media/wysiwyg/EMI_button_slide.png" width="332" height="85"  data-pagespeed-no-transform>
                    </picture>
        </p>
    </div>


<div class="pd__emi__lg__terms"><h3>Terms &amp; Conditions:</h3>
<ul>
<li> EMI transactions are applicable on the purchase of Gold Studded Jewellery, Platinum Jewellery, Silver Jewellery and Diamond Jewellery which are greater than Rs.10, 000.</li>
<li> EMI transactions are not allowed on Gold Bullion in any form, Gold Coins in any form and Plain Gold Jewellery.</li>
<li> This loan facility is being offered by "Jewel Fina" to customers. Vaibhav Jewellers  has no role to play in the approval, extension, pricing, modification, pre-closure, closure or any matter incidental there after pertaining to offering of the facility. It is the sole discretion of Jewelfina.</li>
<li> The customer shall be assessed by Jewelfina on eligibility and other parameters and approved loans shall be disbursed by Jewelfina to Vaibhav Jewellers. In case of returns, Vaibhav Jewellers shall not  refund amount to the Customer till the EMI is closed. Vaibhav Jewllers provides the facility to exchange the goods with in 15 days of Purchase.</li>
<li> Customer cannot club the EMI offered by Jewelfina with purchase plans or any other showroom offers.</li>
<li> The loan facility offered by Jewelfina to the customers is governed by the respective terms and conditions of Jewelfina only and  the customer is advised to approach Jewelfina  in case of any complaints, disputes or enquiry about an EMI transaction.</li>
<li> Vaibhav Jewellers does not charge the customer any processing or convenience fee for the purpose of facilitating the loan facility for its customers. Jewelfina may levy a processing fee of 6.5% -7%   based on the EMI scheme selected by you.</li>
<li> <b>Invoice should always be made in the name of person as given on the credit card that was used to complete the transaction. A proof of delivery should be maintained for every transaction. A proof of delivering the product to the customer should be maintained for future references. Invoice and proof of delivery should be in the name of person as mentioned on the credit card and not in the name of person who is picking the product. </b> </li>
<li> Charge Back: In case if the customer asks his bank to stop payment after the transaction is approved, jewellery has to be returned to the jeweller. Return and refund of jewellery is as per Vaibhav Jewellers policy. Jewelfina is not liable of return or refund after approval.</li>
<li> Transactions once approved cannot be cancelled from our end, please contact your bank for the same.</li>
<li> All disputes in connection with the loan shall be between the Customer and Jewelfina. Vaibhav Jewellers shall not be held liable for any dispute arising out of or in connection with such loan facility being offered by Jewelfina.</li>
</ul>
</div>
</div>
</div>
</div>
<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'EMI Calculator',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#emi_container_popup'));
        $("#emi_opt_btn").click(function() {
            $('#emi_container_popup').modal('openModal');
        });
    });
</script>