<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');

$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
$shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
$finalPriceAmt = round($product->getPriceInfo()->getPrice('final_price')->getValue());
$gst = round($product->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($product));
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
$currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
$currencySymbol = $currency->getCurrencySymbol(); 
$offer_percentage = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
$short_description = $product->getResource()->getAttribute('short_description')->getFrontend()->getValue($product);
$offerPrice = ($finalPriceAmt - ($finalPriceAmt * $offer_percentage)/100);

$priceWithoutTax = $product->getPriceInfo()->getPrice('final_price')->getAmount()->getBaseAmount();
$makingCharges = $product->getResource()->getAttribute('making_charge')->getFrontend()->getValue($product);

echo $offer_percentage;

if($stockQuantity ==1 && isset($offer_percentage)){?>
<div id="smartbuy_prd" class="delay_deilvery" style="display: block;">
    <div class="smart_overlay"></div>
    <div id="delay_deilvery_opt">
    <!--<input type="hidden"  id="check_delayh" name="check_delayh" value="yes"/>-->
    <div id="smrtbuy_oncl">
    <input type="checkbox" value="offer" id="smartbuy_product" name="smartbuy_product">
    <input type="hidden" id="vaoffer" name="vaoofer" value="<?php echo $product->getId(); ?>">
    <input type="hidden" id="deliverytime" name="deliverytime" value="<?php echo $shippingCode ; ?>">
    <input type="hidden" id="vaprice" name="vaprice" value="">
    <label class="fanc_smrtch"></label>
    <label for="smartbuy_product" id="smartbuy_product_label" class="icon-smart-buy-01 smart_buy_label">
    <u class="smartby">Smart Buy</u>
    </label>
    <span id="OtpBaseUrl" class="OtpBaseUrl" style="display: none"><?php echo "https://www.vaibhavjewellers.com/staging/";//$block->getUploadFormUrl(); ?></span>
    <span class="smartmssg" style="font-size: 11px; margin-left: 1px;color:#6d1f81"></span>
    </div>
    </div>
    </div>
<?}?>
<script>
require([
    'jquery',
    'mage/mage'
], function($){
$(document).ready(function(){
        $('input[name="smartbuy_product"]').click(function(){
            var val = $("#smartbuy_product").val();
            if(val == 'offer'){
                $('.smartmssg').css("display", "block");
            if($(this).prop("checked") == true){
                $("#smartbuy_product").attr('value', 'nonoffer');
                $("#buy-now-offer").attr("disabled", false);
                $.cookie('cookie_name', 'nonoffer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                var date = new Date();
                date.setDate(date.getDate() + 30);
                const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
                var dd = date.getDate();
                var mm = monthNames[date.getMonth()];//date.getMonth() + 1;
                var y = date.getFullYear();
                var someFormattedDate = dd + ' ' + mm + ' , ' +  y;
                var conf = "<?php echo $conf; ?>";
                var res = conf.replace('one week', someFormattedDate);
                $('.showmessage').text(res);
                $('.pd_container_rgt_emi').css("display", "none");
                var currencyCode = "<?php echo $currencyCode; ?>";
                var currencySymbol = "<?php echo $currencySymbol; ?>";
                if(currencyCode=='INR' && currencySymbol=='₹'){
                var price = "<?php echo $finalPriceAmt +$gst; ?>";
                var apprx = "<?php echo $offer_percentage; ?>";
                if(apprx != null && apprx != ''){
                var realApprx = Math.ceil(parseFloat((price * apprx)/100));
                var realPrice = Math.ceil(parseFloat(price - realApprx));
                var num = realPrice.toLocaleString();
                }
                 $('.price').html('₹'+num);
                 $('.smartby').append($('.smartmssg').text('You have saved' + ' '+ '₹' + ' '+ realApprx + ' '+ 'for this products'));
               }else if(currencyCode=='USD' && currencySymbol=='$'){
                var price = "<?php echo $finalPriceAmt +($gst*0.014); ?>";
                var apprx = "<?php echo $offer_percentage; ?>";
                if(apprx != null && apprx != ''){
                var realApprx = Math.ceil(parseFloat((price * apprx)/100));
                var realPrice = Math.ceil(parseFloat(price - realApprx));  //Math.ceil()
                //alert('real price'+realPrice);
                var num = realPrice.toLocaleString();
                }
                 $('.price').html('$'+num);
                 $('.smartby').append($('.smartmssg').text('You have saved' + ' '+ '$' + ' '+ realApprx + ' '+ 'for this products'));
                  
               }
            }
            }
            else {
            if(val =='nonoffer'){
                 $('.smartmssg').css("display", "none");
                 //$('.showmessage').text("");
            if($(this).prop("checked") == false){
                $("#smartbuy_product").attr('value', 'offer');
                $("#buy-now-offer").attr("disabled", true);
                $.cookie('cookie_name', 'offer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                $('.pd_container_rgt_emi').css("display", "block");
                $.cookie('cookie_name', 'offer');//,{expires: datecookies}
                var temp = $.cookie('cookie_name');
                $.cookie("cookie_name", 'null');
                var d =  new Date();
                var deliveryDate = "<?php echo $shippingCode; ?>";
                const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
                //const d = new Date();
                //console.log(monthNames[d.getMonth()]);
                d.setDate(d.getDate() + parseInt(deliveryDate, 10));
                var ddd = d.getDate();
                var mmm = monthNames[d.getMonth()];   //d.getMonth()+1;
                var yyy = d.getFullYear();
                var someFormattedDates = ddd + " " + mmm + " , " +  yyy;
                var conf = "<?php echo $conf; ?>";
                var ress = conf.replace('one week', someFormattedDates);
                $('.showmessage').text(ress);
                var currencyCode = "<?php echo $currencyCode; ?>";
                var currencySymbol = "<?php echo $currencySymbol; ?>";
                if(currencyCode=='INR' && currencySymbol=='₹'){
                var price = "<?php echo $finalPriceAmt +$gst; ?>";
                var priceone = Math.ceil(parseFloat(price));
                var num = priceone.toLocaleString();
               $('.price').html('₹'+num);
               $('.smartmssg').css("display", "none");
              // $('.vcontainer').css("margin-top", "-45px");
                }else if(currencyCode=='USD' && currencySymbol=='$'){
                var price = "<?php echo $finalPriceAmt +($gst*0.014); ?>";
                var priceone = Math.ceil(parseFloat(price));
                //alert('real price'+price);
                var num = priceone.toLocaleString();
               $('.price').html('$'+num);
              
                }
            }
            }
            }
        });
    });
});
//});
</script>