<?php 

 $objectManager = \Magento\Framework\App\ObjectManager::getInstance();

 $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');

$productId = $product->getId();

$productge = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);

$productType = $productge->getTypeID();


if($productType != 'simple')

{   


$product = $block->getProduct();

$imageHelper = $this->helper('Magento\Catalog\Helper\Image');


if (!$product->getImage() || $product->getImage() == 'no_selection') {

    $image = $imageHelper->getDefaultPlaceholderUrl('image');

} else {

    $image = $imageHelper->init($product, 'product_page_image_medium')

            ->constrainOnly(true)->keepAspectRatio(true)->keepFrame(false)

            ->setImageFile($product->getImage())

            ->getUrl();

}

?>

<div id="product_slider" class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">

    <div data-role="loader" class="loading-mask" style="display: none;">

        <div class="loader">

            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"

                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">

        </div>

    </div>

</div>

<style type="text/css">

    .gallery-placeholder

    {

        width: 100%;

    }

</style>

<!--Fix for jumping content. Loader must be the same size as gallery.-->

<script type="text/javascript">

    var config = {

            "width": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>,

            "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')

                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,

            "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",

            "height": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'height') ?>

        },

        thumbBarHeight = 0,

        loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];



    if (config.navtype === 'horizontal') {

        thumbBarHeight = config.thumbheight;

    }



    loader.style.paddingBottom = ( config.height / config.width * 100) + "%";

</script>

<script type="text/x-magento-init">

    {

        "[data-gallery-role=gallery-placeholder]": {

            "mage/gallery/gallery": {

                "mixins":["magnifier/magnify"],

                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,

                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,

                "options": {

                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/nav") ?>",

                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/loop") ? 'true' : 'false' ?>,

                    "keyboard": <?= /* @escapeNotVerified */ $block->getVar("gallery/keyboard") ? 'true' : 'false' ?>,

                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/arrows") ? 'true' : 'false' ?>,

                    "allowfullscreen": <?= /* @escapeNotVerified */ $block->getVar("gallery/allowfullscreen") ? 'true' : 'false' ?>,

                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/caption") ? 'true' : 'false' ?>,

                    "width": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>",

                    "thumbwidth": "<?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_small', 'width') ?>",

                    <?php if ($block->getImageAttribute('product_page_image_small', 'height') || $block->getImageAttribute('product_page_image_small', 'width')): ?>

                        "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')

                        ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,

                    <?php endif; ?>

                    <?php if ($block->getImageAttribute('product_page_image_medium', 'height') || $block->getImageAttribute('product_page_image_medium', 'width')): ?>

                        "height": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_medium', 'height')

                        ?: $block->getImageAttribute('product_page_image_medium', 'width'); ?>,

                    <?php endif; ?>

                    <?php if ($block->getVar("gallery/transition/duration")): ?>

                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/transition/duration") ?>,

                    <?php endif; ?>

                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/transition/effect") ?>",

                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/navarrows") ? 'true' : 'false' ?>,

                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",

                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navdir") ?>"

                },

                "fullscreen": {

                    "nav": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/nav") ?>",

                    "loop": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/loop") ? 'true' : 'false' ?>,

                    "navdir": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navdir") ?>",

                    "navarrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navarrows") ? 'true' : 'false' ?>,

                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/navtype") ?>",

                    "arrows": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/arrows") ? 'true' : 'false' ?>,

                    "showCaption": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/caption") ? 'true' : 'false' ?>,

                    <?php if ($block->getVar("gallery/fullscreen/transition/duration")): ?>

                        "transitionduration": <?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/duration") ?>,

                    <?php endif; ?>

                    "transition": "<?= /* @escapeNotVerified */ $block->getVar("gallery/fullscreen/transition/effect") ?>"

                },

                "breakpoints": <?= /* @escapeNotVerified */ $block->getBreakpoints() ?>

            }

        }

    }

</script>

<?php  

} 

else{?>

<link rel="stylesheet" type="text/css" href="<?= $this->getViewFileUrl('Magento_Theme::css/xzoom.css')?>" media="all" />

<style>

.xzoom-container{

width: 670px;

margin: 0px auto;

text-align:center;

border:1px solid lightgrey;

}

.xzoom{

box-shadow: none;

width:500px !important;



}

.xzoom-thumbs{

   text-align:left; 

   margin-top:10px;

}

</style>

<div class="getzoom">

  <div class="xzoom-container">

    <?php

$helperImport = $objectManager->get('\Magento\Catalog\Helper\Image');



$imageUrl = $helperImport->init($product, 'swatch_image')

                ->setImageFile($product->getSwatchImage()) // image,small_image,thumbnail

                ->resize(700, 700)

                ->keepFrame(true)

                ->getUrl();

    //$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId()); 

   $images = $product->getMediaGalleryImages();

    

   // $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getProduct()->getId());

 //echo $product->getThumbnail();

//echo  $product->getProductUrl(); 

   //echo $images;

 ?>



        <img loading="lazy" class="xzoom" width="500" height="600" src="<?php echo $imageUrl; ?>" alt="<?php echo $productge->getName(); ?>" xoriginal="<?php echo $imageUrl; ?>" />



</div>

<div class="xzoom-thumbs">

        <?php 

        $j=1;

        foreach($images as $child){ ?>

        

  <a href="<?php echo $child->getUrl(); ?>">

    <img loading="lazy" class="xzoom-gallery" width="80" alt="<?php echo $productge->getName().'_'.$j; ?>" src="<?php echo $child->getUrl(); ?>">

  </a>

 



<?php 

      $j++;      

        }



?>



</div>

</div>





<?php } ?>