<?php 
$product = $block->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$categories = $product->getCategoryIds(); /*will return category ids array*/
foreach($categories as $category){
    $cat = $objectManager->create('Magento\Catalog\Model\Category')->load($category);
    $categoryName[] = $cat->getName();
    }
$cateName = reset($categoryName);
$groupCollection = $block->getAttributeLabels();
 $_helper = $this->helper('Retailinsights\ConfigProducts\Helper\Data');
$html = '';
$arraySection = array("Basic Information", "Diamond Information", "Metal Information", "Certificaion Details", "Product Dimension", "Other Information", "Product Findings");
$count=0;
?>

	<?php
	foreach ($groupCollection as $group) {
		$attributes = $product->getAttributes($group->getId(), true);
		$count++;
		if(in_array($group->getData('attribute_group_name'),$arraySection)){
			$new_html = "";
			    $attr = str_replace(' ', '_', $group->getData('attribute_group_name'));
			    $show="";
					if($attr=="Basic_Information" || $attr=="Certificaion_Details" || $attr=="Metal_Information") {
						$show="show";
					} else {
						$show="";
					}
				$new_html .= '<div id="'.$attr.'" class="collapse '.$show.'">';
				$attributeSection = array("item_package_quantity", "occassion", "brand");
				foreach ($attributes as $key => $attribute) {
				
					if($attribute->getIsVisibleOnFront() && $attribute->getFrontend()->getValue($product) !="" && $attribute->getFrontend()->getValue($product) !="Non" && $attribute->getFrontend()->getValue($product) !="No" && $attribute->getFrontend()->getValue($product) !="0"){
						$classText = $_helper->getStrReplaceWithHyphen(trim(substr($attribute->getFrontend()->getLabel(), 0, strpos($attribute->getFrontend()->getLabel(), "("))));
					
						if(!$classText)
							$classText = $_helper->getStrReplaceWithHyphen($attribute->getFrontend()->getLabel());
						$new_html .= '<div class="clearfix detail-list '.$cateName.'_'.$attribute->getFrontend()->getLabel().'">' . $attribute->getFrontend()->getLabel(). '
									  <span class="float-right vbj_'.$classText.'_'.$cateName.'">' . $attribute->getFrontend()->getValue($product) . '</span></div>';
					
				}

				}
				$new_html .= '</div>';
				if($new_html!=''){
					$html .= '<div>' ;
					$attr_code=str_replace(' ', '_', $group->getData('attribute_group_name'));
					$collapsed="";
					if($attr_code=="Basic_Information" || $attr_code=="Certificaion_Details" || $attr_code=="Metal_Information") {
						$collapsed="";
					} else {
						$collapsed="collapsed";
					}
					$html .= '<a href="javascript:void(0);" class="detail-collapse mt-1 '.$collapsed.'" data-toggle="collapse" data-target="#'.$attr_code.'">' . $group->getData('attribute_group_name').'</a>';
					$html .= $new_html;
					$html .= '</div>' ;
				}
		} 
		
	}
	echo $html;
	?>
<style>
	.price{
		color: black !important;
	}
	.Silver_Purity{
		display: none;
	}
</style>