<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @var $block \Magento\Checkout\Block\Cart
 */

if ($block->getItemsCount()) {
	?>
    <div class="cart_count page-title-wrapper category-heading">
    	<h3 class="page-title"><?= $block->getItemsCount() ?> <?= $result = ($block->getItemsCount() > 1) ? "ITEMS" : "ITEM"; ?> IN CART</h3></div>
	<?php
    echo $block->getChildHtml('with-items');
} else {
    echo $block->getChildHtml('no-items');
}
