<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<style>
    .category-heading {
    padding: 0;
}
main#maincontent {
    margin-top: 75px;
    padding: 0 10px;
    margin-bottom: 10px;
}
   input.action.primary {
    margin-bottom: 15px;
}
    </style>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?= __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?= __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?= /* @escapeNotVerified */ __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
                                    <?php
$lid = $this->getOrderId();
echo  "Order ID:".$lid."<br/>";

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$order = $objectManager->create('Magento\Sales\Model\Order')->loadByIncrementId($lid);


$grand_total = $order->getGrandTotal();
echo  "Grand Total:".$grand_total."<br/>";
$sub_total = $order->getSubTotal();
$addrs=array();
$shippingAddress = $order->getShippingAddress();
$addrs['firstname'] = $shippingAddress->getFirstName();
$addrs['street'] = implode(', ',$shippingAddress->getStreet());
$addrs['city'] = $shippingAddress->getCity();
$addrs['state'] = $shippingAddress->getRegion();
$addrs['country'] = $shippingAddress->getCountryId();
$addrs['postcode'] = $shippingAddress->getPostcode();
$addrs['telephone'] = $shippingAddress->getTelephone();
$shipping_method = $shippingAddress->getShippingMethod();

$items = $order->getAllVisibleItems();
$itemarr=array();
$item=0;
$total_qty = 0;
$order_id = $order->getId();
$payment = $order->getPayment();
$method = $payment->getMethodInstance();
$payment_method = $method->getCode(); //
foreach($items as $i):
   $product = $objectManager->create('Magento\Catalog\Model\Product')->load($i->getProductId());
$total_qty = $total_qty + $i->getQtyOrdered();
$itemarr['sku'] = $product->getSku();
$itemarr['name'] = $product->getName();
$itemarr['price'] = $product->getPrice();
$item++;
endforeach;
?>
<script type="text/javascript">
  var itemarr = [<?php echo json_encode($itemarr); ?>];
    var addr = [<?php echo json_encode($addrs); ?>]
   if(typeof window.dataLayer !== 'undefined') {
     dataLayer.push({'event':'order_success',
        'order_id':'<?php echo $order_id;  ?>',
        'product_details':itemarr,
        'items_count':'<?php echo $item;  ?>',
        'items_qty':'<?php echo $total_qty;  ?>',
        'subtotal':<?php echo $sub_total;  ?>,
        'grandtotal':<?php echo $grand_total;  ?>,
        'payment_method':'<?php echo $payment_method;  ?>',
        'shipping_method':'<?php echo $shipping_method;  ?>',
        'shipping_address':addr
    });

   }
   
</script>
    <?php endif;?>

    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>
