<form action="<?php echo $this->getUrl('giftcard/giftuser/savebulkitem')?>" method="post" enctype="multipart/form-data">
    Select csv file to upload(Only csv file):
    <input type="file" name="fileToUpload" id="fileToUpload">
    <input type="submit" value="Upload CSV" name="submit">
    <input name="form_key" type="hidden" value="<?php echo $block->getFormKey() ?>" />
    <a target="_blank" href="<?php echo $block->getDownloadUrl();?>">Click here to download demo csv sheet</a>
</form>