<style type="text/css">
	body {
	font-size: 15px;
}
	.block-collapsible-nav .content {
    background: #fff;
    padding: 15px 0 0;
}


.block-collapsible-nav{
        top: 70px;
}
.page-title-wrapper.category-heading {
    /*margin-top: 5px;*/
}
.block-collapsible-nav .item {
   margin: 10px 0 0;
    padding-top: 10px;
    border-top: 1px dashed #999;
}
.block-collapsible-nav .item a:hover {
    color: #121212;
    text-decoration: none;
}
.block-collapsible-nav .item a:visited {
    color: #999;
    text-decoration: none;
}
.block-collapsible-nav .item a {
    color: #999;
    text-decoration: none;
    padding:0;
    font-size: 15px;
}
.block-collapsible-nav .item:first-child {
	    margin-top: 0;
    border-top: 0;
    padding-top: 0;
}
.block-collapsible-nav .item a:hover {
    background: none;
    color: #121212;
    text-decoration: none;
}

.block-collapsible-nav .item.current a, .block-collapsible-nav .item.current>strong {
    border-color: #999;
    color: #121212;
    font-weight: 600;
}

.account .items .item:nth-child(3) {
	display: none;
}
.account .items .item:nth-child(5) {
	display: none;
}
.account .items .item:nth-child(8) {
    display: none;
}
.account .items .item:nth-child(9) {
    display: none;
}
.account .items .item:nth-child(10) {
    display: none;
}
.account .items .item:nth-child(12) {
    display: none;
}
.block-collapsible-nav-content .nav {
display: block;
}
.block-collapsible-nav .item.current a {
    border: none;
}

.block-title strong , .box-title span  {
	font-size: 16px !important;
}
.box-content address {
	font-size: 15px;
}

.account .column.main>.table-wrapper, .account .column.main>.form-address-edit, .account .column.main>.form, .account .column.main .block {
	background-color: #fff;
    padding: 20px;
    box-shadow: 0px 0px 1px #8c8686;
    -moz-box-shadow: 0px 0px 1px #8c8686;
    -webkit-box-shadow: 0px 0px 1px #8c8686;
    -o-box-shadow: 0px 0px 1px #8c8686;
    -ms-box-shadow: 0px 0px 1px #8c8686;
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 0;
    margin-bottom: 20px;
}
legend.legend span {
    font-size: 16px !important;
}
.table-wrapper .table:not(.totals):not(.cart):not(.table-comparison) tbody > tr > td:last-child {
    border-bottom: none;
    
}

.category-heading {
padding: 0.5em;    
}
.block-compare{
    display:none;
}
.block-reorder{
    display:none;
}
.block-wishlist{
     display:none;
}
.products-grid .product-item {
    display:flex;
    }
  .wishlist-index-index .product-item-info {
    width: 100%;
}
.products-grid.wishlist .product-item {
right: 10px;
}
.products-grid.wishlist .product-item-actions .action {
    margin-right: 6px;
}
.block.block-reorder {
    display: none;
}
   .view-more-review {
    background: #b272d3 !important;
    color: #fff !important;
    font-size: 12px;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1) !important;
    border-radius: 2px !important;
    padding: 7px 14px !important;
}
.wishlist-index-index a.btn-remove.action.delete {
    color: #000;
}
.products-grid.wishlist .product-item-name {
    font-size: 1.4rem;
    padding-top:10px;
}
.customer-address-index .box-billing-address .box-content p {
    font-size: 1.3rem;
}
.customer-account-createpassword #maincontent{
    max-width: 100% !important;
   
        padding: 20px 20px;
}
.customer-account-createpassword  button.action.submit.primary{
    background-color: #6e2083;
    border: 1px solid #6e2083;
    letter-spacing: 1px;
    font-size: 1.7rem;
    margin-left: 0px;

}
.customer-account-createpassword .page-title-wrapper {
    text-align: center;
    background-image: linear-gradient(to right top, #ecd0f4, #ead8f5, #e9e0f4, #eae7f1, #eeeeee);
    padding-top: 20px;
    height: 70px;
   
}
/**RMC****/
.amasty_rma-account-history .amreturn-btn,.amasty_rma-account-newreturn .amreturn-btn {
    margin-left: 10px !important; 
    padding: 7px 21px !important;
    border: 1px solid #6e2083 !important;
    color: #fff !important;
    background: #6e2083 !important;
    transition: background-color 0.4s !important;
} 

.amasty_rma-account-newreturn .amrma-link-cancel {
    background-color: lightcoral;
    padding: 7px;
    color: #fff;
    /* padding: 10px; */
    border-radius: 5px;
}
.amasty_rma-account-newreturn h1.page-title{
    padding-bottom:15px;
}

.amasty_rma-account-view button.amrma-send{
    background: #6e2083;
}
.amasty_rma-account-view button:hover {
    background: #e1e1e1 !important;
    border: 1px solid #cccccc !important;
    color: #333333 !important;
}
.amasty_rma-account-history span.amrma-status.-pending {
    padding: 5px;
    }
 .amasty_rma-account-history .amreturns-order-select {
    border: 2px solid #6e2083;
    }
    .amasty_rma-account-view .amrma-header{
    font-size: 1.5rem;
}
.amasty_rma-account-view .columns{
    padding:0 15px;
}
.amasty_rma-account-view .page.messages{
   margin-top: 47px; 
}
.amasty_rma-account-history .amrma-table-container .table-wrapper > .amrma-table .amrma-tbody > .amrma-row > .col:not(:first-child) {
   
    text-align: left;
}
.amasty_rma-account-history tr.amrma-row {
    border: 1px solid #6e2083;
        margin-bottom: 10px;
}
.amasty_rma-account-newreturn .columns{
    padding:0 15px;
}
.amasty_rma-account-newreturn .page.messages{
   margin-top: 47px; 
}
.amasty_rma-account-view .amrma-table-container .table-wrapper > .amrma-table .amrma-tbody > .amrma-row > .col:not(:first-child){
  text-align: left;  
}
.amasty_rma-account-view .amreturn-btn{
    background: #6e2083;
    color: #fff !important;
}
.amasty_rma-account-view .message-warning.warning.message {
    display: none;
    
}
.amasty_rma-account-newreturn .message-warning.warning.message {
    display: none;
    
}
</style>