<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
$baseUrl = $block->getBaseUrl();
$imgUrl = $baseUrl.'pub/media/logo/sign-out-icon.png';
?>
<div class="logout_screen_info">
    <img src="<?php echo $imgUrl ?>" class="img-fluid" alt="Responsive image">
    <p><?= $block->escapeHtml(__('You have signed out and will go to our homepage in 5 seconds.')) ?></p>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/logout-redirect": {
                "url": "<?= $block->escapeJs($block->escapeUrl($block->getUrl())) ?>"
            }
        }
    }
</script>
<style type="text/css">

    .logout_screen_info img{
       padding: 30px 150px 0px 150px;
    }
    .logout_screen_info p{
       font-size: 14px;
       text-align: center;
       padding: 40px 40px 20px 40px;
    }
    
</style>