<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="block block-new-customer">
    <div class="block-title">
        <strong id="block-new-customer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></strong>
    </div>
    <div class="block-content anotherAcc" aria-labelledby="block-new-customer-heading">
        <p class="dt-h-ac"><?= $block->escapeHtml(__('Do not have account?')) ?></p>
        <!-- <div class="actions-toolbar">
            <div class="primary"> -->
                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create"><span><?= $block->escapeHtml(__('Register')) ?></span></a> <!-- primary -->
            <!-- </div>
        </div> -->
    </div>
</div>
<?php endif; ?>
