<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?> 
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
/**
 * @var $block \DavidRobert\GetRatingSummary\Block\GetRatingSummary
 */
?>

<?php
   /* $_ratingSummary = $block->getAllRatingsSummary();
    print_r($_ratingSummary->getData());*/
?>

<?php
$_productCollection = $block->getLoadedProductCollection();
$mainListingCollection = $_productCollection->getData();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?> 
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>


    <div class="wrapper">
        <div class="bread-crumbs">
             <?= $this->getChildHtml('breadcrumbs');?>
        </div>
        <div class="category-page-header" id="category.page.header">
             <?= $this->getChildHtml('page.main.title');?>
            <?= $block->getAdditionalHtml() ?>
            </div>
        <div class="vaibhav_product_list">
        <div class="flex">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php $adbanners=array("products-banner.png","products-banner1.png"); ?>
            <?php $count=1; $adbannercount=1; ?>
            <?php   $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
           <?php foreach ($mainListingCollection as $_product):?>
           
          <?php $productcoll = $objectManager->create('Magento\Catalog\Model\Product')->load($_product['entity_id']); ?>
           
            <div class="products">

                

                     <?php 
                //$noofdays = $_product->getData('no_of_days'); //$_product->getResource()->getAttribute('no_of_days')->getFrontend()->getValue($_product);  
               $smart_percentage = $productcoll->getResource()->getAttribute('smart_percentage')->getFrontend()->getValue($productcoll);
                $metal_discount_in = $productcoll->getResource()->getAttribute('metal_discount_in')->getFrontend()->getValue($productcoll);
                $discount_diamond_in = $productcoll->getResource()->getAttribute('discount_diamond_in')->getFrontend()->getValue($productcoll); //$productcoll->getData('discount_diamond_in');
                $discount_making_charge_in = $productcoll->getResource()->getAttribute('discount_making_charge_in')->getFrontend()->getValue($productcoll);//$productcoll->getData('discount_making_charge_in');
                $noofdays = $productcoll->getResource()->getAttribute('no_of_days')->getFrontend()->getValue($productcoll);// $productcoll->getData('no_of_days');       
               $gst = round($productcoll->getResource()->getAttribute('tax_amount')->getFrontend()->getValue($productcoll));
               
               
               // $discount_making_charge_in = $productcoll->getResource()->getAttribute('making_charge')->getFrontend()->getValue($productcoll); //$productcoll->getData('making_charge');
                
                $offer_label =  $productcoll->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($productcoll);
                   switch (true) {
                    case (isset($smart_percentage) && isset($offer_label) && isset($noofdays)):  ?>
                    <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                  <span class="bs-text"><?php echo __('NEW'); ?></span>
                   <span class="bs-text"><?php echo __('OFFER'); ?></span>
                    </div>
                    <?php break;
                   case (isset($smart_percentage) && isset($offer_label)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                <span class="bs-text"><?php echo __('SmartBuy'); ?></span>
                  <span class="bs-text"><?php echo __('OFFER'); ?></span>
              </div>
                    <?php break;
                   case (isset($smart_percentage) && isset($noofdays)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                  <span class="bs-text"><?php echo __('SmartBuy'); ?></span>
                   <span class="bs-text"><?php echo __('NEW'); ?></span>
              </div>
                    <?php break;
                     case (isset($offer_label) && isset($noofdays)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                  <span class="bs-text"><?php echo __('OFFER'); ?></span>
                   <span class="bs-text"><?php echo __('NEW'); ?></span>
              </div>
                    <?php break;
                     case (isset($offer_label)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                  <span class="bs-text"><?php echo __('OFFER'); ?></span>
              </div>
                    <?php break;
                    case (isset($noofdays)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                    <span class="bs-text"><?php echo __('NEW'); ?></span>
               </div>
                    <?php break;
                      case (isset($smart_percentage)): ?>
                     <div class="sticker"><img class="bs-image" src="<?php echo $this->getUrl('pub/media/');?>bt-star.svg" alt="best-seller-image">
                  <span class="bs-text"><?php echo __('SmartBuy'); ?></span>
              </div>
                    <?php break;
                }
                    ?>
                
                <a href="<?php echo $this->getUrl('wishlist'); ?>" data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($productcoll) ?>' class="action towishlist" data-action="add-to-wishlist"><img class="favourites" src="<?php echo $this->getUrl('pub/media/');?>fav.svg" alt="favourite-icon"></a>
                 <?php
                    $productImage = $block->getImage($productcoll, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
               <?php  $imageUrl = $productcoll->getMediaConfig()->getMediaUrl($productcoll->getImage()); ?>
                <a href="<?= /* @escapeNotVerified */ $productcoll->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                 <?= $productImage->toHtml() ?>
             </a>
                <div class="text-left">
                     <div class="rating">
                            <?= $block->getReviewsSummaryHtml($productcoll, $templateType) ?>
                        </div>
                    <a href="<?= /* @escapeNotVerified */ $productcoll->getProductUrl() ?>">
                    <div class="product-name"><?= /* @escapeNotVerified */ $_helper->productAttribute($productcoll, $productcoll->getName(), 'name') ?></div></a>
                    <div class="price-rating clearfix">
                        <div class="price <?php if($discount_making_charge_in || $metal_discount_in || $discount_diamond_in ){ echo 'dis_make_charge_old'; } ?>"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></div>
                    </div>
                         <?php if($discount_making_charge_in || $metal_discount_in || $discount_diamond_in){

    // $discount_making_charge_in = $_product->getData('discount_making_charge_in');
    // $metal_discount_in= $_product->getData('metal_discount_in');
    // $discount_diamond_in = $_product->getData('discount_diamond_in');

    ?>
    <?php 
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product['entity_id']);
                    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
                    $stockQuantity = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
                    $conf = $objectManager->create('MageArray\CheckDelivery\Helper\Data')->getStoreConfig('checkDelivery/config/success_message');
                    $shippingCode = $product->getResource()->getAttribute('expected_delivery_date')->getFrontend()->getValue($product);
                    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface'); 
                    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
                    $currency = $objectManager->create('\Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
                    $currencySymbol = $currency->getCurrencySymbol(); 
    $inr='₹';
    $usd='$';
    $price_with_tax= round($productcoll->getSpecialPrice()+$gst);
    $inr_price= number_format($price_with_tax); ?>
    <?php $usd_price= number_format(round($price_with_tax * 0.014)); ?>
<?php if($currencyCode =='INR' && $currencySymbol =='₹'){?>

  <?php if(isset($discount_making_charge_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($discount_making_charge_in != 0){?><span class="fh">(<?php echo $discount_making_charge_in; ?>% Making off) </span><?php } ?></span></div>
<?php }  elseif(isset($metal_discount_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($metal_discount_in != 0){?>(<?php echo $metal_discount_in;?>% savings on metal charges) <?php } ?></span></div>
<?php } elseif(isset($discount_diamond_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($discount_diamond_in != 0){?>(<?php echo $discount_diamond_in;?>% savings on diamond charges) <?php } ?></span></div>
<?php } ?>

    <?php
  } else { ?>
      <?php if(isset($discount_making_charge_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($discount_making_charge_in != 0){?>(<?php echo $discount_making_charge_in;?>% Making off) <?php } ?></span></div>
     <?php }  elseif(isset($metal_discount_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($metal_discount_in != 0){?>(<?php echo $metal_discount_in;?>% savings on metal charges) <?php } ?></span></div>
<?php } elseif(isset($discount_diamond_in)) { ?>
     <div class="offer-price">Offer: <span class="text-orange"><span class="fw-bold dis_make_charge_actual"><?= /* @escapeNotVerified */ $block->getProductPrice($productcoll) ?></span> <?php if($discount_diamond_in != 0){?>(<?php echo $discount_diamond_in;?>% savings on diamond charges) <?php } ?></span></div>
<?php } ?>

<?php  }
}?>
                </div>
            </div>
             <?php if($count%10==0): ?>
            <?php if(is_array($adbanners) && count($adbanners) >= $adbannercount): ?>
            <img class="product-banner d-md-block d-none" src="<?php echo $this->getUrl('pub/media/').$adbanners[$adbannercount-1];?>" alt="product-banner">
            <?php $adbannercount++; ?>
            <?php endif; ?>     
        <?php endif; ?>
            <?php $count++; ?>
            <?php endforeach; ?>
        </div>
    </div>
    </div>
     <div class="category-page-footer ft" id="category.page.footer">
    <?= $block->getToolbarHtml() ?>
</div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $productcoll->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
