<?php 
$product = $this->getCurrentProduct() ?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
	//$StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
	  $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
	 $producttype = $product->getTypeId();
	 //$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current product
    $_product = $block->getProduct(); // quantity_and_stock_status
	//$producttype = $product->getTypeId();
     if ($currentProduct = $block->getCurrentProduct()) {
    $product_name = $currentProduct->getName();
     $product_id =   $currentProduct->getSku();
     $product_price =   $currentProduct->getFinalPrice();
   }
?>
<?php if($product && $product->getCheckDeliveryEnable()==1): ?>
	<form data-mage-init='{"validation": {}}' class="form" id="checkDelivery-form" method="post" autocomplete="off" onSubmit="return checkPostcode()" style="padding-top:10px">
	   <fieldset class="fieldset vaiship">
		   <!--legend class="legend"><span><?php // echo __('Check Delivery') ?></span></legend><br-->
		   <!--<a href="#" data-toggle="tooltip" title="Hooray!"><span class="fa fa-bell"></span></a>-->
			<div class="field required">
				<?php if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0) { ?>
				<div style="display:none;">
					<label for="delivery_postcode" class="label"><span><?php echo __('For international Shipment') ?></span></label>
					<input id="international-checkbox" name="checkboxsss" type="checkbox" >
				</div>
				<div id="international-shipment-div" class="control" style="display:none;">
					<input type="text" placeholder="Enter Delivery Pincode" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
				</div>
				<?php } else { ?>
					<div>
						<label for="delivery_postcode" class="label"><span><?php echo __('For international Shipment') ?></span></label>
						<input id="international-checkbox" name="checkboxsss" type="checkbox" >
					</div>
				<div id="international-shipment-div" class="control">
					<input type="text" placeholder="Enter Delivery Pincode" name="postcode" id="delivery_postcode" value="" title="<?php echo __('Postcode') ?>" class="input-text" data-validate="{required:true, 'validate-digits':true}">
				</div>
			<?php } ?>
			</div>
			<div class="message"></div>
	   </fieldset>
		<?php if($StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId()) == 0) { ?>
		<div class="actions-toolbar" style="display:none;">
			<div class="primary">
				<div id="international-shipment-div2">
					<button type="submit" class="action submit primary" title="<?php  echo __('Check') ?>"><span><?php echo __('Check') ?></span></button>
				</div>
			</div>
		</div>
				<?php } else { ?>
		<div class="actions-toolbar">
			<div class="primary">
				<div id="international-shipment-div2">
					<button type="submit" class="action submit primary" title="<?php  echo __('Check') ?>"><span><?php echo __('Check') ?></span></button>
				</div>
			</div>
		</div>
			<?php } ?>
		
	</form>
	<script type="text/x-magento-init">
		{
			"#checkDelivery-form": {
				"validation": {}
			}
		}
	</script>
	<script>
		function checkPostcode() {
			var deliveryMessage = jQuery('#checkDelivery-form .message');
			deliveryMessage.removeClass('success').removeClass('error').hide();
			var deliveryForm = jQuery('#checkDelivery-form');
			if(deliveryForm.valid()) {
				jQuery.ajax({
					type: "POST",
					url: '<?php echo $this->getUrl('checkDelivery/postcode/check',array('id'=>$product->getId())) ?>',
					data: deliveryForm.serialize(),
					dataType: "json",
					showLoader: true,
					success: function(response) {
						deliveryMessage.addClass(response.type).html(response.message).show();
						jQuery('.showmessage').hide();
					}
				});
			}
			return false;
		}
	require([ 'jquery', 'jquery/ui'], function($){ 
      $(document).ready(function($) {
		$('#international-checkbox').change(function () {
        if (!this.checked){
			$('#form_type').val(1);
           $('#international-shipment-div').show();
           $('#international-shipment-div2').show();
           $('#product-addtocart-button').show();
           $('#buy-now').show();
		   $('#international-button').hide();
		}
        else 
		{
			$('#form_type').val(0);
			$('#international-shipment-div').hide();
			$('#international-shipment-div2').hide();
			$('#product-addtocart-button').hide();
			$('#buy-now').hide();
			$('#international-button').show();
			$('.showmessage').hide();
		 	
		}
    });
      });
 });
	</script>
<?php endif; ?>
<?php 
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');
$stockqty = $StockState->getStockQty($product->getId(), $product->getStore()->getWebsiteId());
$conf = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('checkDelivery/config/success_message');
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($product->getId());
$shippingCode = $product->getData('expected_delivery_date');
$smartbuy = $product->getResource()->getAttribute('offer_percentage')->getFrontend()->getValue($product);
if(isset($shippingCode)){
                 $cusdate = $shippingCode;
                $dt = date("Y-m-d");
                $Expecteddate = date( 'd M, Y', strtotime( "$dt +$cusdate day" ) );
                $Finalmessage = str_replace('one week', $Expecteddate, $conf);
                /*$response['type'] = 'success';
                $response['message'] = $Finalmessage;*/
                }/*else{
                    $response['type'] = 'success';
                    $response['message'] = $Finalmessage;//$SuccessMessage; 
                } */
?>
<?php if(isset($shippingCode) && $stockqty != 0 ) { ?>
<div class="showmessage" style="display:block; margin: 102px 0px 10px;font-size: 12px;color: #006400; width: 70%;margin-top:76px;
    position: relative;"><?php echo $Finalmessage;?></div>
<?php } elseif($producttype != 'configurable' && $stockqty != 0){ ?>
<div class="showmessage" style="display:block; margin: 102px 0px 10px;
    padding: 8px 8px 8px 8px;
    font-size: 12px;
    color: #006400;
    width: 70%;
    position: relative;"><?php echo $conf;?></div>
<?php } ?>