<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
	<style type="text/css">
		#my-orders-table tbody tr {
			padding: 5px;
    width: 100%;
    font-size: 14px;
    overflow: hidden;
    transition: box-shadow .1s linear;
    background-color: #fff;
    border: none;
    position: relative;
    cursor: pointer;
    display: block;
    /* box-shadow: 0 20px 50px rgba(59, 43, 91, 0.7);*/
    box-shadow: 0 3px 8px rgba(59, 43, 91, 0.3);
    margin-bottom: 12px;
    border-radius: 4px;
		}
	#my-orders-table > tbody > tr > td {
		border-top: none;
	}
	.account .table-wrapper {
		margin-right: 20px;
	}
	html {
	font-family: helvetica, arial;
}

.htimeline {
	list-style: none;
	padding: 0;
	margin: 10px 0 0;
}

.htimeline .step {
	float: left;
	border-bottom-style: solid;
	border-bottom-width: 5px;
	position: relative;
	margin-bottom: 10px;
	text-align: left;
	padding: 0px 0 5px 0px;
	color: #333;
	height: 50px;
	vertical-align: middle;
	transition: all 0.5s ease;
}


.htimeline .step div {
	margin: 0 5px;
	font-size: 14px;
	vertical-align: top;
	padding: 0;
}

.htimeline .step.green {
	border-bottom-color: #348F50;
}

.htimeline .step.orange {
	border-bottom-color: #F09819;
}

.htimeline .step.red {
	border-bottom-color: #C04848;
}

.htimeline .step.blue {
	border-bottom-color: #49a09d;
}

.htimeline .step::before {
	width: 15px;
	height: 15px;
	border-radius: 50px;
	content: ' ';
	background-color: white;
	position: absolute;
	bottom: -10px;
	left: 0px;
	border-style: solid;
	border-width: 3px;
	transition: all 0.5s ease;
}

.htimeline .step:hover::before {
	width: 18px;
	height: 18px;
	bottom: -12px;
}

.htimeline .step.green::before {
	border-color: #348F50;
}

.htimeline .step.orange::before {
	border-color: #F09819;
}

.htimeline .step.red::before {
	border-color: #C04848;
}

.htimeline .step.blue::before {
	border-color: #49a09d;
}

.htimeline .step::after {
	content: attr(data-date);
	position: absolute;
	bottom: 0px;
	left: 17px;
	font-size: 11px;
	font-style: italic;
	color: #888
}
.image-row {
   width: 20%;
}

.view-more {
	background: #b272d3 !important;
    color: #fff !important;
    font-size: 12px;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1) !important;
    border-radius: 2px !important;
    padding: 7px 14px !important;
}
.table-wrapper.orders-history {
    box-shadow: none !important;
}
.account .table-wrapper {   
    border-bottom: none;
}
.order_id,.order-date {
    position: absolute;
    top: 5px;
    font-size: 12px;
    font-weight: 800;

} 
.order-date {
right: 15px;
}
 .table.table-order-items.history > tbody > tr > th, .table.table-order-items.history > tbody > tr > td {
 border: 0;
 padding: 30px 10px 10px 10px;
 vertical-align: middle;
}
	</style>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <tbody>
            	<?php 
            	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            	$imageHelper  = $objectManager->get('\Magento\Catalog\Helper\Image'); ?>
                <?php foreach ($_orders as $_order) : ?>

                    <tr>
                    	<?php
                        $orderItems = $_order->getAllItems();
                        $produc_id = "";
                        $first = true;
foreach($orderItems as $item)
{
   if ( $first )
    {
        // do something
        $first = false;
        $produc_id = $item->getProductId();
    }
}
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($produc_id);
$image_url = $imageHelper->init($_product, 'product_page_image_small')->setImageFile($_product->getImage())->resize(100, 100)->getUrl();


                    	 ?>
                    	 <td data-th="<?= $block->escapeHtmlAttr(__('Image')) ?>" class="col image-row"><img width="100px" class="order_image" src="<?php echo $image_url; ?>"/>
                             <div class="order_id">#<?php echo $_order->getIncrementId(); ?></div>
                         </td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id"><div class='container-fluid'> 
<ul class='htimeline'>
    <li data-date='<?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>' class='step col-sm-3 blue'><div>Ordered</div></li>
      <?php if($_order->hasShipments()) { ?>
  <li data-date='<?= $_order->getShipmentsCollection()->getFirstItem()->getCreatedAt() ?>' class='step col-sm-4 blue'><div>Shipped</div></li>
   <?php  } ?>
    <?php if($_order->getStatus() == 'complete') { ?>
 <li data-date='<?= /* @noEscape */ $block->formatDate($_order->getUpdatedAt()) ?>' class='step col-sm-3 green'><div>Delivered</div></li>
   <?php  } ?>
    <?php if($_order->getStatus() == 'canceled') { ?>
 <li data-date='<?= /* @noEscape */ $block->formatDate($_order->getUpdatedAt()) ?>' class='step col-sm-3 red'><div>Canceled</div></li>
   <?php  } ?>
  </ul>
</div></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" style="display: table-cell; vertical-align: middle;" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view view-more">
                                <span><?= $block->escapeHtml(__('View More')) ?></span>
                            </a>
                             <div class="order-date"> Order Date: <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
<?php endif ?>
