<?php
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $basemediaurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                       ->getStore()
                       ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
   $imgix_url= $basemediaurl;//'https://cdn-media.vaibhavjewellers.com/pub/media/';   
   ?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>
<style>
   .text-underline{padding-left:0px;}
   .text-underline:after{width: 25%;height: 2px;}
   span.sel__placeholder.sel__placeholder--black-panther{line-height:35px;}
   span.sel__box__options.sel__box__options--black-panther {color: #6e2083;}
   .sel__box__options:hover {background-image: linear-gradient(to right,#FDD8FB,#E6B5E2);}
</style>
<div class="container-fluid">
   <div class="inner-block row d-none d-sm-flex pt-5">
      <a href="<?php echo $linkUrl;?>women-diamond-rings.html" class="col-md-3">
        <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/women-diamond-rings-36.jpg" alt="women-diamond-rings-collection" width="328" height="485">
      </a>
      <!--2starts-->
      <a href="<?php echo $linkUrl;?>diamond-jewellery/women/earrings.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/women-diamond-earrings-37.jpg" alt="women-diamond-earrings-collection" width="328" height="485">
      </a>
      <!--3starts-->
      <a href="<?php echo $linkUrl;?>diamond-jewellery/women/bracelet.html" class="col-md-3">
         <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/women-diamond-bracelets-38.jpg" alt="women-diamond-bracelets-collection" width="328" height="485">
      </a>
      <!--4starts-->
      <a href="<?php echo $linkUrl;?>gold-jewellery/women/mangalsutra.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/gold-black-beads.jpg" alt="gold-black-beads-collection" width="328" height="485">
      </a>
   </div>
   <!-----2-------->
   <div class="align-items-center d-sm-flex inner-block d-none d-sm-block pt-5 row">
      <div class="col-md-4">
         <a href="<?php echo $linkUrl;?>diamond-jewellery.html?p=2">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/myra-collection-diamond-&-you-39.jpg" alt="myra-collection-diamond-&-you-necklace" width="462" height="483">
         </a>
      </div>
      <!--1-->
      <div class="col-md-4 text-center">
         <a href="<?php echo $linkUrl;?>diamond-jewellery.html">
             <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/myra-collection-diamond-&-you-24.jpg" alt="myra-collection-diamond-&-you-necklace" width="462" height="462">
         </a>
         <!--2--><a href="<?php echo $linkUrl;?>gold-jewellery.html"><button class="view-button mt-5">View All Jewellery</button></a>
      </div>
      <!--3-->
      <div class="col-md-4">
         <a href="<?php echo $linkUrl;?>diamond-jewellery.html">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/myra-collection-diamond-&-you-40.jpg" alt="myra-collection-diamond-&-you-necklace" width="462" height="483">
         </a>
      </div>
   </div>
   <!------3------->
   <div class="inner-block pt-5 mb-4">
      <div class="row">
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/bangles.html" class="col-md-3">
             <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/bangles-1.jpg" alt="gold_bangles_collection" width="328" height="219">
         </a>
         <!--1-->       
         <a href="<?php echo $linkUrl;?>diamond-jewellery/women/earrings.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/earrings-2.jpg" alt="diamond_earrings_collection" width="328" height="219">
         </a>
         <!--2-->
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/bracelets.html?collection_type=374" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/bracelets-3.jpg" alt="bracelets_collection" width="328" height="219">
         </a>
         <!--3-->
         <a href="<?php echo $linkUrl;?>women-gold-chains.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/chains-4.jpg" alt="gold_chains_collection" width="328" height="219">
         </a>
      </div>
      <!--4-->
      <div class="row pt-3">
         <a href="<?php echo $linkUrl;?>diamond-jewellery/women/mangalsutra.html" class="col-md-3">
             <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/mangalsutra-5.jpg" alt="diamond_mangalsutra_collection" width="328" height="219">
         </a>
         <!--5-->
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/harams.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/harams-6.jpg" alt="gold_harams_collection" width="328" height="219">
         </a>
         <!--6-->
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/vaddanam.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/vaddanam-7.jpg" alt="gold_vaddanams_collection" width="328" height="219">
         </a>
         <!--7-->
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/choker.html" class="col-md-3">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/choker-8.jpg" alt="gold_chokers_collection" width="328" height="219">
         </a>
      </div>
      <!--8-->
   </div>
   <div class="inner-block row pt-5 bg-color-grey2">
      <div class="align-items-center col-md-6 d-flex position-relative">
        <img class="px-25 w-90 opacity-60" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/23.jpg" alt="25" width="394" height="396">
         <div class="position-absolute w-40 r-10 img-txt" style="background-color: #F9EFF8;padding: 22px 20px;opacity: 0.9;border-radius: 10px;">
            <h5 class="text-underline">Free Try@Home</h5>
            <p class="pt-4 font-14" style="padding: 0;">Want to try your favourite designs at home, with no obligations to buy? Go ahead book a free appointment today!</p>
            <button class="gradient-button p-2 w-100"><a href="<?php echo $linkUrl;?>try-at-home">Know More</a></button>
         </div>
      </div>
      <div class="align-items-center col-md-6 d-flex position-relative">
           <img class="px-25 w-90 opacity-60" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/24.jpg" alt="24" width="394" height="396">
         <div class="position-absolute w-40 r-10 img-txt" style="background-color: #F9EFF8;padding:22px 20px;border-radius: 10px;">
            <h5 class="text-underline">Visit the Nearest Store</h5>
            <p class="pt-4 font-14" style="padding: 0;">For latest designs visit our nearest branch, you can also request for a private viewing in case you want to come along with your entire family or for bridal shopping</p>
            <div class="sel sel--black-panther" style="cursor: pointer;">
               <select name="select-profession" id="select-profession" style="cursor: pointer;">
                  <option value="">Select City</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-visakhapatnam">Visakhapatnam</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-gajuwaka">Gajuwaka</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-kakinada">Kakinada</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-rajahmundry">Rajahmundry</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-anakapalle">Anakapalli</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-srikakulam">Srikakulam</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-parvathipuram">Parvathipuram</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-bobbili">Bobbili</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-tuni">Tuni</option>
                  <option value="<?php echo $linkUrl;?>andhrapradesh-gopalapatnam">Gopalapatnam</option>
                  <option value="<?php echo $linkUrl;?>telangana-dilsukhnagar">Dilsukhnagar</option>
                  <option value="<?php echo $linkUrl;?>telangana-asraonagar">A.S Rao Nagar</option>
               </select>
            </div>
         </div>
      </div>
   </div>
   <div class="inner-block row pt-5">
      <div class="col-md-4">
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/vanki/22kt-precious-stone-gold-baby-vanki-25vg597.html">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/peacock-vanki.jpg" alt="peacock-vanki" width="435" height="250">
         </a>
      </div>
      <div class="col-md-4">
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/necklace/22k-antique-gold-necklace-123vg5325.html">
             <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/peacock-necklace.jpg" alt="peacock-necklace" width="435" height="250">
         </a>
      </div>
      <div class="col-md-4">
         <a href="<?php echo $linkUrl;?>gold-jewellery/women/harams/22k-antique-gold-mango-haram-124vg3037.html">
            <img class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/gold-mango-haram.jpg" alt="gold-mango-haram" width="435" height="250">
         </a>
      </div>
   </div>
   <div class="inner-block pt-5 text-center">
      <div class="row">
         <!-- w-100 m-0 --> 
         <img  class="w-100" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/7 Advantage.jpg" alt="vaibhav-advantage" width="2813" height="355"> 
      </div>
   </div>
</div>
<script>
   var urlMenu = document.getElementById('select-profession');
   urlMenu.onchange = function()
   {
      var useroption = this.options[this.selectedIndex];
      if (useroption.value != "nothing")
      {
         window.open(useroption.value,"HTML CSS JAVASCRIPT","");
      }
   }
</script>
