
<div class="bg-color-voilet p-5 d-none d-sm-block desktop-footer" style="content-visibility: auto; contain-intrinsic-size: 700px;">
<div class="container-fluid">
<div class="footer-top color-white row">
<div class="col-5">
<div class="row">
<div class="col-6">
<h5 style="width: 60%;border-bottom: 2px solid #A558AA;line-height: 29px;" aria-hidden="true">About Vaibhav</h5>
<ul>
<li>
<a href="https://www.vaibhavjewellers.com/business-overview">
About Us
</a>
</li>
<!--<li>
<a href="https://www.vaibhavjewellers.com/founder">
Founder
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/management-team">
Management Team
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/vaibhav-advantage">
Vaibhav Advantage
</a>
</li>-->
<li>
<a href="https://www.vaibhavjewellers.com/work-with-us">
Work with Us
</a>
<!--</li>
<li>
<a href="https://www.vaibhavjewellers.com/environment-page">
CSR
</a>
</li>-->
<li>
<a href="https://www.vaibhavjewellers.com/gold-rate">
Gold Rate
</a>
</li>

<!--
<li>
<a href="https://www.vaibhavjewellers.com/blog/">
Blog
</a>
</li>-->

<li>
<a href="https://www.vaibhavjewellers.com/investor-relations">
Investor Relations
</a>
</li>
</ul>
</div>
<div class="col-6">
<h5 style="width: 60%;border-bottom: 2px solid #A558AA;line-height: 29px;" aria-hidden="true">Customer Services</h5>
<ul>
<li>
<a href="https://www.vaibhavjewellers.com/emi">
EMI
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/privacy-policy">
Privacy Policy
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/shipping-policy">
Shipping Policy
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/refund-policy">
Refund Policy
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/exchange-policy">
 Exchange Policy
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/terms-of-use">
Terms of Use
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/terms-and-conditions">
Terms & Conditions
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/contact">
Contact Us
</a>
</li>
</ul>
</div>
</div>
</div>
<div class="col-2">
<img data-pagespeed-no-transform class="w-100"
                    src="<?php echo $this->getUrl('media/wysiwyg/');?>footer-logo-white.png" alt="" width="218" height="68">
</div>
<div class="col-5">
<h5 style="line-height: 29px;border-bottom: 2px solid #A558AA;width: 27%;" aria-hidden="true">Our Branches</h5>
<div class="d-flex justify-content-between">
<ul>
<li>
<a href="https://www.vaibhavjewellers.com/our-branches">
Andra Pradesh
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-visakhapatnam">
Visakhapatnam
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-gajuwaka">
Gajuwaka
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-kakinada">
Kakinada
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-rajahmundry">
Rajahmundry
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-anakapalle">
Anakapalli
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-srikakulam">
Srikakulam
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-parvathipuram">
Parvathipuram
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-bobbili">
Bobbili
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-gopalapatnam">
Gopalapatnam
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/andhrapradesh-vizianagaram">
Vizianagaram
</a>
</li>
<li>
 <a href="https://www.vaibhavjewellers.com/andhrapradesh-tuni">
Tuni
</a>
</li>
<li>
<b><a href="https://www.vaibhavjewellers.com/our-branches">
Telangana
</a></b>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/telangana-dilsukhnagar">
Dilsukhnagar
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/telangana-asraonagar">
A.S Rao Nagar
</a>
</li>
</ul>
<ul>
<h5 style="border-bottom: 2px solid #A558AA;line-height: 29px;" aria-hidden="true"> Popular Categories </h5>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/earrings.html">
Gold Earrings
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/women-gold-chains.html">
Gold Chains
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/rings.html">
Gold Rings
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/necklace.html">
Gold Necklace
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/mangalsutra.html">
Gold Mangalsutra
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/bangles.html">
Gold Bangles
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/harams.html">
Gold Haram
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/vaddanam.html">
Gold Vaddanam
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/pendants.html">
Gold Pendants
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-jewellery/women/bracelets.html">
Gold Bracelets
</a>
</li>
<li>
<a href="https://www.vaibhavjewellers.com/gold-coins.html">
Gold Coins
</a>
</li>
</ul>
<ul>
</ul>
</div>
</div>
</div>
<div class="footer-bottom row color-white" style="background-color: #431A44;padding: 15px;">
<div class="col-lg-4 text-center">
<h3>We Accept</h3>
<div style="display: flex;justify-content: center;align-items: center;">

<div class="bg-mastercard"></div>

<div class="bg-visa"></div>

<div class="bg-american"></div>
</div>
</div>
<div class="align-items-end col-lg-4 d-flex justify-content-center">
<p class="m-0">©  Vaibhav Jewellers. All Rights Reserved</p>
</div>
<div class="col-lg-4 text-center">
<h3>Connect with us</h3>
<div class="d-flex justify-content-between m-auto w-75">
<a rel="nofollow" aria-label="Facebook" target="_blank" href="https://www.facebook.com/vaibhavjewllers">
<i class="fab fa-facebook-f"></i>
</a>
<a rel="nofollow" aria-label="Instagram" target="_blank" href="https://www.instagram.com/vaibhavjewellers">
<i class="fab fa-instagram"></i>
</a>
<a rel="nofollow" aria-label="Twitter" target="_blank" href="https://twitter.com/vaibhavjewelers">
<i class="fab fa-twitter"></i>
</a>
<a rel="nofollow" aria-label="Youtube" target="_blank" href="https://www.youtube.com/channel/UCT6Uv0OflrUVA2VDNk_C2Tw">
<i class="fab fa-youtube"></i>
</a>
<a rel="nofollow" aria-label="Whatsapp" target="_blank" href="https://api.whatsapp.com/send?phone=919177403000">
<i class="fab fa-whatsapp"></i>
</a>
<a rel="nofollow" aria-label="Pinterest" target="_blank" href="https://in.pinterest.com/VaibhavJewellers">
<i class="fab fa-pinterest"></i>
</a>
</div>
</div>
</div>
</div>
</div>

<!-- <style>
.gold_coin_wrapper.fixed_pos {
    position: fixed;
    bottom: 0;
}
.gold_coin_wrapper {
    position: relative;
    width: 100%;
    left: 0;
    bottom: -20px;
    z-index: 99998;
    box-shadow: 0px -2px 5px 0px rgba(50, 50, 50, 0.43);
    background-color: #fff;
    transition: all .3s ease-in-out;
}
.gold_coin_wrapper img {
    width: 100%;
    display: block;
}
.close__ {
    position: absolute;
    top: 5px;
    right: 5px;
    width: 25px;
    height: 25px;
    border-radius: 25px;
    border: 1px solid #eee;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #ffe9ec;
    cursor: pointer;
}
.close__ img {
    display: block;
    width: 8px;
}
    footer h5 {
    font-size: 16px;
    font-weight: 600;
}

footer li {
    font-size: 14px;
    padding-bottom: 0px;
}

footer li a {
    color: #fff;
}

.footer-bottom h3 {
    margin: 0;
    border-bottom: 1px solid;
    padding: 10px;
    font-size: 20px;
    margin-bottom: 20px;
}

.footer-bottom i {
    font-size: 20px;
    color: #fff;
}

.page-main {
    margin-top: 0px;
}


.footer.content {
    padding-left: 0px !important;
    padding-right: 0px !important;
    padding-top: 0px !important;
}

.columns .column.main {
    padding-left: 0px !important;
    padding-right: 0px !important;
    padding-bottom: 0px !important;
}

.navigation,
.breadcrumbs,
.page-header .header.panel,
.header.content,
.footer.content,
.page-wrapper>.widget,
.page-wrapper>.page-bottom,
.block.category.event,
.top-container,
.page-main {
    padding-left: 0px !important;
    padding-right: 0px !important;
    max-width: 100% !important;
}

.page-footer {
    padding-bottom: 0px !important;
    padding-top: 0px !important;
    text-align: left!important;
}

main#maincontent {
    max-width: 100%;
}

.footer-top li a {
    color: #fff;
}

</style> -->
<script type="text/javascript">// <![CDATA[
    require([
        'jquery'
    ], function ($) {
       $(".close__").click(function(){
        $(this).parent(".gold_coin_wrapper").remove();
    });
    $(document).scroll(function () {
   var y = $(this).scrollTop();
   if (y > 500) {
       $('.offer_sticky').fadeIn();
   } else {
       $('.offer_sticky').fadeOut();
   }

});
    });
    // ]]>
</script>
