  <div id="sticky_header" class="sticky_header">
   <div class="align-items-center container-fluid d-flex justify-content-between">
    <div class="align-items-center col-md-2 d-sm-flex nav-tool-left  d-none d-sm-block p-0">
        <?php echo $this->getlayout()->createBlock('\Magento\Theme\Block\Html\Header\Logo')->setTemplate('Magento_Theme::html/header/logo_scroll.phtml')->toHtml();?>
    </div>
     <div class="align-items-center col-md-7 d-sm-flex nav-tool-left  d-none d-sm-block p-0 nav-sections">
        <?= $this->getBlockHtml('store.menu') ?>
    </div>
     <div id="sticky_right_container" class="align-items-center col-md-3 d-sm-flex nav-tool-left justify-content-end  d-none d-sm-block p-0">
    </div>
   </div>
</div>
   <div class="align-items-center container-fluid d-flex header-bottom justify-content-between ">
         

        <?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');
if ($customerSession->isLoggedIn() != true) {
//your code. 
?>      
    <div class="log_block align-items-center col-md-4 d-sm-flex nav-tool-left  d-none d-sm-block p-0">
        <ul class="d-flex m-0 p-0 color-voilet">
            <li class="p-lg-2 p-1 d-flex align-items-center">
                <a href="<?php echo $this->getUrl('customer/account/login'); ?>" class="d-flex align-items-center"><i class="fas fa-unlock p-1"></i>
                Log In</a>
                
            </li>
            <li class="p-lg-2 p-1 d-flex align-items-center">
                <a href="<?php echo $this->getUrl('customer/account/create'); ?>" class="d-flex align-items-center"><i class="fas fa-key p-1"></i>
                Register</a>
            </li>
            <li class="p-lg-2 p-1 d-flex align-items-center    ">
                <a href="<?php echo $this->getUrl('wishlist'); ?>" class="d-flex align-items-center"><i class="fas fa-heart p-1"></i>
                Wishlist</a>
            </li>
        </ul>
    </div>

<?php } else { ?>

     <div class="align-items-center col-md-4 d-sm-flex nav-tool-left  d-none d-sm-block p-0">
        <ul class="d-flex m-0 p-0 color-voilet">
            <li class="p-lg-2 p-1 d-flex align-items-center">
                <a href="<?php echo $this->getUrl('customer/account'); ?>" class="d-flex align-items-center"><i class="fas fa-unlock p-1"></i>
                My account</a>
                
            </li>
            <li class="p-lg-2 p-1 d-flex align-items-center">
                <a href="<?php echo $this->getUrl('customer/account/logout'); ?>" class="d-flex align-items-center"><i class="fas fa-key p-1"></i>
                Logout</a>
            </li>
            <li class="p-lg-2 p-1 d-flex align-items-center    ">
                <a href="<?php echo $this->getUrl('wishlist'); ?>" class="d-flex align-items-center"><i class="fas fa-heart p-1"></i>
                Wishlist</a>
            </li>
        </ul>
    </div>

<?php } ?>

    <!-- header logo starts-->
    <!-- <div class="col-md-4">
        <img class="px-lg-5 py-xl-2 w-100" src="https://cdn-media.vaibhavjewellers.com/pub/media/logo/stores/1/logo.png" alt="">
    </div> -->
    <!-- header logo ends-->