 <?php  

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$store = $storeManager->getStore();

$currency=$store->getCurrentCurrencyCode();

$rate = $store->getCurrentCurrencyRate();

$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $object_manager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('pricemanager');

//Select Data from table
$sql = "Select * FROM  $tableName WHERE id = 1" ;
$result = $connection->fetchAll($sql);


 ?>
<style type="text/css">
  span.dropdown-item {
    font-size: 13px;
    padding: 5px;
    color: #6e2083;
}
</style>
 <div id="main-header-right-container" class="metal_rate_block align-items-center col-md-4 d-flex justify-content-end p-0">
    <div id="main_header_right_content" class="align-items-center d-flex justify-content-end p-0">
        <div class="dropdown p-2 d-none d-sm-block">
            <button type="button" class="btn dropdown-toggle color-voilet p-0" data-toggle="dropdown">
                Metal Rate
            </button>
           <?php if($currency=='INR'): ?>
            <div class="dropdown-menu">

                <span class="dropdown-item">Gold-22k/1g- <?php echo $result[0]['22K']; ?><!-- ₹3,953.00 --></span>
                <span class="dropdown-item">Gold-18k/1g- <?php echo $result[0]['18K']; ?><!-- ₹3,234.00 --></span>
                <span class="dropdown-item">Silver-1g- <?php echo $result[0]['hundred']; ?><!-- ₹50.10 --></span>
                
            </div>
             <?php else: ?>
                 <div class="dropdown-menu">
                <span class="dropdown-item">Gold-24k/1g- <?php echo $result[0]['24K']*$rate; ?><!-- $63.00 --></span>
                <span class="dropdown-item">Gold-22k/1g- <?php echo $result[0]['22K']*$rate; ?><!-- $58.00 --></span>
                <span class="dropdown-item">Gold-18k/1g- <?php echo $result[0]['18K']*$rate; ?><!-- $47.00 --></span>
                <span class="dropdown-item">Silver-1g- <?php echo $result[0]['hundred']*$rate; ?><!-- $1.00 --></span>
                <span class="dropdown-item">Platinum-1g- <?php echo $result[0]['p_hundred']*$rate; ?><!-- $43.00 --></span>
            </div>
             <?php endif; ?>
        </div>

          <div style="text-align: center; display: none;" class="currency_country p-2">
             <?php if($currency=='INR'): ?>
                         <img data-pagespeed-no-transform class="" src="<?php echo $this->getUrl('pub/media/');?>india_cny_flag.png" alt="shop-facilities"><br/>
                    <span style="font-size: 10px;">IND</span>
                    <?php else: ?>
                        <img data-pagespeed-no-transform class="" src="<?php echo $this->getUrl('pub/media/');?>usa_cny_flag.png" alt="shop-facilities"><br/>
                     <span style="font-size: 10px;">USA</span>
                    <?php endif; ?>
                     </div>

                            <?php

$customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');
if ($customerSession->isLoggedIn() != true) {
//your code. 
?> 
  <div style="text-align: center; display: none;" class="sticky_user_acc p-2">
 <a href="<?php echo $this->getUrl('customer/account/login'); ?>"><i style="font-size:15px;color: #000;margin-top: 5px;" class="fa fa-user" aria-hidden="true"></i></a>
</div>
<?php } else { ?>
    <div style="text-align: center; display: none;" class="sticky_user_acc p-2">
 <a href="<?php echo $this->getUrl('customer/account'); ?>"><i style="font-size:15px;color: #000;margin-top: 5px;" class="fa fa-user" aria-hidden="true"></i></a>
</div>

    <?php } ?>
        <!-- <div class="p-2 color-voilet">
            <a href="">
                <i class="fas fa-shopping-cart "></i>
                <span>(<span>0</span>)</span>
            </a>
        </div> -->
        
        