<style>
	button.mt-5.button-black {
    background-color: #741D80;
    /* color: #000; */
}
.slick-slide img {
    margin-left: 17px;
   
}
li.item.product.product-item.slick-slide{
    background-color:white;
}
#you_also_love .action.towishlist {
    position: absolute;
    top: -10px;
    right: -5px;
    z-index: 99;
}
.product-social-links .action.towishlist:before, .block-bundle-summary .action.towishlist:before, .product-item .action.towishlist:before, .table-comparison .action.towishlist:before {
    content: '\e600';
    font-size: 28px;
}
.bundle-options-container .block-bundle-summary .product-addto-links>.action:before, .product-item-actions .actions-secondary>.action:before, .product-social-links .action.tocompare:before, .wishlist.split.button>.action.split:before, .product-social-links .action.mailto.friend:before, .product-social-links .action.towishlist:before, .block-bundle-summary .action.towishlist:before, .product-item .action.towishlist:before, .table-comparison .action.towishlist:before{
    width:28px;
}
.product.details.product-item-details{
    background-color:#fff;
    padding:7px 5px;
}
.offset-1 {
    margin-left: 3.333333%;
}
#deo1 span.carousel-control-prev-icon.fa.fa-angle-left {
    font-size: 34px;
    color: #000;
    font-weight: 700;
    margin-left: -30px;
}
#deo1 span.carousel-control-next-icon.fa.fa-angle-right {
    font-size: 30px;
    color: #000;
    font-weight: 700;
    margin-right: -30px;
}
.gradient-title:before{
    right: 269px;
    background: purple;
}

.gradient-title:after{
        left: 310px;
    background: purple;
}
.gradient-title span{
    
    color: purple;
    font-family: 'FontAwesome';
    font-size: 26px;

}
.slick-prev {
   
    width: 40px !important;
    height: 40px !important;
    background-color:#000 !important;
}
.slick-next {
    
    width: 40px !important;
    height: 40px !important;
    background-color:#000 !important;
}
.slick-prev:before {
   
    color: #fff !important;
}
.slick-next:before {
   
    color: #fff !important;
}
.slick-slider button:not(:disabled) {
    color: transparent;
}
</style>
<div class="inner-block bg-fixed d-flex justify-content-center align-items-center"> <!-- mt-2 -->
    <div class="text-center">
        <h2 class="font-42">BE YOUR OWN JEWELLERY DESIGNER!</h2>
        <h4 class="color-white font-itallic">We Will Make It Happen.</h4>
        <button class="mt-5 button-black"><a style="color:#fff;" href="https://www.vaibhavjewellers.com/personalize-your-jewellery">SHARE YOUR DESIGNS</a></button>
    </div>
</div>