<?php
   $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
   $basemediaurl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                       ->getStore()
                       ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
   $imgix_url= $basemediaurl;//'https://cdn-media.vaibhavjewellers.com/pub/media/';
    ?>
<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>
<div class="container-fluid" style="margin-top: -120px;">
   <div class="inner-block d-flex mt-5">
      <div class="w-50">
         <a href="<?php echo $linkUrl;?>gold-jewellery.html?product_category_type=229">
            <img style="padding-right: 4px;" class="w-100 hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/uttamakshnam-bridal-collection.jpg" alt="Vaibhav-Uttamakshnam" width="600" height="300">
         </a>
         <a href="<?php echo $linkUrl;?>diamond-jewellery/women/pendants.html">
            <img style="padding-right: 4px;" class="w-100 hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/trinity-collection.gif" alt="Vaibhav-Uttamakshnam-1" width="600" height="300">
         </a>
      </div>
      <div class="w-75">
         <div class="w-100 d-flex ring-row">
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>silvigo-collections.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/silvigo-collection.jpg" alt="silvigo-collection" width="300" height="300">
               </a>
            </div>
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>butterfly-collection.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/butterfly-collection.jpg" alt="butterfly-collection" width="300" height="300">
               </a>
            </div>
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>trinity-collection.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/tanmay-collection.jpg" alt="tanmay-collection" width="300" height="300">
               </a>
            </div>
         </div>
         <div class="w-100 d-flex ring-row">
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>tara-collection.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/tara-collection.jpg" alt="tara-collection" width="300" height="300">
               </a>
            </div>
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>floral-collection.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/floral-collection.jpg" alt="Floral-Collection" width="300" height="300">
               </a>
            </div>
            <div class="ring-col">
               <a href="<?php echo $linkUrl;?>glam-glitz.html">
                    <img style="padding-right: 4px;" class="w-100 home-ring-img hrDesk" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/glam-glitz-collection.jpg" alt="Glam-Collection" width="300" height="300">
               </a>
            </div>
         </div>
      </div>
   </div>
   <div class="inner-block-video mt-5 row">
      <div class="col-md-6">
         <h5 style="text-align:center;text-decoration: underline;margin-right: 155px;">Education</h5>
         <div>
            <img class="col-md-3" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/Home_Page_(41).webp" width="134" height="124">
            <a href="<?php echo $linkUrl;?>diamond-anatomy"><span style="color:black;font-size: 16px;letter-spacing: 0;" class="col-md-7 offset-1">Know your Diamond</span></a>
            <p class="flt" style="font-size: 13px;margin-left: 198px;">Diamond to the princess cut, we'll help you choose the shape that complements your style.</p>
         </div>
         <div class="pt-2">
            <img class="col-md-3" src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/Home_Page_(56).webp" width="134" height="124">
            <a href="<?php echo $linkUrl;?>gold-color"><span style="color:black"  class="col-md-7 offset-1">Know your Metal</span></a>
            <p class="flt" style="font-size: 13px;margin-left: 198px;">GOLD Won't tarnish, rust, or corrode, and though it's very strong, it is also the most malleable of all metals.</p>
         </div>
      </div>
      <div class="col-md-6">
         <h5 style="text-align: center;text-decoration: underline;">Testimonials</h5>
         <div id="slider" class="m-auto">
            <div id="deo" class="carousel slide" data-ride="carousel">
               <!-- Indicators -->
               <ul class="carousel-indicators">
                  <li data-target="#deo" data-slide-to="0" class="active"></li>
                  <li data-target="#deo" data-slide-to="1"></li>
                  <li data-target="#deo" data-slide-to="2"></li>
               </ul>
               <!-- The slideshow -->
               <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/vaibhav-customer-testimonial-4.webp?auto=compress" alt="Vaibhav-Testimony-Desktop-1" width="415"  height="177">
                  </div>
                  <div class="carousel-item">
                    <img src="<?php echo $mediaUrl;?>wysiwyg/homepage_images/desktop/vaibhav-customer-testimonial-3.webp?auto=compress" alt="Vaibhav-Testimony-Desktop-2" width="415" height="177">
                  </div>
               </div>
               <!-- Left and right controls -->
               <a class="carousel-control-prev" href="#deo" data-slide="prev">
               <span class="carousel-control-prev-icon"><span class="arrow arrow-left"></span></span>
               </a>
               <a class="carousel-control-next" href="#deo" data-slide="next">
               <span class="carousel-control-next-icon"><span class="arrow arrow-right"></span></span>
               </a>
            </div>
         </div>
      </div>
   </div>
</div>