<script type="application/ld+json">
{
"@context": "https://schema.org",
"@type": "FAQPage",
"mainEntity": [{
"@type": "Question",
"name": "What is the difference between gold hanging and gold Chandbali earrings?",
"acceptedAnswer": {
"@type": "Answer",
"text": "Gold Hangings come in different lengths; they are the most common adornment among Indian women. On the other hand, Chanbalis come in a crescent moon shape only with variations to the top and bottom of the balis.  Chandbalis gold earrings come in varying lengths, and widths- i.e. the width of the crescent shape varies from piece to piece. Gold hangings are available in all price and weight ranges while Chandbalis start from a minimum of 5gms because of their design."
}
},{
"@type": "Question",
"name": "What is a gold hanging earring?",
"acceptedAnswer": {
"@type": "Answer",
"text": "Gold Hanging earring is shaped straight, they come in different lengths, designs, purity, and weight ranges. They have peacocks, florals, abstracts, geometric, lattice, many such unique patterns."
}
},{
"@type": "Question",
"name": "How is gold hanging different from normal earrings?",
"acceptedAnswer": {
"@type": "Answer",
"text": "Gold Hangings as the name suggests hang down from the ear lobe, on the other hand, normal earrings can be any type such as ear studs, Jhumkis, drops, dangles. While regular earrings come in different shapes, weights, designs."
}
},{
"@type": "Question",
"name": "What is an ideal price to buy gold hanging earrings?",
"acceptedAnswer": {
"@type": "Answer",
"text": "Gold hanging earrings start from INR 8,000 at our online portal, an ideal price range always depends on purity, the weight of gold, design, and making charges. It also depends on the workmanship. For example, you can antique gold hangings with goddess Lakshmi idol, Ganesha, etc. The gold hangings made in special workmanship are priced on a higher side for their uniqueness."
}
},{
"@type": "Question",
"name": "Best suitable weight and carat to buy gold hangings?",
"acceptedAnswer": {
"@type": "Answer",
"text": "Gold hangings are trendy adornments while some like the lightweight earrings others choose to adorn the heavy hangings. Both are equally beautiful when it comes to a suitable weight and carat- it entirely depends on the taste and the preference of the adorner. While purity is an entirely personal choice, the gold hangings are available from 14KT and weight as low as 2.1gms."
}
}
]}}  
</script>