<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<style>
.breadcrumbs {
    display:block !important;
    font-size: 8px;
    display: block;
    white-space: nowrap;
    text-overflow: ellipsis!important;
    width: 100% !important;
    overflow: hidden !important;
}

.breadcrumbs .item:not(:last-child):after {
    font-size: 8px;
    line-height: 10px;
}

</style>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="breadcrumbs" style="margin: 0 0 5px 15px;">
    <ul class="items" style="font-size:12px;">
        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
            <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
            <?php if ($crumbInfo['link']) : ?>
                <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
            <?php elseif ($crumbInfo['last']) : ?>
                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
            <?php else: ?>
                <?= $block->escapeHtml($crumbInfo['label']) ?>
            <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
