<?php  

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();  
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

$store = $storeManager->getStore();

$currency=$store->getCurrentCurrencyCode();

$rate = $store->getCurrentCurrencyRate();


$object_manager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $object_manager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();
$tableName = $resource->getTableName('pricemanager');

//Select Data from table
$sql = "Select * FROM  $tableName WHERE id = 1" ;
$result = $connection->fetchAll($sql);


 ?>

<style>
    button.subscription:active, button.subscription:hover {
        background-color:#6e2083 !important;
    }
</style>
<div class="metal-table">
<h4 class="table-heading">TODAY'S GOLD RATE</h4>
<table class="table table-borderless">
<thead>
<tr>
<th>Metal</th>
<th>Purity</th>
<th>Price per Gram</th>
</tr>
</thead>
 <?php if($currency=='INR'): ?>
<tbody>
<tr>
<td>Gold</td>
<td>24 KT</td>
<td><?php echo $result[0]['24K']; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>22 KT</td>
<td><?php echo $result[0]['22K']; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>18 KT</td>
<td><?php echo $result[0]['18K']; ?></td>
</tr>
<tr>
<td>Silver</td>
<td>100%</td>
<td><?php echo $result[0]['hundred']; ?></td>
</tr>
<tr>
<td>Platinum</td>
<td>995</td>
<td><?php echo $result[0]['p_hundred']; ?></td>
</tr>
</tbody>
<?php else: ?>
<tbody>
<tr>
<td>Gold</td>
<td>24 KT</td>
<td><?php echo $result[0]['24K']*$rate; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>22 KT</td>
<td><?php echo $result[0]['22K']*$rate; ?></td>
</tr>
<tr>
<td>Gold</td>
<td>18 KT</td>
<td><?php echo $result[0]['18K']*$rate ; ?></td>
</tr>
<tr>
<td>Silver</td>
<td>100%</td>
<td><?php echo $result[0]['hundred']*$rate; ?></td>
</tr>
<tr>
<td>Platinum</td>
<td>995</td>
<td><?php echo $result[0]['p_hundred']*$rate; ?></td>
</tr>
</tbody>
<?php endif; ?>
</table>
<button onclick='document.getElementById("middle").scrollIntoView({
            behavior: "smooth"
        });' class="subscription">Subscribe for Metal Rate Update</button></div>