<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>

<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="container-fluid mobile-section d-block d-sm-none">
    <div class="footer-top row pt-4">
       <div class="col-12 text-center footer-logo" style="padding-bottom: 10px;">
            <a href="<?php echo $baseUrl; ?>" aria-label="footer-logo"><img class="m-auto w-60" src="<?php echo $mediaUrl;?>logo/vaibhav_footer_logo_white.png" alt="fotter logo" width="198" height="74"></a>
           
        </div>
        <div class="col-12 ">
            <div class="row">
                <div class="col-6">
                    <h5 class="footer-title" aria-hidden="true">About Vaibhav</h5>
                    <ul>
                        <li>
                            <!-- <a href="<?php echo $baseUrl; ?>about-us"> -->
                            <a href="<?php echo $baseUrl; ?>business-overview">
                                About Us
                            </a>
                        </li>
                        <li>
                            <!-- <a href="<?php echo $baseUrl; ?>founder"> -->
                            <a href="<?php echo $baseUrl; ?>work-with-us">
                                Work with Us
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-rate">
                                Gold Rate
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>investor-relations">
                                Investor Relations
                            </a>
                        </li>
                      <!--   <li>
                            <a href="<?php echo $baseUrl; ?>work-with-us">
                                Work with Us
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>environment-page">
                                CSR
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-rate">
                                Gold Rate
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>blog">
                                Blog
                            </a>
                        </li> -->
                    </ul>
                </div>
                <div class="col-6">
                    <h5 class="footer-title" aria-hidden="true">Customer Services</h5>
                    <ul>
                        <li>
                            <a href="<?php echo $baseUrl; ?>emi">
                                EMI
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>privacy-policy">
                                Privacy Policy
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>shipping-policy">
                                Shipping Policy
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>refund-policy">
                                Refund Policy
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>exchange-policy">
                                Exchange Policy
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>terms-of-use">
                                Terms of Use
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>terms-and-conditions">
                                Terms & Conditions
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>contact">
                                Contact Us
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12">
            <h5 class="footer-title" aria-hidden="true">Our Branches</h5>
        </div>
        <div class="col-12">
            <div class="row">
                <div class="col-6">
                    <ul>
                        <li class="my-2 footer-subtitle">
                            <a href="<?php echo $baseUrl; ?>our-branches">
                                Andra Pradesh
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-visakhapatnam">
                                Visakhapatnam
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-gajuwaka">
                                Gajuwaka
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-kakinada">
                                Kakinada
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-rajahmundry">
                                Rajahmundry
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-anakapalle">
                                Anakapalli
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-srikakulam">
                                Srikakulam
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-parvathipuram">
                                Parvathipuram
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-bobbili">
                                Bobbili
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-gopalapatnam">
                                Gopalapatnam
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-vizianagaram">
                                Vizianagaram
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>andhrapradesh-tuni">
                                Tuni
                            </a>
                        </li>
                        
                    </ul>
                    <ul>
                        <li class="footer-subtitle my-2">
                            <a href="<?php echo $baseUrl; ?>our-branches">
                                Telangana
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>telangana-dilsukhnagar">
                                Dilsukhnagar
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>telangana-asraonagar">
                                A.S Rao Nagar
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6">
                    <h5 class="footer-title" aria-hidden="true">Popular Categories</h5>
                    <ul>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/earrings.html">
                                Gold Earrings
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/chains.html">
                                Gold Chains
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/rings.html">
                                Gold Rings
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/necklace.html">
                                Gold Necklace
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/mangalsutra.html">
                                Gold Mangalsutra
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/bangles.html">
                                Gold Bangles
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/harams.html">
                                Gold Harams
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-jewellery/women/vaddanam.html">
                                Gold Vaddanam
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>gold-coins.html">
                                Gold Coins
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="col-6">
                    <!--<ul>
                        <li class="footer-subtitle my-2">
                            <a href="<?php echo $baseUrl; ?>our-branches">
                                Telangana
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>telangana-dilsukhnagar">
                                Dilsukhnagar
                            </a>
                        </li>
                        <li>
                            <a href="<?php echo $baseUrl; ?>telangana-asraonagar">
                                A.S Rao Nagar
                            </a>
                        </li>
                    </ul>-->
                   
                </div>
            </div>
        </div>
    </div>
    <div class="color-white footer-bottom py-3 row bg-color-voilet">
        <div class="col-md-4 text-center">
            <h3>We Accept</h3>
            <div>
                <a href="#">
                    <img src="<?php echo $mediaUrl;?>wysiwyg/mastercard.png" alt="Vaibhav Online Payment" width="54" height="30">
                </a>
                <a href="#">
                    <img src="<?php echo $mediaUrl;?>wysiwyg/visa.jpg" alt="Vaibhav Online Payment" width="54" height="30">
                </a>
                <a href="#">
                    <img src="<?php echo $mediaUrl;?>wysiwyg/visa.jpg" alt="Vaibhav Online Payment" width="54" height="30">
                </a>
            </div>
        </div>
        <div class="align-items-end col-md-4 d-flex justify-content-center" style="margin-top: 10px;
    margin-bottom: 10px;">
            <p class="m-0" style="color: white;">© <?php echo date("Y"); ?> Vaibhav Jewellers. All Rights Reserved</p>
        </div>
        <div class="col-md-4 text-center">
            <h3>Connect with us</h3>
            <div class="d-flex justify-content-between m-auto w-75">
                <a href="https://www.facebook.com/vaibhavjewllers/" aria-label="Facebook">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="https://www.instagram.com/vaibhavjewellers" aria-label="Instagram">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="https://twitter.com/vaibhavjewelers" aria-label="Twitter">
                    <i class="fab fa-twitter"></i>
                </a>
               
                <a href="https://www.youtube.com/channel/UCT6Uv0OflrUVA2VDNk_C2Tw" aria-label="Youtube">
                    <i class="fab fa-youtube"></i>
                </a>
                <a href="https://api.whatsapp.com/send?phone=919177403000" aria-label="Whatsapp">
                    <i class="fab fa-whatsapp"></i>
                </a>
                <a href="https://in.pinterest.com/VaibhavJewellers/" aria-label="Pinterest">
                    <i class="fab fa-pinterest"></i>
                </a>
            </div>
        </div>
    </div>
</div>

<style>
    .bottom-nav-bar{
    max-width:75rem;
    width:100%;
    padding:0 2rem;
    margin:0 auto
}
.bottom-nav-container .bottom-nav{
    display:-webkit-box;
    display:flex;
    position:fixed;
    bottom:0;
    left:0;
    right:0;
    background-color:#6e2083;
    z-index:99;
    will-change:transform;
    -webkit-transform:translateZ(0);
    transform:translateZ(0);
    box-shadow:0 -2px 3px -2px #212121
}
.bottom-nav-container .bottom-nav-item{
    display:-webkit-box;
    display:flex;
    -webkit-box-orient:vertical;
    -webkit-box-direction:normal;
    flex-direction:column;
    -webkit-box-flex:1;
    flex-grow:1;
    -webkit-box-pack:center;
    justify-content:center;
    text-align:center;
    color:#fff;
    cursor:pointer
}
.bottom-nav-container .bottom-nav-link{
    display:-webkit-box;
    display:flex;
    font-size:13px;
    font-weight:700;
    align-items:center;
    padding:.8rem 0;
    color:#fff;
    justify-content:center
}
.bottom-nav-container .bottom-nav-link span{
    padding:0 5px
}
.bottom-nav-container .bottom-nav .active{
    color:#f7452f
}
.popover-content{
    position:fixed;
    width:100%;
    bottom:0;
    z-index:99999;
    background-position:center;
    background-size:cover;
    overflow:hidden;
    background-color:#d3d3d3;
    color:#fff;
    transition:all 1s;
    height:500px
}
.popover-content.close{
    bottom:0;
    height:0
}
.form-group .control-label{
    color:#000
}
.form-group{
    margin-bottom:2rem
}
.live-form-content{
    position:absolute;
    overflow-y:scroll;
    width:100%;
    display:flex;
    justify-content:center;
    align-items:end;
    bottom:5%
}
.video-intro-text{
    color:#000;
    padding:2rem
}
.btnclose{
    position:absolute;
    top:15px;
    z-index:9;
    right:15px;
    width:25px;
    height:25px;
    border:1px solid;
    border-radius:50%;
    line-height:10px;
    padding-left:6px;
    color:#fff!important;
    font-size:20px!important
}
.live-video-btn{
    border:0;
    width:100%;
    color:#fff;
    height:40px;
    font-weight:700;
    font-size:.8rem;
    text-transform:uppercase;
    /*background-color:#e8e8e8;
    background-color:transparent;*/
    font-size:15px!important
}
.bottom-nav-container .bottom-nav{
    z-index:999999
}
button.live-video-btn:active,button.live-video-btn:hover{
    background-color:transparent!important;
    color:#fff!important
}
.btnclose span{
    font-size:15px;
    color:#fe0000
}
#zsiq_float{
    padding-top:12px;
    visibility:hidden
}
.loader-icon{
    color:#fff;
    font-size:40px;
    text-indent:-9999em;
    overflow:hidden;
    width:1em;
    height:1em;
    border-radius:50%;
    margin:50px auto;
    position:relative;
    -webkit-transform:translateZ(0);
    -ms-transform:translateZ(0);
    transform:translateZ(0);
    -webkit-animation:load6 1.7s infinite ease,round 1.7s infinite ease;
    animation:load6 1.7s infinite ease,round 1.7s infinite ease
}
@-webkit-keyframes load6{
    0%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
    5%,95%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
    10%,59%{
        box-shadow:0 -.83em 0 -.4em,-.087em -.825em 0 -.42em,-.173em -.812em 0 -.44em,-.256em -.789em 0 -.46em,-.297em -.775em 0 -.477em
    }
    20%{
        box-shadow:0 -.83em 0 -.4em,-.338em -.758em 0 -.42em,-.555em -.617em 0 -.44em,-.671em -.488em 0 -.46em,-.749em -.34em 0 -.477em
    }
    38%{
        box-shadow:0 -.83em 0 -.4em,-.377em -.74em 0 -.42em,-.645em -.522em 0 -.44em,-.775em -.297em 0 -.46em,-.82em -.09em 0 -.477em
    }
    100%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
}
@keyframes load6{
    0%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
    5%,95%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
    10%,59%{
        box-shadow:0 -.83em 0 -.4em,-.087em -.825em 0 -.42em,-.173em -.812em 0 -.44em,-.256em -.789em 0 -.46em,-.297em -.775em 0 -.477em
    }
    20%{
        box-shadow:0 -.83em 0 -.4em,-.338em -.758em 0 -.42em,-.555em -.617em 0 -.44em,-.671em -.488em 0 -.46em,-.749em -.34em 0 -.477em
    }
    38%{
        box-shadow:0 -.83em 0 -.4em,-.377em -.74em 0 -.42em,-.645em -.522em 0 -.44em,-.775em -.297em 0 -.46em,-.82em -.09em 0 -.477em
    }
    100%{
        box-shadow:0 -.83em 0 -.4em,0 -.83em 0 -.42em,0 -.83em 0 -.44em,0 -.83em 0 -.46em,0 -.83em 0 -.477em
    }
}
@-webkit-keyframes round{
    0%{
        -webkit-transform:rotate(0);
        transform:rotate(0)
    }
    100%{
        -webkit-transform:rotate(360deg);
        transform:rotate(360deg)
    }
}
@keyframes round{
    0%{
        -webkit-transform:rotate(0);
        transform:rotate(0)
    }
    100%{
        -webkit-transform:rotate(360deg);
        transform:rotate(360deg)
    }
}
footer h5{
    font-size:16px;
    font-weight:600
}
footer li{
    font-size:14px;
    padding-bottom:10px
}
footer li a{
    color:#fff
}
@media (max-width:768px){
    footer .container{
        display:none
    }
    footer{
        width:100%;
        height:100px
    }
}
.footer-bottom h3{
    margin:0;
    border-bottom:1px solid;
    padding:10px;
    font-size:20px;
    margin-bottom:20px
}
.footer-bottom i{
    font-size:20px;
    color:#fff
}
.mobile-section .footer-logo p{
    font-size:10px;
    color:#6e2083;
    font-weight:500
}
.mobile-section .footer-top{
    background-color:#6e2083 !important;
}
.mobile-section .footer-top li a{
    color:#fff !important
}
.mobile-section .footer-title{
    color:#ffffff !important;
    display:inline-block;
    position:relative;
     margin-bottom: 20px;
    margin-top: 20px;
}
.mobile-section .footer-title::after{
    position:absolute;
    content:"";
    width:50%;
    height:2px;
    background-color:#fff !important;
    left:0;
    bottom:-5px
}
.mobile-section .footer-subtitle{
    font-weight:600;
    border-bottom:1px solid #6e2083;
    display:inline-block;
    padding:0
}

</style>