<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$welcomeMessage = $block->getWelcome();
?>
<style>
    .slick-slide .product-image-wrapper img {
    border: none !important;
border-radius: unset !important;
width: 100% !important;
height: 100% !important;
}
</style>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
            <?= $block->getBlockHtml('header.additional') ?>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>
 <div class="header mobile-section d-block d-sm-none">
    <div class="container-fluid d-flex header-top justify-content-between bg-color-voilet color-white py-2">
        <span class="d-flex align-items-center">
    <!-- <img src="http://assets.stickpng.com/images/580b57fcd9996e24bc43c543.png" alt=""> -->
    <span class="bg-whatsapp" alt=""></span> <!-- class="bg-whatsapp" alt="" style="width:20px;" -->
            +91 9177403000
        </span>
        <span>
            International Shipping Available
        </span>
    </div>

<script type="text/javascript">require(['bootstrap']);</script>