<?php 
   $_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
   $storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
   $currentStore = $storeManager->getStore();
   $baseUrl = $currentStore->getBaseUrl();
   $mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
   $linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
   
?>
<style>
   .header{
    background-color:#fff;
    z-index:99
}
.header .header-top img{
    width:20px;
    vertical-align:sub
}
.header .header-top{
    font-size:13px
}
.header a,.menu a{
    color:#6e2083;
    font-size:14px
}
.menu a{
    font-weight:600
}
.menu .category-items{
    width:75%
}
.header-height{
    height:148px
}
@media only screen and (max-width:1024px){
    .menu .category-items{
        width:100%
    }
    .header-height{
        height:125px
    }
}
.header .nav-search .dropdown-toggle::after{
    display:none
}
.header .search-dropdown{
    right:0;
    background-color:#fff;
    z-index:1;
    top:105%
}
.header .search-dropdown input{
    width:500px;
    border:1px solid #ccc;
    border-radius:4px;
    height:45px;
    background-color:#fff;
    padding:0 10px
}
.header .search-dropdown input::placeholder{
    color:#ccc;
    font-weight:500
}
.header .search-dropdown button{
    position:absolute;
    right:0;
    height:45px;
    background-color:#6e2083;
    color:#fff;
    font-weight:500;
    border:0;
    border-radius:2px;
    padding:0 14px
}
.header .search-suggestion{
    box-shadow:-4px 4px 8px -4px #000
}
.header .search-suggestion li{
    padding:5px;
    color:#000;
    font-size:12px
}
.header .search-suggestion li i{
    padding-right:5px
}
.header .search-suggestion>i{
    right:15px;
    top:15px
}
.header .search-suggestion li a{
    font-size:15px;
    color:#167ac6
}
@media only screen and (max-width:767px){
    #slide-navbar-collapse{
        position:fixed;
        top:35px;
        left:0;
        z-index:99;
        width:280px;
        height:100%;
        background-color:#ddd;
        overflow:auto
    }
    .menu-overlay{
        display:none;
        background-color:#fff;
        bottom:0;
        left:0;
        opacity:0;
        position:fixed;
        right:0;
        top:0;
        z-index:49
    }
}
.mobile-heading1{
    font-size:16px;
    background:url(<?php echo $mediaUrl;?>wysiwyg/title-underline.png) no-repeat center bottom;
    text-align:center;
    padding-bottom:22px;
    padding-top:10px;
    margin-top:0;
    font-weight:500;
    color:#6d1f82
}
.mobile-menu #slide-navbar-collapse{
    background-color:#fff
}
.mobile-menu li{
    padding:12px 20px;
    border-bottom:1px solid #848181;
    font-size:10px;
    display:flex!important;
    align-items:center;
    justify-content:space-between
}
.mobile-menu li i{
    font-size:18px;
    color:#6e2083
}
.mobile-menu li a{
    color:#848181;
    font-size:13px
}
.menu-close{
    position:absolute;
    top:5px;
    right:5px;
    z-index:3;
    font-size:17px
}
.mobile-search form{
    position:relative
}
.mobile-search form input{
    width:100%;
    border:2px solid #6e2083;
    border-radius:5px;
    padding:10px
}
.mobile-search form input::placeholder{
    color:#6e2083
}
.mobile-search form button{
    position:absolute;
    right:9px;
    top:50%;
    transform:translateY(-50%);
    background-color:transparent;
    border:0
}
.mobile-search form button i{
    font-size:24px;
    color:#6e2083
}
.mobile-section .fa-shopping-cart{
    font-size:26px
}
.mobile-section .section-1{
    background-color:#f7f7f7;
    border-top:2px solid #fad892
}
.mobile-section .section-1 .inner-tile img{
    width:70px
}
.mobile-section .section-1 .inner-tile img{
    padding-bottom:5px
}
.mobile-section .section-1 .inner-tile .inner-tile-title{
    font-size:13px
}
.mobile-section .navbar-header button{
    background-color:transparent;
    border:0;
    font-size:24px;
    color:#6e2083
}
.color-voilet{
    color:#6e2083;
    margin-left:50px;
    margin-bottom:10px
}
.mt-minus-15{
    margin-top:0
}
.logo{
    margin:2px -7px 10px 10px;
    max-width:100%;
    top:0;
    left:20px
}
.minicart-wrapper{
    margin-top:-10px
}
.minicart-wrapper .action.showcart:before{
    color:#6e2083
}
.page-footer .switcher .options ul.dropdown a,.page-header .switcher .options ul.dropdown a{
    color:#6e2083
}
.page-footer .switcher strong,.page-header .switcher strong{
    color:#6e2083;
    font-size:larger
}
.p-2{
    top:-3px
}
button:not(.primary){
    box-shadow:none!important
}
button:active,button:hover{
    background:0 0!important;
    border:1px solid transparent!important;
    color:#6e2083
}
.btn:hover{
    color:#6e2083;
    font-size:larger
}
.btn{
    font-size:1.3rem!important;
    color:#6e2083!important
}
.block-search input{
    left:0!important;
    top:-41px!important;
    height:45px
}
.block-search .control{
    border-top:1px solid #fff
}
.mobile-search form button{
    position:absolute;
    right:-7px;
    top:-3px;
    transform:translateY(-50%);
    background-color:transparent;
    border:0
}
.block.category.event,.breadcrumbs,.footer.content,.header.content,.navigation,.page-header .header.panel,.page-main,.page-wrapper>.page-bottom,.page-wrapper>.widget,.top-container{
    padding-left:0;
    padding-right:0
}
.block.newsletter .field .control:before{
    color:#fff;
    content:''
}
.columns .column.main{
    padding-bottom:0
}
.page-footer{
    margin-top:0;
    height:auto!important
}
.footer.content{
    border-top:0;
    padding-top:0
}
.nav-toggle:before{
    color:#6e2083
}
.ms-t{
    margin-top:10px
}
img.ms-t-w{
    max-width:200px
}
img.mst{
    max-width:70px
}
.dropdown-menu.mt-rate.show{
    left:-20px!important
}
.nav-open .nav-sections{
    background-color:#fff
}
.navigation{
    background:#fff
}
li.active.ms-u{
    padding-left:17px;
    margin-top:2.25rem;
    margin-bottom:-10px
}
.navigation .level0{
    font-size:1.35rem
}
.navigation .level0>.level-top{
    font-weight:100
}
.navigation .parent .level-top::after,.submenu>.parent>a.ui-corner-all::after{
    font-family:"Font Awesome 5 Pro"!important;
    color:#6e2083;
    content:"\f055"!important;
    font-weight:900!important
}
.navigation .parent .level-top.ui-state-active::after,.submenu>.parent>a.ui-corner-all.ui-state-active::after{
    content:"\f056"!important
}
.submenu>.parent>a::after{
    right:20%;
    position:absolute;
    font-size:1.6rem
}
.log_info .login_mob{
    margin-right:9px!important
}
.log_info a:active{
    padding:0!important
}
.log_info .login_mob{
    margin-right:9px!important
}
header .header-top{
    font-size:11px!important
}
.search-autocomplete{
    margin-top:18px!important
}
.sidebar .mts-category-list-custom>ul.o-list{
    height:auto
}
.sidebar .mts-category-list-custom>ul.o-list{
    display:block;
    padding:5px 15px 0 0
}
.sidebar .o-list li{
    list-style:none;
    border-bottom:none;
    padding-bottom:0!important
}
.sidebar .expand i,.sidebar .expanded i{
    color:#6d2080
}
.sidebar .expand,.sidebar .expanded{
    margin-top:10px
}
.navigation .level0.active>a:not(.ui-state-active),.navigation .level0.has-active>a:not(.ui-state-active){
    border-style:none
}
.old-price .price-label{
    display:none
}
.old-price,.old.price{
    color:#000
}
.dis_make_charge_actual .old-price{
    display:none
}
.dis_make_charge_old .special-price{
    display:none
}
.dis_make_charge_actual .price-box{
    display:inline-block
}
.dis_make_charge_actual .price{
    float:none;
    color:#ee853c!important
}
.catalog-product-view .price-box .dis-price{
    display:none
}
body .page-wrapper .v-navbar-fixed-htop{
    position:fixed;
    top:0;
    z-index:99
}
.page-wrapper{
    overflow-x:hidden
}
#sticky_header{
    position:fixed;
    top:22px;
    background-image:linear-gradient(to right top,#fff,#fff,#fff,#fff,#fff)
}
#sticky_header .logo img{
    width:55px!important;
    margin-left:0;
}
#sticky_header .block-search .control{
    border-top:0
}
#sticky_header .block-search input{
    left:0!important;
    top:0!important;
    height:35px;
    position:relative!important;
    font-size:10px
}
#sticky_header .mobile-search form button{
    right:-7px;
    top:16px;
    transform:none
}
#sticky_header #minicart_content{
    margin-top:17px;
    margin-left:10px;
    margin-bottom:0
}
#sticky_switcher_container{
    margin-left:15px;
    margin-top:17px
}
#sticky_header .mobile-search form button i{
    font-size:18px
}
#sticky_header .mobile-search form input{
    border-radius:50px;
    width:175px
}
#sticky_header .nav-toggle{
    left:0;
    position:relative;
    top:0
}
#sticky_header .logo{
    top:0;
    left:0;
    margin:0
}
#sticky_header .cart-icon,#sticky_header .switcher-trigger .currency_icon_span img{
    width:20px
}
#sticky_header .currency_text_span,#sticky_header .minicart-wrapper .action.showcart::before{
    display:none
}
#sticky_header .action.showcart .cart-icon,#sticky_header .switcher-trigger .currency_icon_span{
    display:inline!important
}
#sticky_header .minicart-wrapper .action.showcart .counter.qty{
    position:absolute;
    top:10px;
    left:8px;
    width:15px;
    height:15px;
    line-height:17px;
    font-size:12px;
    border-radius:15px;
    color:#fff;
    background-image:linear-gradient(to right,#e459e0,#9362f2)
}
#sticky_search_container .search-autocomplete{
    margin-top:-15px!important
}
#search-suggestion .nested{
    display:none
}
.minicart-items-wrapper{
    clear:both;
    height:max-content!important;
    border:1px solid #e5e5e5;
    border-right-color:#e5e5e5;
    border-right-style:solid;
    border-right-width:1px;
    border-left-color:#e5e5e5;
    border-left-style:solid;
    border-left-width:1px;
    margin:0 -20px 15px;
    border-left:0;
    border-right:0;
    overflow-x:auto;
    padding:15px
}
.block-minicart .price{
    float:none
}
.minicart-wrapper .block-minicart{
    padding:10px 20px
}
.minicart-wrapper .action.close{
    outline:0
}
.minicart-wrapper .action.close::before{
    vertical-align:middle!important
}
.block-minicart .items-total{
    font:500 14px/1.55 Lato,sans-serif;
    margin:0 10px 5px
}
.block-minicart .block-content .subtotal .label{
    font:500 14px/1.55 Lato,sans-serif;
    float:left
}
.block-minicart .action.primary{
    outline:0;
    background-color:#509ec4!important;
    border:1px solid #fff!important;
    padding:10px 20px!important;
    transition:all .5s ease;
    font:700 18px/1.35 Lato,Helvetica Neue,Helvetica,Arial,sans-serif!important;
    border-radius:3px
}
.logo img{
    margin-left:55px
}
.minicart-wrapper .action.showcart .counter.qty{
    border-radius:10px;
    width:10px;
    height:20px;
    padding-top:0;
    color:#fff;
    background-image:linear-gradient(to right,#e459e0,#9362f2);
    top:3px;
    position:absolute
}
@media screen and (max-width:767px){
    .mst-searchautocomplete__autocomplete{
        max-height:400px!important;
        overflow-x:hidden;
        overflow-y:scroll!important
    }
    #sticky_search_container .mst-searchautocomplete__autocomplete{
        min-width:300px!important;
        left:-66px!important
    }
    .mst-searchautocomplete__autocomplete .mst-searchautocomplete__index-title{
        font-size:10px;
        line-height:10px
    }
    .mst-searchautocomplete__index.magento_catalog_categoryproduct{
        display:none
    }
    .mst-searchautocomplete__autocomplete ul li a.title{
        font-size:10px
    }
    .mst-searchautocomplete__item.magento_catalog_product .description{
        display:none
    }
    .mst-searchautocomplete__item.magento_catalog_product .price,.mst-searchautocomplete__item.magento_catalog_product .title a{
        font-size:12px
    }
    .mst-searchautocomplete__index.magento_catalog_product ul li{
        margin:0 1.5rem;
        padding-bottom:0;
        padding-top:0
    }
    .page-wrapper{
        overflow:hidden
    }
    .page-header{
        width:100%
    }
    .bg-whatsapp{
        width:15px;
        height:15px;
        background:url(<?php echo $mediaUrl;?>css_sprites.png) -305px -300px
    }
}
@media (max-width:768px){
    .descon,.mobile_slider,.pdtcon{
        max-width:100%;
        flex:0 0 100%
    }
    .imgae_dese{
        max-width:100%;
        flex:0 0 100%;
        text-align:center
    }
    .prod-title{
        font-size:16px
    }
    .askques,header.header.position-fixed.w-100{
        display:none
    }
    .fz-small.text-violet.text-uppercase{
        width:50%;
        float:left
    }
    .rating-reivew .list-inline-item{
        font-size:13px
    }
    .removeadd{
        border-right:none
    }
    .text-uppercase.pin-check.text-violet{
        margin-top:1em;
        display:none
    }
    .shopping .try-on{
        display:none!important
    }
    .shopping.mb-4.text-uppercase{
        width:100%;
        float:left
    }
    .shopping .cart{
        float:left;
        width:47%;
        font-size:11px;
        margin-right:0;
        margin-left:2%;
        padding:1em .3em!important
    }
    .shopping .add-to-cart{
        float:left;
        width:47%;
        font-size:11px;
        margin-right:2%;
        padding:1em .3em!important
    }
    .customize{
        font-size:13px
    }
    .contact-section{
        width:100%;
        float:left
    }
    .contact-section .d-inline-block{
        width:36%;
        float:left;
        margin-right:0!important
    }
    .contact-us.d-inline-block{
        width:64%;
        float:left;
        padding-right:0!important;
        padding-left:0!important
    }
    .whatapp-no.text-green{
        display:none
    }
    .c-img{
        width:37px;
        float:left
    }
    .contact-us .align-top{
        float:left;
        width:15%;
        margin-left:6%
    }
    .need-help{
        font-size:13px
    }
    .contact-us .align-right{
        float:left;
        width:75%
    }
    .descon .info-tab,.pdtcon .info-tab{
        padding-right:5px;
        padding-left:0;
        border:none
    }
    .tab-pane .col{
        max-width:50%;
        flex:0 0 50%
    }
    #testimonial img{
        width:200px;
        max-width:100%
    }
    .future{
        text-align:center
    }
    .col.review-faq{
        padding:0;
        flex:0 0 100%
    }
    .review-faq.nav-link.border-0.active{
        background:#e1d7d8;
        color:#555!important;
        margin-left:9%;
        margin-right:3%
    }
    .review-faq .nav-link.border-0{
        margin-left:3%;
        margin-right:8%;
        font-size:.7rem
    }
    .review-faq{
        padding:0;
        background:#f4f4f4;
        padding-top:3%
    }
    .cancel,.send{
        border:0;
        color:#6f2d91;
        width:135px
    }
    .vaijew{
        font-size:25px
    }
    .pdt{
        width:100%;
        max-width:100%;
        flex:0 0 100%;
        padding-left:0;
        padding-right:0
    }
    .destr{
        width:100%;
        max-width:100%;
        flex:0 0 100%;
        padding-left:0;
        padding-right:0
    }
    .prod-tab{
        color:#fff;
        padding:.6rem 1rem .3rem 1rem;
        font-size:.8rem;
        letter-spacing:.5px;
        display:inline-block;
        background-color:#81aa6e;
        text-transform:capitalize;
        width:100%
    }
    .head2.text-uppercase.text-violet{
        padding-top:1em
    }
    .Exchange,.Refund,.dayretun,.emiopt,.international-shi,.jewellery,.shop-facilities{
        float:left
    }
    .inner-block-newsletter{
        background-color:#ccc;
        float:left;
        width:100%
    }
    .mobile_display{
        display:inherit!important
    }
    .first_one,.first_two{
        width:100%!important;
        float:left
    }
    .mobile_hide{
        display:none!important
    }
    .shop-facilities{
        float:left;
        margin:0!important;
        margin-top:1em!important
    }
    .first_one p,.first_two p{
        font-size:12px
    }
    .Refund img,.dayretun img{
        width:80%!important
    }
    .container.justify-content-between{
        display:initial!important
    }
    .advantage{
        margin-bottom:0!important
    }
    .subsri{
        width:auto!important
    }
    .justify-content-between h2{
        padding-left:1em
    }
    .news_letter{
        width:90%;
        margin:0 5%
    }
    #product_slider .carousel-indicators li{
        opacity:1;
        width:13px;
        height:13px;
        text-indent:0;
        border:1px solid #ebebeb;
        border-radius:50%;
        background:#eee
    }
    #product_slider .carousel-indicators li.active{
        background:orange
    }
    .destr,.dotshide,.recent_pdts:nth-child(n+3),.view_pdts:nth-child(n+3){
        display:none
    }
    #product_slider .carousel-indicators{
        bottom:-60px;
        margin-left:0;
        justify-content:center;
        margin-right:0
    }
    #product_slider .carousel-inner{
        margin-bottom:70px
    }
    .mobi_des{
        display:block;
        width:100%;
        margin-left:0;
        margin-top:1em
    }
    .mobi_des .destr{
        display:block!important
    }
    .view-recent{
        margin-bottom:0!important
    }
    .header-cover{
        height:20px
    }
    .prod-tab::after{
        content:'V';
        font-size:18px;
        float:right;
        transform:rotate(180deg);
        top:-6px;
        position:relative;
        font-weight:700;
        right:8px
    }
    .cms-video-shopping-page footer{
        width:100%;
        height:100%!important
    }
}
</style>
<script type="text/javascript">
   let images = [...document.querySelectorAll('.lazy-image')];

const interactSettings = {
  root: document.querySelector('.center'),
  rootMargin: '0px 0px 200px 0px' };


function onIntersection(imageEntites) {
  imageEntites.forEach(image => {
    if (image.isIntersecting) {
      observer.unobserve(image.target);
      image.target.src = image.target.dataset.src;
      image.target.onload = () => image.target.classList.add('loaded');
    }
  });
}

let observer = new IntersectionObserver(onIntersection, interactSettings);

images.forEach(image => observer.observe(image));
</script>
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
$welcomeMessage = $block->getWelcome();
?>
<?php switch ($block->getShowPart()):
    case 'welcome': ?>
        <li class="greet welcome" data-bind="scope: 'customer'">
            <!-- ko if: customer().fullname  -->
            <span data-bind="text: new String('<?= $block->escapeHtml(__('Welcome, %1!', '%1')) ?>').replace('%1', customer().fullname)">
            </span>
            <!-- /ko -->
            <!-- ko ifnot: customer().fullname  -->
            <span data-bind='html:"<?= $block->escapeHtml($welcomeMessage) ?>"'></span>
            <?= $block->getBlockHtml('header.additional') ?>
            <!-- /ko -->
        </li>
        <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "customer": {
                            "component": "Magento_Customer/js/view/customer"
                        }
                    }
                }
            }
        }
        </script>
    <?php break; ?>

    <?php case 'other': ?>
        <?= $block->getChildHtml() ?>
    <?php break; ?>

<?php endswitch; ?>
 <div class="header mobile-section d-block d-sm-none">
    <div style="<?php if ($request->getFullActionName() != 'cms_index_index' ) { echo "position: fixed;z-index: 999;"; }
?>" class="container-fluid d-flex header-top justify-content-between bg-color-voilet color-white py-2">
        <a rel="nofollow" target="_blank" href="https://api.whatsapp.com/send?phone=919177403000" style="color: #fff"><span class="d-flex align-items-center">
            <span class="bg-whatsapp"></span>
            +91 9177403000
        </span></a>
        <span>
            International Shipping Available
        </span>
    </div>

<script type="text/javascript">require(['bootstrap']);</script>

<?php if ($request->getFullActionName() == 'onestepcheckout_index_index') { ?>
    echo '<style>.minicart-wrapper{display:none;}</style>';
<?php }?>