
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Block\Account\AuthorizationLink');

$cus_Session = $objectManager->get('Magento\Customer\Model\Session');
?>

<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?= /* @escapeNotVerified */ $groupCss ?>">
        <?php $layout = $block->getLayout();?>
            <?php if ($customerSession->isLoggedIn() != true) {?>
                <ul id="ui-id-1" class="ui-menu ui-widget ui-widget-content ui-corner-all">
                    <span class="menu-close"><i class="fas fa-times"></i></span>
                    <li class="active ms-u"><a href="#">HI GUEST,</a></li><br><hr>
                    <li class="log_info"><a class="login_mob" href="<?php echo $this->getUrl('customer/account/login'); ?>">LOGIN</a><span class="ver_line"></span>   
                    <a class="account_mob" href="<?php echo $this->getUrl('customer/account/create'); ?>">SIGN UP</a></li>
                </ul>
            <?php } else { ?> 
                <ul id="ui-id-1" class="ui-menu ui-widget ui-widget-content ui-corner-all">
                    <span class="menu-close"><i class="fas fa-times"></i></span>
                    <li class="active"><a href="#">HI, <?php echo $cus_Session->getCustomer()->getName();; ?></a></li>
                    <li class="log_info"><a class="login_mob" href="<?php echo $this->getUrl('customer/account/logout'); ?>">LOGOUT</a>
                        &nbsp&nbsp&nbsp&nbsp<span class="ver_line"></span>&nbsp&nbsp&nbsp&nbsp  
                    <a class="account_mob" href="<?php echo $this->getUrl('customer/account'); ?>">MY ACCOUNT</a></li>
                </ul>

        <?php } ?>

        <?= /* @escapeNotVerified */ $layout->renderElement('store.menu'); ?>
    </div>
<?php endif; ?>


<!-- <div class="active"><a href="#">HI GUEST,</a></div>
    <div class="log_info" >
        <a class="login_mob" href="#">LOGIN</a>
        <span class="ver_line"></span>
        <a class="account_mob" href="#">MAKE AN ACCOUNT</a>
    </div> -->