<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>

<?php

$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();

date_default_timezone_set('Asia/Kolkata');

$currentTime = date('h:i:A');
$currenDate= date('d.m.Y');
$str= explode(":",$currentTime);
list($hr, $min, $timestamp) = $str; 
$live_sku = "LIVE_SHOPPING";
$curTime=date('Y-m-d H:i:s', time());
$datetime = new DateTime($curTime);
$currenDateTime = $datetime->format(DateTime::ATOM);
$product_url= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);


if ($request->getFullActionName() == 'catalog_category_view' || $request->getFullActionName() == 'catalogsearch_result_index' ) {
?>
<div class="bottom-nav-container" style="">
  <div class="bottom-nav-bar">
    <nav class="bottom-nav">
       <div class="bottom-nav-item sorfilter"style="border-right: 1px solid #fff;">
        <div class="bottom-nav-link">
          <span>SORT</span>
        </div>
      </div>
       <div class="bottom-nav-item filtersort"style="border-right: 1px solid #fff;">
        <div class="bottom-nav-link">
          <span>FILTER</span>
        </div>
      </div>
      <div class="bottom-nav-item">
        <div class="bottom-nav-link">
           <img src="<?php echo $mediaUrl;?>message_icon.png" width="40" height="35" alt="message_icon"/>
        </div>
      </div>
    </nav>
  </div>
  <?php if($request->getFullActionName() != 'onestepcheckout_index_index'){ ?>
    <div id="popover-content" class="popover-content close" style="bottom: 50px;">
      <button type="button" class="btn btn-default btnclose" id="btnclose">x</button>
      <img src="<?php echo $mediaUrl;?>live-shop--360x500mobile.jpg" class="w-100" width="330" height="157" alt="video-shop">
      <div class="live-form-content" style="display: block; bottom: 0;">
      <form class="form-horizontal" enctype="multipart/form-data"  id="live-form" method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
         <input name="type" value="product"  type="hidden" />
                         <input name="hrs" value="<?php echo $hr; ?>"  type="hidden" />
                         <input name="min" value="<?php echo $min; ?>"  type="hidden" />
                         <input name="meri" value="<?php echo $timestamp; ?>"  type="hidden" />
                         <input name="language" value="any"  type="hidden" />
                         <input name="fullname" value="Guest"  type="hidden" />
                         <input name="email" value="dummyguest@gmail.com"  type="hidden" />
                         <input name="product" value="<?php echo $product_url; ?>"  type="hidden" />
                         <input name="remarks" value="Dummy"  type="hidden" />
                         <input name="takedate" value="<?php echo $currenDateTime; ?>"  type="hidden" />
                         <?php echo $block->getBlockHtml('formkey')?>
<fieldset>
<div class="form-group loader-block" style="display: none;margin-bottom: 0px;">
   <div class="row success-block" style="flex-direction: column;justify-content: center;align-items: center;">
  <div class="col-12" style="color:#8bd8bd">
   <div class="loader-icon">Loading...</div>
  </div>
  </div>
  </div>
  
<div class="form-group success-block" style="margin-bottom: 5rem;display: none;">
  <div class="row success-block" style="flex-direction: column;justify-content: center;align-items: center;">
  <div class="col-12" style="color:#8bd8bd">
    <h3 style="text-align: center;">Your details has been submitted successfully</h3>
    <h5 style="text-align: center;">Our team will contact very soon</h5>
  </div>
  </div>
</div>
<div class="form-group form-block">
  <div class="row" style="flex-direction: column;justify-content: center;align-items: center;">
    <div class="col-8">
  <input  id="live_mobile" style="border-radius: 10px;" maxlength="12" name="mobile" type="tel" placeholder="*Mobile No" class="form-control input-md required-entry in">
    <span id="errmsg" style="color: red;text-align:center;"></span>
  </div>
  <div class="col-4">
 <div style="text-align: center;">
<button type="submit" id="live_submit" style="color: #fff !important;" class="btn btn-primary live-video-btn">Submit</button>
</div>
  </div>
  </div>
</div>
</fieldset>
</form>
</div>
    </div>

 <?php }?>
</div>


<?php } else  { ?>
<style>
   
    .checkout-index-index .logo {
    margin-left: 40px;
}
</style>
<div class="bottom-nav-container" style="">
  <div class="bottom-nav-bar">
    <nav class="bottom-nav">
       <?php if($request->getFullActionName() != 'onestepcheckout_index_index'){ ?>
        <div class="bottom-nav-item active">
          <div  id="live-shop" class="bottom-nav-link" style="border-right: 1px solid #fff;">
            <img src="<?php echo $mediaUrl;?>live_shopping_icon.png" width="35" height="31"/>
            <span>LIVE SHOPPING</span>
          </div>
        </div>
      <?php } ?>

      <?php

       if ($request->getFullActionName() == 'catalog_product_view') {
       ?>
        <?php if($request->getFullActionName() != 'onestepcheckout_index_index'){ ?>
          <div class="bottom-nav-item"style="border-right: 1px solid #fff;" onclick="location.href='/try-at-home/';">
            <div class="bottom-nav-link">
               <img src="<?php echo $mediaUrl;?>try_on_icon.png" width="25" height="21"/>
              <span>TRY AT HOME</span>
            </div>
          </div>
        <?php } ?>
       <?php
} else {
       ?>
       <?php if($request->getFullActionName() != 'onestepcheckout_index_index'){ ?>
          <div class="bottom-nav-item"style="border-right: 1px solid #fff;" onclick="location.href='/try-on/';">
          <div class="bottom-nav-link">
             <img src="<?php echo $mediaUrl;?>try_on_icon.png" width="25" height="21"/>
            <span>TRY ON</span>
          </div>
        </div>
      <?php }?>
       <?php
}
       ?>
      <div class="bottom-nav-item">
        <div class="bottom-nav-link">
           <img src="<?php echo $mediaUrl;?>message_icon.png" width="40"height="35" />
        </div>
      </div>
    </nav>
  </div>
   <?php if ($request->getFullActionName() == 'onestepcheckout_index_index') { ?>
    <div id="popover-content" class="popover-content close" style="bottom: 50px; display:none !important">
        <?php }else{ ?>
        
        <div id="popover-content" class="popover-content close" style="bottom: 50px;">
        
        <?php } ?>
        
        
      <button type="button" class="btn btn-default btnclose" id="btnclose">x</button>
      <img src="<?php echo $mediaUrl;?>live-shop--360x500mobile.jpg" class="w-100" width="330" height="157" alt="video-shop">
      <div class="live-form-content" style="display: block; bottom: 0;">
      <form class="form-horizontal" enctype="multipart/form-data"  id="live-form" method="POST"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
          <input name="type" value="product"  type="hidden" />
                         <input name="hrs" value="<?php echo $hr; ?>"  type="hidden" />
                         <input name="min" value="<?php echo $min; ?>"  type="hidden" />
                         <input name="meri" value="<?php echo $timestamp; ?>"  type="hidden" />
                         <input name="language" value="any"  type="hidden" />
                         <input name="fullname" value="Guest"  type="hidden" />
                         <input name="email" value="dummyguest@gmail.com"  type="hidden" />
                         <input name="product" value="<?php echo $product_url; ?>"  type="hidden" />
                         <input name="remarks" value="Dummy"  type="hidden" />
                         <input name="takedate" value="<?php echo $currenDateTime; ?>"  type="hidden" />
                         <?php echo $block->getBlockHtml('formkey')?>
<fieldset>
<div class="form-group loader-block" style="display: none;margin-bottom: 0px;">
   <div class="row success-block" style="flex-direction: column;justify-content: center;align-items: center;">
  <div class="col-12" style="color:#8bd8bd">
   <div class="loader-icon">Loading...</div>
  </div>
  </div>
  </div>
  
<div class="form-group success-block" style="margin-bottom: 5rem;display: none;">
  <div class="row success-block" style="flex-direction: column;justify-content: center;align-items: center;">
  <div class="col-12" style="color:#8bd8bd">
    <h3 style="text-align: center;">Your details has been submitted successfully</h3>
    <h5 style="text-align: center;">Our team will contact very soon</h5>
  </div>
  </div>
</div>
<div class="form-group form-block">
  <div class="row" style="flex-direction: column;justify-content: center;align-items: center;">
    <div class="col-8" style="padding-bottom: 5px;">
  <input  id="live_mobile" style="border-radius: 10px;" name="mobile" type="tel" placeholder="*Mobile No" class="form-control input-md required-entry in">
  </div>
  <div class="col-4">
 <div style="text-align: center;">
<button type="submit" id="live_submit" style="color: #fff !important;" class="btn btn-primary live-video-btn">Submit</button>
</div>
  </div>
  </div>
</div>
</fieldset>
</form>
</div>
    </div>
</div>



<?php } ?>

 <script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
 $(document).ready(function(){
  var w = Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    var h = Math.max(document.documentElement.clientHeight, window.innerHeight || 0);
    $("html, body").css({"width":w,"height":h});
  $('#live-shop,#btnclose').click(function() {
  $('.popover-content').toggleClass('close');
});
  $(document).on('focus', 'input', function() {
    document.querySelector('input').scrollIntoView();
});

var dataForm = $('#live-form');
   dataForm.mage('validation', {});

   jQuery("#live-form").submit(function(e){
    e.preventDefault();

var status = dataForm.validation('isValid'); //validates form and returns boolean
if(status){
  $(".form-block").hide();
  $(".loader-block").show();
   setTimeout(function(){
             $(".loader-block").hide();
             $(".success-block").show();
}, 3000);
  var fd = new FormData($('form#live-form')[0]);
 $.ajax({
    type: "POST",
    url: "<?php echo $block->getUrl('videoform/index/livevideoshop'); ?>",
    data : $(this).serialize(),
    success: function (data) {
        if (data == "success") {
            $('#live-form')[0].reset();
            setTimeout(function(){
            $(".success-block").hide();
            $(".form-block").show();
}, 5000); 
            
        } else {
          $(".success-block").hide();
            $(".form-block").show();
           alert(data);
        }
    },
    error: function (jqXHR, textStatus, errorThrown) {
                   // error handling
    }
});
}else{
return false;

}

   });

}); 

   function setInputFilter(textbox, inputFilter) {
  ["input", "keydown", "keyup", "mousedown", "mouseup", "select", "contextmenu", "drop"].forEach(function(event) {
    textbox.addEventListener(event, function() {
      if (inputFilter(this.value)) {
        this.oldValue = this.value;
        this.oldSelectionStart = this.selectionStart;
        this.oldSelectionEnd = this.selectionEnd;
      } else if (this.hasOwnProperty("oldValue")) {
        this.value = this.oldValue;
        this.setSelectionRange(this.oldSelectionStart, this.oldSelectionEnd);
      } else {
        this.value = "";
      }
    });
  });
}
setInputFilter(document.getElementById("live_mobile"), function(value) {
  return /^-?\d*$/.test(value); });
}); 
</script>
<style type="text/css">
    .bottom-nav-container{
        display: block !important;
    }
</style> 
 <?php if($request->getFullActionName() == 'onestepcheckout_index_index'){ ?>
  <style type="text/css">
    .product-name {
      /* display: inline-block; */
      width: 100%;
      /* white-space: nowrap; */
      overflow: hidden !important;
      text-overflow: ellipsis;
      padding: 0 10px 10px;
      text-align: center;
      line-height: 1.2;
  }
  .three-columns-new-osc #one-step-checkout-form .checkout-review-load .data-table td h2 {
      font-size: 14px;
  }
  #one-step-checkout-form .checkout-review-load .data-table td h2 {
      display: block;
  }
  #one-step-checkout-form .checkout-review-load .data-table td h2 {
      /* font-size: 17px; */
      color: #363636;
      text-transform: none;
      margin-bottom: 0;
      /* display: table-cell; */
      vertical-align: top;
      padding-left: 8px;
  }
  
      .popover-content {
         background-image: url(<?php echo $mediaUrl;?>wysiwyg/homepage_images/mobile/Live_video_shopping.jpg) !important;
         height: auto !important;
       }

</style>

<?php } ?>