<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base ct-title" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');
if ($request->getFullActionName() == 'catalog_category_view') {
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    $catTitle = $category->getData('title_h1');
    $title = '<span class="base ct-title" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $catTitle . '</span>';
}

?>

    <?php if ($title): ?>

    <div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?> category-heading">
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
            <?php endif; ?>>
            <?= /* @escapeNotVerified */ 
                $title
            ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
    <?php endif; ?>

