<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>



<nav class="navigation" data-action="navigation">
	<div class="sidebar">
		<div class="c-sidebar c-sidebar--categories">
	<div class="mts-category-list-custom">
  <?php echo $this->getLayout()->createBlock("Sebwite\Sidebar\Block\MobileSidebar")->setTemplate("Sebwite_Sidebar::sidebar.phtml")->toHtml(); ?>
</div>
</div>
</div>
</nav>

 