<!--<div class="gold_coin_wrapper fixed_pos" style="position: fixed; bottom: 50px; width: 100%; left: 0; z-index: 99998; box-shadow: 0px -2px 5px 0px rgba(50, 50, 50, 0.43); background-color: #fff; transition: all .3s ease-in-out;">-->
<!--<div class="offer_sticky"><a class="gtm_home_sticky_offer_banner" href="diamond-jewellery/women/rings.html"> <img data-pagespeed-no-transform src="https://www.vaibhavjewellers.com/pub/media/Mobile-Sticky-banner.jpg" alt="Valantine-offer"> </a></div>-->
<!--<div class="close__" style="position: absolute; top: 5px; right: 5px; width: 25px; height: 25px; border-radius: 25px; border: 1px solid #eee; display: flex; justify-content: center; align-items: center; background-color: #ffe9ec; cursor: pointer;"><img src="https://www.vaibhavjewellers.com/pub/media/close.png"></div>-->
<!--</div>-->

<!--<script type="text/javascript">
//     require([
//         'jquery'
//     ], function ($) {
//       $(".close__").click(function(){
//         $(this).parent(".gold_coin_wrapper").remove();
//     });
//     $(document).scroll(function () {
//   var y = $(this).scrollTop();
//   if (y > 500) {
//       $('.offer_sticky').fadeIn();
//   } else {
//       $('.offer_sticky').fadeOut();
//   }

// });
//     });
<!--</script>-->