<style type="text/css">
	body {
	font-size: 15px;
}
	.block-collapsible-nav .content {
    background: #fff;
    padding: 15px 0 0;
}

.block-collapsible-nav .item {
   margin: 10px 0 0;
    padding-top: 10px;
    border-top: 1px dashed #999;
}
.block-collapsible-nav .item a:hover {
    color: #121212;
    text-decoration: none;
}
.block-collapsible-nav .item a:visited {
    color: #999;
    text-decoration: none;
}
.block-collapsible-nav .item a {
    color: #999;
    text-decoration: none;
    padding:0;
    font-size: 15px;
}
.block-collapsible-nav .item:first-child {
	    margin-top: 0;
    border-top: 0;
    padding-top: 0;
}
.block-collapsible-nav .item a:hover {
    background: none;
    color: #121212;
    text-decoration: none;
}

.block-collapsible-nav .item.current a, .block-collapsible-nav .item.current>strong {
    border-color: #999;
    color: #121212;
    font-weight: 600;
}

.items .item:nth-child(2) {
	display: none;
}
.items .item:nth-child(4) {
	display: none;
}
.block-collapsible-nav-content .nav {
display: block;
}
.block-collapsible-nav .item.current a {
    border: none;
}
main#maincontent {
    margin-left: auto;
    margin-right: auto;
    max-width: 1200px !important;
    box-sizing: border-box;
}
.block-title strong , .box-title span  {
	font-size: 16px !important;
}
.box-content address {
	font-size: 15px;
}

.account .column.main>.table-wrapper, .account .column.main>.form-address-edit, .account .column.main>.form, .account .column.main .block {
	background-color: #fff;
    padding: 20px;
    box-shadow: 0px 0px 1px #8c8686;
    -moz-box-shadow: 0px 0px 1px #8c8686;
    -webkit-box-shadow: 0px 0px 1px #8c8686;
    -o-box-shadow: 0px 0px 1px #8c8686;
    -ms-box-shadow: 0px 0px 1px #8c8686;
    -webkit-border-radius: 0;
    -moz-border-radius: 0;
    border-radius: 0;
    margin-bottom: 20px;
}
legend.legend span {
    font-size: 16px !important;
}

.account .column.main>.table-wrapper.reviews {
    padding: 0px;
}

.table.table-reviews tbody tr td.date,.table.table-reviews thead tr th.date {
width: 25%;
}
.table-wrapper.reviews {
    box-shadow: 0 2px 8px rgba(59, 43, 91, 0.3) !important;
}
.table.table-reviews thead th {
    border-bottom: 0;
}
.table.table-reviews tbody tr td.item, .table.table-reviews thead tr th.item {
    width:45%;
}
.table.table-reviews tbody tr td.actions, .table.table-reviews thead tr th.actions {
    width:10%;
}
.table.table-reviews .description {   
    display: table-cell;
    }
    .view-more {
    background: #b272d3 !important;
    color: #fff !important;
    font-size: 12px;
    box-shadow: 0 0 10px 2px rgba(0, 0, 0, 0.1) !important;
    border-radius: 2px !important;
    padding: 7px 14px !important;
}
.customer-account-index .product-name{
    font-size:1rem;
}
.wishlist-index-index .product-item-inner {
    background:none;
    box-shadow: none;
    top:0;
   
        border: none !important;
    text-align: right;
    padding-right: 18px !important;
}
.wishlist-index-index a.btn-remove.action.delete {
    color: #000;
}
.wishlist-index-index .products-grid .product-item-info:hover, .products-grid .product-item-info.active {
    margin:0px;
    padding:0px;
    }
    .products-grid.wishlist .product-item-name {   
    padding: 0px 10px;
}
.review-customer-index .limiter{
display:none;
}
.customer-address-index .box-billing-address .box-content p {
    /*font-size: 1rem;*/
    font-size: 14px !important;
    padding-bottom: 10px;
}
.customer-address-index .box-billing-address .box-content a {
    font-size: 14px;
    color: #b014bf;
}
.add-new-address-btn {
    margin-bottom: 0;
    background-color: #b013bf !important;
    color: white !important;
    border-radius: 4px;
}


.customer-account-createpassword #maincontent{
    max-width: 600px !important;
    margin:0px auto;
        padding: 20px 20px;
}
.customer-account-createpassword  button.action.submit.primary{
    background-color: #6e2083;
    border: 1px solid #6e2083;
    letter-spacing: 1px;
    font-size: 1.3rem;
    margin-left: 170px;

}
.customer-account-createpassword .page-title-wrapper {
    text-align: center;
    background-image: linear-gradient(to right top, #ecd0f4, #ead8f5, #e9e0f4, #eae7f1, #eeeeee);
    padding-top: 10px;
    height: 70px;
   
}

/**RMA****/

.amasty_rma-account-history .column.main {
    font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif; 
}

.amasty_rma-account-history .amreturn-btn,.amasty_rma-account-newreturn .amreturn-btn {
    margin-left: 10px !important; 
    padding: 7px 21px !important;
    border: 1px solid #6e2083 !important;
    color: #fff !important;
    background: #6e2083 !important;
    transition: background-color 0.4s !important;
} 
.amasty_rma-account-history .col {
   width:0%;
} 
.amasty_rma-account-newreturn .amrma-link-cancel {
    background-color: lightcoral;
    padding: 7px;
    color: #fff;
    /* padding: 10px; */
    border-radius: 5px;
}
.amasty_rma-account-newreturn h1.page-title{
    padding-bottom:15px;
}
.amasty_rma-account-view .col {
   width:0%;
}

.amasty_rma-account-history .table thead th, .amasty_rma-account-view .table thead th {
    border-bottom: 0;
}
.amrma-items-table .table thead th {
    border-top: 0;
}

._keyfocus *:focus, input:not([disabled]):focus, textarea:not([disabled]):focus, select:not([disabled]):focus {
    box-shadow: 0 4px 8px rgba(0, 62, 176, 0.1);
}

.amasty_rma-account-history .amrma-status {
    font-size: 9px;
}
.amasty_rma-account-view button.amrma-send{
    background: #6e2083;
}
.amasty_rma-account-view button:hover {
    background: #e1e1e1 !important;
    border: 1px solid #cccccc !important;
    color: #333333 !important;
}
.amasty_rma-account-history span.amrma-status.-pending {
    padding: 5px;
    }
 .amasty_rma-account-history .amreturns-order-select {
    border: 2px solid #b3b0d1;
    }
    .amasty_rma-account-view .amrma-header{
    font-size: 1.5rem;
}
.amasty_rma-account-view .amreturn-btn{
    background: #6e2083;
}
.amasty_rma-account-newreturn .amrma-image{   
    width: 240px;
    height: 180px;
}
.amasty_rma-account-newreturn .amrma-product-information { 
    margin-top: 30px;
}
.amasty_rma-account-newreturn .amrma-products-table {
    margin-bottom: 20px;
}
.amasty_rma-account-newreturn .amrma-bank-details{
        margin-bottom: 20px;
}
.amasty_rma-account-view .amrma-table-container {
    margin-bottom: 20px;
}
.amasty_rma-account-view .account .table-wrapper{
    margin-top: 0;
}
.amasty_rma-account-newreturn .amrma-return-select .amrma-title{
    font-size: 15px;
    margin-bottom:5px;
}
.amasty_rma-account-view span.amrma-status{
    padding-top: 2px;
}

</style>