<?php 
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$linkUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);

?>

 <div class="row" ><!-- style="background-color: #f8f0fd;" -->
          <img class="" style="margin-left: 100px;" width="548" height="603" src="<?php echo $mediaUrl;?>vaibhav_advantage/login-page-desktop.jpg" alt="shop-facilities">
</div>
