       
        <div class="row" ><!-- style="background-color: #f8f0fd;" -->
          <img class="" style="margin-left: 100px;" src="<?php echo $this->getUrl('pub/media/vaibhav_advantage');?>Login-Page-Image---Desktop.jpg" alt="shop-facilities">
           <!-- <div class="col-1">
           </div>
           <div class="col-10">
            <div class="advantage">
                <h3 class="mb-3 vaijew">VAIBHAV ADVANTAGE</h3>
                <p>we believe in making jewellery shopping fun and spontaneous that is why we take care of everything else</p>
                <div class="divider"></div>
            </div>
            <div class="inner-block text-center">
                <div class="m-auto px-5 vaibhav_img">

                    <div class="row">
                        <span class="col-3 p-2 dayretun">
                            <img class=""  src="<?php //echo $this->getUrl('pub/media/');?>store-fac-1.png" alt="shop-facilities">
                            <p>15 Days<br>Returns</p>
                             <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-2.png" alt="shop-facilities">
                            <p>Lifetime<br>Exchange</p>
                        </span>
                         <span style="display: grid;" class="col-6 align-items-center shop-facilities">
                           <img class="w-100" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-4.jpg" alt="shop-facilities">
                         </span>
                         <span class="col-3 p-2 Refund">
                          <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-5.png" alt="shop-facilities">
                          <p>100%<br>Refund</p>
                           <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-6.png" alt="shop-facilities">
                            <p>EMI<br>Option</p>
                        </span>   
                    </div>
                
                    <div class="row">
                        <span class="col-3 p-2 jewellery">
                            <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-3.png" alt="shop-facilities">
                            <p>Certified<br>Jewellery</p>
                        </span>

                        <span class="col-6 p-2 emiopt">
                            <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-6.png" alt="shop-facilities">
                            <p>EMI</p>
                        </span>
                        <span class="col-3 p-2 international-shi">
                            <img class="" src="<?php //echo $this->getUrl('pub/media/');?>store-fac-7.png" alt="shop-facilities">
                            <p>International<br>Shipping</p>
                        </span>
                  </div>
                </div>
            </div>
         </div>
        <div class="col-1"></div> --> 
       </div>
