<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_OneStepCheckout
 * @author    Extension Team
 * @copyright Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php /** @var \Bss\OneStepCheckout\Block\Adminhtml\Order\GiftWrapInfo $block */ ?>
<?php // @codingStandardsIgnoreFile ?>
<div id="order-gift_wrap">
    <?= $block->getChildHtml('gift_wrap_checkbox') ?>
</div>

<script>
    require(['prototype'], function () {
        giftWrapOrder = {
            saveData: function () {
                var data = order.serializeData('order-gift_wrap');
                order.loadArea(['totals', 'billing_method', 'gift_wrap'], true, data.toObject());
            },

            init: function () {
                var self = this;
                $('gift-wrap').observe('click', function (e) {
                    self.saveData();
                });
            }
        }
        giftWrapOrder.init();
    });
</script>
