<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_OneStepCheckout
 * @author    Extension Team
 * @copyright Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php /** @var \Bss\OneStepCheckout\Block\Adminhtml\Order\GiftWrapCheckbox $block */ ?>
<?php // @codingStandardsIgnoreFile ?>
<div class="admin__field admin__field-option">
    <input id="use-gift-wrap-action" type="hidden" name="use_giftwrap_action" value="1" class="admin__control-checkbox">
    <input id="gift-wrap" type="checkbox" name="giftwrap" <?php if (!$block->isDisable()): ?>disabled<?php endif;?> <?php if ($block->isChecked()): ?>checked<?php endif;?> class="admin__control-checkbox">
    <label class="admin__field-label"><?= $block->getLabel() ?></label>
</div>