<form data-mage-init='{"validation": {}}' class="form tryform" style="background-color:#e2dede;margin: 0px auto;border-color: #d4af3700;" id="tryathomes-form" method="post" autocomplete="off" action="<?php echo $this->getUrl('tryathome/index/index'); ?>">
<fieldset class="fieldset" style="margin-bottom: 20px;">
<div class="trymain">
<div class="nfaq" style="width:100%;padding: 0px 0px 0px;">
<button class="newtryaccordion" style="background-color: #6e2083;color: white;">
 Gold Rate Update Via SMS and Email
    </button>

<div class="newtrypanel" style="max-height: 600px;">
<div class="field name required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px; margin-top: 10px;">
    <input class="input-text" type="text" placeholder="Customer Name" name="sname" data-validate="{required:true}" /></div>
</div>
<div class="field required" style="width: 90%; margin: auto;display:none">
           <label for="area" class="label"><span><?php echo __('Select Area') ?></span></label>
           <div class="control" style="border: none;display: flex;	flex-direction: row;justify-content: flex-start;break-before: always;margin: 0 0 1em 0;">
           <div style="width: 50%;line-height: 31px;">
           <div style="margin: 0 1.81em 0 0">
           <label>
           <input type="radio" name="area" value="Kakinada">
           Kakinada
           </label>
           </div>
           <div style="margin: 0 1.81em 0 0"><label><input type="radio" name="area" value="Rajahmundry">Rajahmundry</label></div>
           </div>
           <div style="line-height: 31px;">
           <div style="margin: 0 1.81em 0 0"><label> <input type="radio" name="area" value="A.S Rao Nagar" >A.S Rao Nagar</label></div>
           <div style="margin: 0 1.81em 0 0"><label><input type="radio" name="area" value="Dilsukhnagar" >Dilsukhnagar</label></div>
           </div>
           </div>
</div>
<div class="field email required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px;">
    <input  class="input-text emailcontact" title="Email" name="semail" type="email" value="" placeholder="Enter Your Email Address" data-validate="{required:true, 'validate-email':true}" data-gaconnector-tracked="true" /></div>
</div>
<div class="field telephone required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px;">
								<input name="mobile" type="text" class="input-text in mobile" placeholder="Mobile Number *" />
								<input type="hidden" name="verify" class="txt_verify" tabindex="1000" value="0" data-validate="{required:true, 'validate-upload-design-verify':true}" data-msg-required="Please enter Mobile" aria-required="true" aria-invalid="true" aria-describedby="verify-error" /> <span class="customized-errmsg" style="color: red; text-align:center;"></span>
								<div class="verifyErr"  style="display:none">
									<?php echo __( "Mobile verification is pending");?>
								</div>
								<div class="RepeatErr"  style="display:none">
									<?php echo __( "Mobile number already taken");?>
								</div>
								<div class="ValidErr"  style="display:none">
									<?php echo __( "Please Enter Mobile Number");?>
								</div>
								<div class="ValidErrt"  style="display:none">
									<?php echo __( "Phone Number should be 10 digits");?>
								</div>
								<div class="SuccessMsg"  style="display:none">
									<?php echo __( "Mobile number verified");?>
								</div>
								<div class="right_user_mobile">
									<button type="button" style="background: white;color: black;padding: 0px;border: none;" class="btn btn-primary btn-block otp-verify-submit">Verify</button> <span  class="OtpBaseUrl" style="display: none"><?php echo "https://www.vaibhavjewellers.com/";//$block->getUploadFormUrl(); ?></span>
								</div>
								<div>
									<div class="field form-group verification user_otp" style="display:none;">
										<label for="verification" style="width: 36%;float: left;margin-top: 10px;" class="label col-sm-5 control-label"><span>
                                <?php
                                /* @escapeNotVerified */
                                echo __('Phone Verification')
                                ?>
                                            </span>
										</label>
										<div class="control col-sm-7" style="width: 50%;">
											<input type="text" name="otp" class="form-control otps" placeholder="Enter Code" data-validate="{required:true}" data-msg-required="Please enter OTP">
											<button style="width: 100%;margin-top: 9px;" type="button" class="btn btn-primary btn-block otp-verification">Verify OTP</button>
										</div>
									</div>
								</div>
</div>
</div>
        <div class="field required"   style="width: 40%;margin: auto;margin-top: 45px;float: left;margin-left: 20px;display:none">
            <label for="date" class="label"><span><?php echo __('Select Date') ?></span></label>
            <div class="control">
             <input name="takedate" id="datepicker" title="Terminwunsch" value="" type="text" placeholder="Select Date" class="input-text" data-validate="{required:true}"/>
                    <script type="text/javascript">
                    require([
                        "jquery",
                        "mage/calendar"
                        ], function($){
                             var dateToday = new Date();
                             $('#datepicker').datepicker({
                               prevText: '&#x3c;zur체ck', prevStatus: '',
                                prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                                nextText: 'Vor&#x3e;', nextStatus: '',
                                nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                                monthNames: ['Januar','Februar','M채rz','April','Mai','Juni',
                                'Juli','August','September','October','November','December'],
                                monthNamesShort: ['Jan','Feb','M채r','Apr','Mai','Jun',
                                'Jul','Aug','Sep','Oct','Nov','Dec'],
                                dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
                                dayNamesShort: ['So','Mo','Tue','Wed','Thu','Fr','Sa'],
                                dayNamesMin: ['So','Mo','Tue','Wed','Thu','Fr','Sa'],
                              showMonthAfterYear: false,
                              dateFormat:'dd.mm.yy',
                               minDate: dateToday,
                              yearRange: '2018:2020',
                              changeMonth: true,
                              changeYear: true
                              
                            } 
                          );
                        });
                    </script>
            </div>
        </div>
    <div class="field required" style="width:40%;margin:auto;margin-top:10px;float:right;margin-right:20px;display:none">
    <label for="time" class="label"><span><?php echo __('Select Time') ?></span></label>
    <div class="control">
    <input style="height: 33px;color: #282828;border-color: #dcdcdc;background-color: #fff;font: 500 14px/1.55 Lato,sans-serif;padding: 5px 10px;line-height: 28px;-webkit-border-radius: 3px;-moz-border-radius: 3px;border-radius: 3px;" class="input-text" type="time" placeholder="Time" name="usr_time" data-validate="{required:true}" />
    </div>
    </div>
<div class="primary" style="padding-bottom: 10px; text-align: center;">
    <input class="hideit" name="hideit" type="hidden" value="" data-gaconnector-tracked="true" /> 
    <button class="action submit primary sub" title="Submit" type="submit"> <span>Submit</span> </button>
</div>
</fieldset>

</div>
</div>
</div>




</form>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){

   var dataForm = $('#tryathomes-form');
   dataForm.mage('validation', {});
});
</script>
<script type="text/javascript">
	require([
	    'jquery',
	    'mage/mage'
	], function($){
	 $(document).ready(function(){
	   $(".mobile").keypress(function (e) {
	     //if the letter is not digit then display error and don't type anything
	     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
	        //display error message
	        $(".customized-errmsg").html("Digits Only").show().fadeOut("slow");
	          return false;
	    }
	   });
	 }); 
	});
</script>
<script type="text/javascript">
	require([
	                                    'jquery', // jquery Library
	                                    'jquery/ui', // Jquery UI Library
	                                    'jquery/validate', // Jquery Validation Library
	                                    'mage/translate' // Magento text translate (Validation message translte as per language)
	                            ], function($){
	                            jQuery(document).ready(function () {
	                                $.validator.setDefaults({ ignore: '' });
	                                $.validator.addMethod(
	                                        'validate-upload-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                                $.validator.addMethod(
	                                        'validate-customize-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                                 $.validator.addMethod(
	                                        'validate-designer-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                            });
var acc = document.getElementsByClassName("newtryaccordion");
var i;
for (i = 0; i < acc.length; i++) {
 acc[i].addEventListener("click", function() {
   this.classList.toggle("active");
   var panel = this.nextElementSibling;
   if (panel.style.maxHeight) {
     panel.style.maxHeight = null;
   } else {
     panel.style.maxHeight = panel.scrollHeight + "px";
   } 
 });
}
	                                
	                            });
</script>
<script type="text/javascript">
	require([
	                                    'jquery', // jquery Library
	                                    'jquery/ui', // Jquery UI Library
	                                    'jquery/validate', // Jquery Validation Library
	                                    'mage/translate' // Magento text translate (Validation message translte as per language)
	                            ], function($){ 
	jQuery(document).ready(function () {
	                            jQuery(document).on('click', '.otp-verify-submit', function(){
	                                   /*var mobile = jQuery(".mobile").val();
	                                   console.log('Mobile - ' + mobile);
	                                   var mobileLength = jQuery(".mobile").val().length;
	                                   console.log('mobileLength - ' + mobileLength);*/
	                                   var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
	                                   baseUrl = baseUrl.trim();
	                                   var controllerUrl = 'sociallogin/popup/codesend';
	                                   var ajxUrl = baseUrl.concat(controllerUrl);
	                                  if (jQuery(".mobile").val() == '') {
	                                       /*console.log('sarvesh');*/
	                                       jQuery(".ValidErr").show();
	                                       jQuery(".RepeatErr").hide();
	                                       jQuery(".SuccessMsg").hide();
	                                       return false;
	                                   } else {
	                               if (jQuery(".mobile").val().length != '10'){
	                                                        /*console.log('tiwari');*/
	                                                        jQuery(".ValidErrt").show();
	                                                        jQuery(".ValidErr").hide();
	                                                        jQuery(".user_otp").hide();
	                                                        jQuery(".RepeatErr").hide();
	                                                        jQuery(".SuccessMsg").hide();
	                                                       return false;
	                                  
	                                  }
	                               }
	                                   jQuery(".otp-verify-submit").hide();
	                                   var form_data = "telephone="+jQuery(".mobile").val();//jQuery("#user_mobile :input").serialize();
	                                                jQuery.ajax({
	                                                url: ajxUrl, // Upload Script
	                                                showLoader: true,   
	                                                dataType: 'json',
	                                                data: form_data, // Setting the data attribute of ajax with file_data
	                                                type: 'post',
	                                                success: function(data) {  // Do something after Ajax completes 
	                                                               // jQuery("div[id='verifyloading']").hide();
	                                                                    // alert(data['message']);
	                                                    jQuery('.RepeatErr').hide();
	                                                    jQuery('.verifyErr').hide();
	                                                        if (data['success'] == true)
	                                                        {
	                                                        jQuery(".RepeatErr").hide();
	                                                                    jQuery(".verify-error").hide();
	                                                                    jQuery(".mobile-error").hide();
	                                                                    jQuery('.RepeatErr').html("");
	                                                                    jQuery('.SuccessMsg').html("");
	                                                                    jQuery('.SuccessMsg').html(data['message']);
	                                                                    jQuery('.SuccessMsg').show();
	                                                                    jQuery(".otp").val('');
	                                                                    jQuery(".user_otp").show();
	                                                                     jQuery(".otp-verify-submit").text('Resend Otp');
	                                                                    jQuery(".ValidErrt").hide();
	                                                                    jQuery(".ValidErr").hide();
	                                                                    } else {
	                                                                    jQuery(".SuccessMsg").hide();
	                                                                    jQuery('.SuccessMsg').html("");
	                                                                    jQuery('.RepeatErr').html("");
	                                                                    //jQuery('#RepeatErr').html(data['message']);
	                                                                    jQuery('.RepeatErr').show();
	                                                                    jQuery(".otp-verify-submit").show();
	                                                                    jQuery(".user_otp").hide();
	                                                                    }
	                                                                }
	                                                    });
	                              
	                            });
	                            jQuery(document).on('click', '.otp-verification', function(){
	                                /*console.log('sarvesh tiwari');*/
	                            //if(jQuery(".otp").valid()) { 
	                                var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
	                                baseUrl = baseUrl.trim();
	                                var controllerUrl = 'sociallogin/popup/codeverify';
	                                var ajxUrl = baseUrl.concat(controllerUrl);
	                                /*console.log(ajxUrl);*/
	                                var frm_data = "telephone="+ jQuery(".mobile").val();
	                                var form_data = frm_data + "&" + "otp="+ jQuery(".otps").val();
	                                /*console.log(form_data);*/
	                                if (jQuery(".otps").val() == '')
	                                {
	                                 return false;
	                                }
	                                jQuery('.verifyErr').hide();
	                                jQuery('.RepeatErr').hide();
	                                jQuery.ajax({
	                                url: ajxUrl, // Upload Script
	                                        showLoader: true,
	                                        dataType: 'json',
	                                        data: form_data, // Setting the data attribute of ajax with file_data
	                                        type: 'post',
	                                        success: function(data) {// Do something after Ajax completes 
	                                        //alert(data['message']);
	                                        //alert('verification success');
	                                        if (data['success'] == true)
	                                        {
	                                            /*console.log('otp');*/
	                                        jQuery(".RepeatErr").hide();
	                                        jQuery('.SuccessMsg').html("");
	                                        jQuery("#verify-error").hide();
	                                        jQuery(".telephone-error").hide();
	                                        jQuery('.SuccessMsg').html(data['message']);
	                                        jQuery('.SuccessMsg').show();
	                                        jQuery(".user_otp").hide();
	                                        jQuery('input[name="verify"]').val('1');
	                                        jQuery(".verifyErr").hide();
	                                        jQuery(".otp-verify-submit").hide();
	                                        } else {
	                                            /*console.log('otp not verified');*/
	                                        jQuery(".SuccessMsg").hide();
	                                        jQuery('.RepeatErr').html("");
	                                        jQuery('.RepeatErr').html(data['message']);
	                                        jQuery('.RepeatErr').show();
	                                        jQuery(".otp-verify-submit").text('Resend Otp');
	                                        jQuery(".otp-verify-submit").show();
	                                        jQuery(".user_otp").hide();
	                                        jQuery('input[name="verify"]').val('0');
	                                        }
	                                        }
	                                });
	                            //}
	                            });
	 });                                                                        
	});
</script>