<style>
    .card-header {
        padding-left:0px !important;
    }
</style>
<div style="margin: 0px 0px auto;">
    <form style="margin: 16px auto; background-color: #ffffff; box-shadow: 2px 2px 5px 5px #E6E6E6, 0px 0px 0px 0px #E6E6E6, 0px 0px 0px 0px #E6E6E6; border-radius: 4px;" data-mage-init='{"validation": {}}' class="form" id="custom-form" method="post" autocomplete="off" action="<?php echo $this->getUrl('tryathome/index/index'); ?>">
    <fieldset class="fieldset" style="margin-bottom: 20px;">
<div class="contact-form-lacble" style="background-color: #f7f7f7; margin-bottom: 2px;">
<h1 style="text-align: center; background-color: #6e2083; margin-bottom: 0px; height: 50px;color: white;; margin-bottom: 0px;font-size:26px;padding-top: 10px;">Schedule Your Free Trail</h1>
</div>
 <input name="source" value="Try at Home"  type="hidden" />
 <?php $product_url= $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>
 <input name="product" value="<?php echo $product_url; ?>"  type="hidden" />
<div class="field name required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px; margin-top: 10px;">
    <input class="input-text" type="text" placeholder="Customer Name" name="cust_name" data-validate="{required:true}" /></div>
</div>
<div class="field name required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px;">
    <input class="input-text" type="text" placeholder="Enter Your Area" name="area" data-validate="{required:true}" /></div>
</div>
<div class="field email required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px;">
    <input id="emailcontact" class="input-text" title="Email" name="email" type="email" value="" placeholder="Enter Your Email Address" data-validate="{required:true, 'validate-email':true}" data-gaconnector-tracked="true" /></div>
</div>
<div class="field telephone required" style="width: 90%; margin: auto;">
<div class="control" style="margin-bottom: 20px;">
								<input name="mobile" type="tel" class="input-text required-entry in customized-mobile" placeholder="Mobile Number *" />
								<input type="hidden" name="verify" class="txt_verify" tabindex="1000" value="0" id="upload-design" data-validate="{required:true, 'validate-upload-design-verify':true}" data-msg-required="Please enter Mobile" aria-required="true" aria-invalid="true" aria-describedby="verify-error" /> <span class="customized-errmsg" style="color: red; text-align:center;"></span>
								<div class="verifyErr" id="verifyErr" style="display:none;color: red;">
									<?php echo __( "Mobile verification is pending");?>
								</div>
								<div class="RepeatErr" id="RepeatErr" style="display:none;color: red;">
									<?php echo __( "Mobile number already taken");?>
								</div>
								<div class="ValidErr" id="ValidErr" style="display:none;color: red;">
									<?php echo __( "Please Enter Mobile Number");?>
								</div>
								<div class="ValidErrt" id="ValidErrt" style="display:none;color: red;">
									<?php echo __( "Phone Number should be 10 digits");?>
								</div>
								<div class="SuccessMsg" id="SuccessMsg" style="display:none;color: red;">
									<?php echo __( "Mobile number verified");?>
								</div>
								<div class="right_user_mobile">
									<button type="button" style="margin-top: 34px;" class="btn btn-primary btn-block otp-verify-submit">Verify</button> <span id="OtpBaseUrl" class="OtpBaseUrl" style="display: none;color: red;"></span>
								</div>
								<div>
									<div class="field form-group verification user_otp" style="display:none;">
										<label for="verification" class="label col-sm-5 control-label"><span>
                                <?php
                                /* @escapeNotVerified */
                                echo __('Phone Verification')
                                ?>
                                            </span>
										</label>
										<div class="control col-sm-7">
											<input type="text" name="otp" class="form-control otp" placeholder="Enter Code" data-validate="{required:true}" data-msg-required="Please enter OTP">
											<button type="button" class="btn btn-primary btn-block otp-verification">Verify OTP</button>
										</div>
									</div>
								</div>
</div>
</fieldset>
<div class="primary" style="padding-bottom: 10px; text-align: center;">
    <input id="hideit" name="hideit" type="hidden" value="" data-gaconnector-tracked="true" /> 
    <button id="sub" class="action submit primary" title="Submit" type="submit"> <span>Submit</span> </button>
</div>
</form>
</div>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){

   var dataForm = $('#custom-form');
   dataForm.mage('validation', {});

});
</script>
<script type="text/javascript">
	require([
	    'jquery',
	    'mage/mage'
	], function($){
	 $(document).ready(function(){
	   $(".customized-mobile").keypress(function (e) {
	     //if the letter is not digit then display error and don't type anything
	     if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
	        //display error message
	        $(".customized-errmsg").html("Digits Only").show().fadeOut("slow");
	          return false;
	    }
	   });
	 }); 
	});
</script>
<script type="text/javascript">
	require([
	                                    'jquery', // jquery Library
	                                    'jquery/ui', // Jquery UI Library
	                                    'jquery/validate', // Jquery Validation Library
	                                    'mage/translate' // Magento text translate (Validation message translte as per language)
	                            ], function($){
	                            jQuery(document).ready(function () {
	                                $.validator.setDefaults({ ignore: '' });
	                                $.validator.addMethod(
	                                        'validate-upload-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                                $.validator.addMethod(
	                                        'validate-customize-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                                 $.validator.addMethod(
	                                        'validate-designer-design-verify', function (value) {
	                                       return (value=='1') 
	                                        },$.mage.__('Mobile verification is pending')
	                                );
	                            });
	                            });
</script>
<script type="text/javascript">
	require([
	                                    'jquery', // jquery Library
	                                    'jquery/ui', // Jquery UI Library
	                                    'jquery/validate', // Jquery Validation Library
	                                    'mage/translate' // Magento text translate (Validation message translte as per language)
	                            ], function($){ 
	jQuery(document).ready(function () {
	                            jQuery(document).on('click', '.otp-verify-submit', function(){
	                                //var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
	                                //baseUrl = baseUrl.trim();
	                                //var controllerUrl = 'sociallogin/popup/phoneverify';
	                                //var ajxUrl = baseUrl.concat(controllerUrl);
	/*                                  if (jQuery("#telephone").val() == '') {
	                                    jQuery("#ValidErr").show();
	                                    jQuery("#RepeatErr").hide();
	                                    jQuery("#SuccessMsg").hide();
	                                    return false;
	                                } else {
	                                    if (jQuery("#telephone").val().length != 10){
	                                        jQuery("#ValidErrt").show();
	                                        jQuery("#ValidErr").hide();
	                                        jQuery("#user_otp").hide();
	                                        jQuery("#RepeatErr").hide();
	                                        jQuery("#SuccessMsg").hide();
	                                        
	                                        return false;
	                                    }
	                                }*/
	                                //var form_data = "telephone="+jQuery("#telephone").val();
	                               /* jQuery.ajax({
	                                    url: ajxUrl, // Upload Script
	                                    showLoader: true,   
	                                    dataType: 'json',
	                                    data: form_data,
	                                    type: 'post',*/
	                                    //success: function(data) {
	                                        /*if(data) {*/
	                                            //if(jQuery("#telephone").valid()) {
	                                                    var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
	                                                    baseUrl = baseUrl.trim();
	                                                    var controllerUrl = 'sociallogin/popup/codesend';
	                                                    var ajxUrl = baseUrl.concat(controllerUrl);
	                                                    if (jQuery(".customized-mobile").val() == '') {
	                                                    jQuery(".ValidErr").show();
	                                                    jQuery(".RepeatErr").hide();
	                                                    jQuery(".SuccessMsg").hide();
	                                                    return false;
	                                                } else {
	                                                    if (jQuery(".customized-mobile").val().length != 10){
	                                                        jQuery(".ValidErrt").show();
	                                                        jQuery(".ValidErr").hide();
	                                                        jQuery(".user_otp").hide();
	                                                        jQuery(".RepeatErr").hide();
	                                                        jQuery(".SuccessMsg").hide();
	                                                        return false;
	                                                    }
	                                                }
	                                                jQuery(".otp-verify-submit").hide();
	                                                var form_data = "telephone="+jQuery(".customized-mobile").val();//jQuery("#user_mobile :input").serialize();
	                                                jQuery.ajax({
	                                                url: ajxUrl, // Upload Script
	                                                showLoader: true,   
	                                                dataType: 'json',
	                                                data: form_data, // Setting the data attribute of ajax with file_data
	                                                type: 'post',
	                                                success: function(data) {  // Do something after Ajax completes 
	                                                               // jQuery("div[id='verifyloading']").hide();
	                                                                    // alert(data['message']);
	                                                    jQuery('.RepeatErr').hide();
	                                                    jQuery('.verifyErr').hide();
	                                                        if (data['success'] == true)
	                                                        {
	                                                        jQuery(".RepeatErr").hide();
	                                                                    jQuery(".verify-error").hide();
	                                                                    jQuery(".mobile-error").hide();
	                                                                    jQuery('.RepeatErr').html("");
	                                                                    jQuery('.SuccessMsg').html("");
	                                                                    jQuery('.SuccessMsg').html(data['message']);
	                                                                    jQuery('.SuccessMsg').show();
	                                                                    jQuery(".otp").val('');
	                                                                    jQuery(".user_otp").show();
	                                                                     jQuery(".otp-verify-submit").text('Resend Otp');
	                                                                    jQuery(".ValidErrt").hide();
	                                                                    jQuery(".ValidErr").hide();
	                                                                    } else {
	                                                                    jQuery(".SuccessMsg").hide();
	                                                                    jQuery('.SuccessMsg').html("");
	                                                                    jQuery('.RepeatErr').html("");
	                                                                    //jQuery('#RepeatErr').html(data['message']);
	                                                                    jQuery('.RepeatErr').show();
	                                                                    jQuery(".otp-verify-submit").show();
	                                                                    jQuery(".user_otp").hide();
	                                                                    }
	                                                                }
	                                                    });
	                                        
	                                      /*  } else {
	                                            jQuery("#ValidErr").hide();
	                                            jQuery('#RepeatErr').show();
	                                            jQuery("#ValidErrt").hide();
	                                            //jQuery("#otp-verify-submit").text('Mobile Number alreday taken click to change again');
	                                            jQuery("#ValidErr").hide();
	                                        }*/
	                               /*     }else {
	                                    jQuery("#ValidErr").hide();
	                                    jQuery('#RepeatErr').show();
	                                    jQuery("#ValidErrt").hide();
	                                    //jQuery("#otp-verify-submit").text('Mobile Number alreday taken click to change again');
	                                    jQuery("#ValidErr").hide();
	                                }*/
	                            //}
	                                //});
	                            });
	                            jQuery(document).on('click', '.otp-verification', function(){
	                            //if(jQuery(".otp").valid()) { 
	                                var baseUrl = document.getElementsByClassName('OtpBaseUrl')[0].innerHTML;
	                                baseUrl = baseUrl.trim();
	                                var controllerUrl = 'sociallogin/popup/codeverify';
	                                var ajxUrl = baseUrl.concat(controllerUrl);
	                                var frm_data = "telephone="+jQuery(".customized-mobile").val();
	                                var form_data = frm_data + "&" + "otp="+jQuery(".otp").val();
	                                if (jQuery("#otp").val() == '')
	                                {
	                               return false;
	                               }
	                                jQuery('.verifyErr').hide();
	                                jQuery('.RepeatErr').hide();
	                                jQuery.ajax({
	                                url: ajxUrl, // Upload Script
	                                        showLoader: true,
	                                        dataType: 'json',
	                                        data: form_data, // Setting the data attribute of ajax with file_data
	                                        type: 'post',
	                                        success: function(data) {// Do something after Ajax completes 
	                                        //alert(data['message']);
	                                        //alert('verification success');
	                                        if (data['success'] == true)
	                                        {
	                                        jQuery(".RepeatErr").hide();
	                                        jQuery('.SuccessMsg').html("");
	                                        jQuery(".verify-error").hide();
	                                        jQuery(".telephone-error").hide();
	                                        jQuery('.SuccessMsg').html(data['message']);
	                                        jQuery('.SuccessMsg').show();
	                                        jQuery(".user_otp").hide();
	                                        jQuery('input[name="verify"]').val('1');
	                                        jQuery(".verifyErr").hide();
	                                        jQuery(".otp-verify-submit").hide();
	                                        } else {
	                                        jQuery(".SuccessMsg").hide();
	                                        jQuery('.RepeatErr').html("");
	                                        jQuery('.RepeatErr').html(data['message']);
	                                        jQuery('.RepeatErr').show();
	                                        jQuery(".otp-verify-submit").text('Resend Otp');
	                                        jQuery(".otp-verify-submit").show();
	                                        jQuery(".user_otp").hide();
	                                        jQuery('input[name="verify"]').val('0');
	                                        }
	                                        }
	                                });
	                            //}
	                            });
	 });                                                                        
	});
</script>